{
  "hash": "1a5bb517121bb9e78c4625ffb8f4f245",
  "result": {
    "engine": "knitr",
    "markdown": "# Análise de Variância\n\n## Pacotes necessários para este capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(car, effectsize, flextable,\n               ggpubr, ggsci, RColorBrewer,\n               readxl, rstatix, tidyverse)\n```\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## ANOVA de um fator\n\n### Por que realizar uma ANOVA?\n\nA análise de variância (ANOVA) é um método estatístico para comparar as médias de três ou mais grupos, testando se existem diferenças significativas entre elas. Para analisar três ou mais médias, uma tendência intuitiva seria fazer comparações por pares, usando um teste *t* de amostras independentes. Com quatro grupos, por exemplo, é possível compará-los realizando seis testes, grupo 1 versus grupo 2, grupo 1 versus grupo 3, grupo 1 versus grupo 4, grupo 2 versus grupo 3, grupo 2 versus grupo 4 e grupo 3 versus grupo 4. Com 5 grupos o número de testes necessários seria igual a 10. Generalizando, a expressão combinatória, usada para calcular o número de combinações de *n* elementos distintos de um conjunto de *k* grupos, sem se importar com a ordem é igual a:\n\n$$ \n\\frac {k!}{n!(k-n)!} $$\n\nOu, usando uma função do R , `choose(k, n)`, facilmente se chega ao resultado. Portanto, para quatro grupos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoose(4, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\nFoi visto na @sec-erros que ao realizar um teste de hipótese podem ocorrer erros. Em geral, tolera-se aceitar um taxa de falsos positivos (erro tipo I) de até 5% ($\\alpha$ = 0,05). Consequentemente, a probabilidade de um erro do tipo I não ocorrer para cada teste *t* é de 0,95 (isto é, 1 – 0,05). Como os três testes são independentes, a probabilidade de um erro do tipo I não ocorrer nos seis testes é de $(0,95)^6 = 0,735$. Dessa maneira, a probabilidade de ocorrer pelo menos um erro do tipo I nos seis testes *t* de duas amostras é de 1 – 0,735 ou 0,265 (26,5%), o que é mais alto do que o nível de significância definido de 0,05 [@field2012anova]. Ou seja, realizar múltiplos testes *t*, infla o erro tipo I.\n\nPor essa razão, a ANOVA de um fator é usada para verificar as diferenças entre várias médias dentro de um fator, reduzindo assim o número de comparações de pares e a probabilidade de ocorrer um erro tipo I.\n\n### Lógica do Modelo da ANOVA {#sec-logicamodel}\n\nO procedimento de ANOVA é utilizado para testar a hipótese nula de que as médias de três [^15-anova-1] ou mais populações são as mesmas contra hipótese alternativa de que nem todas as médias são iguais.\n\n[^15-anova-1]: Pode ser usada também para comparar a média de duas populações e o resultado será o mesmo de um teste *t* para amostras independentes.\n\nNa @sec-homovar, foram comparadas duas variâncias, usando um teste, denominado de *teste F*. Este teste, é uma razão entre duas variâncias e recebeu este nome em homenagem a *Sir Ronald Aylmer Fisher* (veja a @sec-historia). A variância é uma medida de dispersão que mensura como os dados estão espalhados em torno da média (veja @sec-variancia ) . Quanto maior o seu valor, maior a dispersão.\n\nConsidere a @fig-logica, onde está representada a distribuição de uma variável *X* em três grupos independentes. Pode-se, claramente, distinguir observações provenientes dessas distribuições, pois a sobreposição delas é pequena. Cada uma dela se dispersa pouco em torno da média.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Três distribuições diferentes](15-anova_files/figure-html/fig-logica-1.png){#fig-logica fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nAgora, observe o @fig-logicb, onde a distribuição da variável *X* é mostrada, mantendo as mesmas médias, mas com variâncias maiores. Isto torna claro que se o objetivo é distinguir observações provenientes desses grupos não basta avaliar suas médias, há necessidade de comparar a **variação entre os grupos** com a **variação dentro de cada grupo** [@menezes2004anova].\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuições com mesmas médias da figura anterior, mas variâncias maiores](15-anova_files/figure-html/fig-logicb-1.png){#fig-logicb fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nSe a variação entre os grupos for grande quando comparada à variação dentro de cada grupo, aumenta a probabilidade de reconhecer a proveniência das observações (@fig-logica). Entretanto, se a variação entre os grupos for pequena comparada à variação dentro do grupo, torna difícil a distinção de observações provenientes dos grupos (@fig-logicb).\n\nPortanto, a ANOVA de uma via se baseia na comparação da variância entre grupos com a variância dentro dos grupos, utilizando as **Somas dos Quadrados** (SQ) e os graus de liberdade (gl) para calcular os **Quadrados Médios** (QM). A razão entre o Quadrado Médio entre os grupos (QM~E~) e a Quadrado Médio dentro dos grupos (QM~D~) resulta na estatística F, que é comparada com um valor crítico da distribuição F para determinar a significância estatística da diferença entre as médias dos grupos.\n\n$$ \nF = \\frac{\\text{variância entre os grupos}}{\\text{variância dentro dos grupos}}$$\n\nQuando o valor de *F* fica próximo de 1, significa que as variâncias são muito próximas; quando *F* é significativamente maior do que 1, é possível distinguir os indivíduos de diferentes grupos. Ou seja, se o objetivo for mostrar que as médias são diferentes, será bom que a variância dentro dos grupos seja baixa. Pode-se pensar na variância dentro do grupo como o ruído que pode obscurecer a diferença entre os sons (as médias). No gráfico da @fig-logica, o valor de *F* seria grande; no da @fig-logicb, seria pequeno.\n\nComo saber se o valor de *F* é grande o suficiente? Um único valor *F* é difícil de interpretar sozinho. Há necessidade de colocá-lo em um contexto maior antes que seja possível interpretá-lo. Para fazer isso, usa-se a distribuição *F* para calcular as probabilidades.\n\n### Distribuição *F* {#sec-distF}\n\nA **distribuição F**, também conhecida como distribuição de Fisher-Snedecor, é uma distribuição de probabilidade contínua fundamental na estatística inferencial. Sua principal aplicação é para comparar variâncias de duas ou mais populações normais.\n\nA razão entre a **variabilidade entre os grupos** e a **variabilidade dentro do grupo** segue uma distribuição *F* quando a hipótese nula é verdadeira. Quando se realiza uma ANOVA com um fator obtém-se um valor *F*. No entanto, se forem extraídas várias amostras aleatórias do mesmo tamanho da mesma população e fosse repetida a mesma análise, o resultado seriam muitos valores *F* diferentes, constituindo uma distribuição amostral, denominada de **distribuição F**.\n\nA distribuição *F* assumindo que a hipótese nula é verdadeira, é possível colocar o resultado de qualquer valor *F* e determinar quão consistente ele é com a hipótese nula e calcular a probabilidade. A probabilidade que se quer calcular é a probabilidade de observar uma estatística *F* que é pelo menos tão alta quanto o valor que o estudo obteve. Essa probabilidade permite determinar quão comum ou raro é o valor *F*, sob a suposição de que a hipótese nula é verdadeira. Se a probabilidade for pequena o suficiente, pode-se concluir que dados são inconsistentes com a hipótese nula. Como já foi mostrado em outros momentos, essa probabilidade é o valor *p* (@sec-valorp).\n\nA forma da curva de distribuição *F* varia de acordo com **dois graus de liberdade** - um para o numerador (variância entre) e outro para o denominador (variância dentro). Cada combinação de graus de liberdade fornece uma curva de distribuição *F* diferente. As unidades de uma distribuição *F* são denotadas por *F*, que possui características importantes:\n\n1.  **Distribuição contínua**: Como as distribuições normal, *t* e qui-quadrado (veja @sec-qui), a distribuição *F* é uma distribuição contínua;\n\n2.  **Valores positivos**: A variável F só pode assumir valores maiores ou iguais a zero; A distribuição é limitada à esquerda por zero e não tem limite superior, estendendo-se indefinidamente à direita, o que reflete o fato de que as variâncias são sempre não negativas.\n\n3.  **Assimetria positiva**: A distribuição F é assimetrica à direita, ou seja, tem uma cauda longa para o lado positivo, mas a assimetria diminui à medida que o número de graus de liberdade aumenta, conforme observado na @fig-distf.\n\n4.  **Parâmetros**: A distribuição F é definida por seus graus de liberdade, o do numerador (gl1) e o do denominador (gl2)[^15-anova-2].\n\n[^15-anova-2]: Quando se referir a abreviação `df` de `degree of freedom` em algumas funções, optou-se por manter `df` ,sem a tradução para `gl` (graus de liberdade), como em geral se usa no texto.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuições F](15-anova_files/figure-html/fig-distf-1.png){#fig-distf fig-align='center' width=90% height=90%}\n:::\n:::\n\n\n#### Distribuição F e os graus de liberdade\n\nNa @fig-distf, observa-se que à medida que os graus de liberdade aumentam, a distribuição F realmente começa a se parecer com a distribuição normal, especialmente em termos de simetria e concentração em torno da média. Entretanto, há pormenores importantes sobre como isso acontece com o grau de liberdade do numerador (gl~1~) e com o grau de liberdade do denominador (gl~2~).\n\n\n::: {#tbl-gl1gl2 .cell tbl-cap='Importância dos graus de liberdade'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-8c40cf40{}.cl-8c371a90{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8c371aa4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8c3b0060{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8c3b39ea{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8c3b39f4{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8c3b3a08{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8c3b3a09{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8c3b3a12{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8c3b3a13{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-8c40cf40'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-8c3b39ea\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371a90\">Graus de Liberdade</span></p></th><th class=\"cl-8c3b39f4\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371a90\">Papel na Distribuição F</span></p></th><th class=\"cl-8c3b39f4\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371a90\">Efeito ao aumentar</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8c3b3a08\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">gl1 (numerador)</span></p></td><td class=\"cl-8c3b3a09\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">Relacionado ao número de grupos ou variáveis</span></p></td><td class=\"cl-8c3b3a09\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">A curva fica menos assimétrica, mas ainda com cauda à direita</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8c3b3a12\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">gl2 (denominador)</span></p></td><td class=\"cl-8c3b3a13\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">Relacionado ao tamanho da amostra</span></p></td><td class=\"cl-8c3b3a13\"><p class=\"cl-8c3b0060\"><span class=\"cl-8c371aa4\">A curva se aproxima mais rapidamente da normal</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n[Por que isso acontece]{.underline} ?\n\nBom, é um pouco mais complicado!\n\nProcurando tornar o mais simples possível[^15-anova-3], acima (@sec-logicamodel) foi mostrado que a razão F na distribuição F é definida como a razão entre duas variâncias estimadas e variância (@sec-variancia) é a razão da soma dos quadrados (*SQ*) dividido pelos graus de liberdade, logo\n\n[^15-anova-3]: Na realidade, bem simplista!\n\n$$ \nF = \\frac{(SQ_1 / gl_1)}{(SQ_2 / gl_2)} $$\n\nonde (SQ~1~) e (SQ~2~) são variáveis independentes com distribuições qui-quadrado (veja @sec-qui) com graus de liberdade (gl~1~) e (gl~2~), respectivamente.\n\nComo a distribuição qui-quadrado se aproxima da normal quando os graus de liberdade aumentam, a razão entre elas (a distribuição F) também começa a se comportar como uma normal — especialmente quando gl~2~ é grande (@tbl-gl1gl2) [@ferreira2011distf].\\\nEsse comportamento é útil na prática porque permite usar testes que assumem normalidade quando os graus de liberdade são grandes, mesmo quando a distribuição original é mais complexa.\n\n#### Funções do R para trabalhar com a distribuição F\n\nNo *R*, existem quatro funções principais que são ferramentas essenciais para trabalhar com a distribuição F. Elas seguem um padrão comum a muitas distribuições de probabilidade, e cada uma tem uma finalidade específica.\n\n##### Função de Densidade de Probabilidade (FDP)\n\nA função `df()` calcula a densidade de probabilidade de um valor específico em uma distribuição F. A densidade de probabilidade não é a probabilidade em si, mas sim a altura da curva da distribuição F em um determinado ponto.\\\nÉ usada principalmente para visualizar a forma da distribuição F ou para cálculos mais avançados que exigem a densidade em um ponto. Ela ajuda a entender a \"concentração\" de probabilidade em diferentes valores. Usa os seguintes argumentos:\n\n- `x` : representa o valor na escala F, que é o valor que se obtém ao calcular a estatística de um teste F (F~observado~) em uma análise, como um teste ANOVA, por exemplo;\\\n- `df1`: são os graus de liberdade do numerador;\\\n- `df2`; são os graus de liberdade do denominador.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo: FPD de 2, com df1 = 4 e df2 = 50\n\ndf(x = 2, df1 = 4, df2 = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1512717\n```\n\n\n:::\n:::\n\n\n##### Função de Distribuição Cumulativa (CDF)\n\nA função `pf()` calcula a probabilidade acumulada de uma distribuição F. Ela retorna a probabilidade de que uma variável aleatória F seja menor ou igual a um valor `q` (quantil).\\\nÉ a função mais usada para obter o valor *p* de um teste F. Dado um valor F~observado~ (estatística de teste), você usa `pf()` para encontrar a probabilidade de obter um valor F igual ou mais extremo, o que é fundamental para tomar decisões sobre rejeitar ou não a hipótese nula. Usa os seguintes argumentos:\n\n- `q` : O valor quantil para o qual se quer calcular a probabilidade acumulada;\n- `df1`: são os graus de liberdade do numerador;\n- `df2`; são os graus de liberdade do denominador;\n- `lower.tail = TRUE`: (Padrão) Calcula a probabilidade da cauda inferior ($P(F \\le q)$). Usar `FALSE` para a cauda superior ($P(F > q)$), que é o que geralmente se busca em testes de hipótese.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo: Probabilidade de F ser menor que 2, com df = 4 e df2 = 50\npf(q = 2, df1 = 4, df2 = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8911717\n```\n\n\n:::\n\n```{.r .cell-code}\n# Exemplo: Probabilidade da cauda superior de F ser maior que 2 (para valor p)\npf(q = 2, df1 = 4, df2 = 50, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1088283\n```\n\n\n:::\n:::\n\n\n##### Função Quantil\n\nA função `qf()` é o inverso de `pf()`. Ela recebe uma probabilidade *p* e retorna o valor quantil correspondente, ou seja, o valor *q* que tem uma probabilidade acumulada *p*.\n\nÉ usada para encontrar o valor crítico de uma distribuição F para um certo nível de significância ($\\alpha$). Esse valor crítico é a linha de corte que se compara com sua estatística de teste F~observada~ para decidir sobre o resultado do teste. Usa os seguintes argumentos:\n\n- `p` : A probabilidade acumulada (geralmente, $1 − \\alpha$ para testes de cauda superior);\n\n- `df1`: são os graus de liberdade do numerador;\n\n- `df2`; são os graus de liberdade do denominador;\n\n- `lower.tail = TRUE`: (Padrão) Encontra o valor `q` tal que ($P(F \\le q) = p$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo: Encontrar o valor crítico de F para um nível de significância de 5% (0.05) com df1 = 4 e df2 = 50.\nqf(p = 0.95, df1 = 4, df2 = 50) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.557179\n```\n\n\n:::\n\n```{.r .cell-code}\n# ou \nqf(0.05, 4, 50, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.557179\n```\n\n\n:::\n:::\n\n\n##### Geração de Números Aleatórios\n\nA função `rf()` gera números aleatórios que seguem a distribuição F.\\\nÉ útil para simulações, modelagem estatística, testes de Monte Carlo[^15-anova-4] ou para entender a forma da distribuição F gerando amostras aleatórias. Seus argumentos são:\\\n- `n` : O número de observações aleatórias que se deseja gerar.\\\n- `df1`: são os graus de liberdade do numerador;\n\n[^15-anova-4]: Testes de Monte Carlo, também conhecidos como Simulações de Monte Carlo, são uma classe de métodos computacionais que dependem de **amostragem aleatória** repetida para obter resultados numéricos. O nome \"Monte Carlo\" vem do famoso cassino em Mônaco, pois o método se baseia na aleatoriedade de um jogo de roleta.\n\n- `df2`; são os graus de liberdade do denominador.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exemplo: Gerar 50 números aleatórios de uma distribuição F com df1 = 4 e df2 = 50\namostra_aleatoria <- rf(n = 50, df1 = 4, df2 = 50)\namostra_aleatoria\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0.19102995 1.98529760 0.78537126 1.53334225 0.86646077 0.21788733\n [7] 2.52518562 1.11538295 1.51422579 0.74201507 2.32047414 1.70248638\n[13] 1.31543821 2.64128795 0.62561396 0.34272733 0.95758658 1.70471267\n[19] 0.33702073 0.27846082 2.64184884 0.76078407 0.51719001 0.46439880\n[25] 0.76693575 0.62200981 4.96470212 0.14416959 0.83920953 0.77250959\n[31] 0.41239292 0.30120260 1.38646280 1.16490291 0.83761761 1.27498409\n[37] 0.59402418 0.23310862 0.09351867 1.28626487 0.90983281 0.20644917\n[43] 1.13006060 0.51319698 0.92917764 0.91977304 0.11643606 0.58667216\n[49] 0.36195305 1.30987721\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Exercício 1\n\nEssas funções são úteis para resolver problemas de probabilidade envolvendo a distribuição *F*. Por exemplo, qual é a probabilidade de uma variável aleatória *F* com 4 e 50 graus de liberdade no numerador e no denominador, respectivamente, ser menor que 1? Qual a função deve ser usada?\n:::\n\n[Resposta]{.underline}:\n\nPode-se usar a função `pf()` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nq <- 1\npf(q, df1=4, df2=50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5835786\n```\n\n\n:::\n:::\n\n\nOu seja, ao se observar a curva da @fig-distf de cor verde (gl1 = 4 e gl2 = 50), a probabilidade abaixo de x = 1 é igual a 58,4%, arredondando.\n\n::: callout-tip\n## Exercício 2\n\nPara saber altura (densidade de probabilidade) da curva de cor verde quando *x* = 1, basta olhar na @fig-distf, ou seja, ao redor de 0.50. Entretanto, é difícil saber o valor exato. O que fazer para obter este valor?\n:::\n\n[Resposta]{.underline}:\n\nCalcular a densidade de probabilidade com a função `df()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 1\ndf(x, df1=4, df2=50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5207772\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Exercício 3\n\nQual o valor do nível crítico de F que deixa 50% da área da curva à esquerda, supondo-se os mesmos graus de liberdade anteriores?\n:::\n\n[Resposta]{.underline}:\n\nCalcular a com a função `qf()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.50 \nFcrit <- qf(p, df1 = 4, df2 = 50)\nFcrit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8506612\n```\n\n\n:::\n:::\n\n\nPara representar, graficamente, esse resultado, foi construído o gráfico da @fig-distf450 com a função `ggplot2()`. Verifica-se que a área sob a curva abaixo de 0,85 é igual a 50%.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Área da curva da distribuição F (4,50) abaixo de x = 0,85 é igual a 50%](15-anova_files/figure-html/fig-distf450-1.png){#fig-distf450 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n::: callout-tip\n## Exercício 4\n\nGerar 10.000 valores aleatórios de uma distribuição F (20, 100) e após plotar um histograma com curva da distribuição F sobreposta.\n:::\n\n[Resposta]{.underline}:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Parâmetros da distribuição F\ndf1 <- 20\ndf2 <- 100\n\n# Gerar 100.000 valores aleatórios da distribuição F\nset.seed(123)  # para reprodutibilidade\nvalores <- rf(10000, df1, df2)\n\n# Criar histograma com densidade\ndf_dados <- data.frame(F_valores = valores)\n\n# Curva teórica da distribuição F\nx_teorico <- seq(0, max(valores), length.out = 500)\ny_teorico <- df(x_teorico, df1, df2)\ndf_teorico <- data.frame(x = x_teorico, y = y_teorico)\n\n# Gráfico com histograma e curva teórica\nggplot(df_dados, aes(x = F_valores)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50, fill = \"lightblue\", color = \"black\", alpha = 0.6) +\n  geom_line(data = df_teorico, aes(x = x, y = y), color = \"red\", linewidth = 1.2) +\n  labs(\n    title = \"Histograma de valores simulados da distribuição F(20, 100)\",\n    subtitle = \"Com curva teórica sobreposta\",\n    x = \"Valor de F\",\n    y = \"Densidade\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Histograma com curva sobreposta de uma distribuição F (20,100)](15-anova_files/figure-html/fig-distfcurve-1.png){#fig-distfcurve fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nObservando o gráfico da @fig-distfcurve, verifica-se que a curva se assemelha muito com a curva normal (@sec-normal).\n\n### Cenário para a ANOVA de um fator\n\nA **análise de variância (ANOVA) de um fator**, também conhecida como ANOVA de uma via, é uma extensão do teste *t* independente para comparar duas médias em uma situação em que há mais de dois grupos. Dito de outra forma, o teste *t* para uso com duas amostras independentes é um caso especial da análise de variância de uma via. A ANOVA de um fator compara o efeito de uma variável preditora (variável independente, fator) sobre uma variável contínua (desfecho). Por exemplo, verificar se a intensidade do tabagismo na gestação afeta o peso dos recém-nascidos @fig-scatterfumo.\n\n::: callout-note\n## Contexto\n\nEstá bem documentada [@schuh2008efeitos] a associação entre tabagismo materno na gestação e redução do peso dos recém-nascidos. Em um estudo [@madi2010prevalence] foi registrado informações maternas e neonatais 1368 partos na maternidade do Hospital Geral de Caxias do Sul (HGCS), 2008.\n:::\n\n#### Dados do exemplo {#sec-dadosANOVA}\n\nPara testar a hipótese de que a intensidade do tabagismo materno afeta o peso do recém-nascido, foram selecionadas as variáveis `quant_fumo` (número de cigarros por dia) e `peso_rn` (peso ao nascer, em gramas) do banco de dados `dadosMater.xlsx` (@sec-dadosMater). A variável `quant_fumo` foi categorizada em três níveis, formando a variável `tabagismo`, por meio das funções `mutate()` e `case_when()`:\n\n- **Não fumantes**: gestantes que relataram nunca ter fumado;\\\n- **Fumantes leves**: gestantes que fumavam até 10 cigarros por dia;\\\n- **Fumantes intensas**: gestantes que fumavam mais de 10 cigarros por dia.\n\nEm seguida, foram filtrados os recém-nascidos a termo[^15-anova-5] (entre 37 e 41 semanas completas de gestação), e o resultado foi atribuído ao objeto `dados`. Como os grupos apresentavam tamanhos amostrais bastante desbalanceados[^15-anova-6], foi realizada uma subamostragem aleatória[^15-anova-7] de 120 gestantes não fumantes, de modo a equilibrar os três grupos para a análise. O conjunto final de dados balanceados foi atribuído ao objeto `dados_anova`.\n\n[^15-anova-5]: Filtrar recém-nascidos a termo (≥37 e \\<42 semanas) foi uma escolha para reduzir variabilidade.\n\n[^15-anova-6]: O desbalanceamento pode introduzir vieses com potencial de afetar a validade das conclusões, pois grupos pequenos podem não ser representativos; os grupos maiores podem ter uma média mais estável, enquanto que os menores podem ter flutuações aleatórias ou *outliers*.\n\n[^15-anova-7]: A subamostragem foi realizada com controle de aleatoriedade (`set.seed`) para garantir reprodutibilidade, e os grupos foram praticamente igualados , permitindo aplicação da ANOVA de uma via com maior robustez e comparabilidade entre os níveis de exposição ao tabagismo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosMater.xlsx\") |> \n  dplyr::select(quant_fumo, peso_rn, sexo, ig) |>   \n  dplyr::mutate(tabagismo = case_when(\n                  quant_fumo == 0 ~ \"Não\",\n                  quant_fumo >0 & quant_fumo <= 10 ~ \"Leve\",\n                  quant_fumo > 10  ~ \"Intenso\"),\n                tabagismo = factor(tabagismo,\n                                   levels = c(\"Não\", \"Leve\", \"Intenso\")),\n    sexo = factor(sexo,\n                  levels = c(1, 2),\n                  labels = c(\"Masc\", \"Fem\"))) |> \n  dplyr::filter(ig>=37 & ig < 42)\n\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [1,084 × 5] (S3: tbl_df/tbl/data.frame)\n $ quant_fumo: num [1:1084] 0 0 20 0 20 0 0 0 0 0 ...\n $ peso_rn   : num [1:1084] 3285 3100 3100 2800 3270 ...\n $ sexo      : Factor w/ 2 levels \"Masc\",\"Fem\": 1 1 1 1 1 1 1 1 1 1 ...\n $ ig        : num [1:1084] 37 37 37 38 39 39 39 39 39 39 ...\n $ tabagismo : Factor w/ 3 levels \"Não\",\"Leve\",\"Intenso\": 1 1 3 1 3 1 1 1 1 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dados$tabagismo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Não    Leve Intenso \n    853     121     110 \n```\n\n\n:::\n:::\n\n\nCorrigindo em parte o desbalanceamento:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subamostragem dos não fumantes\nset.seed(123)  # para reprodutibilidade\n\nnao_fumantes <- dados |>\n  filter(tabagismo == \"Não\") |>\n  slice_sample(n=120)\n\n# Manter os outros grupos como estão\nleves <- dados |> filter(tabagismo == \"Leve\")\nintensos <- dados |> filter(tabagismo == \"Intenso\")\n\n# Unir os três grupos balanceados\ndados_anova <- bind_rows(nao_fumantes, leves, intensos)\n\n# Manter apenas as variáveis necessárias\ndados_anova <- dados_anova |> \n  dplyr::select(sexo, tabagismo, peso_rn)\n\nstr(dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [351 × 3] (S3: tbl_df/tbl/data.frame)\n $ sexo     : Factor w/ 2 levels \"Masc\",\"Fem\": 1 1 1 2 1 2 1 1 1 1 ...\n $ tabagismo: Factor w/ 3 levels \"Não\",\"Leve\",\"Intenso\": 1 1 1 1 1 1 1 1 1 1 ...\n $ peso_rn  : num [1:351] 3110 2580 2965 3430 3060 ...\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(dados_anova$tabagismo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Não    Leve Intenso \n    120     121     110 \n```\n\n\n:::\n:::\n\n\n::: callout-caution\n## CUIDADO! Perda do Poder estatístico\n\nAo reduzir o grupo de `não fumantes` de 853 para 120, perde-se informação. E isso pode diminuir a precisão da estimativa da média desse grupo. Reduz o pode estatístico, ou seja, aumenta o risco de erro tipo II (veja @sec-erros).\n\nEntretanto, como o objetivo é comparar grupos de forma justa, esse sacrifício é aceitável — especialmente em análises exploratórias ou didáticas.\n:::\n\n#### Exploração e resumo dos dados\n\nAs medidas resumidoras serão obtidas, usando as funções `group_by ()` e `summarise ()` do pacote `dplyr`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha = 0.05\nresumo <- dados_anova |>\n  dplyr::group_by(tabagismo) |>\n  dplyr::summarise(n = n(),\n                   media = mean(peso_rn, na.rm = TRUE),\n                   dp = sd (peso_rn, na.rm = TRUE),\n                   ep = dp/sqrt(n),\n                   me = qt ((1-alpha/2), n-1)*ep,\n                   IC_Inf = media - me,\n                   IC_sup = media + me)\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 8\n  tabagismo     n media    dp    ep    me IC_Inf IC_sup\n  <fct>     <int> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>\n1 Não         120 3235.  461.  42.1  83.4  3152.  3319.\n2 Leve        121 3121.  444.  40.4  80.0  3041.  3201.\n3 Intenso     110 3059.  512.  48.8  96.8  2962.  3156.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia_geral <- mean(dados_anova$peso_rn)\nround(media_geral, 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3141\n```\n\n\n:::\n:::\n\n\n#### Visualização gráfica dos dados\n\nOs gráficos de dispersão (@fig-scatterfumo) são uma maneira interessante de visualizar os dados, principalmente com o pacote `ggplot2`[^15-anova-8] :\n\n[^15-anova-8]: Volte à @sec-ggplot2 para mais informações sobre o como fazer gráficos no `ggplot2.`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = dados_anova, \n       mapping = aes(x = tabagismo, y = peso_rn, fill = tabagismo)) +\n  geom_point(position = position_jitter(width = 0.2, height = 0),\n             shape = 21,\n             alpha = 1,\n             size = 3,\n             stroke = 1) +\n  stat_summary(fun = \"mean\", color = \"blue\", size = 3, geom = \"point\") +\n  geom_hline(yintercept=media_geral, linetype='dashed', col = 'red')+\n  scale_fill_brewer(palette = \"Pastel2\") +\n  annotate(geom=\"text\", \n           x=1.75, \n           y=1950, \n           label=\"Média Geral\",\n           color=\"red\") +\n  annotate(\"segment\", x = 1.5, xend = 1.5, \n           y = 2050, yend = 3120,\n           colour = \"red\", linetype = \"dashed\", \n           arrow = arrow(length = unit(0.18, \"cm\"),type = \"closed\"))+\n  labs(title=\"\",\n       x = \"Tabagismo Materno\",\n       y = \"Peso do Recém-nascido (g)\",\n       fill = \"\") +\n  theme_classic(base_size = 13) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Gráficos de dispersão do impacto do tabagismo materno no peso ao nascer](15-anova_files/figure-html/fig-scatterfumo-1.png){#fig-scatterfumo fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nA @fig-scatterfumo exibe uma variabilidade pequena entre as médias dos grupos (pontos azuis), comparada a média geral (linha vermelha tracejada) e uma grande variabilidade dentro dos grupos. Pensando na estatística F que avalia se a variância entre os grupos é substancialmente maior que a variância dentro dos grupos, pode-se esperar que o efeito do tabagismo sobre os pesos dos recém-nascidos não é tão acentuado.\n\n### Definição das hipóteses estatísticas\n\nNa ANOVA de um fator com três grupos, o objetivo é verificar se existem diferenças significativas entre as médias populacionais desses grupos.\n\nAssim , as hipóteses nula e alternativa são:\n\n- **Hipótese Nula:**Não há diferença entre as médias dos grupos. Ou seja todas as médias populacionais são iguais.\n\n$$H_{0}: \\mu_{1} = \\mu_{2} =  \\mu_{3}$$\n\n- **Hipótese alternativa:** Pelo menos, uma das médias é diferente das demais. Ela não é unilateral ou bilateral, é *multifacetada* porque permite qualquer relação que não seja *todas as médias iguais*. Por exemplo, a $H_1$ inclui o caso em que $μ_1=μ_2$, mas $μ_3$ tem um valor diferente.\n\n### Definição da regra de decisão\n\nO nível significância, $\\alpha$, geralmente escolhido é igual a 0,05. A distribuição da estatística do teste, sob a $H_{0}$, é a distribuição *F*. O número de graus de liberdade total $(n – 1)$ é dividido em dois componentes:\n\n- Grau de liberdade do numerador (ENTRE) é dado por $gl_{E} = k - 1$, onde *k* é o número de grupos.\n- Grau de liberdade do denominador (DENTRO ou residual) é dado por $gl_{D} = n - k$, onde, $n = \\sum n_{i}$.\n\nNo exemplo, para um $\\alpha = 0,05$, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nk <-  length(resumo$media)\nn <- nrow(dados_anova)\nglE <-  k - 1\nglE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\nglD <- n - k\nglD\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 348\n```\n\n\n:::\n:::\n\n\nCom esses dados, usando a função `qf()`calcula-se o valor crítico de *F* (@fig-fc2349) que é igual:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFcrit <- qf(1 - alpha, glE, glD)\nround(Fcrit, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.02\n```\n\n\n:::\n:::\n\n\nPortanto, se\n\n$$\\begin{array}{l}\n|F_{calculado}| < |F_{crítico}| \\Rightarrow \\text{não se rejeita } H_0 \\\\\n|F_{calculado}| \\ge |F_{crítico}| \\Rightarrow \\text{rejeita-se } H_0\n\\end{array}$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Curva da Distribuição F 3,196 = 2,65](15-anova_files/figure-html/fig-fc2349-1.png){#fig-fc2349 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\n### Teste Estatístico\n\nA estatística de teste é obtida calculando duas estimativas da variância populacional, $\\sigma^2$: a *variância entre os grupos* ($s_{E}^2$) e a *variância dentro dos grupos* ($s_{D}^2$).\n\nA variância entre os grupos também é chamada de *quadrado médio entre os grupos* ($QM_{E}$) e é igual a soma dos quadrados entre ($SQ_{E}$) ou do fator dividida pelos graus de liberdade entre:\n\n$$QM_{E} = \\frac{SQ_{E}}{gl_{E}}$$\n\nA variância dentro dos grupos é também denominada de *quadrado médio dentro dos grupos* ou residual ($QM_{D}$) e é igual a soma dos quadrados dentro dividida pelos graus de liberdade dentro:\n\n$$QM_{D} = \\frac {SQ_{D}}{gl_{D}}$$\n\nA variância entre os grupos, $QM_{E}$, dá uma estimativa de $\\sigma^2$ com base na variação entre as médias das amostras extraídas de diferentes populações. Para o exemplo das três categorias de tabagismo durante a gestação, o $QM_{E}$ será baseado nos valores das médias dos pesos dos recém-nascidos nos três grupos diferentes. Se as médias de todas as populações em consideração forem iguais, as médias das respectivas amostras ainda serão diferentes, mas a variação entre elas deverá ser pequena e, consequentemente, espera-se que o valor do $QM_{E}$ seja pequeno. No entanto, se as médias das populações consideradas não são todas iguais, espera-se que a variação entre as médias das respectivas amostras seja grande e, consequentemente, o valor de $QM_{E}$ seja grande.\n\nA variância dentro das amostras, $QM_{D}$, dá uma estimativa de $\\sigma^2$ com base na variação dos dados de diferentes amostras. Para o exemplo das três categorias de tabagismo durante a gestação, o $QM_{D}$ será baseado nas médias individuais dos pesos dos recém-nascidos incluídos nas três amostras retiradas de três populações. O conceito de $QM_{D}$ é semelhante ao conceito de desvio padrão conjugado ou agrupado, $s_{o}$, para duas amostras.\n\nA estatística de teste é, como já mencionado, a **razão das variâncias entre e dentro do grupo**. Dessa maneira,\n\n$$F = \\frac {s_{E}^2}{s_{D}^2} = \\frac {\\frac {SQ_{E}}{gl_{E}}}{\\frac {SQ_{D}}{gl_{D}}} = \\frac {QM_{E}}{QM_{D}}$$\n\n#### Ajuste do modelo\n\nNo R, para ajustar um modelo ANOVA clássica com um fator categórico, pode-se usar a função `aov()` do R base[^15-anova-9]. É uma função simples e direta para modelos balanceados. Ela espera a chamada notação de `fórmula`, portanto, os dados são incluídos separando as duas variáveis de interesse separadas por $\\sim$ (til) e os dados (`dados_anova`), onde as variáveis especificadas na fórmula, são encontradas.\n\n[^15-anova-9]: O teste estatístico também pode ser realizado com a função `anova_test()` do pacote `rstatix` que será usado na construção da @fig-view.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo.aov <- aov(peso_rn ~ tabagismo, dados_anova)  \nsummary(modelo.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df   Sum Sq Mean Sq F value Pr(>F)  \ntabagismo     2  1849499  924749   4.146 0.0166 *\nResiduals   348 77611700  223022                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nA saída, liberada pela função `summary()`, é bem reduzida, relatando as informações específicas da *Tabela da ANOVA*, a estatística *F* junto com o valor *p* e os graus de liberdade, soma dos quadrados (*Sum Sq*) e quadrados médios (*Mean Sq*), que com frequência se necessita para o relatório do modelo.\n\nA variância entre os grupos também é chamada de **quadrado médio entre os grupos** e é igual à soma dos quadrados entre ou do fator dividida pelos graus de liberdade entre. A variância dentro dos grupos é também denominada de **quadrado médio dentro dos grupos ou residual** e é igual à soma dos quadrados dentro dividida pelos graus de liberdade dentro.\n\nA ANOVA detectou um efeito significativo do fator, que neste caso é o `tabagismo`, o valor $F_{calculado} = 4,647 > F_{crítico} = 3.02$ e o valor *p* = 0,0102 (\\< 0,05).\n\nPode-se simplesmente relatar isso e encerrar, mas é provável que se queira saber quais grupos diferem uns dos outros. Lembre-se de que não se pode apenas inferir isso a partir de uma visão dos dados, existem testes estatísticos para ajudar a entender as diferenças dos grupos, que serão posteriormente realizados, após a avaliação dos pressupostos do modelo.\n\n#### Avaliação dos pressupostos do teste\n\nAo realizar um teste de ANOVA de um fator deve-se assumir que:\n\n1.  Exista normalidade dos resíduos [@altman1991anova];\n2.  Exista homogeneidade de variâncias: os grupos devem ter variâncias semelhantes (homocedasticidade);\n3.  Amostras aleatórias e independentes;\n4.  Todos os grupos devem ter tamanho amostral adequado. Grupos com menos de 10 participantes são problemáticos por reduzirem a precisão da média. Na prática, deve-se evitar menos de 30 participantes. A relação entre os grupos não deve ser maior do que 1:4 @peat2014anova;\n5.  Não devem existir valores atípicos (*outliers*);\n6.  A mensuração dos dados deve ser em nível intervalar ou de razão.\n\n##### Avaliação da normalidade\n\nVerifica-se a premissa de normalidade dos resíduos, usando o teste de Shapiro-Wilk e/ou desenhando um gráfico de probabilidade normal (*gráficos Q-Q*).\n\nOs resíduos podem ser diretamente assessados através do `modelo.aov`. Assim, cria-se uma variável nos `dados_anova` com o nome de `residuos`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova$residuos <- modelo.aov$residuals\n```\n:::\n\n\nPara avaliar a normalidade dos resíduos, pode-se usar a função `shapiro_test()` do pacote `rstatix`, usando um teste geral dos resíduos, pois dados têm tamanhos semelhantes e se quer validar a suposição global do modelo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova  |> \n  shapiro_test(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  variable statistic     p\n  <chr>        <dbl> <dbl>\n1 residuos     0.993 0.116\n```\n\n\n:::\n:::\n\n\nUma das maneiras de desenhar um gráfico Q-Q (@fig-qqres1), é através da função `ggqqplot ()` do pacote `ggpubr`. Ele produz uma linha de referência, acompanhada de área sombreada, correspondente ao $IC_{95\\%}$. Se os pontos acompanharem a linha de referência, pode-se aceitar a normalidade dos resíduos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggqqplot(\n  data = dados_anova,\n  x = \"residuos\",\n  color = \"steelblue\",\n  title = \"QQ Plot dos Resíduos\",\n  ylab = \"Quantis amostrais\",\n  xlab = \"Quantis teóricos\",\n  conf.int = TRUE)\n```\n\n::: {.cell-output-display}\n![Gráficos Q-Q](15-anova_files/figure-html/fig-qqres1-1.png){#fig-qqres1 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nA saída do teste de Shapiro-Wilk retornou um valor *p* = 0,082, ou seja, maior que 0.05 e, portanto, não há evidência de violação da normalidade. O gráfico Q-Q reforça está conclusão, e pode-se assumir que os resíduos têm uma distribuição praticamente normal.\n\n##### Verificação da presença de outliers\n\nPode-se aqui usar a função `identify_outliers()` do pacote `rstatix` [@kassambara2022rstatix] e, quando os grupos forem desbalanceados, usar a função `by_group()` do pacote `dplyr` para avaliar por nível de fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova  |>  \n  rstatix::identify_outliers(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   sexo  tabagismo peso_rn residuos is.outlier is.extreme\n   <fct> <fct>       <dbl>    <dbl> <lgl>      <lgl>     \n 1 Masc  Não          2051   -1184. TRUE       FALSE     \n 2 Masc  Leve         4350    1229. TRUE       FALSE     \n 3 Fem   Leve         1715   -1406. TRUE       FALSE     \n 4 Fem   Leve         4620    1499. TRUE       FALSE     \n 5 Masc  Intenso      1795   -1264. TRUE       FALSE     \n 6 Masc  Intenso      4410    1351. TRUE       FALSE     \n 7 Fem   Intenso      1895   -1164. TRUE       FALSE     \n 8 Fem   Intenso      4390    1331. TRUE       FALSE     \n 9 Fem   Intenso      4225    1166. TRUE       FALSE     \n10 Fem   Intenso      1785   -1274. TRUE       FALSE     \n```\n\n\n:::\n:::\n\n\nExistem 11 observações marcadas como `is.outlier = TRUE`, mas nenhuma como `is.extreme = TRUE`, o que indica que esses pontos estão fora dos limites interquartis (IIQ), mas não ultrapassam os limites extremos (\\> 3×IIQ). São *outliers* moderados, não extremos — ainda assim, merecem atenção, verificando se esses pontos têm influência desproporcional no modelo .\n\nPara isso, pode-se usar medidas de influência [@armitage_berry_matthews_2002], que são usadas na análise de regressão, pois a ANOVA pode ser encarada como um caso especial de regressão linear com variáveis categóricas. E como foi observado a presença de vários *outliers* eles devem ser avaliados, pois podem influenciar os coeficientes. Isto é particularmente importante quando se trabalha com poucos grupos ou grupos desbalanceados e também quando se tem mais de um fator e existe interação entre os fatores.\n\n1.  [Distância de Cook]{.underline}: avalia o impacto de cada ponto na estimativa dos coeficientes [@cook1986residuals]. É calculada pela função `cooks.distance()` que exige um objeto da classe `lm` (*linear model*) e, portanto, o modelo deve ser refeito. Este modelo necessita, como o `aov()`, de uma fórmula (`peso_rn~tabagismo`) e dos dados:\n\n\n    ::: {.cell layout-align=\"center\"}\n    \n    ```{.r .cell-code}\n    modelo_lm <- lm(peso_rn~tabagismo,data = dados_anova) \n    \n    plot(cooks.distance(modelo_lm), \n         type = \"h\", \n         main = \"\")\n    abline(h = 1, col = \"red\", lty = 2) \n    ```\n    \n    ::: {.cell-output-display}\n    ![Distância de Cook](15-anova_files/figure-html/fig-cook-1.png){#fig-cook fig-align='center' width=80% height=80%}\n    :::\n    :::\n\n\n    Valores acima de 1 (ou muito maiores que os demais) indicam alta influência. Como não existem valores acima de 1[^15-anova-10], a influência é pequena.\n\n2.  [Alavancagem]{.underline} (Leverage)\n\n    As estatísticas de alavancagem (ou valores *hat*) medem a influência do valor observado da variável desfecho sobre os valores previstos. Os valores de alavancagem podem situar-se entre 0 (o caso não tem qualquer influência) e 1 (o caso tem influência total ). Se nenhum caso exercer influência indevida sobre o modelo, seria de esperar que todos os valores de alavancagem se situassem próximos do valor médio. Alguns autores [@Hoaglin1978TheHM] recomendam investigar casos com valores superiores ao dobro da média como ponto de corte para identificar casos com influência indevida.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    valores_hat <- hatvalues(modelo_lm)\n    \n    summary(valores_hat)\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n        Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n    0.008264 0.008264 0.008333 0.008547 0.009091 0.009091 \n    ```\n    \n    \n    :::\n    \n    ```{.r .cell-code}\n    valores_altos <- valores_hat[valores_hat > 2 * summary(valores_hat)[4]]\n    valores_altos\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n    named numeric(0)\n    ```\n    \n    \n    :::\n    :::\n\n\n3.  [DFBETAS]{.underline} (Difference in BETA)\n\n    É uma medida de diagnóstico importante na análise de resíduos em um modelo linear. Ele serve para quantificar o quanto a remoção de uma única observação (um ponto de dados) **influencia** a estimativa de **cada coeficiente** no modelo [@belsley1980regression.]\n\n[^15-anova-10]: Por isso, não apareceu a linha vermelha horizontal tracejada com a função `abline(h = 1, col = \"red\", lty = 2)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfb <- dfbetas(modelo_lm)\nhead(dfb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) tabagismoLeve tabagismoIntenso\n1 -0.02437699    0.01727286       0.01685825\n2 -0.12789393    0.09062209       0.08844685\n3 -0.05262310    0.03728727       0.03639225\n4  0.03792146   -0.02687010      -0.02622512\n5 -0.03411360    0.02417195       0.02359174\n6  0.10624314   -0.07528095      -0.07347394\n```\n\n\n:::\n:::\n\n\nUm valor de DFBETAS grande em valor absoluto (positivo ou negativo) para uma observação específica e um coeficiente indica que essa observação é **altamente influente** na estimativa daquele coeficiente em particular.\n\nUm DFBETAS **positivo** significa que a remoção da observação fez com que a estimativa do coeficiente **diminuísse**. Um DFBETAS **negativo** significa que a remoção da observação fez com que a estimativa do coeficiente **aumentasse**.\n\nValores maiores que 1 ou menores que –1 (em amostras pequenas) indicam influência relevante. A função `summary()` permite ver os extremos por coeficiente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dfb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept)         tabagismoLeve        tabagismoIntenso    \n Min.   :-2.326e-01   Min.   :-1.949e-01   Min.   :-1.892e-01  \n 1st Qu.: 0.000e+00   1st Qu.:-1.935e-02   1st Qu.:-2.396e-02  \n Median : 0.000e+00   Median : 0.000e+00   Median : 0.000e+00  \n Mean   : 5.964e-06   Mean   : 2.049e-06   Mean   : 1.996e-06  \n 3rd Qu.: 0.000e+00   3rd Qu.: 1.880e-02   3rd Qu.: 1.961e-02  \n Max.   : 2.118e-01   Max.   : 2.080e-01   Max.   : 2.009e-01  \n```\n\n\n:::\n:::\n\n\nOs valores estão todos abaixo de 0.25, o que indica que nenhuma observação está alterando significativamente os coeficientes. O modelo está estável e não sofre influência desproporcional de nenhuma observação individual. Isso reforça a confiabilidade dos efeitos estimados para os níveis de tabagismo.\n\n##### Avaliação da homogeneidade das variâncias\n\nEm seguida, testa-se a suposição de que as variâncias são iguais, usando o Teste de Levene através da função `leveneTest ()` do pacote `car`.\n\nQuando há interação entre os fatores, cada combinação de níveis dos fatores forma um grupo distinto. O teste de Levene deve ser aplicado entre esses grupos combinados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest(peso_rn~tabagismo, \n                center = mean, \n                data = dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n       Df F value Pr(>F)\ngroup   2  1.3335 0.2649\n      348               \n```\n\n\n:::\n:::\n\n\nO teste de Levene exibe como resultado um valor *p* \\> 0,05, mostrando que não é possível rejeitar a $H_0$ de igualdade das variâncias.\n\nO teste de Levene calcula a **distância de cada observação ao centro do grupo** (média ou mediana), e testa se essas distâncias têm variâncias semelhantes entre os grupos. Quando os dados são aproximadamente normais usa-se `center = mean`. É mais sensível, mas menos robusto. Quando há `outliers` ou dados assimétricos, recomenda-se `center = median`, porque é mais robusto[^15-anova-11].\n\n[^15-anova-11]: Um método é mais **robusto** quando ele **continua funcionando bem mesmo que algumas suposições sejam violadas**, como presença de *outliers* ou dados não perfeitamente normais.\n\nObserve que , neste exemplo, tanto faz usar um ou outro método, pois os dados não violam o a pressuposição de normalidade:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::leveneTest (peso_rn~tabagismo, \n                 center = median, \n                 data = dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  1.3344 0.2647\n      348               \n```\n\n\n:::\n:::\n\n\nDa mesma maneira que no teste *t*, os pressupostos têm mais importância em grupos pequenos e desiguais. Para o exemplo em análise, os pressupostos foram verificados e pode-se assumir que os grupos são independentes e as médias têm distribuição normal e existe homocedasticidade, além disso, os grupos têm o tamanhos semelhantes. Portanto, a análise pode ser interpretada\n\n##### Interpretação\n\nA análise de variância de uma via foi aplicada para investigar o efeito do tabagismo sobre o escore da variável dependente. Os resultados indicaram diferenças estatisticamente significativas entre os níveis do fator, evidenciando que o tabagismo está associado a variações no escore analisado. A suposição de normalidade dos resíduos foi avaliada por meio do teste de Shapiro-Wilk, cujo resultado (p = 0,082) não indicou violação da normalidade. A presença de *outliers* foi identificada globalmente, com 11 observações classificadas como moderadas, distribuídas entre os grupos de tabagismo. Nenhuma observação foi considerada extrema, o que reduz o risco de distorção sistemática nos resultados. A análise de influência, realizada por meio dos DFBETAS e do gráfico de influência, demonstrou que nenhuma observação individual exerceu impacto relevante sobre os coeficientes do modelo. Os valores máximos de DFBETAS permaneceram abaixo de 0,25, indicando estabilidade nas estimativas, conforme os critérios propostos por Field [@field2012influential]. Dessa forma, o modelo ajustado pode ser considerado estatisticamente adequado, com efeitos confiáveis e interpretáveis entre os níveis do fator tabagismo. As suposições da ANOVA foram atendidas, e os resultados obtidos são válidos para fins de inferência.\n\n#### O que fazer se os pressupostos são violados?\n\nSe a homogeneidade da variância é o problema, um teste possível de ser implementado no *R* é o *F de Welch*, aplicando a função`welch.test()`, incluída no pacote `onewaytests` [@dag2018onewaytests]. Existem também testes não paramétricos, como o *Teste de Kruskal-Wallis*, que será visto mais adiante (@sec-kruskalwallis).\n\n### Testes *post-hoc*\n\nOs testes de comparações múltiplas constituem-se na análise após a realização de uma ANOVA significativa. Se houve uma diferença, indicada pela ANOVA, os testes de comparações múltiplas ou também conhecidos como *teste post hoc*, ajudam a quantificar as diferenças entre os grupos para determinar quais grupos diferem significativamente uns dos outros.\n\nAqui será usado o *HSD de Tukey*, que é conservador. *HSD* vem da expressão em inglês - *Honest Significant Difference* [@damasio2021posthoc]. Este teste requer um objeto `aov` no qual executa seu procedimento, que chamaremos de `pwc` [^15-anova-12]. O procedimento de Tukey HSD executará uma comparação de pares de todas as combinações possíveis dos grupos e testará esses pares para diferenças significativas entre suas médias, tudo enquanto ajusta o valor *p* a um limite superior de significância para compensar o fato de que muitos testes estatísticos estão sendo realizados e a probabilidade de um falso positivo aumenta com o aumento do número de testes. A função a ser usada é a `tukey_hsd()`, do pacote `rstatix`.\n\n[^15-anova-12]: Foi escolhido o nome `pwc` com o objetivo de lembrar que uma comparação de pares (*Pairwise Comparison)*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwc <- rstatix::tukey_hsd (modelo.aov)\npwc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  term  group1 group2 null.value estimate conf.low conf.high  p.adj p.adj.signif\n* <chr> <chr>  <chr>       <dbl>    <dbl>    <dbl>     <dbl>  <dbl> <chr>       \n1 taba… Não    Leve            0   -114.     -257.      29.5 0.149  ns          \n2 taba… Não    Inten…          0   -176.     -323.     -29.4 0.0138 *           \n3 taba… Leve   Inten…          0    -62.4    -209.      84.1 0.576  ns          \n```\n\n\n:::\n:::\n\n\nCom base nos valores *p* \\< 0,05 tem-se três combinações de grupos: Não-Leve, Não-Intenso e Leve-Intenso Isto mostra que uma diferença significativa (p = 0,0076) entre mães não fumantes e as fumates intensas. Os demais grupos não apresentaram uma diferença significativa.\n\nPode-se visualizar isso na @fig-tukeyhsd obtida , usando os resultados da função `tukey_hsd()` Esta função gera o teste de Tukey com as diferença entre os pares e os intervalos de confiança que permitem a construção do gráfico, com o código abaixo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Criar uma coluna com os pares comparados\npwc$comparacao <- paste(pwc$group1, \"vs\", pwc$group2)\n\n# Reordenar os pares para o eixo Y\npwc$comparacao <- factor(pwc$comparacao, levels = rev(pwc$comparacao))\n\n# Gráfico horizontal\nggplot(pwc, aes(x = estimate, y = comparacao, color = p.adj.signif)) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(xmin = conf.low, xmax = conf.high), \n                height = 0.2, \n                linewidth = 1.2, \n                orientation = \"y\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"gray40\") +\n  labs(\n    x = \"Diferença estimada no peso ao nascer (g)\",\n    y = \"Comparações entre grupos\",\n    color = \"Significância\") +\n  theme_bw(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Teste de Tukey ([**]: *p* entre 0,001 e 0,01; [ns]: *p* > 0,05).](15-anova_files/figure-html/fig-tukeyhsd-1.png){#fig-tukeyhsd fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n### Tamanho do efeito\n\nUma das medidas de tamanho de efeito mais comumente relatadas para a ANOVA é o **eta ao quadrado** ($\\eta^2$), que é um índice da força da associação entre um fator e uma variável dependente. Eta ao quadrado é a proporção da variação total atribuível ao fator. É calculado como a razão da variância do fator para a variância total e os valores variam de 0 a 1. Pode ser calculado o eta ao quadrado parcial ou generalizado. Aqui o eta ao quadrado parcial é suficiente, enquanto que para desenhos mais complexos, como ANOVA de medidas repetidas, está mais indicado o generalizado, pois além de incluir o efeito entre sujeito, inclui outros efeitos\n\nEsta medida pode ser obtida com o pacote `effectsize` [@ben2020effectsize], usando a função `eta_squared()`, usando o modelo `modelo.aov`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntep <- effectsize::eta_squared (modelo.aov, partial = TRUE)\n\neffectsize::interpret_eta_squared(tep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA\n\nParameter | Eta2 |       95% CI | Interpretation\n------------------------------------------------\ntabagismo | 0.02 | [0.00, 1.00] |          small\n\n- One-sided CIs: upper bound fixed at [1.00].\n- Interpretation rule: field2013\n```\n\n\n:::\n:::\n\n\nApesar de ser controverso, pode-se seguir a orientação da @tbl-effectsize, para a interpretação [@kirk1996practical; @watson2021effectsize]:\n\n\n::: {#tbl-effectsize .cell tbl-cap='Interpretação do Tamanho do Efeito'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-8e6beba6{}.cl-8e62c1ac{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8e62c1c0{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8e665362{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8e6690a2{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e6690ac{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e6690b6{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e6690b7{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e6690c0{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e6690ca{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-8e6beba6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-8e6690a2\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1ac\">Resultado</span></p></th><th class=\"cl-8e6690ac\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1ac\">Tamanho do Efeito</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8e6690b6\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">0.01</span></p></td><td class=\"cl-8e6690b7\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8e6690b6\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">0,06</span></p></td><td class=\"cl-8e6690b7\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">médio</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8e6690c0\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">0,14</span></p></td><td class=\"cl-8e6690ca\"><p class=\"cl-8e665362\"><span class=\"cl-8e62c1c0\">grande</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n::: callout-tip\n## Para curiosos\n\nO tamanho do efeito (**eta ao quadrado**) pode ser obtido de uma forma bem simples, sob o ponto de vista matemático. Ele é obtido pela fórmula, onde SQ = soma dos quadrados:\n\n$$\\eta^{2}=\\frac{SQ_{efeito}}{SQ_{total}}$$\n\nAssim, obtendo a soma dos quadrados a partir do `modelo.aov` utilizando a função `model_parameters()`[^15-anova-13] do pacote `parameters`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova <- parameters::model_parameters(modelo.aov)\n\nSS_efeito <- anova$Sum_Squares[1]\nSS_total <- anova$Sum_Squares[1]+anova$Sum_Squares[2]\n\neta_quadrado <- SS_efeito/SS_total\nround(eta_quadrado,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02\n```\n\n\n:::\n:::\n\n\nDesta forma , a variância do efeito, no caso tabagismo, corresponde a 0,03 (3%) da variância total.\n:::\n\n[^15-anova-13]: Para saber quais modelos são suportados pela função, digite no *Console* do *RStudio*: `parameters::supported_models()`\n\n### Conclusão da ANOVA de um fator\n\nO peso dos recém-nascidos foi estatisticamente diferente entre os diferentes grupos, *F*(2, 349) = 4.65, *P* = 0.0102, $\\eta^2$ = 0,03.\n\nAs análises *post-hoc* de Tukey revelaram que o peso dos recém-nascidos a termo no grupo das gestantes não fumantes apresentou uma diferença estatisticamente significativa do grupo de tabagismo intenso (-191g, IC95%: -339 a -42.1 g; *P* = 0,0076). Nos demais grupos não houve diferença significativa.\n\n### Apresentação dos resultados da ANOVA de um fator\n\nSerão apresentados boxplots (@fig-view), com `ggboxplot()`, do pacote `ggpubr`, utilizando as cores do pacote `ggsci`, paleta do periódico *New England Journal of Medicine* . Para adicionar teste estatístico, usou-se a função `get_test_label()` e para o teste *post hoc*, a função `get_pwc_label()`, ambas do pacote `rstatix`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Construir um gráfico de linha com ggline do ggpubr\ngbox <- dados_anova |> \n  ggpubr::ggboxplot(\n    x = \"tabagismo\",\n    y = \"peso_rn\",\n    bxp.errorbar = T,\n    bxp.errorbar.width = 0.1,\n    outliers = FALSE,\n    fill = \"grey90\",\n    xlab = \"Tabagismo Materno\" ,\n    ylab = \"Peso do Recém-nascido (g)\") +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    color = \"red\",\n    size = 3) +\n  theme (text = element_text (size = 13),\n         axis.text.x = element_text(size = 10),\n         axis.text.y = element_text(size = 10))\n\n# 2. Realizar a ANOVA com rstatix para verificar o efeito geral\nteste_anova <- rstatix::anova_test(dados_anova, \n                                   peso_rn ~ tabagismo)  |> \n  rstatix::add_significance()\n\n# 2. Realizar o Teste de Tukey (comparações múltiplas par a par)\npwc <- dados_anova |> \n  rstatix::tukey_hsd(peso_rn ~ tabagismo)  |> \n  rstatix::add_significance()\n\n# 3. Adicionar as posições x e y para as comparações post-hoc\npwc <- pwc  |>  \n  rstatix::add_xy_position(x = \"tabagismo\")\n\npwc <- pwc  |> \n  dplyr::mutate(y.position = c(4330, 4450, 4570))\n\n# 4. Plotar o gráfico com o resultado das comparações post-hoc\ngbox + \n  stat_pvalue_manual(pwc, \n                     tip.length = 0,\n                     hide.ns = FALSE) + \n  # Incluir a estatística da ANOVA no subtítulo\n  labs(subtitle = get_test_label(stat.test = teste_anova, \n                                 detailed = TRUE),\n       caption = get_pwc_label(pwc))\n```\n\n::: {.cell-output-display}\n![Efeito do tabagismo na gestação sobre o peso do recém-nascido.([**]: *p* entre 0,001 e 0,01; [ns]: *p* > 0,05).](15-anova_files/figure-html/fig-view-1.png){#fig-view fig-align='center' width=80% height=80%}\n:::\n:::\n\n\n## ANOVA de dois fatores\n\nA **ANOVA de dois fatores** é uma extensão da ANOVA de um fator. Neste tipo de ANOVA, ao invés de observar o efeito de um fator sobre a variável desfecho contínua, é analisado simultaneamente o efeito de duas variáveis de agrupamento. Outros sinônimos para a ANOVA de dois fatores são: *ANOVA fatorial* ou *ANOVA de duas vias*. Quando se tem dois ou mais fatores, além de observar o efeito desses fatores sobre a variável desfecho, há necessidade de verificar se eles não interagem entre si. Portanto, é um objetivo importante da ANOVA fatorial avaliar se há um efeito de *interação* estatisticamente significativo entre os fatores.\n\n### Dados para o exemplo {#sec-dadosaovII}\n\nO conjunto de dados, usado no exemplo, será o mesmo trabalhado na ANOVA de um fator (@sec-dadosANOVA) com as variáveis `peso_rn`, `sexo` e `tabagismo`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova <- dados_anova |> \n  dplyr::select(peso_rn, sexo, tabagismo)\n\nstr(dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [351 × 3] (S3: tbl_df/tbl/data.frame)\n $ peso_rn  : num [1:351] 3110 2580 2965 3430 3060 ...\n $ sexo     : Factor w/ 2 levels \"Masc\",\"Fem\": 1 1 1 2 1 2 1 1 1 1 ...\n $ tabagismo: Factor w/ 3 levels \"Não\",\"Leve\",\"Intenso\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nEstes dados permitem a sua aplicação em uma ANOVA de dois fatores, pois têm:\n\n- Uma **Variável Dependente** (numérica/contínua): `peso_rn` (Peso do Recém-Nascido, em gramas).\n\n- Duas **Variáveis Independentes** (categóricas/fatores): `sexo` (com 2 níveis: Masc, Fem) e `tabagismo` (com 3 níveis: Não, Leve, Intenso).\n\nA partir da ANOVA de dois fatores será possível avaliar:\n\n- O **Efeito Principal** do **`sexo`** no `peso_rn`.\n\n- O **Efeito Principal** do **`tabagismo`** no `peso_rn`.\n\n- O **Efeito de Interação** entre **`sexo`** e **`tabagismo`** no `peso_rn`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dados_anova$sexo, dados_anova$tabagismo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      \n       Não Leve Intenso\n  Masc  72   63      58\n  Fem   48   58      52\n```\n\n\n:::\n:::\n\n\nAtravés da função `table()`, observa-se que os dados têm uma estrutura um pouco mais complexa daquela da ANOVA de um fator, pois, à medida que aumentam os fatores, aumentam o número de células na estrutura do modelo. Existe uma preocupação a mais a ser analisada no ajuste do modelo. Esses dados estão claramente **desbalanceados**, tanto entre os níveis de tabagismo quanto entre os sexos. Tem-se um desenho 2 x 3 com cada célula contendo um número diferente de indivíduos. Isso pode afetar diretamente a forma como os efeitos são estimados em uma ANOVA de duas vias. Entretanto, as contagens variam de 48 a 72. Essa variação (máx/mín ≈ 1,5:1) é muito mais gerenciável. Segundo Peat [@Barton_Peat2014anova], um desequilíbrio no tamanho das células de mais de 1:4, no modelo, seria uma preocupação. Da mesma forma, um número mínimo por célula de 10, sendo desejável pelo menos 30, pois um número pequeno leva a uma perda de poder estatístico. Na prática, na área da saúde, igual número em cada uma das caselas é muito raro [@bland2015anova].\n\n#### Descrição dos dados\n\nNa saída da função `str()`, verifica-se que as variáveis de interesse: `tabagismo` está como fator com 3 níveis colocados de acordo com a intensidade de tabagismo materno em uma ordem lógica (Não, Leve e Intenso); a variável `sexo` está como fator em dois níveis: Masculino e Feminino e não tem uma ordem lógica. A variável peso do recém-nascido (`peso_rn`) é uma variável `num` (numérica).\n\nA sumarização dos dados será feita com as funções `group_by()` e `summarise()` do pacote `dplyr` para a variável `peso_rn` por grupos, `sexo` e `tabagismo`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nresumo <- dados_anova |> \n  dplyr::group_by(sexo, tabagismo) |> \n  dplyr::summarise(n = n(),\n                   media = mean(peso_rn, na.rm=TRUE),\n                   dp = sd(peso_rn, na.rm=TRUE),\n                   ep = dp/sqrt(n),\n                   me = qt((1 - alpha/2),n-1)*ep,\n                   linf = media - me,\n                   lsup = media + me,\n                   .groups = \"drop\")\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  sexo  tabagismo     n media    dp    ep    me  linf  lsup\n  <fct> <fct>     <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Masc  Não          72 3265.  456.  53.7  107. 3158. 3372.\n2 Masc  Leve         63 3198.  406.  51.1  102. 3096. 3300.\n3 Masc  Intenso      58 3153.  474.  62.2  125. 3029. 3278.\n4 Fem   Não          48 3191.  470.  67.9  137. 3054. 3327.\n5 Fem   Leve         58 3038.  473.  62.0  124. 2914. 3162.\n6 Fem   Intenso      52 2954.  537.  74.5  150. 2805. 3104.\n```\n\n\n:::\n:::\n\n\nUsou-se `.groups =`, para controlar o argumento final.\n\n- `= \"drop\"` , Remove todos os agrupamentos. O resultado fica como uma tabela comum;\n\n- `= \"drop_last\"` remove apenas o último agrupamento, mantendo o outro;\n\n- `= \"keep\"` mantém todos os agrupamentos (padrão).\n\n#### Visualização dos dados\n\nUm gráfico de dispersão (@fig-fumo1) é uma boa maneira de visualizar o comportamento das variáveis. Mostra o impacto dos níveis de tabagismo (não fumante, fumante leve e fumante pesado) sobre peso dos recém-nascidos de acordo com o sexo.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = dados_anova, \n       aes(x = tabagismo, y = peso_rn, fill = sexo)) +\n  geom_point(\n    position = position_jitterdodge(\n      jitter.width = 0.15,    # espalhamento horizontal\n      jitter.height = 0,      # mantém a altura real\n      dodge.width = 0.6),     # separação entre os subgrupos\n    shape = 21,\n    alpha = 1,\n    size = 3,\n    stroke = 1) +\n  stat_summary(\n    fun = \"mean\",\n    geom = \"point\",\n    color = c(\"red\", \"red\", \"red\", \"red\", \"red\", \"red\"),\n    size = 4,\n    position = position_dodge(width = 0.6),\n    show.legend = FALSE) +\n  scale_fill_brewer(palette = \"Pastel2\") +\n  labs(\n    x = \"Tabagismo Materno\",\n    y = \"Peso do Recém-nascido (g)\",\n    fill = \"Sexo\") +\n  theme_classic() +\n  theme (text = element_text (size = 13),\n         axis.text.x = element_text(size = 10),\n         axis.text.y = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![Efeito do tabagismo materno no peso do recém-nascido de acordo com o sexo.](15-anova_files/figure-html/fig-fumo1-1.png){#fig-fumo1 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nA dispersão dos pontos parece ser bastante semelhantes em todos os momentos. Observando as médias da @fig-fumo1 (pontos vermelhos centrais), verifica-se uma diminuição do peso dos recém-nascidos à medida que os níveis de tabagismo aumentam, bem como parece haver uma diferença entre os sexos.\n\n::: callout-note\n## Questão\n\nUma pergunta muito importante na ANOVA de duas vias é se o tabagismo afeta meninos e meninas de forma diferente?\n\nPara se ter uma ideia inicial, pode-se construir um gráfico de interação:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dados_anova, aes(x = tabagismo, y = peso_rn, color = sexo, group = sexo)) +\n  stat_summary(fun = mean, geom = \"point\", size = 3) +\n   stat_summary(fun = mean, geom = \"line\", linewidth = 1) +\n  scale_color_brewer(palette = \"Dark2\") +\n  labs(\n    x = \"Tabagismo Materno\",\n    y = \"Peso do Recém-nascido (g)\",\n    color = \"Sexo\") +\n  theme_classic() +\n  theme (text = element_text (size = 13),\n         axis.text.x = element_text(size = 10),\n         axis.text.y = element_text(size = 10))\n```\n\n::: {.cell-output-display}\n![Gráfico de Interação: Tabagismo x Sexo.](15-anova_files/figure-html/fig-fumo2-1.png){#fig-fumo2 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nA figura não sugere que exista uma interação entre o sexo e o nível de tabagismo materno, Ou seja, o efeito do tabagismo sobre o peso do recém-nascido a termo parece não depender do sexo. Observa-se que à medida que a intensidade do tabagismo aumenta, o peso do recém-nascido a termo, diminui (efeito principal de tabagismo). Meninos pesam mais que meninas (efeito principal de sexo)\n\nA diferença entre meninos e meninas é parecida em todos os níveis de tabagismo.\n:::\n\n### Hipóteses estatísticas\n\nComo mencionado acima, uma ANOVA de duas vias é usada para avaliar simultaneamente o efeito de duas variáveis categóricas em uma variável quantitativa contínua. Ela é chamada de ANOVA de duas vias porque compara grupos formados por duas variáveis categóricas independentes.\n\nA questão acima suscita várias hipóteses. Em particular, o interesse está em:\n\n1.  medir e testar a relação entre a tabagismo e o peso do recém-nascido,\n2.  medir e testar a relação entre sexo do recém-nascido e o seu peso, e\n3.  possivelmente verificar se a relação entre tabagismo e peso do recém-nascido é diferente para meninos e meninas (o que é equivalente a verificar se a relação entre sexo e peso do recém-nascido depende do tabagismo)\n\nAs duas primeiras relações são chamadas de **efeitos principais**, enquanto o item 3 é conhecido como **efeito de interação**.\n\nOs efeitos principais testam se pelo menos um grupo é diferente de outro (durante o controle da outra variável independente). Por outro lado, o efeito de interação tem como objetivo testar se a relação entre duas variáveis difere dependendo do nível de uma terceira variável. Em outras palavras, se a variação entre a resposta e a primeira variável categórica não depender das modalidades da segunda variável categórica, então não há interação entre as duas variáveis. Se, ao contrário, houver uma modificação dessa variação, seja por um aumento no efeito da primeira variável, seja por uma diminuição, então há uma interação.\n\nVoltando ao exemplo, a ANOVA de Duas Vias testa três hipóteses nulas ($H_{0}$):\n\n[Efeito principal do sexo no peso do recém-nascido:]{.underline}\n\n$H_{0}$: o peso médio do recém-nascido é igual entre meninas e meninos.\n\n$H_{1}$: o peso médio do recém-nascido é diferente entre meninas e meninos.\n\n[Efeito principal do tabagismo no peso do recém-nascido:]{.underline}\n\n$H_{0}$: o peso médio dos recém-nascidos é igual entre as categorias de tabagismo.\\\n$H_{1}$: o peso médio dos recém-nascidos é diferente entre as categorias de tabagismo\n\n[Interação entre sexo e tabagismo:]{.underline}\n\n$H_{0}$: não há interação entre sexo e tabagismo, o que significa que o efeito do tabagismo no peso do recém-nascido é o mesmo para meninas e meninos. \\\n$H_{1}$: há interação entre sexo e peso do recém-nascido, o que significa que o efeito do tabagismo no peso do recém-nascido é diferente para meninas e meninos.\n\n### Teste estatístico\n\nDe um modo geral, o software estatístico calcula a **Soma dos Quadrados**(SQ) para cada uma das fontes de variação (sexo, tabagismo, interação e resíduos) e a partir delas, calcula os **Quadrados Médios** (QM)[^15-anova-14] e dividindo cada um pelos seus respectivos graus de liberdade, obtém-se a estatística F para cada efeito. O valor de F é comparado a uma distribuição F (veja a @sec-distF) para obter o valor *p* associado a cada hipótese, de acordo com o valor de $\\alpha$ escolhido previamente (em geral, 0,05) .\n\n[^15-anova-14]: Que são as variâncias.\n\n$$F = \\frac{\\text{variância entre}}{\\text{variância dentro}} = \\frac{\\frac{SQ_{E}}{gl_{E}}}{\\frac{SQ_{R}}{gl_{R}}} =\\frac{QM_{E}}{QM_{D}}$$ O resultado do teste é tipicamente apresentado em uma tabela como esta (@tbl-anova), denominada de **Tabela da ANOVA**:\n\n\n::: {#tbl-anova .cell tbl-cap='Tabela da ANOVA'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-8fa9d578{}.cl-8f9f73b2{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8f9f73c6{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8fa30806{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8fa30810{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8fa33fba{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fc4{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fc5{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fce{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fcf{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fd8{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fd9{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fe2{width:1.3in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8fa33fe3{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-8fa9d578'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-8fa33fba\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73b2\">Fonte de Variação</span></p></th><th class=\"cl-8fa33fc4\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73b2\">Soma dos Quadrados</span></p></th><th class=\"cl-8fa33fc4\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73b2\">Graus de Liberdade</span></p></th><th class=\"cl-8fa33fc5\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73b2\">Quadrado Médio</span></p></th><th class=\"cl-8fa33fc5\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73b2\">Estatística F</span></p></th><th class=\"cl-8fa33fc5\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73b2\">Valor p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8fa33fce\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73c6\">Sexo(A)</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">SQA</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">1</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">QMA</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">FA</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">pA</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8fa33fce\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73c6\">Tabagismo(B)</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">SQB</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">2</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">QMB</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">FB</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">pB</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8fa33fce\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73c6\">Interação (A*B)</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">SQA*B</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">2</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">QMA*B</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">FA*B</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">pA*B</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8fa33fce\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73c6\">Resíduo/Erro</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">SQErro</span></p></td><td class=\"cl-8fa33fcf\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">346</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">QErro</span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\"></span></p></td><td class=\"cl-8fa33fd8\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-8fa33fd9\"><p class=\"cl-8fa30806\"><span class=\"cl-8f9f73c6\">Total</span></p></td><td class=\"cl-8fa33fe2\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">SQTotal</span></p></td><td class=\"cl-8fa33fe2\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\">351</span></p></td><td class=\"cl-8fa33fe3\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\"></span></p></td><td class=\"cl-8fa33fe3\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\"></span></p></td><td class=\"cl-8fa33fe3\"><p class=\"cl-8fa30810\"><span class=\"cl-8f9f73c6\"></span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nOs graus de liberdade são obtidos da seguinte maneira:\n\n- Graus de liberdade do fator A (sexo) = nº de níveis de A - 1 = 2 - 1 = 1;\\\n- Graus de liberdade do fator B (tabagismo) = nº de níveis de B - 1 = 3 - 1 = 2;\\\n- Graus de liberdade do Interação (sexo:tabagismo) = (nº de níveis de A - 1) x (nº de níveis de B - 1) = 1 x 2 = 2;\\\n- Graus de liberdade do Erro = Total de observações - nº de grupos formados pelos níveis dos fatores = 352 - (2 x 3) = 346;\\\n- Graus de liberdade total = 1 + 2 + 2 + 346 = 351.\n\n#### Ajustando um modelo com interação\n\nNa ANOVA de uma via, avalia-se diferenças entre médias considerando apenas uma variável independente. Uma das vantagens da ANOVA é que ela pode ser estendida para investigar simultaneamente o efeito de mais de um fator e, além disso, verificar se esses fatores interagem entre si.\n\nPara ajustar uma ANOVA de dois fatores no R, utiliza-se a mesma função `aov()`, acrescentando o segundo fator ao modelo. O operador ´\\*\\` é o mais apropriado, pois ele expande automaticamente para:\n\n$$Fator \\ 1 *\\ Fator \\ 2 = Fator \\ 1  +  Fator \\ 2 + Fator1:Fator2$$\n\nOu seja, inclui os dois efeitos principais e o termo de interação. Já o operador `:` representa apenas a interação, sem os efeitos principais, e portanto não corresponde ao modelo completo de ANOVA de duas vias.\n\nA inclusão da interação não é obrigatória, mas é recomendável iniciar a análise com o modelo completo (efeitos principais + interação). Caso a interação não seja significativa, ela pode ser removida, permitindo interpretar os efeitos principais de forma independente. Se a interação for significativa, ela deve ser mantida, pois indica que o efeito de um fator depende do nível do outro.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod.aov.int <- aov(formula = peso_rn ~ tabagismo * sexo, \n               data = dados_anova) \n\nsummary(mod.aov.int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df   Sum Sq Mean Sq F value  Pr(>F)   \ntabagismo        2  1849499  924749   4.220 0.01546 * \nsexo             1  1786278 1786278   8.152 0.00456 **\ntabagismo:sexo   2   232311  116156   0.530 0.58901   \nResiduals      345 75593111  219110                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n#### Interpretação do modelo com interação {#sec-tiposanova}\n\nSemelhante a uma ANOVA de uma via, o princípio de uma ANOVA de duas vias baseia-se na dispersão total dos dados e em sua decomposição em quatro componentes:\n\n1.  Parcela atribuível ao primeiro fator\n\n2.  Parcela atribuível ao segundo fator\n\n3.  Parcela atribuível à interação dos dois fatores\n\n4.  Parte não explicada ou residual.\n\nA soma dos quadrados (coluna `Sum Sq` ) mostra esses quatro componentes. A ANOVA de duas vias consiste em usar um teste estatístico para determinar se cada componente de variação (atribuível aos dois fatores estudados e à interação deles) é significativamente maior do que o componente residual. Se esse for o caso, concluí-se que o efeito considerado (tabagismo, sexo ou a interação) é significativo.\n\nVê-se que a variável `tabagismo` assim como a variável `sexo` mostraram-se significativas. Os valores *p* são exibidos na última coluna do resultado acima ( `Pr(>F )`). A partir desses valores, conclui-se que, no nível de $\\alpha$= 0,05 :\n\n- Controlando para o tabagismo, o peso dos recém nascidos são significativamente diferentes entre os dois sexos (*p* = 0,01),\n\n- Controlando para o sexo, o peso dos recém-nascidos é significativamente diferente (*p* \\< 0,01) para pelo menos uma categoria de tabagismo, e\n\n- A interação entre sexo e tabagismo (exibida na linha `tabagismo:sexo` no resultado) mostrou-se não significativa (*p* = 0,703). Isso quer dizer que o efeito do tabagismo não depende do sexo .\n\n::: callout-caution\n## Tipos de ANOVA (I, II e III) em desenhos balanceados e desbalanceados\n\n**Desenhos balanceados**\n\nQuando todas as células da ANOVA têm **o mesmo número de observações**, os três tipos de soma de quadrados — **Tipo I, Tipo II e Tipo III** — produzem **resultados idênticos** (mesmos SQ, F e p). A função `aov()` usa **Tipo I** (sequencial), mas isso **não faz diferença** em dados balanceados.\n\n**Desenhos desbalanceados**\n\nQuando as células têm tamanhos diferentes, os tipos de ANOVA passam a produzir resultados distintos:\n\n- **Tipo I (sequencial)** Depende da **ordem dos termos no modelo**. Ex.:\n\n  `peso_rn ~ tabagismo + sexo + tabagismo:sexo`\n\n  ou\n\n  `peso_rn ~ sexo + tabagismo + tabagismo:sexo`.\n\n- **Tipo II** Use quando **não há interação significativa**. Testa cada efeito principal ajustado para os outros efeitos principais.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAnova(modelo, type = \"II\")\n```\n:::\n\n\n- **Tipo III** Use quando **há interação significativa** e você ainda deseja testar efeitos principais. Testa cada efeito ajustado para **todos os outros termos**, incluindo a interação. Requer **contrastes de soma zero**:\n\n\n  ::: {.cell}\n  \n  ```{.r .cell-code}\n  options(contrasts = c(\"contr.sum\", \"contr.poly\"))\n  \n  Anova(modelo, type = \"III\")\n  ```\n  :::\n\n\n**Em resumo**\n\nA diferença entre os tipos de ANOVA está em **como a soma dos quadrados é calculada**. Em dados balanceados, isso não importa; em dados desbalanceados, escolher o tipo correto é essencial para interpretar o modelo corretamente.[^15-anova-15].\n:::\n\n[^15-anova-15]: Para os interessados, pode-se obter maiores informações sobre os diferentes tipos de ANOVA em <https://metricgate.com/blogs/anova-type-i-vs-type-ii-vs-type-iii-ss/>\n\nPode-se dar seguimento, ajustando o modelo sem a interação.\n\n#### Modelo sem interação\n\nA análise anterior mostrou que a interação não é significativa, deve-se re-analisar os efeitos principais usando a ANOVA Tipo II (que é o padrão quando não há interação).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod.aov <- aov(formula = peso_rn ~ tabagismo + sexo, \n               data = dados_anova) \n\ncar::Anova(mod.aov, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type II tests)\n\nResponse: peso_rn\n            Sum Sq  Df F value   Pr(>F)   \ntabagismo  1610778   2  3.6857 0.026067 * \nsexo       1786278   1  8.1745 0.004505 **\nResiduals 75825422 347                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n1.  Efeito do Tabagismo (p = 0.0153): conclui-se que o tabagismo tem um efeito estatisticamente significativo no peso, ajustado para o sexo. Isso significa que a diferença de peso entre os níveis (Não, Leve, Intenso) é real, independentemente de ser menino ou menina.\n2.  Efeito do Sexo ( *p =* 0.0088): conclui-se que sexo tem um efeito estatisticamente significativo no peso, ajustado para o tabagismo. Isso significa que a diferença de peso entre meninos e meninas é real, independentemente do nível de tabagismo.\n\n### Avaliação dos pressupostos\n\n#### Criação da variável residuos e valores ajustados\n\nComo os pressupostos são avaliados nos resíduos, eles, junto com os valores ajustados, serão obtidos a partir do modelo de ajuste em uso (`mod.aov`)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova$residuos <- mod.aov$residuals\n\nstr(dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [351 × 4] (S3: tbl_df/tbl/data.frame)\n $ peso_rn  : num [1:351] 3110 2580 2965 3430 3060 ...\n $ sexo     : Factor w/ 2 levels \"Masc\",\"Fem\": 1 1 1 2 1 2 1 1 1 1 ...\n $ tabagismo: Factor w/ 3 levels \"Não\",\"Leve\",\"Intenso\": 1 1 1 1 1 1 1 1 1 1 ...\n $ residuos : Named num [1:351] -183 -713 -328 281 -233 ...\n  ..- attr(*, \"names\")= chr [1:351] \"1\" \"2\" \"3\" \"4\" ...\n```\n\n\n:::\n:::\n\n\n#### Normalidade dos resíduos\n\nOs resíduos (erros) do modelo devem seguir uma distribuição normal. Isto pode ser verificado, como visto na ANOVA de uma via, com o teste Shapiro-Wilk, através da função `shapiro_test()` do pacote `rstatix`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova |>\n  shapiro_test(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  variable statistic      p\n  <chr>        <dbl>  <dbl>\n1 residuos     0.990 0.0199\n```\n\n\n:::\n:::\n\n\nO teste retornou um valor p = 0,0164 (*p* \\< 0,05). Isto indica evidência estatisticamente significativa de que os residuos não seguem uma distribuição normal, considerando um nível de significância de 5%. Entretanto, como um *n* \\> 30 por grupo a ANOVA costuma ser robusta a pequenas violações da normalidade.\n\n##### QQplot\n\nComplementando a avaliação da normalidade, será construído um QQ plot com a função `ggqqplot()` do pacote `ggpubr`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggqqplot(data = dados_anova,\n                 x = \"residuos\",\n                 conf.int = TRUE,\n                 shape = 19,\n                 xlab = \"Quantis teóricos\",\n                 ylab = \"Resíduos\",\n                 color = \"dodgerblue4\")\n```\n\n::: {.cell-output-display}\n![QQ Plot dos resíduos](15-anova_files/figure-html/fig-fumo3-1.png){#fig-fumo3 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nApesar do valor *p* de 0,0164 no teste de Shapiro-Wilk indicar desvio da normalidade, o gráfico QQ (@fig-fumo3) mostra que os resíduos seguem uma linha razoavelmente reta, com pequenas curvaturas apenas nas extremidades (caudas).\n\n##### Histograma\n\nUm histograma aumenta a segurança na avaliação da normalidade, principalmente quando o teste de Shapiro-Wilk rejeita a hipótese nula da normalidade:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::gghistogram(data = dados_anova, \n                    x = \"residuos\",\n                    fill = \"lightblue\",\n                    bins = 15,\n                    color = \"black\",\n                    ylab = \"Frequência\",\n                    xlab = \"Resíduos\")\n```\n\n::: {.cell-output-display}\n![Histograma dos resíduos](15-anova_files/figure-html/fig-fumo4-1.png){#fig-fumo4 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nA @fig-fumo4 do histograma dos resíduos, mostra uma distribuição aproximadamente simétrica, centrada em torno de 0, leves caudas mais pesadas, mas sem grandes distorções e sem assimetrias graves nem multimodalidade.\n\nA conclusão geral da avaliação da normalidade aponta um leve desvio de normalidade dos resíduos (valor *p* de 0,0164 no Shapiro-Wilk), mas com base no QQ plot razoavelmente linear e no histograma com forma quase normal e no tamanho amostral (\\> 100 por grupo), pode-se seguir com a ANOVA com segurança. A ANOVA é bastante robusta a essa leve violação.\n\n#### Homogeneidade da variância\n\nPara verificar a homoscedasticidade (igualdade de variâncias) na ANOVA de duas vias, o Teste de Levene é uma excelente escolha. A forma de aplicar o teste usa a função `leveneTest()` do pacote `car` e depende se a interação entre os fatores for incluída ou não.\\\nQuando há interação entre os fatores, cada combinação de níveis dos fatores:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n       Df F value Pr(>F)\ngroup   5  0.6881 0.6327\n      345               \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n       Df F value Pr(>F)\ngroup   5  0.6881 0.6327\n      345               \n```\n\n\n:::\n:::\n\n\nNo exemplo que está sendo testado não houve interação, então, o teste de Levene pode ser aplicado separadamente para cada fator principal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(peso_rn ~ tabagismo, data = dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  1.3344 0.2647\n      348               \n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(peso_rn ~ sexo, data = dados_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value  Pr(>F)  \ngroup   1  2.9781 0.08528 .\n      349                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n##### Gráfico diagnóstico\n\nGráficos diagnósticos podem ser criados usando a função `plot()` do R base. O gráfico de resíduos vs. valores ajustados ajuda a avaliar a homoscedasticidade dos resíduos e ausência de padrão sistemático nos resíduos. É obtido da seguinte maneira:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(mod.aov, which = 3)\n```\n\n::: {.cell-output-display}\n![Gráfico diagnóstico de homoscedasticidade](15-anova_files/figure-html/fig-fumo5-1.png){#fig-fumo5 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nA @fig-fumo5 mostra que a distribuição vertical dos resíduos parece razoavelmente constante em torno de zero, para todos os valores ajustados, não havendo uma heteroscedasticidade visível. Também não há um padrão em forma de funil, sinal de que o modelo está bem ajustado e os resíduos se comportam aleatoriamente.\\\nSão visíveis alguns *outliers* (resíduos bem distantes de zero), mas nada extremo ou preocupante considerando o tamanho da amostra.\n\nPortanto, apoiado no Teste de Levene e no gráfico da @fig-fumo5, pode-se concluir pela homogeneidade das variâncias.\n\n#### Outliers\n\nO gráfico diagnóstico @fig-fumo5 apontou alguns *outliers* que serão identificados, usando a função `identify_outliers()` do pacote `rstatix`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_anova |> \n  dplyr::group_by(sexo, tabagismo) |> \n  rstatix::identify_outliers(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   sexo  tabagismo peso_rn residuos is.outlier is.extreme\n   <fct> <fct>       <dbl>    <dbl> <lgl>      <lgl>     \n 1 Masc  Não          2051   -1242. TRUE       FALSE     \n 2 Masc  Não          4305    1012. TRUE       FALSE     \n 3 Masc  Não          4315    1022. TRUE       FALSE     \n 4 Masc  Leve         4350    1160. TRUE       FALSE     \n 5 Masc  Intenso      1980   -1147. TRUE       FALSE     \n 6 Masc  Intenso      1795   -1332. TRUE       FALSE     \n 7 Masc  Intenso      4410    1283. TRUE       FALSE     \n 8 Fem   Leve         1715   -1332. TRUE       FALSE     \n 9 Fem   Leve         4620    1573. TRUE       FALSE     \n10 Fem   Intenso      4390    1407. TRUE       FALSE     \n```\n\n\n:::\n:::\n\n\nAlguns *outliers* (11) foram identificados com base nos resíduos padronizados, mas não foram classificados como extremos (acima de $3 \\times IIQ$). Eles estão distribuídos entre diferentes combinações de fatores, o que sugere que não há viés sistemático. Considerando o tamanho amostral e a robustez da ANOVA, optou-se por mantê-los na análise.\n\n::: callout-tip\n## Resumo\n\n**Verificação dos pressupostos da ANOVA Fatorial**\n\nAntes da interpretação dos resultados obtidos por meio da Análise de Variância (ANOVA), é fundamental avaliar se os pressupostos do modelo foram atendidos. A validade das inferências estatísticas depende diretamente do cumprimento dessas condições.\n\n1.  Normalidade dos resíduos\\\n    A suposição de normalidade dos resíduos foi inicialmente avaliada por meio do teste de Shapiro-Wilk, cujo resultado indicou uma leve violação desse pressuposto (*p* = 0,02). Apesar disso, a inspeção visual do gráfico quantil-quantil (QQ plot) e do histograma dos resíduos revelou uma distribuição aproximadamente simétrica, com pequeno desvio nas caudas, sem indícios de distorções severas. Considerando o elevado tamanho amostral por grupo (superior a 100 observações), a ANOVA demonstra robustez suficiente para lidar com pequenas violações da normalidade.\n\n2.  Homogeneidade das variâncias (homocedasticidade)\n\n    A igualdade das variâncias entre os grupos foi testada por meio do teste de Levene, utilizando a mediana como medida de centralidade. O resultado (p = 0,7696) não indicou diferenças estatisticamente significativas entre as variâncias, corroborando o pressuposto de homocedasticidade. Essa evidência foi reforçada pelo gráfico de resíduos versus valores ajustados, no qual a dispersão dos resíduos se apresentou constante, sem tendência ou padrão sistemático.\n\n3.  Independência dos resíduos\\\n    A independência dos resíduos é assumida com base no delineamento experimental adotado, o qual não apresenta indícios de dependência entre as observações.\n\n4.  Identificação de valores atípicos (outliers)\\\n    Alguns resíduos foram identificados como outliers, porém nenhum foi classificado como extremo. Esses casos encontram-se distribuídos entre diferentes grupos e não apresentam padrão que indique viés sistemático. Dado o tamanho da amostra e o impacto estatístico limitado desses pontos, optou-se por mantê-los na análise.\n\n[Conclusão]{.underline}\\\nA análise conjunta dos testes estatísticos e das evidências gráficas indica que os pressupostos da ANOVA foram suficientemente atendidos. Dessa forma, os resultados inferenciais obtidos podem ser interpretados com segurança e validade estatística.\n:::\n\n### Testes post hoc\n\n#### Teste de Tukey\n\nQuando uma análise de variância (ANOVA) detecta diferenças estatisticamente significativas entre médias de grupos, o próximo passo é identificar quais pares de médias diferem entre si. Para isso, utiliza-se um teste post hoc, ou seja, um procedimento complementar que controla o erro tipo I em múltiplas comparações.\n\nEntre os testes post hoc disponíveis, o teste de Tukey HSD (*Honest Significant Difference*) é um dos mais utilizados pela sua robustez e facilidade de interpretação.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwc <- rstatix::tukey_hsd (mod.aov)\npwc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 9\n  term      group1 group2  null.value estimate conf.low conf.high   p.adj\n* <chr>     <chr>  <chr>        <dbl>    <dbl>    <dbl>     <dbl>   <dbl>\n1 tabagismo Não    Leve             0   -114.     -256.      28.0 0.143  \n2 tabagismo Não    Intenso          0   -176.     -321.     -30.9 0.0127 \n3 tabagismo Leve   Intenso          0    -62.4    -207.      82.6 0.569  \n4 sexo      Masc   Fem              0   -143.     -242.     -44.4 0.00461\n# ℹ 1 more variable: p.adj.signif <chr>\n```\n\n\n:::\n:::\n\n\n##### Gráfico com pontos (diferença média) e barras de erro(IC)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Criar uma coluna com os pares comparados\npwc$comparacao <- paste(pwc$group1, \"vs\", pwc$group2)\n\n# Reordenar os pares para o eixo Y\npwc$comparacao <- factor(pwc$comparacao, levels = rev(pwc$comparacao))\n\n# Gráfico horizontal\nggplot(pwc, aes(x = estimate, y = comparacao, color = p.adj.signif)) +\n  geom_point(size = 3) +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), width = 0.2, linewidth = 1.2) +\n  geom_vline(xintercept = 0, linetype = \"dashed\", color = \"gray40\") +\n  labs(\n    x = \"Diferença estimada no peso ao nascer (g)\",\n    y = \"Comparações entre grupos\",\n    color = \"Significância\"\n  ) +\n  theme_bw(base_size = 13) \n```\n\n::: {.cell-output-display}\n![Teste de Tukey](15-anova_files/figure-html/fig-fumo6-1.png){#fig-fumo6 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n##### Análise dos Testes Post-hoc (Tukey HSD)\n\n[Comparações entre níveis de tabagismo]{.underline}:\n\n1.  [Não fumante vs. Leve]{.underline}:\n\n    Não há diferença estatisticamente significativa no peso do recém-nascido entre os grupos \"Não Fumante\" e \"Fumante Leve\". A diferença estimada de **perda** (sinal negativo) ou **ganho** (sinal positivo) de peso foi de -113,75 g (IC~95%~: - 257,90; 30,41), *p* = 0,153.\n\n2.  [Não fumante vs. Intenso]{.underline}:\n\n    **Existe uma diferença estatisticamente significativa** no peso dos recém-nascidos entre os grupos \"Não Fumante\" e \"Fumante Intenso\". A diferença estimada de **perda** de peso foi de -190,72 g (IC~95%~: -338,07; -43,37), *p* = 0,007. Os recém-nascidos de mães fumantes intensas apresentaram peso significativamente menor do que os de mães não fumantes.\n\n3.  [Leve vs. Intenso]{.underline}:\n\n    Não há diferença estatisticamente significativa no peso dos recém-nascidos entre os grupos \"Fumante Leve\" e \"Fumante Pesado\". A diferença estimada de **perda** (sinal negativo) ou **ganho** (sinal positivo) de peso foi de -76,97 g (IC~95%~: - 224,03; 70,08), *p* = 0,435.\n\n    **Conclusão Principal:** O principal impacto no peso não vem da transição de \"Não Fumante\" para \"Fumante Leve\", mas sim da comparação entre os extremos, mostrando que a exposição intensa ao tabagismo causa uma redução de peso estatisticamente relevante.\n\n    [Comparação entre sexos]{.underline}:\n\n4.  [Masculino vs. Feminino]{.underline}:\n\n    A **comparação entre os sexos revelou diferença estatisticamente significativa** (p = 0,0089). Recém-nascidos do sexo masculino apresentaram, em média, peso 133,97 g superior ao dos do sexo feminino (IC~95%~: 33,78; 234,16).\n\n### Tamanho do Efeito\n\nO eta quadrado ($\\eta^{2}$) e omega quadrado ($\\omega^{2}$) para cada fator, que indicam quanto da variância total é explicada por cada um:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta <- effectsize::eta_squared (mod.aov, partial = TRUE)\neffectsize::interpret_eta_squared(eta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Eta2 (partial) |       95% CI | Interpretation\n----------------------------------------------------------\ntabagismo |           0.02 | [0.00, 1.00] |          small\nsexo      |           0.02 | [0.00, 1.00] |          small\n\n- One-sided CIs: upper bound fixed at [1.00].\n- Interpretation rule: field2013\n```\n\n\n:::\n\n```{.r .cell-code}\nomega <- effectsize::omega_squared (mod.aov, partial = TRUE)\neffectsize::interpret_omega_squared(omega)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type I)\n\nParameter | Omega2 (partial) |       95% CI | Interpretation\n------------------------------------------------------------\ntabagismo |             0.02 | [0.00, 1.00] |          small\nsexo      |             0.02 | [0.00, 1.00] |          small\n\n- One-sided CIs: upper bound fixed at [1.00].\n- Interpretation rule: field2013\n```\n\n\n:::\n:::\n\n\n### Relatando os resultados\n\n#### Construção de um gráfico com teste e valor *p*\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Construção do Boxplot Base\nggbox <- dados_anova |> \n  ggpubr::ggboxplot(\n    x = \"tabagismo\",\n    y = \"peso_rn\",\n    color = \"sexo\",\n    bxp.errorbar = TRUE,\n    bxp.errorbar.width = 0.15,\n    add = \"jitter\", \n    add.params = list(alpha = 0.3, size = 1.5), \n    palette = \"jama\",\n    outliers = FALSE) +\n  theme_classic() +\n  theme(text = element_text(size = 13),\n        axis.text.x = element_text(size = 10),\n        axis.text.y = element_text(size = 10),\n        legend.position = \"right\",\n        legend.key.size = unit(0.4, 'cm'),\n        legend.key = element_blank()) +  \n  \n  guides(color = guide_legend(title = NULL, \n                              override.aes = list(size = 3, \n                                                  linetype = 0, \n                                                  stroke = 0))) \n\n# 2. Realizar a ANOVA Geral e criar subtítulo com os resultados\nanova <- rstatix::anova_test(mod.aov) |>  \n  rstatix::add_significance()\n\nanova_clean <- rstatix::get_anova_table(anova)\nclass(anova_clean) <- \"data.frame\"\n\nanova_tab <- anova_clean |> dplyr::filter(Effect == \"tabagismo\")\nanova_sex <- anova_clean |> dplyr::filter(Effect == \"sexo\")\n\nsub_tab <- sprintf(\n  \"Tabagismo: F(%s,%s) = %.2f, p = %.3f\",\n  anova_tab$DFn, anova_tab$DFd, anova_tab$F, anova_tab$p\n)\n\nsub_sex <- sprintf(\n  \"Sexo: F(%s,%s) = %.2f, p = %.3f\",\n  anova_sex$DFn, anova_sex$DFd, anova_sex$F, anova_sex$p\n)\n\nsubtitulo_final <- paste(sub_tab, sub_sex, sep = \"   |   \")\n\n# 3. Tukey para tabagismo\npwc <- dados_anova |> \n  rstatix::tukey_hsd(peso_rn ~ tabagismo) |> \n  rstatix::add_significance()|> \n  add_xy_position(x = \"tabagismo\")\n\n# Você pode ajustar esses números (4500, 4700...) conforme o teto real dos seus dados\npwc$y.position <- 4500\n\n# 4. Plotar o gráfico final combinando tudo\nggbox +\n  ggpubr::stat_pvalue_manual(pwc,\n                             tip.length = 0.01, # Um dente bem pequeno fica melhor para indicar os limites\n                             hide.ns = TRUE) +\n  labs(\n    x = \"Tabagismo Materno\",                   # Garante que o rótulo bonito permaneça\n    y = \"Peso do Recém-nascido (g)\",           # Garante que o rótulo bonito permaneça\n    subtitle = subtitulo_final,\n    caption = rstatix::get_pwc_label(pwc))  \n```\n\n::: {.cell-output-display}\n![Gráfico mostrando o efeito do tabagismo de acordo com o sexo sobre o peso do recém-nascido a termo.([**] = p < 0,001)](15-anova_files/figure-html/fig-ggboxfinal-1.png){#fig-ggboxfinal fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nOs resultados da @fig-ggboxfinal indicam que tanto o sexo do recém-nascido a termo quanto o nível de tabagismo materno influenciam significativamente o peso ao nascer. Observou-se:\n\n- Um efeito negativo do tabagismo intenso sobre o peso neonatal, sugerindo impacto negativo crescente conforme o nível de exposição.\n\n  [Efeito do Tabagismo]{.underline} (@tbl-final1):\n\n\n::: {#tbl-final1 .cell tbl-cap='Efeito do tabagismo sobre o peso neonatal'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-91fdd81a{}.cl-91eddf3c{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-91eddf50{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-91f3f61a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-91f3f62e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-91f46f64{width:1.398in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f78{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f79{width:1.406in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f82{width:0.769in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f8c{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f8d{width:1.398in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f96{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f97{width:1.406in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46f98{width:0.769in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46fa0{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46faa{width:1.398in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46fb4{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46fb5{width:1.406in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46fb6{width:0.769in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-91f46fbe{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-91fdd81a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-91f46f64\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf3c\">Comparação</span></p></th><th class=\"cl-91f46f78\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf3c\">Diferença</span></p></th><th class=\"cl-91f46f79\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf3c\">IC95%</span></p></th><th class=\"cl-91f46f82\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf3c\">Valor p</span></p></th><th class=\"cl-91f46f8c\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf3c\">Sig</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-91f46f8d\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">Não vs. Leve</span></p></td><td class=\"cl-91f46f96\"><p class=\"cl-91f3f62e\"><span class=\"cl-91eddf50\">-113.75</span></p></td><td class=\"cl-91f46f97\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">[-257,90; 30,41]</span></p></td><td class=\"cl-91f46f98\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">0.153</span></p></td><td class=\"cl-91f46fa0\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">ns</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-91f46f8d\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">Não vs. Intenso</span></p></td><td class=\"cl-91f46f96\"><p class=\"cl-91f3f62e\"><span class=\"cl-91eddf50\">-190.72</span></p></td><td class=\"cl-91f46f97\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">[-338,07; -43,37]</span></p></td><td class=\"cl-91f46f98\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">0.007</span></p></td><td class=\"cl-91f46fa0\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">**</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-91f46faa\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">Leve vs. Intenso</span></p></td><td class=\"cl-91f46fb4\"><p class=\"cl-91f3f62e\"><span class=\"cl-91eddf50\">-76.97</span></p></td><td class=\"cl-91f46fb5\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">[-224,03; 70,08]</span></p></td><td class=\"cl-91f46fb6\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">0.435</span></p></td><td class=\"cl-91f46fbe\"><p class=\"cl-91f3f61a\"><span class=\"cl-91eddf50\">ns</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n- Um peso maior entre recém-nascidos do sexo masculino, corroborado pelos dados descritivos e pelos resultados inferenciais.\n\n  [Efeito do Sexo]{.underline} (@tbl-final2):\n\n\n::: {#tbl-final2 .cell tbl-cap='Efeito do sexo sobre o peso neonatal'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-923f23ba{}.cl-922f909e{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-922f90a8{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-9235c176{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-9235fca4{width:1.236in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fcb8{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fcb9{width:1.305in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fcc2{width:0.769in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fccc{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fccd{width:1.236in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fcd6{width:0.939in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fce0{width:1.305in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fcea{width:0.769in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-9235fceb{width:0.506in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-923f23ba'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-9235fca4\"><p class=\"cl-9235c176\"><span class=\"cl-922f909e\">Comparação</span></p></th><th class=\"cl-9235fcb8\"><p class=\"cl-9235c176\"><span class=\"cl-922f909e\">Diferença</span></p></th><th class=\"cl-9235fcb9\"><p class=\"cl-9235c176\"><span class=\"cl-922f909e\">IC95%</span></p></th><th class=\"cl-9235fcc2\"><p class=\"cl-9235c176\"><span class=\"cl-922f909e\">Valor p</span></p></th><th class=\"cl-9235fccc\"><p class=\"cl-9235c176\"><span class=\"cl-922f909e\">Sig</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-9235fccd\"><p class=\"cl-9235c176\"><span class=\"cl-922f90a8\">Masc vs. Fem</span></p></td><td class=\"cl-9235fcd6\"><p class=\"cl-9235c176\"><span class=\"cl-922f90a8\">133.97</span></p></td><td class=\"cl-9235fce0\"><p class=\"cl-9235c176\"><span class=\"cl-922f90a8\">[33,78; 234,16]</span></p></td><td class=\"cl-9235fcea\"><p class=\"cl-9235c176\"><span class=\"cl-922f90a8\">0.008</span></p></td><td class=\"cl-9235fceb\"><p class=\"cl-9235c176\"><span class=\"cl-922f90a8\">**</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nTodos os pressupostos da ANOVA foram adequadamente atendidos, permitindo confiança nos resultados obtidos.\n",
    "supporting": [
      "15-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}