{
  "hash": "f74faa7e8944a3fcc25b79b9e05dc1b6",
  "result": {
    "engine": "knitr",
    "markdown": "# Métodos não paramétricos\n\n## Pacotes necessários neste capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load (coin,\n                flextable,\n                ggpubr,\n                ggsci,\n                officer,\n                readxl,\n                rstatix,\n                tidyverse)\n```\n:::\n\n\n## Distribuição livre {#sec-distlivre}\n\nA maioria dos testes estatísticos, discutidos neste livro, são testes paramétricos. Nestes, o interesse estava focado em estimar ou testar uma hipótese sobre um ou mais parâmetros populacionais e ,por isso, são denominados de paramétricos. Além disso, o aspecto central desses procedimentos era o conhecimento da forma funcional da população da qual foram retiradas as amostras que forneceram a base para a inferência. Por exemplo, o teste *t* de Student para amostras independentes e a ANOVA são baseados no pressuposto de que os dados foram amostrados de populações que têm distribuição normal.\n\nOs **testes não paramétricos** não fazem suposições em relação à distribuição da população. Não têm, portanto, os pressupostos restritivos, comuns nos testes paramétricos. Têm *distribuição livre*. São baseados em uma ideia simples de ordenação por postos, do valor mais baixo ao mais alto. Analisam somente os postos, ignorando os valores. Podem ser usados tanto com variáveis ordinais como quantitativas numéricas.\n\n## Postos {#sec-postos}\n\nOs métodos estatísticos não paramétricos não lidam diretamente com os valores observados. Em função disso, para poder usar a informação fornecida pelas observações, sem trabalhar diretamente com os valores observados, utiliza-se os postos das observações. Posto (*rank*) de uma observação é a sua posição em relação aos demais valores.\n\nA atribuição dos postos de uma variável é realizada da seguinte maneira:\n\n1.  Colocam-se as observações em ordem crescente;\n2.  Associam-se valores, correspondendo às suas posições relativas na amostra. O primeiro elemento recebe o valor 1, o segundo o valor 2 e, assim por diante, até que a maior observação receba o valor *n*;\n3.  Se todas as observações são distintas, os postos são iguais aos valores associados às observações no passo anterior.\n4.  Para observações iguais (empates), associam-se postos iguais à média das suas posições relativas na amostra.\n\nPor exemplo, suponha uma amostra contendo os escores de Apgar no primeiro minuto de 10 recém-nascidos a termo (@tbl-apgar1). Em primeiro lugar, os valores são colocados em ordem crescente e, após, atribui-se postos aos valores. Observe que os postos atribuídos aos valores das posições 4, 5 e 6 são iguais e correspondentes a média de 4, 5 e 6, que é igual a 5. O mesmo ocorreu com os outros valores onde houve empate. A soma dos postos, no exemplo, é igual a 55. Para verificar a correção do cálculo, haja ou não empates, a soma dos postos será sempre $\\frac {n\\ \\times \\ (n+1)}{2}$. No exemplo, *n* = 10, logo $\\frac {10\\ \\times \\ (10+1)}{2}=55$.\n\n\n::: {#tbl-apgar1 .cell tbl-cap='Construção dos postos'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1cb506a0{}.cl-1ca8a496{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1ca8a4b4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1cad009a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1cad46f4{width:0.761in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad46fe{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad46ff{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad4708{width:0.761in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad4712{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad471c{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad471d{width:0.761in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad4726{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1cad4727{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1cb506a0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1cad46f4\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a496\">apgar1</span></p></th><th class=\"cl-1cad46fe\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a496\">ordem</span></p></th><th class=\"cl-1cad46ff\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a496\">posto</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">4</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">1</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">5</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">2</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">2.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">7</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">3</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">3.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">4</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">5.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">5</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">5.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">6</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">5.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">9</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">7</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">9</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">8.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad4708\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">10</span></p></td><td class=\"cl-1cad4712\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">9</span></p></td><td class=\"cl-1cad471c\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">9.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1cad471d\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">10</span></p></td><td class=\"cl-1cad4726\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">10</span></p></td><td class=\"cl-1cad4727\"><p class=\"cl-1cad009a\"><span class=\"cl-1ca8a4b4\">9.5</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n## Teste de Mann-Whitney\n\nO *teste de Mann-Whitney* é usado para analisar a diferença na variável dependente (desfecho) para dois grupos independentes. O teste classifica todos os valores dependentes, ou seja, o valor mais baixo obtém o posto um e, em seguida, usa a soma dos postos de cada grupo no cálculo da estatística de teste.\n\nÉ o substituto do teste *t* para amostras independentes quando os pressupostos deste teste são violados. Para a aplicação do teste de Mann-Whitney a variável de interesse deve ser ordinal ou numérica. Este teste é equivalente ao desenvolvido por Frank Wilcoxon (1892 – 1965), assim algumas vezes é denominado de *Wilcoxon Rank Sum Test* ou teste de Wilcoxon-Mann-Whitney [@MannWhitney1947]. O R usa esta denominação e é importante não confundir com o teste não paramétrico para amostra pareadas, discutido mais adiante.\n\n### Dados usados no exemplo\n\nOs dados do exemplo são do arquivo `dadosCirurgia.xlsx`, já usado na Seção @sec-dadosCirurgia. Ele contém 144 recém-nascidos que foram submetidos a diferentes procedimentos cirúrgicos. A questão de pesquisa a ser respondida é:\n\n> Existe diferença no tempo de hospitalização (`tempohosp`) dos recém-nascidos de acordo com a presença ou não de infecção (`infec`)?\n\nEssa pergunta foi respondida de outra maneira, na Seção @sec-tabextensas. Agora, será respondida pelo teste de Mann-Whitney.\n\n#### Leitura, exploração e visualização dos dados\n\nOs dados serão lidos com a função `read_excel()` do pacote `readxl`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncirurgia <- readxl::read_excel (\"dados/dadosCirurgia.xlsx\")\nstr(cirurgia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [144 × 7] (S3: tbl_df/tbl/data.frame)\n $ id       : num [1:144] 1 2 3 4 5 6 7 8 9 10 ...\n $ sexo     : chr [1:144] \"masc\" \"masc\" \"masc\" \"masc\" ...\n $ peso     : num [1:144] 2020 1850 2540 1150 2900 ...\n $ ig       : num [1:144] 36 30 38 31 36 37 38 39 38 39 ...\n $ tempohosp: num [1:144] 37 37 37 46 37 36 30 18 25 14 ...\n $ infec    : chr [1:144] \"não\" \"não\" \"sim\" \"sim\" ...\n $ cirurgia : chr [1:144] \"abdominal\" \"abdominal\" \"abdominal\" \"outra\" ...\n```\n\n\n:::\n:::\n\n\nA variável `infec` aparece como caractere e será transformada como fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncirurgia$infec <- factor(cirurgia$infec, levels = c(\"sim\", \"não\"))\n```\n:::\n\n\nOs boxplots (@fig-bpapgar1), construídos com a função `ggboxplot()` do pacote `ggpubr` com as cores da paleta do *New England Journal of Medicine (NEJM)*, são uma boa maneira de visualizar os dados:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggboxplot(cirurgia,\n                  x = \"infec\",\n                  y = \"tempohosp\",\n                  bxp.errorbar = TRUE,\n                  bxp.errorbar.width = 0.1,\n                  fill = \"infec\",\n                  palette = \"nejm\",\n                  legend = \"none\",\n                  ggtheme = theme_bw(),\n                  xlab = \"Presença de infecção\" ,\n                  ylab = \"Tempo de hospitalização (dias)\")   \n```\n\n::: {.cell-output-display}\n![Impacto da infecção no pós-operatório no tempo de hospitalização](20-testes-naoParametricos_files/figure-html/fig-bpapgar1-1.png){#fig-bpapgar1 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOs boxplots exibem uma série de valores atípicos, indicando que existe uma assimetria em ambos os grupos. Essa assimetria também pode ser verificada usando o teste de Shapiro-Wilk, que mostrando valores *p* \\< 0,05, confirma que os dados não seguem a distribuição normal. Este teste não é pré-requisito para o teste. Foi realizado como uma demonstração.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncirurgia |> \n  dplyr::group_by(infec) |> \n  rstatix::shapiro_test(tempohosp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  infec variable  statistic        p\n  <fct> <chr>         <dbl>    <dbl>\n1 sim   tempohosp     0.692 1.47e- 9\n2 não   tempohosp     0.565 9.87e-15\n```\n\n\n:::\n:::\n\n\n#### Sumarização dos dados\n\nComo a variável `tempohosp` é assimétrica conforme mostrado acima, onde ambos os valores *p* são menores do que 0,05, será realizado um sumário numérico com a obtenção da mediana e IIQ. Isto será feito através da função `group_by()` e `summarise()`, incluídas no pacote `dplyr`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- cirurgia |> \n  dplyr::group_by(infec) |> \n  dplyr::summarise(n = n(),\n                   mediana = median (tempohosp, na.rm = TRUE),\n                   p25=quantile(tempohosp, probs = 0.25, na.rm = TRUE),\n                   p75=quantile(tempohosp, probs = 0.75, na.rm = TRUE))\nres\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  infec     n mediana   p25   p75\n  <fct> <int>   <dbl> <dbl> <dbl>\n1 sim      56      37  22.8    49\n2 não      88      23  18      37\n```\n\n\n:::\n:::\n\n\nOs dados mostram que a mediana de tempo de internação dos neonatos infectados é bem maior do que a mediana dos não infectados.\n\n### Hipóteses estatísticas\n\nDa mesma maneira que o teste *t*, as hipóteses estabelecidas comparam dois grupos independentes. Se não houver diferença entre os grupos, ou seja, os grupos são provenientes de populações com distribuições iguais, as somas dos postos em cada grupo devem ficar próximas. Desta forma,\n\n> $H_{0}$: As duas populações têm distribuições iguais.\n\n> $H_{1}$: As duas populações não têm distribuições iguais.\n\nNão foi escrita a hipótese nula como sendo que as médias (ou as medianas) são iguais, pois o teste não usa as medidas de posição tradicionais e sim os postos.\n\n### Pressupostos do teste de Mann-Whitney\n\nO teste de Mann-Whitney é baseado nos seguintes pressupostos:\n\n1.  Os dados são aleatórios;\n2.  As amostras são de dois grupos independentes;\n3.  Um dos grupos é denominado de 1 e o outro de 2;\n4.  A variável a ser comparada nos grupos deve ser ordenável;\n5.  O grupo 1 será o grupo de menor tamanho e, se tiverem o mesmo tamanho, o grupo 1 é aquele cuja soma dos postos é a menor.\n\n### Cálculo da estatística de teste\n\n#### Lógica do teste U de Mann-Whitney\n\nDe acordo com as hipóteses estabelecidas, o teste é bicaudal. Se as observações nos dois grupos forem provenientes da mesma população, a soma dos postos em cada grupo devem ficar próximas.\n\nPara calcular o teste, procede-se da seguinte maneira:\n\n1.  Deve haver uma variável que identifique o grupo a que pertence cada uma das observações. No exemplo proposto, a variável desfecho é `tempohosp` e a variável agrupadora é `infec`, categorizada como `sim` e `não`.\n\n2.  Ordenar de forma crescente todos os valores da variável `tempohosp`, sem levar em consideração a que grupo pertence. Para realizar este procedimento, será usada a função `rank()` do R base com o método para empates igual à média dos valores empatados (`ties.method=\"average`). Ao executar a função, será criada uma nova variável, denotada `postos`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncirurgia$postos <- rank(cirurgia$tempohosp, ties.method = \"average\") \nhead(cirurgia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n     id sexo   peso    ig tempohosp infec cirurgia  postos\n  <dbl> <chr> <dbl> <dbl>     <dbl> <fct> <chr>      <dbl>\n1     1 masc   2020    36        37 não   abdominal   94.5\n2     2 masc   1850    30        37 não   abdominal   94.5\n3     3 masc   2540    38        37 sim   abdominal   94.5\n4     4 masc   1150    31        46 sim   outra      120  \n5     5 masc   2900    36        37 não   abdominal   94.5\n6     6 fem    2480    37        36 sim   abdominal   91  \n```\n\n\n:::\n:::\n\n\n3.  Verificar o tamanho (*n*) de cada grupo (presença ou não de infecção) e somar os postos em cada um dos grupos, usando a função `group_by()` junto com a função `summarise()`,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- cirurgia |> \n  dplyr::group_by(infec) |> \n  dplyr::summarise(soma = sum(postos))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  infec  soma\n  <fct> <dbl>\n1 sim   4876.\n2 não   5564.\n```\n\n\n:::\n:::\n\n\n4.  Denominar de *grupo_1* o grupo com menor soma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrupo_1 <- min(resumo$soma)\ngrupo_1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4875.5\n```\n\n\n:::\n:::\n\n\n5.  Denotar o *grupo_1* como T\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT <- grupo_1\n```\n:::\n\n\nConsequentemente,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- res$n[1]\nn1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 56\n```\n\n\n:::\n\n```{.r .cell-code}\nn2 <- res$n[2]\nn2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88\n```\n\n\n:::\n:::\n\n\n6.  Calcular a estatística do teste, usando a fórmula preconizada por Altman [@altman1991mannwhitney]:\n\n$$U =n_{1} \\times n_{2} \\ +\\left [\\frac{n_{1} \\times \\left (n_{1} + 1  \\right )}{2}  \\right ] - T$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nU <- (n1*n2 + ((n1*(n1 + 1))/2)) - T\nU\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1648.5\n```\n\n\n:::\n:::\n\n\n**Obs**.: O U de Mann-Whitney aparece no teste de Wilcoxon como W, eles representam o mesmo.\n\n7.  Se $n_{1}$, $n_{2}$ $\\ge$ 10, a distribuição da estatística do teste pode ser aproximada por uma distribuição normal com média igual a\n\n$$\\mu_{U} =\\left [\\frac{n_{S} \\times \\left (n_{S} + n_{L} + 1  \\right )}{2}  \\right ]$$\n\nonde $n_{S}$ e $n_{L}$, são, respectivamente, o grupo de menor e maior tamanho. No exemplo, $n_{1}$ e $n_{2}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_U <- (n1*(n1+n2+1))/2\nm_U\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4060\n```\n\n\n:::\n:::\n\n\nE desvio padrão igual a\n\n$$\\sigma_{U}= \\sqrt {\\frac{n_{1}\\times n_{2} \\times (n_{1}+n_{2}+1)}{12}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndp_U <- sqrt((n2*m_U)/6)\ndp_U\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 244.0219\n```\n\n\n:::\n:::\n\n\nOs resultados fornecem os dados para calcular a estatística $Z_{U}$ com correção de continuidade e, a partir dela, calcular o valor *P*.\n\n$$Z_{U}= \\frac{(T -0,5) - \\mu_{U}}{\\sigma_{U}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ_U <- ((T - 0.5) - m_U)/dp_U\nround(Z_U, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.34\n```\n\n\n:::\n:::\n\n\n8.  Finalmente, calcula-se o valor *p*, usando a função `pnorm()`, multiplicada por 2, pois o teste é bicaudal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalor_p <- pnorm(Z_U, lower.tail = FALSE) * 2\nround(valor_p, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8e-04\n```\n\n\n:::\n:::\n\n\nNa prática, não há necessidade de fazer todos esses cálculos, pois o R calcula facilmente o teste. Os cálculos foram mostrados para melhorar o entendimento de como o teste de Mann-Whitney funciona.\n\n#### Cálculo do teste de Mann-Whitney no R\n\nO teste pode ser realizado com a função `wilcox_test()` [^20-testes-naoparametricos-1] do pacote `rstatix`:\n\n[^20-testes-naoparametricos-1]: O cálculo pode também ser realizado, usando a função `wilcox.test()` do pacote `stats`, incluído no R base.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste <- rstatix::wilcox_test(formula = tempohosp ~ infec, data = cirurgia)\nteste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  .y.       group1 group2    n1    n2 statistic        p\n* <chr>     <chr>  <chr>  <int> <int>     <dbl>    <dbl>\n1 tempohosp sim    não       56    88     3280. 0.000830\n```\n\n\n:::\n:::\n\n\nO valor *p* \\< 0,001 confirma a diferença estatisticamente significativa, em concordância com o cálculo manual. No entanto, a estatística **W** reportada pelo R difere do **U** calculado manualmente. Isso ocorre por dois motivos:\n\n1.  **Grupos de referência diferentes**: o cálculo manual segue a convenção de Altman e usa como referência o grupo com a **menor** soma de postos (aqui, o grupo \"não infectado\"); o `wilcox_test()` calcula W para o **primeiro nível do factor** (`infec = \"sim\"`), independentemente de qual grupo tem a menor soma de postos.\n\n2.  **Estatísticas complementares**: U (manual) e W (R) referem-se a grupos opostos e satisfazem a relação $W + U = n_1 \\times n_2$. Somados, devem totalizar o produto dos tamanhos dos dois grupos.\n\n\n    ::: {.cell}\n    \n    ```{.r .cell-code}\n    teste$statistic + U == n1 * n2\n    ```\n    \n    ::: {.cell-output .cell-output-stdout}\n    \n    ```\n       W \n    TRUE \n    ```\n    \n    \n    :::\n    :::\n\n\nO **valor *p*** é idêntico nos dois casos — a conclusão não muda.\n\n### Tamanho do efeito {#sec-tefMW}\n\nÉ interessante calcular o tamanho do efeito, a magnitude do efeito. O tamanho do efeito *r* é calculado como a estatística $Z_{U}$ dividida pela raiz quadrada do tamanho da amostra ($n = n_{1} + n_{2}$).\n\n$$r = \\frac {Z_{U}}{\\sqrt{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- Z_U/sqrt(n1+n2)\nround(r,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.278\n```\n\n\n:::\n:::\n\n\nO R possui a função `wilcox_effsize()` incluída no pacote `rstatix`. Necessita também do pacote `coin` [@hothorn2006lego] instalado para calcular a estatística *r*.[^20-testes-naoparametricos-2] A saída exibirá junto a magnitude o efeito, que no caso é pequena (veja @tbl-wilcoxef).\n\n[^20-testes-naoparametricos-2]: Para maiores detalhes consulte a ajuda da função.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox_effsize(cirurgia, tempohosp~infec)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  .y.       group1 group2 effsize    n1    n2 magnitude\n* <chr>     <chr>  <chr>    <dbl> <int> <int> <ord>    \n1 tempohosp sim    não      0.279    56    88 small    \n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-wilcoxef .cell tbl-cap='Interpretação do valor r'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1e14e056{}.cl-1e0c80aa{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e0c80be{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e0c80bf{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-1e0fc828{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e0fc83c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-1e0ffc8a{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e0ffc94{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e0ffc9e{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-1e0ffc9f{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1e14e056'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-1e0ffc8a\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80aa\">r</span></p></th><th class=\"cl-1e0ffc8a\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80aa\">magnitude</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e0ffc94\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">0,10 &lt; 0,30</span></p></td><td class=\"cl-1e0ffc94\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e0ffc94\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">0,30 &lt; 0,50</span></p></td><td class=\"cl-1e0ffc94\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">médio</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-1e0ffc9e\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">&gt;= 0,50</span></p></td><td class=\"cl-1e0ffc9e\"><p class=\"cl-1e0fc828\"><span class=\"cl-1e0c80be\">grande</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-1e0ffc9f\"><p class=\"cl-1e0fc83c\"><span class=\"cl-1e0c80bf\">Sem considerar o sinal</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n### Conclusão\n\nO valor $p < 0,0001$ está bem abaixo do nível de significância estabelecido ($\\alpha = 0,05)$. Pode-se concluir que o tempo de hospitalização nos dois grupos é estatisticamente diferente. Entretanto, a magnitude dessa diferença é pequena.\n\nIsto pode ser visualizado no gráfico (@fig-bpres):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncirurgia |> \n  ggplot2::ggplot( aes(x=infec, y=tempohosp, fill = infec)) +\n  geom_errorbar(stat = \"boxplot\", width = 0.1) +\n  geom_boxplot() +\n  scale_fill_bmj() +\n  labs(\n    subtitle = rstatix::get_test_label(teste, detailed = TRUE),\n    x =\"Presença de infecção\",\n    y=\"Tempo de hospitalização (dias)\") +\n  theme_bw() +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Impacto da infecção no pós-operatório no tempo de hospitalização](20-testes-naoParametricos_files/figure-html/fig-bpres-1.png){#fig-bpres fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n## Teste de Wilcoxon para amostras pareadas\n\nO *teste de Wilcoxon*, também conhecido como teste dos postos com sinais de Wilcoxon (*Wilcoxon Signed-Rank Test*), é um teste não paramétrico utilizado em situações em que existem dois conjuntos de dados emparelhados, ou seja, dados provenientes do mesmo participante. O teste não examina os dois grupos individualmente; em vez disso, ele se concentra na diferença existente entre cada par de observações. É um equivalente não paramétrico do teste *t* pareado [@Wilcoxon1945].\n\n### Dados usados como exemplo\n\n::: callout-note\n## Cenário\n\nPara verificar se a realização de exercícios aeróbicos modifica a função respiratória de 10 escolares asmáticos, foi medido o Pico de Fluxo Expiratório Máximo (*Peak Flow Meter*) no início e no final do programa, após 120 dias. O Pico de Fluxo Expiratório Máximo (PFE), medido em L/min, serve como uma forma simples de avaliar a força e a velocidade de saída do ar de dentro dos pulmões.\n:::\n\nOs dados têm apenas três variáveis, `id`(identificação), `basal` (PFE basal) e `final`(PFE final).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid <- c(1:10)\nbasal <- c(120, 200, 140, 200, 110, 240, 150, 120, 250, 190)\nfinal <- c(220, 300, 230, 180, 300, 330, 230, 250, 300, 200)\n\ndados <- tibble(id, basal, final)\n\nstr (dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [10 × 3] (S3: tbl_df/tbl/data.frame)\n $ id   : int [1:10] 1 2 3 4 5 6 7 8 9 10\n $ basal: num [1:10] 120 200 140 200 110 240 150 120 250 190\n $ final: num [1:10] 220 300 230 180 300 330 230 250 300 200\n```\n\n\n:::\n:::\n\n\nA questão de pesquisa a ser respondida, portanto, é:\n\n> Existe diferença entre as medidas iniciais e finais do PFE dos escolares asmáticos que entraram em um programa de exercícios aeróbicos?\n\n#### Exploração e transformação dos dados\n\nOs dados estão no formato amplo com as variáveis basal e final classificadas como númericas. Serão transformados para o formato longo, usando a função `pivot_longer()` do pacote `tidyr`. Este processo é opcional, mas, como foi feito com o teste *t* pareado, será repetido aqui, por questões didáticas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL <- dados |> \n  tidyr::pivot_longer(c(basal, final), \n                      names_to = \"momento\", \n                      values_to = \"medidas\")\nstr(dadosL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [20 × 3] (S3: tbl_df/tbl/data.frame)\n $ id     : int [1:20] 1 1 2 2 3 3 4 4 5 5 ...\n $ momento: chr [1:20] \"basal\" \"final\" \"basal\" \"final\" ...\n $ medidas: num [1:20] 120 220 200 300 140 230 200 180 110 300 ...\n```\n\n\n:::\n:::\n\n\n#### Medidas resumidoras\n\nComo o número de participantes é de apenas 10, a medida de posição mais adequada para resumir os dados é mediana e a medida de dispersão é o intervalo interquartil (IIQ). Para isso, se fará uso das funções `group_by()` e `summarise()` do pacote `dplyr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dadosL |> \n  dplyr::group_by(momento) |> \n  dplyr::summarise(n = n(),\n                   mediana = median (medidas, na.rm = TRUE),\n                   p25=quantile(medidas, probs = 0.25, na.rm = TRUE),\n                   p75=quantile(medidas, probs = 0.75, na.rm = TRUE),\n                   media = mean (medidas, na.rm = TRUE),\n                   dp = sd (medidas, na.rm = TRUE),\n                   ep = dp/sqrt(n),\n                   me = ep * qt(1 - (0.05/2), n - 1))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 9\n  momento     n mediana   p25   p75 media    dp    ep    me\n  <chr>   <int>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1 basal      10     170  125    200   172  50.9  16.1  36.4\n2 final      10     240  222.   300   254  50.4  15.9  36.0\n```\n\n\n:::\n:::\n\n\n#### Visualização dos dados\n\nPode-se fazer visualização gráfica dos dados usando um boxplot (@fig-aero) ou um gráfico de linha (@fig-aero1).\n\n##### Boxplot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggboxplot(dadosL,\n                  x = \"momento\",\n                  y = \"medidas\",\n                  bxp.errorbar = TRUE,\n                  bxp.errorbar.width = 0.1,\n                  fill = \"momento\",\n                  palette = c(\"cyan4\", \"cyan3\"),\n                  legend = \"none\",\n                  ggtheme = theme_bw(),\n                  xlab = \"Momento\" ,\n                  ylab = \"PEF (L/min) \")+\n  theme (text = element_text (size = 13),\n         axis.text.x= element_text(size = 12)) \n```\n\n::: {.cell-output-display}\n![Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos](20-testes-naoParametricos_files/figure-html/fig-aero-1.png){#fig-aero fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n##### Gráfico de linha\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggline(dadosL,\n               x = \"momento\",\n               y = \"medidas\",\n               color = \"cyan4\",\n               linetype = \"dashed\",\n               size = 0.7,\n               add = \"mean_ci\",\n               point.size = 2,\n               xlab = \"Momento\" ,\n               ylab = \"PEF (L/min) \",\n               ggtheme = theme_bw()) +\n  theme (text = element_text (size = 13),\n         axis.text.x= element_text(size = 12))\n```\n\n::: {.cell-output-display}\n![Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos](20-testes-naoParametricos_files/figure-html/fig-aero1-1.png){#fig-aero1 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n#### Criação de uma variável que represente a diferença entre os momentos\n\nA diferença entre as médias basal e final será atribuída ao nome `D`. Esta ação será realizada, utilizando o banco de dados amplo (`dados`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$D <- dados$basal - dados$final\nhead (dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n     id basal final     D\n  <int> <dbl> <dbl> <dbl>\n1     1   120   220  -100\n2     2   200   300  -100\n3     3   140   230   -90\n4     4   200   180    20\n5     5   110   300  -190\n6     6   240   330   -90\n```\n\n\n:::\n:::\n\n\n[Resumo da variável D]{.underline}\n\nAo resumo será atribuído ao nome `resumo2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo2 <- dados |> \n  dplyr::summarise(n = n (),\n                   mediana = median (D, na.rm = TRUE),\n                   p25=quantile(D, probs = 0.25, na.rm = TRUE),\n                   p75=quantile(D, probs = 0.75, na.rm = TRUE))\nresumo2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n mediana   p25   p75\n  <int>   <dbl> <dbl> <dbl>\n1    10     -90  -100 -57.5\n```\n\n\n:::\n:::\n\n\nO sinal negativo demonstra que houve um aumento do PFE do momento basal para o final.\n\n### Definição das hipóteses estatísticas\n\nDa mesma maneira que o teste *t* pareado, as hipóteses estabelecidas comparam dois grupos dependentes. O teste de Wilcoxon é usado para avaliar a hipótese nula de que a distribuição das diferenças entre os grupos tem uma diferença mediana igual a 0.\n\n> $H_{0}: A \\ mediana \\ da \\ (D_{i}) = 0$\n\n> $H_{A}: A \\ mediana \\ da \\ (D_{i}) \\ne 0$\n\nNote que a $H_{A}$ estabelece que a diferença pode aumentar ou diminuir. Logo, o teste é bicaudal.\n\n### Execução do teste estatístico\n\n#### Lógica do teste de Wilcoxon\n\n1.  A ideia do teste é verificar se as diferenças positivas são maiores ou menores, em grandeza absoluta, que as diferenças negativas. Para isso, foi criada, anteriormente, a variável `D`. Agora, será criada outra variável, igual à variável `D`, apenas ignorando o sinal, denominada `D_abs`, diferença absoluta entre as variáveis `final` e `basal`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$D_abs <- abs(dados$basal - dados$final)\n```\n:::\n\n\n2.  Excluir os casos com diferença igual a 0 (zero). Para isso, uma maneira possível é extrair um subconjunto de dados do conjunto principal (`dados`), criando um conjunto de dados com a função `filter()` do pacote `dplyr`, que receberá o nome de `dados1`. O argumento `D_abs != 0` significa todas as diferenças absolutas diferentes de 0:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados1 <- dados |> dplyr::filter(D_abs != 0)\n```\n:::\n\n\nObserve que como não há diferenças zeradas. Ou seja, o novo conjunto de dados continua o mesmo. O que pode ser confirmado, executando a função `str()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr (dados1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [10 × 5] (S3: tbl_df/tbl/data.frame)\n $ id   : int [1:10] 1 2 3 4 5 6 7 8 9 10\n $ basal: num [1:10] 120 200 140 200 110 240 150 120 250 190\n $ final: num [1:10] 220 300 230 180 300 330 230 250 300 200\n $ D    : num [1:10] -100 -100 -90 20 -190 -90 -80 -130 -50 -10\n $ D_abs: num [1:10] 100 100 90 20 190 90 80 130 50 10\n```\n\n\n:::\n:::\n\n\n3.  Ordenar de forma crescente todos os valores da variável `D_abs` do banco de dados `dados1`, usando a função `arrange()` do pacote `dplyr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados1 <- dados1 |> dplyr::arrange(dados1$D_abs)\n```\n:::\n\n\n4.  Estabelecer postos para os valores ordenados da variável `D_abs`, do conjunto de dados `dados1`, fazendo a média das ordens quando houver empate. A execução deste comando cria uma nova variável, chamada `postos`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados1$postos <- rank(dados1$D_abs)\n```\n:::\n\n\n5.  Estabelecer sinais para os postos, criando dois subconjuntos de dados do conjuntos dados1, um com os escolares com postos positivos (`pos`) e outros com postos negativos(`neg`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneg <- dados1 |> dplyr::filter(D < 0)\npos <- dados1 |> dplyr::filter(D > 0)\n```\n:::\n\n\n6.  Somar todos os postos (variável `posto`) em cada um dos subconjuntos criados (`neg` e `pos`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsoma_neg <- sum(neg$postos)\nsoma_pos <- sum(pos$postos)\nprint (c(soma_neg, soma_pos))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 53  2\n```\n\n\n:::\n:::\n\n\n7.  Atribuir a menor soma à estatística do teste, denotada *T*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nT <- min (soma_neg : soma_pos)\nT\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n:::\n\n\n8.  Para dados com tamanhos grandes (\\> 20 pares), a significância de *T* pode ser determinada [@zar2014wilcoxon], considerando que a distribuição de *T* tem aproximadamente distribuição normal com média igual a\n\n$$\\mu_{T} =\\frac{n \\times \\left (n + 1  \\right )}{4}$$\n\nonde *n* é o tamanho da amostra.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(dados$D)\nmu_T <- (n * (n + 1))/4\nmu_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 27.5\n```\n\n\n:::\n:::\n\n\nE desvio padrão igual a:\n\n$$\\sigma_{T}= \\sqrt {\\frac{n\\left (n + 1  \\right )\\times \\left (2n + 1  \\right )}{24}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndp_T <- sqrt ((n*(n + 1)) * (2 * n + 1) /24) \ndp_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.810708\n```\n\n\n:::\n:::\n\n\nOs resultados da execução das equações fornecem os dados para calcular a estatística `Z_T` com correção de continuidade e, a partir dela, calcular o valor *p*.\n\n$$Z_{T}= \\frac{\\left |T - \\mu_{T}  \\right | - 0,5}{\\sigma_{T}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ_T <- (abs(T - mu_T)- 0.5)/dp_T\nZ_T\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.548236\n```\n\n\n:::\n:::\n\n\n9.  Concluindo, o valor da estatística de teste *T* é superior ao $Z_{crítico} = 1,96$, para um $\\alpha = 0,05$. Dessa forma, a $H_{0}$ é rejeitada. Existe uma diferença significativa entre o PFE basal e o PFE final, neste grupo de escolares asmáticos.\n\n10. O valor *p* pode ser obtido com a função `pnorm()` e multiplicando o resultado por 2, pois o teste é bilateral.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalor_p <- pnorm (Z_T, lower.tail = FALSE) * 2\nvalor_p\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01082692\n```\n\n\n:::\n:::\n\n\nComo já dito anteriormente, na prática, não há necessidade de fazer todos esses cálculos, pois o R calcula facilmente o teste. Eles são apenas uma demonstração de como o teste funciona.\n\n#### Cálculo do teste de Wilcoxon no R\n\nUsando o conjunto de dados no formato longo (`dadosL`), calcula-se o teste com a função `wilcox_test()` do pacote `rstatix`. É a mesma função utilizada para o teste de U de Mann-Whitney, mudando apenas o argumento `paired=FALSE` para `paired=TRUE`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste1 <- dadosL |> \n  rstatix::wilcox_test(medidas ~ momento, paired = TRUE) |> \n  rstatix::add_significance()\nteste1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 8\n  .y.     group1 group2    n1    n2 statistic       p p.signif\n  <chr>   <chr>  <chr>  <int> <int>     <dbl>   <dbl> <chr>   \n1 medidas basal  final     10    10         2 0.00586 **      \n```\n\n\n:::\n:::\n\n\nObserve que o resultado é o mesmo calculado manualmente.\n\n### Tamanho do efeito\n\nO tamanho do efeito pode ser calculado da mesma forma que para o teste de Mann-Whitney (@sec-tefMW), usando a mesma equação e os dados obtidos acima, onde 2.548 e *n* = 10 tem-se\n\n$$r = \\frac {Z_{T}}{\\sqrt{n}}$$\n\nPode-se usar também a função `wilcox_effsize()` para calcular a estatística *r*. A Saída exibe junto a magnitude o efeito, que no caso é grande (\\> 0,5 como mostra a @tbl-wilcoxef do teste de Mann-Whitney).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL |> \n  wilcox_effsize(medidas ~ momento, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  .y.     group1 group2 effsize    n1    n2 magnitude\n* <chr>   <chr>  <chr>    <dbl> <int> <int> <ord>    \n1 medidas basal  final    0.823    10    10 large    \n```\n\n\n:::\n:::\n\n\n### Conclusão\n\nAssumindo um $\\alpha = 0,05$, se o valor *p*, obtido pelo teste, for menor do que 0,05, rejeita-se a hipótese nula (V = 2, *p* = 0,01, *n* = 10).\n\nPode-se concluir que existe diferença nas medidas do pico de fluxo expiratório máximo no início e no fim do programa de exercícios aeróbicos realizados pelos escolares asmáticos e a magnitude do efeito foi grande (*r* = 0,82).\n\nIsto pode ser visualizado na @fig-aero2:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbxp <- ggpubr::ggboxplot(dadosL,\n                         x = \"momento\",\n                         y = \"medidas\",\n                         bxp.errorbar = TRUE,\n                         bxp.errorbar.width = 0.1,\n                         fill = \"momento\",\n                         palette = c(\"cyan4\", \"cyan3\"),\n                         legend = \"none\",\n                         ggtheme = theme_bw(),\n                         xlab = \"Momento\" ,\n                         ylab = \"PEF (L/min) \") +\n  theme (text = element_text (size = 13),\n         axis.text.x = element_text(size = 11))\n\nteste <- dadosL |> \n  rstatix::wilcox_test (medidas ~ momento, paired = TRUE) |>\n  rstatix::add_significance ()\nteste <- teste |> rstatix::add_xy_position ()\n\nbxp + \n  stat_pvalue_manual (teste, \n                      tip.length = 0) +\n  labs (subtitle = get_test_label (stat.test = teste, \n                                   detailed = TRUE))\n```\n\n::: {.cell-output-display}\n![Impacto de exercícios aeróbicos na função respiratória de 10 escolares asmáticos](20-testes-naoParametricos_files/figure-html/fig-aero2-1.png){#fig-aero2 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n## Teste de Kruskal-Wallis {#sec-kruskalwallis}\n\nQuando os pressupostos subjacentes à ANOVA não são atendidos, é possível usar o teste não paramétrico de Kruskal-Wallis (KW) para testar a hipótese de que os parâmetros de localização são iguais [@KruskalWallis1952]. Pode ser considerado uma extensão do teste de Wilcoxon-Mann-Whitney.\n\nEnquanto a ANOVA depende da hipótese de que todas as populações são independentes e com resíduos normalmente distribuídos, o teste de Kruskal-Wallis exige apenas amostras aleatórias independentes provenientes de suas respectivas populações. Entretanto, este teste somente deve ser aplicado se a amostra for pequena e/ou os pressupostos para a ANOVA forem seriamente violados.\n\nO teste não usa diretamente medições de quantidade conhecida, utiliza, como outros testes não paramétricos, os postos dos valores analisados. Em função disso, é também conhecido como *análise de variância de um fator em postos*.\n\n### Dados usados no exemplo\n\n::: callout-note\n## Cenário\n\nUm experimento foi realizado para verificar se o álcool ou o café afetam os tempos de reação ao dirigir [@karadimitriou2020kruskal]. O estudo tem três grupos diferentes de participantes: 10 bebendo água (controle), 10 bebendo cerveja contendo duas unidades de álcool[^20-testes-naoparametricos-3] e 10 bebendo café. O tempo de reação em uma simulação de direção foi medido para cada participante.\n:::\n\n[^20-testes-naoparametricos-3]: Para calcular as unidades de álcool, multiplique o volume da bebida (em mililitros) pelo teor alcoólico (ABV, do inglês *Alcohol by Volume*) e divida o resultado por 1000.\n\nOs dados encontram-se no arquivo `dadosResposta.xlsx`. Clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosResposta.xlsx) para baixar e, após, salve o mesmo no seu diretório de trabalho.\n\nAs variáveis são:\n\n- **id** $\\to$ identificação do participante;\n- **tempo** $\\to$ tempo de reação na simulação de direção em segundos;\n- **bebida** $\\to$ três grupo: água, álcool e café.\n\nO estudo pretende verificar se existe diferença no tempo de reação dos participantes em um teste de direção com a ingesta de água, café e álcool.\n\n#### Leitura e exploração dos dados\n\nComo o dados estão contidos em um arquivo Excel (*.xlsx*), serão lidos com a função `read_excel()` do pacote `readxl` e a sua estrutura será observada com função `str()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel (\"dados/dadosResposta.xlsx\")\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [30 × 3] (S3: tbl_df/tbl/data.frame)\n $ id    : num [1:30] 1 2 3 4 5 6 7 8 9 10 ...\n $ tempo : num [1:30] 0.37 0.38 0.61 0.78 0.83 0.86 0.9 0.95 1.63 1.97 ...\n $ bebida: chr [1:30] \"agua\" \"agua\" \"agua\" \"agua\" ...\n```\n\n\n:::\n:::\n\n\nO formato do arquivo é o longo. A variável bebida encontra-se como caracter e deve ser transformada em fator e as categorias na sequência: `agua`, `cafe` e `alcool`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$bebida <- factor(dados$bebida, \n                       levels = c(\"agua\", \"cafe\", \"alcool\"))\n```\n:::\n\n\nOs dados serão observados visualmente através de boxplots (@fig-bebida), usando a função `ggplot()` do pacote `ggplot2`, com cores do `nejm` (*New England Journal of Medicine*) o pacote `ggsci`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggboxplot(dados,\n                   x = \"bebida\",\n                   y = \"tempo\",\n                   bxp.errorbar = T,\n                   bxp.errorbar.width = 0.1,\n                   fill = \"bebida\",\n                   palette = \"nejm\",\n                   legend = \"none\",\n                   ggtheme = theme_bw(),\n                   xlab = \"Tipo de bebida\" ,\n                   ylab = \"Tempo de reação (seg)\") +\n  theme(text = element_text(size = 12))\n```\n\n::: {.cell-output-display}\n![Impacto do tipo de bebida no tempo de reação ao dirigir](20-testes-naoParametricos_files/figure-html/fig-bebida-1.png){#fig-bebida fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOs boxplots exibem dados com medianas visualmente diferentes, bigodes diferentes e grupos com presença de *outliers*. Para verificar o impacto desses achados, pode-se usar a função `identify_outliers()`, do pacote `rstatix` que confirma, na sua Saída, a presença de *outliers* no grupo `agua` e `cafe`, sendo dois extremos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |> \n  dplyr::group_by(bebida) |> \n  rstatix::identify_outliers(tempo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  bebida    id tempo is.outlier is.extreme\n  <fct>  <dbl> <dbl> <lgl>      <lgl>     \n1 agua       9  1.63 TRUE       FALSE     \n2 agua      10  1.97 TRUE       TRUE      \n3 cafe      19  2.56 TRUE       FALSE     \n4 cafe      20  3.07 TRUE       TRUE      \n```\n\n\n:::\n:::\n\n\nPara avaliar a normalidade será usado o teste de Shapiro-Wilk, com a função `shapiro_test()` e a função `group_by()` do pacote `dplyr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |> \n  dplyr::group_by (bebida) |> \n  rstatix::shapiro_test (tempo) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  bebida variable statistic      p\n  <fct>  <chr>        <dbl>  <dbl>\n1 agua   tempo        0.863 0.0837\n2 cafe   tempo        0.815 0.0220\n3 alcool tempo        0.875 0.114 \n```\n\n\n:::\n:::\n\n\nA variável `cafe` tem uma distribuição que não se ajusta à distribuição normal.\n\nPara completar a exploração dos dados, será solicitado, usando as funções `group_by ()` e `summarise`, do pacote `dplyr`, medidas de localização e dispersão adquadas para variáveis bem assimétricas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dados |> \n  dplyr::group_by(bebida) |> \n  dplyr::summarise(n = n(),\n                   mediana = median (tempo, na.rm = TRUE),\n                   p25=quantile(tempo, probs = 0.25, na.rm = TRUE),\n                   p75=quantile(tempo, probs = 0.75, na.rm = TRUE))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  bebida     n mediana   p25   p75\n  <fct>  <int>   <dbl> <dbl> <dbl>\n1 agua      10   0.845 0.653 0.937\n2 cafe      10   1.44  1.28  1.68 \n3 alcool    10   2.25  1.77  2.85 \n```\n\n\n:::\n:::\n\n\n### Hipóteses estatísticas\n\nNo contexto da comparação de três ou mais grupos independentes, o teste de Kruskal‑Wallis é empregado para verificar se há diferenças estatisticamente significativas entre as distribuições populacionais dos grupos analisados. As hipóteses são definidas da seguinte forma:\n\n> $H_{0} (Hipótese \\ nula)$: Os grupos são provenientes de uma mesma população, isto é, não há diferença entre as distribuições dos grupos.\n\n> $H_{1}(Hipótese \\ alternativa)$: Pelo menos um dos grupos é proveniente de uma população diferente, indicando que existe diferença entre as distribuições de pelo menos um dos grupos em relação aos demais.\n\n### Pressupostos do teste\n\nO teste de Kruskal-Wallis pressupõe as seguintes condições para o seu adequado uso:\n\n1.  As amostras são amostras aleatórias independentes de suas respectivas populações;\n2.  A escala de medição utilizada é pelo menos ordinal e, se houver apenas três grupos, deve haver pelo menos 5 casos em cada grupo;\n3.  As distribuições dos valores nas populações amostradas são idênticas, exceto pela possibilidade de que uma ou mais das populações sejam compostas por valores que tendem a ser maiores do que os das outras populações.\n\n### Execução do teste estatístico\n\n#### Lógica do teste de Kruskal-Wallis\n\nA teoria do teste Kruskal-Wallis é semelhante à do teste de Mann-Whitney, ou seja, tem como base a soma dos postos. Em primeiro lugar, os escores são ordenados do menor para o maior, independentemente do grupo que pertençam.\n\nO menor recebe o posto 1 e assim por diante. Após a atribuição dos postos, soma-se os postos por grupo. A soma dos postos de cada grupo é representada por $R_{1}$, $R_{2}$, $R_{3}$, ..., $R_{i}$. A estatística do teste, *H*, é calculada com a equação [@zar2014kruskal]:\n\n$$H =\\frac {12}{N \\times \\left (N + 1  \\right )} \\sum_{i=1}^{k} \\frac {R_{i}^{2}}{n_{{i}}}-3 \\times\\left (N + 1\\right)$$\n\nonde $n_{i}$ é o número de observações no grupo *i*, $N = \\sum_{i=1}^{k}\\times n_{i}$ (o número total de observações em todos os *k* grupos) e $R_{i}$ é a soma dos postos das $n_{i}$ observações no grupo *i*.\n\nUma boa verificação (mas não uma garantia) de que os postos foram atribuídos corretamente é ver se a soma de todos os postos é igual a $\\frac {N \\times \\left (N + 1\\right )}{2}$.\n\n1.  Criar a variável `posto` com os postos ordenados de forma crescente, independente do grupo, como realizado no teste de Mann-Whitney:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$posto <- rank(dados$tempo, ties.method = \"average\")\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [30 × 4] (S3: tbl_df/tbl/data.frame)\n $ id    : num [1:30] 1 2 3 4 5 6 7 8 9 10 ...\n $ tempo : num [1:30] 0.37 0.38 0.61 0.78 0.83 0.86 0.9 0.95 1.63 1.97 ...\n $ bebida: Factor w/ 3 levels \"agua\",\"cafe\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ posto : num [1:30] 1 2 3 4 5 6 7 8 16 22.5 ...\n```\n\n\n:::\n:::\n\n\n2.  Somar os postos de cada grupo separadamente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo1 <- dados |> \n  dplyr::group_by(bebida) |> \n  dplyr::summarise(n = n(),\n                   soma = sum(posto))\nresumo1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  bebida     n  soma\n  <fct>  <int> <dbl>\n1 agua      10  74.5\n2 cafe      10 157  \n3 alcool    10 234. \n```\n\n\n:::\n:::\n\n\n3.  Cálculo da estatística do teste *H*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN <- 30\nn <- 10\nR_agua <- resumo1[1,3]\nR_alcool <- resumo1[2,3]\nR_cafe <- resumo1[3,3]\n\nH <- (12/(N*(N+1))) * ((R_agua^2/n) + (R_alcool^2/n) + (R_cafe^2/n)) - (3*(N+1))\nH\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      soma\n1 16.31806\n```\n\n\n:::\n:::\n\n\n4.  Cálculo do Valor *p*\n\nSe existir três grupos, com cinco ou menos participantes em cada grupo, há necessidade de usar a tabela especial para tamanhos de amostra pequenos [@gopal2006table]. Se você tiver mais de cinco participantes por grupo, trate *H* como qui-quadrado. A estatística *H* é estatisticamente significativo se for igual ou maior que o valor crítico qui-quadrado para o grau de liberdade específico, igual a $k - 1$. Aqui, tem-se 10 participantes por grupo e, assumindo um $\\alpha = 0,05$, o $H_{crítico}$ é igual a:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nk <- 3\ngl = k - 1\nH_critico <- qchisq(1 - alpha, gl)\nH_critico\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.991465\n```\n\n\n:::\n:::\n\n\nUma vez que o $H_{calculado} = 16,3$ é maior que $H_{crítico} = 6,0$ , rejeita-se a $H_{0}$. O valor *P* é obtido através da função `pchisq()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nH <- 16.32\npchisq(H, 2, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0002858624\n```\n\n\n:::\n:::\n\n\nO R tem funções que fazem facilmente esses cálculos enfadonhos. Eles são colocados aqui apenas para ilustrar o raciocínio de como o teste de Kruskal-Wallis funciona. Sempre existem curiosos lendo o livro!\n\n#### Teste de Kruskal-Wallis no R\n\nNo R, pode-se calcular o teste, usando a função `kruskal_test()` do pacote `rstatix`, cujos argumentos podem ser consultados na ajuda do *RStudio*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste <- rstatix::kruskal_test (data = dados, formula = tempo ~ bebida)\nteste\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.       n statistic    df        p method        \n* <chr> <int>     <dbl> <int>    <dbl> <chr>         \n1 tempo    30      16.3     2 0.000286 Kruskal-Wallis\n```\n\n\n:::\n:::\n\n\n### Tamanho do efeito\n\nO eta quadrado ($\\eta^{2}$), com base na estatística *H*, pode ser usado como a medida do tamanho do efeito do teste de Kruskal-Wallis. É calculado pela equação:\n\n$$\\eta_{H}^{2} = \\frac {\\left (H - k + 1 \\right)}{\\left (N - k\\right)}$$\n\nonde *H* é a estatística obtida no teste de Kruskal-Wallis; *k* é o número de grupos; N é o número total de observações [@tomczak2014need].\n\nA estimativa eta ao quadrado assume valores de 0 a 1 e, multiplicada por 100, indica a porcentagem de variância na variável dependente explicada pela variável independente. Pode ser obtido no R com a função `kruskal_effsize()` do pacote `rstatix:`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados |> kruskal_effsize (tempo~bebida)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  .y.       n effsize method  magnitude\n* <chr> <int>   <dbl> <chr>   <ord>    \n1 tempo    30   0.530 eta2[H] large    \n```\n\n\n:::\n:::\n\n\nUm efeito $\\ge 0,14$ é considerado grande e $<0,06$ é pequeno [@watson2021effectsize].\n\n### Testes post hoc\n\nA partir do resultado do teste de Kruskal-Wallis, sabe-se que há uma diferença significativa entre os grupos, mas não se sabe quais pares de grupos são diferentes.\n\nUm teste de Kruskal-Wallis significativo é geralmente seguido pelo teste de Dunn [@dunn1964multiple] para identificar quais grupos são diferentes.\n\nPara realizar as múltiplas comparações, no R, pode ser usada a função `dunn_test()`, incluído no pacote `rstatix`. O ajuste de *P* é feito pelo método de Bonferroni:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwc <- dados |> \n  dunn_test (tempo ~ bebida, p.adjust.method = \"bonferroni\") \npwc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.   group1 group2    n1    n2 statistic         p    p.adj p.adj.signif\n* <chr> <chr>  <chr>  <int> <int>     <dbl>     <dbl>    <dbl> <chr>       \n1 tempo agua   cafe      10    10      2.10 0.0361    0.108    ns          \n2 tempo agua   alcool    10    10      4.04 0.0000537 0.000161 ***         \n3 tempo cafe   alcool    10    10      1.94 0.0520    0.156    ns          \n```\n\n\n:::\n:::\n\n\nA saída do teste de Dunn, mostra que existe uma diferença estatisticamente significativa apenas entre a água e o álcool, valor *p* ajustado igual a 1.61\\times 10^{-4}.\n\n### Conclusão\n\nUm teste de Kruskal-Wallis foi realizado para comparar os tempos de reação em uma simulação de direção após beber água, café ou álcool. Houve evidência de uma diferença (*p* = 0,00029) de pelo menos um par de grupos (@fig-bebida1).\n\nO teste de comparações de pares, usando o teste de Dunn, foi realizado para os três pares de grupos. Houve evidencia de diferença entre o grupo que consumiu duas unidades de álcool e o grupo que ingeriu água (*p* ajustado (Bonferroni) = 0,00016). Entre os demais pares não houve diferença significativa. O tempo mediano de reação para o grupo que recebeu água foi de 0,84 (0,65 – 0,94) segundos, em comparação com 2,25(1,77 – 2,85) segundos no grupo que bebeu cerveja equivalente a duas unidades de álcool, enquanto para o café foi de 1,45(1,28 – 1,69) segundos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npwc <- pwc |> rstatix::add_xy_position(x= \"bebida\")\n\nggpubr::ggboxplot(dados,\n                  x = \"bebida\",\n                  y = \"tempo\",\n                  bxp.errorbar = TRUE,\n                  bxp.errorbar.width = 0.1,\n                  fill = \"bebida\",\n                  palette = \"nejm\",\n                  legend = \"none\",\n                  ggtheme = theme_bw())+\n  ggpubr::stat_pvalue_manual (pwc,\n                              label = \"p = {scales::pvalue(p.adj)}\",\n                              label.size = 3.2,\n                              hide.ns = FALSE) +\n  ggplot2::labs(x = \"Tipo de bebida\", \n                y = \"Tempo de reação (seg)\",\n                subtitle = get_test_label (teste, detailed = TRUE),\n                caption = get_pwc_label(pwc))\n```\n\n::: {.cell-output-display}\n![Impacto do tipo de bebida no tempo de reação ao dirigir](20-testes-naoParametricos_files/figure-html/fig-bebida1-1.png){#fig-bebida1 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n## Teste de Friedman\n\nO **teste de Friedman** [@friedman1937use] serve para comparar três ou mais tratamentos/condições medidos nas mesmas unidades experimentais (mesmos indivíduos, mesmos objetos), quando osdados são ordinais ou não seguem distribuição normal. Ele é o equivalente **não paramétrico** da ANOVA de medidas repetidas.\n\n> <font size=3> O Teste de Friedman verifica se **as distribuições dos tratamentos diferem**, analisando **postos (*ranks*)** dentro de cada bloco (indivíduo). </font>\n\n### Dados usados no exemplo\n\n::: callout-note\n## Cenário\n\nPara avaliar a eficácia de uma dieta para perda de peso, um nutricionista usou um escore de avaliação de autoestima[^20-testes-naoparametricos-4] em três momentos diferentes em 10 indivíduos diferentes.\n:::\n\n[^20-testes-naoparametricos-4]: Escala de Autoestima de Rosenberg (RSES)[@rosenberg1965autoestima]. A RSES é uma medida de autorrelato com dez itens de **autoestima global**, variando de \"discordo totalmente\" (1) a \"concordo totalmente\" (4). O escore total varia de 10 a 40, sendo que quanto maior o escore, maior o nível de autoestima. Escores entre 15 e 25 são considerados médios. Valores abaixo de 15 indicam autoestima baixa e acima de 25, autoestima elevada.\n\nOs dados podem ser obtidos [aqui](https://github.com/petronioliveira/Arquivos/blob/main/dadosAutoestima1.xlsx) e baixados para o seu diretório de trabalho.\n\n#### Leitura e transformação dos dados\n\nA leitura é feita pela função `read_excel()` do pacote `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosAutoestima.xlsx\")\n\nglimpse(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 10\nColumns: 4\n$ id <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10\n$ t1 <dbl> 22.0, 17.7, 19.7, 20.3, 18.6, 16.1, 20.6, 19.5, 20.5, 19.1\n$ t2 <dbl> 25.5, 30.7, 23.3, 24.1, 21.7, 26.0, 26.7, 23.1, 23.2, 23.5\n$ t3 <dbl> 31.3, 28.9, 39.3, 35.0, 29.4, 30.0, 30.5, 33.5, 35.4, 35.7\n```\n\n\n:::\n:::\n\n\nOs dados serão transformados do formato atual `wide` para o formato `long` através da função `pivot_longer()` do pacote `tidyr` . Junto as variáveis `id` e `tempo` serão transformadas em fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosl <- dados |> \n  tidyr::pivot_longer(cols = 2:4,\n               names_to = \"tempo\",\n               values_to = \"escores\")|>\n  convert_as_factor(id, tempo)\n\nhead(dadosl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  id    tempo escores\n  <fct> <fct>   <dbl>\n1 1     t1       22  \n2 1     t2       25.5\n3 1     t3       31.3\n4 2     t1       17.7\n5 2     t2       30.7\n6 2     t3       28.9\n```\n\n\n:::\n:::\n\n\n#### Resumo numérico dos dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dadosl|>\n  dplyr::group_by(tempo) |> \n  summarise(\n    n       = n(),\n    média   = mean(escores),\n    mediana = median(escores),\n    dp      = sd(escores),\n    mín     = min(escores),\n    máx     = max(escores)\n  )\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  tempo     n média mediana    dp   mín   máx\n  <fct> <int> <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 t1       10  19.4    19.6  1.66  16.1  22  \n2 t2       10  24.8    23.8  2.58  21.7  30.7\n3 t3       10  32.9    32.4  3.41  28.9  39.3\n```\n\n\n:::\n:::\n\n\n#### Visualização dos dados\n\nA @fig-auto mostra a evolução do escore de autoestima com o tempo:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = dadosl, aes(x = tempo, y = escores)) +\n  geom_errorbar(\n    stat = \"boxplot\",\n    width = 0.2) +\n  geom_boxplot(\n    fill = \"grey90\",\n    outliers = FALSE) +\n  geom_jitter(\n    width = 0.1,\n    color = \"red\") +\n  labs(\n    x = \"Tempo\",\n    y = \"Escores de Autoestima (10 - 40)\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Boxplot dos Escores de Autoestima (Escala de Rosemberg) por Tempo](20-testes-naoParametricos_files/figure-html/fig-auto-1.png){#fig-auto fig-align='center' width=90% height=90%}\n:::\n:::\n\n\nHá uma tendência de aumento consistente da autoestima ao longo do tempo. Em T1, todos os indivíduos estão na faixa de autoestima *média* (16–25), com pouca variabilidade entre eles (DP = 1,66 — o grupo é bastante homogêneo nesse ponto). Em T2, os escores sobem em média \\~5,4 pontos e a dispersão aumenta levemente. Em T3, há um salto mais expressivo (\\~8,1 pontos em relação a T2), com maior variabilidade (DP = 3,41), e a maioria dos indivíduos alcança a faixa *alta* (\\> 25).\n\n### Hipóteses estatísticas\n\n> $H_{0} (Hipótese \\ nula)$: Os grupos são provenientes de uma mesma população, isto é, não há diferença entre as distribuições dos grupos relacionados.\n\n> $H_{1} (Hipótese \\ alternativa)$: Pelo menos um dos grupos é proveniente de uma população diferente, indicando que existe diferença entre as distribuições de pelo menos um dos grupos em relação aos demais.\n\n### Pressupostos\n\nO Teste de Friedman é robusto e exige pouco, mas ainda tem regras:\n\n1.  Os dados devem ser organizados em blocos ou pares (relacionados), onde cada unidade experimental deve ser medida em todos os tratamentos. Ou seja, dados pareados;\\\n2.  Variável dependente ordinal ou contínua;\n3.  Variável independente categórica com mais de duas categorias;\n4.  Observações independentes entre os indivíduos.\n\n### Execução do teste\n\n#### Lógica do Teste de Friedman\n\nOs dados do exemplo estão colocados na @tbl-friedman:\n\n\n::: {#tbl-friedman .cell tbl-cap='Dados brutos do Teste de Friedman'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-21d40230{}.cl-21c8adcc{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-21c8add6{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-21cd332e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-21cd7596{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21cd75a0{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21cd75a1{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21cd75aa{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21cd75ab{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21cd75b4{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-21d40230'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-21cd7596\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8adcc\">id</span></p></th><th class=\"cl-21cd75a0\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8adcc\">t1</span></p></th><th class=\"cl-21cd75a0\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8adcc\">t2</span></p></th><th class=\"cl-21cd75a0\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8adcc\">t3</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">1</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">22.0</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">25.5</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">31.3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">2</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">17.7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">30.7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">28.9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">3</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">19.7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">23.3</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">39.3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">4</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">20.3</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">24.1</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">35.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">5</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">18.6</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">21.7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">29.4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">6</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">16.1</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">26.0</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">30.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">20.6</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">26.7</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">30.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">8</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">19.5</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">23.1</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">33.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75a1\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">9</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">20.5</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">23.2</span></p></td><td class=\"cl-21cd75aa\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">35.4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21cd75ab\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">10</span></p></td><td class=\"cl-21cd75b4\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">19.1</span></p></td><td class=\"cl-21cd75b4\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">23.5</span></p></td><td class=\"cl-21cd75b4\"><p class=\"cl-21cd332e\"><span class=\"cl-21c8add6\">35.7</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nComo o teste de Friedman é baseado em postos, a primeira ação a ser feita é calcular os postos para cada linha (sujeito), Por exemplo, para o o **Sujeito 1** tem-se que 22.0 \\< 25.5 \\< 31.3. Assim os postos são 1, 2, 3. Para o **Sujeito 2**, os valores seguem esta ordem: 17.7 \\< 28.9 \\< 30.7 e, portanto, a ordem da linha é 1, 3, 2. No exemplo, não existem empates, mas se houvessem, há necessidade de fazer a média entre eles e estabelecer essa média como o posto de cada valor. Se for seguida essa mesma lógica para os demais sujeitos, tem-se a @tbl-friedman1:\n\n\n::: {#tbl-friedman1 .cell tbl-cap='Cálculo dos postos no Teste de Friedman'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-22080f80{}.cl-21f8a162{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-21f8a176{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-21fd68a0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-21fdb134{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21fdb13e{width:0.413in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21fdb13f{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21fdb148{width:0.413in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21fdb149{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-21fdb152{width:0.413in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-22080f80'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-21fdb134\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a162\">id</span></p></th><th class=\"cl-21fdb13e\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a162\">t1</span></p></th><th class=\"cl-21fdb13e\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a162\">t2</span></p></th><th class=\"cl-21fdb13e\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a162\">t3</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">4</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">5</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">6</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">7</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">8</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb13f\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">9</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb148\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-21fdb149\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">10</span></p></td><td class=\"cl-21fdb152\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">1</span></p></td><td class=\"cl-21fdb152\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">2</span></p></td><td class=\"cl-21fdb152\"><p class=\"cl-21fd68a0\"><span class=\"cl-21f8a176\">3</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nO próximo passo é somar os postos de cada coluna (cada momento no tempo):\n\n\n::: {#tbl-friedman2 .cell tbl-cap='Cálculo da soma dos postos por coluna'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-2238e2ea{}.cl-222e36e2{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-222e36f6{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-2232ef52{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-22331bc6{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22331bd0{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22331bd1{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-22331bda{width:0.455in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-2238e2ea'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-22331bc6\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36e2\">id</span></p></th><th class=\"cl-22331bc6\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36e2\">t1</span></p></th><th class=\"cl-22331bc6\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36e2\">t2</span></p></th><th class=\"cl-22331bc6\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36e2\">t3</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">4</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">5</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">6</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">7</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">8</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">9</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd0\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bd1\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">10</span></p></td><td class=\"cl-22331bd1\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">1</span></p></td><td class=\"cl-22331bd1\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">2</span></p></td><td class=\"cl-22331bd1\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-22331bda\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">Rⱼ</span></p></td><td class=\"cl-22331bda\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">10</span></p></td><td class=\"cl-22331bda\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">21</span></p></td><td class=\"cl-22331bda\"><p class=\"cl-2232ef52\"><span class=\"cl-222e36f6\">29</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nOnde na @tbl-friedman2, $R_{j}$ representa essa soma por coluna, $R_{1}$, $R_{2}$ e $R_{3}$, `tempo 1`, `2` e `3`, respectivamente.\n\nA fórmula para o cálculo manual da estatística do teste é:\n\n$$ \n Q=\\left [ \\frac{12}{nk(k+1)}\\sum _{j=1}^{k}R_{j}^{2} \\right ]-3n(k+1)$$\n\nOnde:\n\n- **(n)**: número de linhas (blocos/sujeitos). No exemplo, *n* = 10.\\\n- **(k)**: número de colunas (grupos/tratamentos). No exemplo, *k* = 3.\n- **(**$R_{j}$): a soma dos postos da coluna (j). Ver @tbl-friedman2.\n- **(**$\\sum R_{j}^{2}$): o somatório do quadrado das somas de cada coluna. Ver no código abaixo:\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsomatorio <- (10^2)+(21^2)+(29^2)\nsomatorio\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1382\n```\n\n\n:::\n:::\n\n\nSubstituindo na fórmula :\n\n$$ \n Q=\\left [ \\frac{12}{10\\times 3 \\times (3+1)} \\times 1382 \\right ]-3 \\times 10\\times (3+1)$$\n\nFazendo os cálculos, tem-se o $Q_{calculado}$:\n\n$$Q=\\left [ \\frac{12}{120} \\times 1382 \\right ]-120 = 18,2$$\n\nPortanto, a estatística do teste de Friedman, Q = 18,2[^20-testes-naoparametricos-5] . A estatística *Q* será estatisticamente significativa se for igual ou maior que o valor crítico qui-quadrado para o grau de liberdade específico, igual a $k - 1$. Aqui, tem-se *k* = 3 , assumindo um $\\alpha = 0.05$, o $Q_{crítico}$ é igual a:\n\n[^20-testes-naoparametricos-5]: Às vezes, denotada como $F_{r}$ ou $\\chi_{r}^{2}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\nk <- 3\ngl = k - 1\nQ_critico <- qchisq(1 - alpha, gl)\nQ_critico\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.991465\n```\n\n\n:::\n:::\n\n\nUma vez que o $Q_{calculado} = 18,2$ é maior que $Q_{crítico} = 5,99$ , rejeita-se a $H_{0}$. O valor *p* é obtido através da função `pchisq()`, porque a estatística *Q* segue a distribuição qui-quadrado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ <- 18.2\np <- pchisq(Q, gl, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0001116658\n```\n\n\n:::\n:::\n\n\n::: callout-caution\n## Atenção!\n\nA fórmula, usada acima, somente funciona corretamente se não existirem empates (como no exemplo). Quando há empates, ela deve ser dividida por um fator de correção:\n\n$$Q_{corr}=\\frac{Q}{1-\\frac{\\sum T}{n\\left ( k^{3}-k \\right )}}$$\n\nO termo de correção *T* é calculado da seguinte maneira:\n\n1)  Para cada linha (cada sujeito), identifique grupos de empates.\\\n2)  Se houver um grupo de𝑡valores empatados, o termo é: $T = t^{3}-t$\n3)  Em escalas Likert, os empates são comuns!\n\nNo exemplo usado no cálculo, tem-se que $T = 0$ para todos os sujeitos. Assim, $\\sum T=0$ e o fator de correção vira 1 e fórmula simples funciona perfeitamente.\n:::\n\nEsses cálculos aborrecidos são colocados aqui apenas para ilustrar o raciocínio de como o teste de Friedman funciona. Repetindo o dito para o Teste de Kruskal-Wallis, acredito que sempre haverão curiosos que se interessarão por coisas chatas!\n\n#### Teste de Friedman no R\n\nPara realizar o Teste de Friedman é necessário que os dados estejam estruturados no formato longo, como os `dadosl`, que é o padrão para análises de medidas repetidas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste_friedman <- dadosl |> \n  rstatix::friedman_test(escores ~ tempo |id)\nteste_friedman\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  .y.         n statistic    df        p method       \n* <chr>   <int>     <dbl> <dbl>    <dbl> <chr>        \n1 escores    10      18.2     2 0.000112 Friedman test\n```\n\n\n:::\n:::\n\n\nO escore de autoestima foi estatisticamente significativo, Q(2) = 18,2, p \\< 0,001. Observe que o resultado da estatística do teste (Q = 18,2) é o mesmo do cálculo manual, realizado para demonstração do funcionamento do teste.\n\n### Tamanho do Efeito\n\nO tamanho do efeito será verificado usando o coeficiente W de Kendall. O coeficiente W de Kendall é calculado como $W = Q / (n(k-1))$, onde *Q* é a estatística de Friedman e *k* é o número de grupos. Para este exemplo, $W = 18.2 / (10(3-1)) = 18.2 / 20 = 0,91$. O valor de W indica o tamanho do efeito, sendo que valores maiores indicam um efeito mais forte.\n\nInterpretação é dada pelos critérios de Cohen [@cohen1988statistical], veja @tbl-kendall:\n\n\n::: {#tbl-kendall .cell tbl-cap='Interpretação do valor W'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-22876d8e{}.cl-22767cc2{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-22767cd6{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-22767cd7{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-227c9f80{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-227c9f94{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-227cf962{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-227cf976{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-227cf977{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-227cf980{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-22876d8e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-227cf962\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cc2\">w</span></p></th><th class=\"cl-227cf962\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cc2\">magnitude</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-227cf976\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">0,10 &lt; 0,30</span></p></td><td class=\"cl-227cf976\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-227cf976\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">0,30 &lt; 0,50</span></p></td><td class=\"cl-227cf976\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">médio</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-227cf977\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">&gt;= 0,50</span></p></td><td class=\"cl-227cf977\"><p class=\"cl-227c9f80\"><span class=\"cl-22767cd6\">grande</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-227cf980\"><p class=\"cl-227c9f94\"><span class=\"cl-22767cd7\">Sem considerar o sinal</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosl  |> rstatix::friedman_effsize(escores ~ tempo |id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  .y.         n effsize method    magnitude\n* <chr>   <int>   <dbl> <chr>     <ord>    \n1 escores    10    0.91 Kendall W large    \n```\n\n\n:::\n:::\n\n\n### Testes post hoc\n\nO pós‑teste mais recomendado após o Friedman é o teste de Wilcoxon pareado, utilizando o `pairwise_wilcox_test()` do pacote `rstatix`. Para controlar o erro tipo I nas comparações múltiplas, recomenda-se a correção de Holm, que é um procedimento mais poderoso que o método de Bonferroni [@holm1979posthoc], principalmente, não havendo empates. Entretanto, se houver empates, pode-se usar o mesmo teste, pois o teste de Wilcoxon pareado lida naturalmente com os empates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npwc <- dadosl |> \n  pairwise_wilcox_test(\n    escores ~ tempo,\n    paired = TRUE,\n    p.adjust.method = \"holm\")\npwc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 9\n  .y.     group1 group2    n1    n2 statistic       p   p.adj p.adj.signif\n* <chr>   <chr>  <chr>  <int> <int>     <dbl>   <dbl>   <dbl> <chr>       \n1 escores t1     t2        10    10         0 0.00195 0.00586 **          \n2 escores t1     t3        10    10         0 0.00195 0.00586 **          \n3 escores t2     t3        10    10         1 0.00391 0.00586 **          \n```\n\n\n:::\n:::\n\n\n### Conclusão\n\nPara avaliar a evolução dos escores de autoestima (Escala de Rosenberg) nos três momentos avaliados ($t_{1}$, $t_{2}$ e $t_{3}$), foi aplicado o teste não paramétrico de Friedman para medidas repetidas, uma vez que os mesmos sujeitos ($n = 10$) foram acompanhados longitudinalmente.\n\nA análise indicou uma mudança estatisticamente significativa nos escores de autoestima (@fig-end) ao longo do tempo ($\\chi^2(2) = 18,2$; $p < 0,001$). Para identificar entre quais momentos ocorreram essas mudanças, realizou-se o teste post-hoc de Wilcoxon pareado com correção de Holm para múltiplas comparações. Os resultados do teste post-hoc demonstraram diferenças significativas entre todos os intervalos avaliados: houve um aumento significativo nos escores de $t_{1}$ para $t_{2}$ ($p = 0,008$), de $t_{2}$ para $t_{3}$ ($p = 0,008$) e de $t_{1}$ para $t_{3}$ ($p = 0,006$) .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npwc <- pwc  |>  \n  rstatix::add_xy_position(x = \"tempo\")\n\n\nggplot(data = dadosl, aes(x = tempo, y = escores)) +\n  geom_errorbar(\n    stat = \"boxplot\",\n    width = 0.2) +\n  geom_boxplot(\n    fill = \"grey90\",\n    outliers = FALSE) +\n  geom_jitter(\n    width = 0.1,\n    color = \"red\") +\n  ggpubr::stat_pvalue_manual(\n    pwc,\n    hide.ns = TRUE,\n    label = \"p = {round(p.adj, 4)}\",\n    tip.length = c(0.01, 0.01)) +\n  labs(\n    subtitle = get_test_label(teste_friedman, detailed = TRUE),\n    caption  = get_pwc_label(pwc),\n    x = \"Tempo\",\n    y = \"Escores de Autoestima (10 - 40)\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Boxplot dos Escores de Autoestima (Escala de Rosemberg) por Tempo](20-testes-naoParametricos_files/figure-html/fig-end-1.png){#fig-end fig-align='center' width=90% height=90%}\n:::\n:::\n\n",
    "supporting": [
      "20-testes-naoParametricos_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}