{
  "hash": "f0d3b188fe2cf25ce7d07f18bcf34753",
  "result": {
    "engine": "knitr",
    "markdown": "# Comparação entre duas médias {#sec-testet}\n\n## Pacotes necessários para este capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif(!require(\"pacman\")) {install.packages(\"pacman\")}\npacman::p_load(car, \n               effectsize, \n               flextable,\n               ggbeeswarm,               ggpubr, \n               ggsignif, \n               ggsci, \n               readxl,\n               report,\n               scales,\n               rstatix, \n               tidyverse)\n```\n:::\n\n\n## Teste *t* para amostras independentes\n\nO teste *t* de amostras independentes é usado para comparar duas médias de amostras de grupos não relacionados. Isso significa que há pessoas diferentes fornecendo escores para cada grupo. O objetivo desse teste é determinar se as médias das amostras são diferentes entre si.\n\n### Dados usados neste capítulo\n\nPara responder a seguinte pergunta de pesquisa:\n\n> <font size=3> A nota em Bioestatística de homens e mulheres difere estatisticamente? </font>\n\nForam coletadas, em uma determinada Universidade, as notas de Bioestatística de uma turma de 40 alunos. Estes dados estão [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosNotas.xlsx). Baixe e salve o mesmo no seu diretório de trabalho para a leitura dos dados.\n\n#### Leitura dos dados\n\nOs dados serão lidos com a função `read_excel()`, incluída no pacote `readxl`, e serão designados a um objeto `dados`.\\\nA seguir, para exibir a estrutura interna do objeto, será usada a função `str()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosNotas.xlsx\") \n  \nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [40 × 2] (S3: tbl_df/tbl/data.frame)\n $ notas: num [1:40] 63.1 76.3 57.7 66.9 73.1 70.3 63.6 75.7 73.5 83 ...\n $ sexo : num [1:40] 2 2 2 2 2 2 2 2 2 2 ...\n```\n\n\n:::\n:::\n\n\nO conjunto de dados é um `tibble` que contém uma variável numérica `notas` com 40 observações e uma variável `sexo` também com 40 observações. O R leu esta variável como numérica, mas ela é uma variável categórica e deve ser transformada em fator, usando a função `mutate()` do pacote `dplyr`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- dados |> \n  mutate(sexo = factor(sexo,\n                       levels = c(1, 2),\n                       labels = c(\"Masculino\", \"Feminino\")))\n\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [40 × 2] (S3: tbl_df/tbl/data.frame)\n $ notas: num [1:40] 63.1 76.3 57.7 66.9 73.1 70.3 63.6 75.7 73.5 83 ...\n $ sexo : Factor w/ 2 levels \"Masculino\",\"Feminino\": 2 2 2 2 2 2 2 2 2 2 ...\n```\n\n\n:::\n:::\n\n\nA variável `sexo`, agora, está correta. É uma variável categórica com dois níveis: `Masculino` e `Feminino`.\n\n#### Exploração e resumo dos dados\n\nSerão calculadas algumas métricas descritivas para melhor explorar os dados. Para isso, as notas dos alunos serão divididas em dois grupo, de acordo com o sexo. Essa ação será realizada pela função de agrupamento `group_by()` e pela função resumidora `summarise`, ambas do pacote `dplyr`. O objeto `resumo` receberá os resultados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dados |> \n  dplyr::group_by(sexo) |> \n  dplyr:: summarise(n = n(),\n                    media = mean(notas, na.rm = TRUE),\n                    dp = sd(notas, na.rm = TRUE),\n                    mediana = median(notas, na.rm = TRUE),\n                    Q1 = quantile(notas,0.25, na.rm = TRUE),    \n                    Q3 = quantile(notas, 0.75, na.rm = TRUE),\n                    me = 1.96 * dp/sqrt(n)) \nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  sexo          n media    dp mediana    Q1    Q3    me\n  <fct>     <int> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 Masculino    20  59.9  7.34    59.2  54.3  63.5  3.22\n2 Feminino     20  68.4  7.79    68.6  63.2  73.8  3.41\n```\n\n\n:::\n:::\n\n\nUma outra maneira de obter um resumo dos dados é usar a função nativa `summary()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     notas              sexo   \n Min.   :46.30   Masculino:20  \n 1st Qu.:57.60   Feminino :20  \n Median :63.15                 \n Mean   :64.12                 \n 3rd Qu.:72.83                 \n Max.   :83.00                 \n```\n\n\n:::\n:::\n\n\nA saída mostra as estatísticas descritivas mais comuns das variáveis numéricas (min, Q1, mediana, média, Q3, max) e a distribuição das variáveis categóricas. Se existirem valores ausentes (NAs) eles aparecem.\n\nA saída informa que a média das notas das mulheres é 68.4, bem acima das notas dos homens, mostrando uma diferença nos escores de 8.5. Parece que o desempenho das mulheres em Bioestatística é melhor do que o dos homens!\n\nAlém do resumo numérico, é interessante construir um gráfico do tipo `boxplot` (@fig-bxpnotas), usando o pacote `ggplot2` (veja @sec-ggplot2) para observar a distribuição dos dados:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot2::ggplot(data = dados, aes(x = sexo, \n                                  y = notas, \n                                  fill = sexo)) + \n  geom_errorbar(stat = \"boxplot\", width = 0.1) +\n  geom_boxplot() +\n  geom_jitter(width = 0.05) +\n  scale_fill_manual(values = c(\"steelblue\",\"pink2\")) +\n  labs (x = \"Sexo\", \n        y = \"Notas\") + \n  theme_classic(base_size = 13) + \n  theme(legend.position=\"none\")\n```\n\n::: {.cell-output-display}\n![Boxplot dos dados](14-teste-t_files/figure-html/fig-bxpnotas-1.png){#fig-bxpnotas fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOs boxplot sugerem que as notas dos alunos diferem, de acordo o sexo.\n\n### Definição das hipóteses estatísticas\n\nAs hipóteses comparam as médias dos dois grupos. Para um teste bicaudal, as hipóteses são escritas como:\n\n$$H_{0}: \\mu_{F} = \\mu_{M}$$\n\n$$H_{1}: \\mu_{F} \\neq \\mu_{M}$$\n\n### Definição da regra de decisão\n\nO nível significância escolhido, $\\alpha$, é igual a `0.05`. A distribuição *t* é dependente dos graus de liberdade, dados por:\n\nNo exemplo,\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- resumo$n[1]\nn2 <- resumo$n[2]\ngl <- n1 + n2 - 2\ngl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 38\n```\n\n\n:::\n:::\n\n\nPara um $\\alpha = 0,05$, o valor crítico de *t* para gl =38 para uma hipótese alternativa bicaudal é obtido com a função `qt (p, df)`, onde $df = gl$ e $p = 1 - \\alpha/2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\np <- 1 - alpha/2\ntc <- round (qt((1-alpha/2), gl), 3)\ntc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.024\n```\n\n\n:::\n:::\n\n\nPortanto, se\n\n$$|t_{calculado}| < |t_{crítico}|  \\to não \\quad se \\quad rejeita \\quad H_{0}$$\n\n$$|t_{calculado}| \\ge |t_{crítico}| \\to rejeita-se \\quad H_{0}$$\n\n### Teste estatístico\n\nPara determinar se existe uma diferença estatisticamente significativa entre as médias das notas de dois grupos, será usado o teste *t* para duas amostras independentes, também conhecido como teste *t* de Student, baseado na distribuição de mesmo nome (@sec-dist_t).\n\n#### Lógica do teste *t*\n\nO teste *t* compara as médias de duas amostras independentes, usando o erro padrão como métrica da diferença entre essas médias. Quanto maior o valor de *t* , maior a probabilidade de que as amostras pertençam a grupos diferentes, ocorrendo nessas circunstâncias a rejeição da hipótese nula [@pagano2000t_test].\n\nCalcula-se o teste *t* com a seguinte equação:\n\n$$t = \\frac{(\\bar{x}_1 - \\bar{x}_2) - (\\mu_1 - \\mu_2)}{EP_{d}}$$\n\nOnde $EP_d$ é o erro padrão da diferença entre a médias $\\bar{x}_1 - \\bar{x}_2$. Se a hipótese nula for verdadeira, as amostras foram retiradas da mesma população e, portanto, $\\mu_1 - \\mu_2 = 0$. Assim, a equação fica:\n\n$$t = \\frac{(\\bar{x}_1 - \\bar{x}_2)}{EP_d}$$\n\nO erro padrão da diferença $\\bar{x}_1 - \\bar{x}_2$ é calculado de maneiras diferentes:\n\n1)  Se a variâncias nos dois grupos forem iguais, usa-se:\n\n$$EP_d = \\sqrt{s_o^2(\\frac{1}{n_1}+\\frac{1}{n_2})}$$\n\nOnde $s_o^2$ é a variância combinada ou conjugada que é, simplesmente, a média ponderada das variância dos grupos:\n\n$$s_o^2 = \\frac{(n_1 - 1)s_1^2 + (n_2 -1)s_2^2}{(n_1 -1)+ (n_2-1)}$$\n\nQuando os grupos têm o mesmo tamanho ($n_1 = n_2$), $s_o^2$ é simplesmente a média aritmética da variância dos grupos:\n\n$$s_o^2 = \\frac {s_1^2 + s_2^2}{2}$$\n\n$$EP_d = \\sqrt{\\frac{2 s_o^2}{n}}$$\n\n2)  Se as variâncias dos dois grupos forem diferentes:\n\n$$EP_d = \\sqrt{\\frac{s_1^2}{n_1}+\\frac{s_2^2}{n_2}}$$\n\nEsta explicação da lógica e dedução da estatística de teste serve para uma melhor compreensão de como o teste funciona, mas para executar um teste *t* não há necessidade disso, basta saber como encaminhar ao R e como interpretar o resultado fornecido por ele.\n\n#### Pressupostos do teste *t* {#sec-homovar}\n\nO teste *t* assume que:\n\n1.  As amostras são independentes;\n2.  Deve haver distribuição normal. Entretanto, quando as amostras são grandes (teorema do limite central), isso não é muito importante;\n3.  Exista homocedasticidade, ou seja, as variâncias dos grupos devem ser iguais.\n\nViolar o pressuposto de número 3 tem importância se os tamanhos dos grupos forem diferentes. Se os grupos tiverem o mesmo tamanho e a amostra for grande, este pressuposto torna-se menos importante, não preocupando muito se essa hipótese foi violada [@zimmerman2004note]. O pressuposto tem mais importância em grupos pequenos e desiguais. Existe um teste, denominado *teste t de Welch* que corrige essa violação. É possível portanto, esquecer esse pressuposto e fazer o teste de Welch sempre.\n\n[Avaliação da normalidade]{.underline}\n\nUma boa parte dos procedimentos estatísticos são testes paramétricos [^14-teste-t-1] com base na distribuição normal. Ou seja, se assume que a distribuição dos dados segue o modelo da distribuição normal. Se essa suposição não for atendida, a lógica por trás do teste de hipóteses pode ser violada.\n\n[^14-teste-t-1]: Testes paramétricos são testes estatísticos que se baseiam nos padrões da distribuição populacional da variável em estudo, por exemplo, a distribuição normal é descrita por dois parâmetros – média e desvio padrão – que são suficientes para se conhecer as probabilidades. Os testes que não requerem a especificação da forma de distribuição da população, ou seja, têm **distribuição livre**, são denominados de não paramétricos.\n\nPode-se verificar a normalidade de maneira visual, observando o comportamento dos dados através de gráficos como o próprio boxplot (@fig-bxpnotas), onde se observa que as medianas dos boxplots se encontra praticamente no centro das caixas. Outra forma, é o *gráfico Q-Q* (@fig-qqnotas). O *gráfico QQ* (ou gráfico quantil-quantil) desenha a correlação entre uma determinada amostra e a distribuição normal. Uma linha de referência de 45 graus também é plotada. Um gráfico Q-Q é um gráfico de dispersão criado plotando dois conjuntos de quantis um contra o outro. Se ambos os conjuntos de quantis vierem da mesma distribuição, observa-se os pontos formando uma linha aproximadamente reta. Se os valores caírem na diagonal do gráfico, a variável é normalmente distribuída. Os desvios da diagonal mostram desvios da normalidade. Para desenhar um gráfico Q-Q pode ser usado a função `ggqqplot ()`[^14-teste-t-2] do pacote `ggpubr`(@kassambara2022ggpubr) que produz um gráfico QQ normal com uma linha de referência, acompanhada de área sombreada, correspondente ao IC95%.\n\n[^14-teste-t-2]: Veja também a @sec-qqplot.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggqqplot(dados, \n                 x = \"notas\", \n                 color = \"sexo\") +\n  labs(y = \"Notas\",\n       x = \"Quantis teóricos\") +\n  theme_classic(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Gráficos Q-Q](14-teste-t_files/figure-html/fig-qqnotas-1.png){#fig-qqnotas fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nObservando os gráficos, verifica-se que a variável `notas` tem uma distribuição visualmente normal aceitável em ambos grupos, pois os gráficos Q-Q mostram que os dados seguem aproximadamente a linha diagonal.\n\nOutra maneira de analisar a normalidade é verificar se a distribuição como um todo se desvia de uma distribuição normal comparável. Para isso, usam-se *testes estatísticos de normalidade*. Os dois principais são o *teste de Shapiro-Wilk* e o *teste de Kolmogorov-Smirnov (K-S)*.\n\nEsses testes comparam os dados da amostra com um conjunto de valores normalmente distribuídos com a mesma média e desvio padrão. Se o teste não for significativo (*p* \\> 0,05), informa-se que a distribuição da amostra não é significativamente diferente de uma distribuição normal. Se, no entanto, o teste for significativo (*p* $\\le$ 0,05), a distribuição em questão será significativamente diferente de uma distribuição normal.\n\nO método de Shapiro-Wilk é amplamente recomendado para teste de normalidade [@razali2011power], [@ghasemi2012normality], [@yap2011comparisons].\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw <- dados |> \n  dplyr::group_by(sexo) |>\n  rstatix::shapiro_test(notas)\nsw\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sexo      variable statistic     p\n  <fct>     <chr>        <dbl> <dbl>\n1 Masculino notas        0.972 0.802\n2 Feminino  notas        0.973 0.812\n```\n\n\n:::\n:::\n\n\nA saída mostra que ambos valores *p* do teste, 0.802 e 0.812, estão acima de 0,05, corroborando com a não rejeição da normalidade dos dados.\n\n[Homogeneidade da Variância]{.underline}\n\nNa visualização da @fig-bxpnotas, nos dois grupos de alunos, observa-se que há, entre os limites inferior e superior, uma dispersão das notas em torno da região central. Esta dispersão parece ser semelhante. Isto sugere que haja *homogeneidade das variâncias*.\n\nPortanto, homogeneidade da variância é o pressuposto de que a dispersão das medidas é aproximadamente igual em diferentes grupos de casos, ou que a dispersão dos valores são aproximadamente iguais em pontos diferentes da variável preditora.\n\nAlém do aspecto visual, a homogeneidade da variância pode ser testada com o *teste de Levene*. Neste teste, a $H_{0}$ é todas as variâncias são iguais. No *R*, uma função que calcula o teste é `leveneTest()` do pacote `car` [@fox2018car]. Os argumentos são:\n\n- **y** $\\to$ variável de resposta para o método padrão ou um objeto `lm` ou `fórmula`. Se `y` for um objeto de modelo linear ou uma fórmula, as variáveis do lado direito do modelo devem ser todas fatores e devem ser completamente cruzadas;\n- **group** $\\to$ fator que define os grupos;\n- **center** $\\to$ O nome de uma função para calcular o centro de cada grupo; `mean` fornece o teste de Levene original; o padrão, `median`, fornece um teste mais robusto;\n- **data** $\\to$ conjunto de dados para avaliar a `formula`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevene <- car::leveneTest(notas~sexo, \n                          center = mean, \n                          data = dados)\nlevene\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = mean)\n      Df F value Pr(>F)\ngroup  1  0.4575 0.5029\n      38               \n```\n\n\n:::\n:::\n\n\nA saída do teste de Levene retorna um valor *p* \\> 0,05, confirma a impressão visual dos boxplots de que os grupos têm homogeneidade das variâncias, portanto a hipótese nula de igualdade das variâncias não pode ser rejeitada.\n\nO `rstatix` também tem uma função para calcular o teste de Levene (`?levene_test`). Esta função tem a vantagem de ser *pipe-friendly*. Os resultados são os mesmos porque a função `levene_test()` do pacote `rstatix` [@kassambara2022rstatix] é um *wrapper* em torno da função `leveneTest()` do pacote `car`. Ou seja, ela chama internamente a função `car::leveneTest()`, mas oferece uma interface mais simples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste_levene <- dados |> \n  rstatix::levene_test(formula = notas ~ sexo, \n                       center = \"mean\")\nteste_levene\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n    df1   df2 statistic     p\n  <int> <int>     <dbl> <dbl>\n1     1    38     0.458 0.503\n```\n\n\n:::\n:::\n\n\n#### Execução do teste *t* de Student\n\nOs pressupostos do teste não foram violados, portanto ele pode ser realizado com confiança. Será utilizado a função `t_test()` do pacote `rstatix` para calcular o teste *t*. Ele fornece uma estrutura compatível com operador pipe `|>` (*pipe-friendly*) para executar testes *t* de uma e duas amostras. Para consultar os argumentos, consulte a ajuda do *RStudio*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n teste <- dados |> rstatix::t_test(formula = notas ~ sexo,\n                                    detailed = TRUE,\n                                    var.equal = TRUE)\n print(teste, n =Inf, width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 15\n  estimate estimate1 estimate2 .y.   group1    group2      n1    n2 statistic\n*    <dbl>     <dbl>     <dbl> <chr> <chr>     <chr>    <int> <int>     <dbl>\n1    -8.51      59.9      68.4 notas Masculino Feminino    20    20     -3.56\n        p    df conf.low conf.high method alternative\n*   <dbl> <dbl>    <dbl>     <dbl> <chr>  <chr>      \n1 0.00102    38    -13.4     -3.67 T-test two.sided  \n```\n\n\n:::\n:::\n\n\nA saída retorna a estimativa da diferença média (-8.51), as estimativas das médias dos grupos (arredondadas), a estatística do teste (-3.56) o valor p (0.0010203), graus de liberdade (38)[^14-teste-t-3] e outras métricas. Foram colocados, na função `print()`, os argumentos `n = Inf` e `width = Inf` para evitar que a saída seja truncada e abreviada.\n\n[^14-teste-t-3]: Se as variâncias forem diferentes (`var.equal = FALSE`), o teste calcula os graus de liberdade pela fórmula de Welch, bem mais complicada.\n\nTambém é possível ver os resultados do teste *t* , usando o objeto `teste` que os recebeu. Por exemplo, os limites inferior (`conf.low`) e superior (`conf.high`) do intervalo de confiança de 95% da estimativa da diferença entre as médias.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIC95 <- round(c(teste$conf.low, teste$conf.high),3)\nIC95\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -13.359  -3.671\n```\n\n\n:::\n:::\n\n\n### Tamanho do Efeito\n\nA significância estatística deve ter uma atenção relativa do pesquisador, pois ela apenas mede a probabilidade de rejeitar uma hipótese nula, uma vez que ela seja verdadeira. Ajudam a determinar, em uma pesquisa, a significância dos resultados encontrados em relação à hipótese nula, mas não informam nada em relação a magnitude do efeito. Por exemplo, mostra se determinado tratamento afeta as pessoas, mas não dizem quanto isso as afeta.\n\nO tamanho do efeito (*effect size*) é uma medida quantitativa da magnitude do efeito. Quanto maior o tamanho do efeito, mais forte é a relação entre duas variáveis. É possível observar o tamanho do efeito ao comparar dois grupos quaisquer para ver quão substancialmente diferentes eles são.\n\nNormalmente, em ensaios clínicos tem-se um grupo de tratamento e um grupo de controle. O grupo de tratamento é uma intervenção que se espera efetue um resultado específico. O valor do tamanho do efeito mostrará se a terapia teve um efeito pequeno, médio ou grande. Isso tem mais relevância do que simplesmente informar o tamanho do valor *p*.\n\n#### *d* de Cohen {#sec-cohen}\n\nO *d* de Cohen[@cohen1988power] [@lindenau2012effect] é uma medida adequada e bastante popular para encontrar a magnitude do efeito na comparação entre duas médias quando o n \\> 20 e as variâncias são semelhantes.\n\nPara calcular essa diferença média padronizada se verifica a diferença entre as médias dos dois grupos e se divide pelo desvio padrão agrupado ($s_{p}$):\n\n$$d = \\frac{(\\bar{x}_1 - \\bar{x}_2)}{s_{p}}$$\n\nOnde,\n\n$$s_o =\\sqrt \\frac{(n_1 - 1)s_1^2 + (n_2 -1)s_2^2}{n_1 + n_2 - 2}$$\n\nVoltando ao exemplo das notas dos alunos de Bioestatística, o *d* de Cohen pode ser calculado, usando a função `cohens_d()` do pacote `effectsize` [@shachar2020effectsize]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- effectsize::cohens_d(notas ~ sexo, data = dados, paired = F)\nd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-1.13     | [-1.79, -0.45]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n:::\n\n\nAgora, como interpretar este resultado de -1.13, 0.95, -1.79, -0.45? Sua interpretação não é intuitiva, recomenda-se usar a @tbl-effect para interpretar [@cohen1988power].\n\n\n::: {#tbl-effect .cell tbl-cap='Tamanho do Efeito'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7c7c07e6{}.cl-7c6e0eb6{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c6e0ed4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c73949e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7c73e00c{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c73e020{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c73e021{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7c7c07e6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7c73e00c\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0eb6\">d de Cohen</span></p></th><th class=\"cl-7c73e00c\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0eb6\">Interpretação (Cohen,1988)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c73e020\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">0,2 &lt; 0,5</span></p></td><td class=\"cl-7c73e020\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c73e020\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">0,5 &lt; 0,8</span></p></td><td class=\"cl-7c73e020\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">médio</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c73e021\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">&gt;= 0,8</span></p></td><td class=\"cl-7c73e021\"><p class=\"cl-7c73949e\"><span class=\"cl-7c6e0ed4\">grande</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nAssim, as notas dos alunos diferem significativamente (*p* = 0.0010203) de acordo com o sexo, sendo que as mulheres têm notas mais altas do que os homens e a magnitude dessa diferença é grande (d = -1.13, 0.95, -1.79, -0.45). O sinal fica negativo porque a média das mulheres (segundo grupo) é mais alta que a dos homens. A interpretação do efeito usa \\|d\\|, não o sinal.\n\nA função `interpret_cohens_d()` do pacote `effectsize` permite ver direto a interpretação da magnitude do efeito:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::interpret_cohens_d(d, rules = \"cohen1988\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI | Interpretation\n-------------------------------------------\n-1.13     | [-1.79, -0.45] |          large\n\n- Estimated using pooled SD.\n- Interpretation rule: cohen1988\n```\n\n\n:::\n:::\n\n\nShlomo Sawilowsky propôs uma expansão [@sawilowsky2009effect] para a interpretação tradicional do *d* de Cohen (pequeno, médio, grande), incluindo mais categorias (@tbl-effect1), adaptadas para estudos que observam diferenças maiores .\n\n\n::: {#tbl-effect1 .cell tbl-cap='Tamanho do Efeito'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-7ca0d1fc{}.cl-7c988448{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c98845c{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7c9bdf12{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7c9bfeca{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9bfed4{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7c9bfede{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-7ca0d1fc'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-7c9bfeca\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c988448\">d de Cohen</span></p></th><th class=\"cl-7c9bfeca\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c988448\">Interpretação (Sawilowsky,2009)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">&lt; 0,20</span></p></td><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">muito pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">0,20 &lt; 0,50</span></p></td><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">pequeno</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">0,50 &lt; 0,80</span></p></td><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">médio</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">0,80 &lt; 1,20</span></p></td><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">grande</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">1,20 &lt; 2,00</span></p></td><td class=\"cl-7c9bfed4\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">muito grande</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-7c9bfede\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">&gt;= 2,00</span></p></td><td class=\"cl-7c9bfede\"><p class=\"cl-7c9bdf12\"><span class=\"cl-7c98845c\">enorme</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::interpret_cohens_d(d, rules = \"sawilowsky2009\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI | Interpretation\n-------------------------------------------\n-1.13     | [-1.79, -0.45] |          large\n\n- Estimated using pooled SD.\n- Interpretation rule: sawilowsky2009\n```\n\n\n:::\n:::\n\n\n#### *g* de Hedges {#sec-hedges}\n\nÉ uma correção do *d* de Cohen para amostras pequenas (n \\< 20) ou quando as amostras são muito diferentes. Corrige o \"viés para cima\" que o *d* de Cohen apresenta em amostras pequenas, sendo conhecido como um **tamanho de efeito corrigido**.\n\nÉ dados pela fórmula\n\n$$g = d \\ \\times \\ J$$\n\nOnde J é o fator de correção do d de Cohens e é igual a\n\n$$J = 1 \\ - \\ \\frac{3}{4(n_{1}+n_{2})-9} $$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng <- effectsize::hedges_g(notas ~ sexo, data = dados, paired = F)\n```\n:::\n\n\nQue pode ser interpretado tanto pelas regras de `cohen1988` como pela de `sawilowsky2009`, usando a função `interpret_cohens_g()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::interpret_hedges_g(g, rules = \"sawilowsky2009\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHedges' g |         95% CI | Interpretation\n-------------------------------------------\n-1.10     | [-1.75, -0.44] |          large\n\n- Estimated using pooled SD.\n- Interpretation rule: sawilowsky2009\n```\n\n\n:::\n:::\n\n\n#### Delta ($\\Delta$) de Glass {#sec-delta}\n\nO delta ($\\Delta$) de Glass deve ser usado quando as variâncias entre os grupos são muito diferentes (heterogêneas). É mais robusto que os outros dois quando a suposição de homogeneidade de variância é violada.\\\nDivide a diferença das médias pelo desvio-padrão de apenas um dos grupos, geralmente o grupo de controle. Para isso, supõe-se que o desvio padrão deste não é afetado pelos efeitos do tratamento, refletindo melhor o desvio padrão populacional [@espirito2017calcular].\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndelta <- effectsize::glass_delta(notas ~ sexo, data = dados)\ndelta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGlass' delta (adj.) |         95% CI\n------------------------------------\n-1.05               | [-1.71, -0.37]\n```\n\n\n:::\n:::\n\n\nPode ser interpretado como feito com o g de Hedges, usando a mesma função com a interpretação de `sawilowsky2009`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::interpret_glass_delta(-1.05, rules = \"sawilowsky2009\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"large\"\n(Rules: sawilowsky2009)\n```\n\n\n:::\n:::\n\n\n### Conclusão\n\nComo $|t_{calculado}|$ = 3.559 \\> $|t_{0,05;38}|$ = 2.024, rejeita-se $H_{0}$. Observa-se que o valor *p* é muito pequeno (0.0010203) e, portanto, a diferença observada nas médias dos dois grupos deve ser assumida como significativa.\n\nAssim, pode-se admitir que as médias das notas são diferentes, com probabilidade de erro extremamente pequena. A estimativa da diferença média ($\\mu_1 - \\mu_2$) é fornecida pelo intervalo de confiança de 95% (-13.359, -3.671). Observe que o valor zero não está contido no intervalo e isto confirma a significância estatística da diferença.\n\nConcluindo, as notas de Bioestatística das mulheres e as notas dos homens são diferentes, a diferença ($\\mu_1 - \\mu_2$) encontrada é estatisticamente significativa (*t* = -3.559, gl = 38, *p* = 0.0010203), com uma confiança de 95%.\n\nEsta conclusão pode ser visualizada em um gráfico (@fig-bxpt) que exibirá a saída do teste *t*:\n\n1)  Construir dois boxplots, usando o `ggplot2` com cores do *New England Journal of Medicine* (NEJM), do pacote `ggsci` . Atribuir a um objeto `bp`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbp <- ggplot(dados, aes(x=sexo, y=notas)) +\n    geom_errorbar(stat = \"boxplot\", width = 0.1)+\n    geom_boxplot(aes(fill = sexo),\n                 color = \"black\")+\n    scale_color_nejm() +\n    theme_classic(base_size = 13) +\n    theme(legend.position=\"none\")\n```\n:::\n\n\n2)  Adicionar ao boxplot novos rótulos e os testes realizados:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbp +\n labs(x = \"Sexo\", \n      y = \"Notas\", \n      title = \"Notas de Bioestatística\",\n      subtitle = rstatix::get_test_label(stat.test = teste,\n                                           correction = \"none\",\n                                           detailed = TRUE,\n                                           type = \"expression\",\n                                           p.col = \"p\"))\n```\n\n::: {.cell-output-display}\n![Boxplots comparando os dois grupos](14-teste-t_files/figure-html/fig-bxpt-1.png){#fig-bxpt fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nUma alternativa ao boxplot é usar o gráfico dotplot (@fig-dot), função `geom_beeswarm()` e uma barra de erro e a significância [^14-teste-t-4]:\n\n[^14-teste-t-4]: Se o *p* for pequeno é convertido para `*`, `**`, `***` em função da ação do argumento `map_signif_level = TRUE` da função `ggsignif()` do pacote `ggsignif`. Para mostrar o valor numérico em vez de asteriscos, trocar para `map_signif_level = FALSE`. Um asterisco `*` já indica que o resultado é estatisticamente significativo, ou seja, é $p < 0,05$ ; `**` significa $p < 0,01$; `***` , $p < 0,001$ e **quatro asteriscos** (`****`) são raros e indicam um *p* extremamente pequeno ($< 0,0001$).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data = dados, aes(x = sexo, y = notas)) +\n  ggbeeswarm::geom_beeswarm(method = \"swarm\",\n                            color = \"cadetblue\",\n                            alpha = 0.8, \n                            size = 2,\n                            cex = 2) +\n  geom_errorbar(stat = \"summary\", \n                fun.data = \"mean_sd\", \n                width = 0.10,\n                linewidth = 0.8,\n                linetype = \"solid\",\n                color = \"red\") +\n  geom_point(stat = \"summary\", fun = mean, color = \"red\", size = 2) +\n  ggsignif::geom_signif(comparisons = list(c(\"Feminino\", \"Masculino\")),\n                        map_signif_level = TRUE,\n                        textsize = 4, \n                        tip_length = 0.01) +\n  labs(y = \"Notas\", x = NULL) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Dotplots com barra de erro comparando os dois grupos. [**] significa p < 0,01](14-teste-t_files/figure-html/fig-dot-1.png){#fig-dot fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n## Teste *t* para grupos pareados\n\nUm *teste t pareado* é usado para estimar se as médias de duas medidas relacionadas são significativamente diferentes uma da outra. Esse teste é usado quando duas variáveis contínuas são relacionadas porque são coletadas do mesmo participante em momentos diferentes (antes e depois), de locais diferentes na mesma pessoa ao mesmo tempo ou de casos e seus controles correspondentes.\n\n### Dados usados nesta seção\n\nO banco de dados é constituído por uma amostra de 15 escolares portadores de asma não controlada. Fizeram avaliação da sua função pulmonar no início do uso de um novo corticoide inalatório. Após 60 dias, repetiram a avaliação da função pulmonar[^14-teste-t-5].\n\n[^14-teste-t-5]: O autor entende e recomenda que esta metodologia \"ante e depois\" deve ser evitada, pois traz consigo importante vieses como regressão à média, efeito placebo ou nocebo, viés temporal, viés de mensuração, etc. Ver @sec-trials . O uso aqui tem objetivo didático de mostrar a lógica estatística.\n\nPara baixar o banco de dados, clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosPar.xlsx). Faça o downloado para o seu diretório de trabalho.\n\n#### Leitura e transformação dos dados {#sec-pivot}\n\nLeia o arquivo `dadosPar.xlsx` a partir do diretório de trabalho, usando a função `read_excel()` do pacote `readxl`. Atribuir os dados a um objeto com o nome `dados`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosPar.xlsx\")\n```\n:::\n\n\nA estrutura dos dados podem ser visualizada, usando a função `str()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [15 × 3] (S3: tbl_df/tbl/data.frame)\n $ id   : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...\n $ basal: num [1:15] 1.3 1.47 2.06 1.95 1.47 1.13 1.48 0.94 1.05 0.87 ...\n $ final: num [1:15] 1.53 1.63 2.35 2.7 2.01 1.53 1.66 1.59 1.5 1.61 ...\n```\n\n\n:::\n:::\n\n\nO dataframe `dados` encontra-se no formato amplo (*wide*), ou seja, com as colunas basal e final colocadas lado a lado como se fossem duas variáveis distintas, quando, na realidade, constituem-se em apenas uma variável contendo as medidas de VEF1 (Volume Expiratório Forçado no primeiro segundo).\n\nA função `pivot_longer()` do pacote `tidyr` fará a transformação do formato amplo para o longo (*long*). Este processo não é obrigatório, mas será realizado para fins de treinamento. O novo banco de dados será atribuído ao objeto `dadosL`. A função `pivot_longer()` necessita dos seguintes argumentos:\n\n- **dados** $\\to$ dataframe a ser pivotado, transformado;\n- **cols** $\\to$ colunas a serem transformadas no formato longo;\n- **names_to** $\\to$ Especifica o nome da coluna a ser criada a partir dos dados armazenados nos nomes das colunas de dados;\n- **values_to** $\\to$ Especifica o nome da coluna a ser criada a partir dos dados armazenados nos valores das células;\n- **...** $\\to$ possui outros argumento. Ver ajuda.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL <- dados |> \n  tidyr::pivot_longer(c(basal, final), \n                      names_to = \"momento\",\n                      values_to = \"medidas\") |> \n  dplyr::mutate(momento = factor(momento,\n                               levels = c(\"basal\", \"final\")))\nstr(dadosL)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [30 × 3] (S3: tbl_df/tbl/data.frame)\n $ id     : num [1:30] 1 1 2 2 3 3 4 4 5 5 ...\n $ momento: Factor w/ 2 levels \"basal\",\"final\": 1 2 1 2 1 2 1 2 1 2 ...\n $ medidas: num [1:30] 1.3 1.53 1.47 1.63 2.06 2.35 1.95 2.7 1.47 2.01 ...\n```\n\n\n:::\n:::\n\n\n#### Medidas Resumidoras\n\nPara resumir as variáveis, serão usadas as funções `group_by()` e `summarise()` do pacote `dplyr`, aplicadas ao formato longo `dadosL`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dadosL |> \n  dplyr::group_by(momento)  |>  \n  dplyr::summarise(n = n (),\n                   media = mean(medidas, na.rm = TRUE),\n                   dp = sd (medidas, na.rm = TRUE),\n                   mediana = median (medidas, na.rm = TRUE),\n                   IIQ = IQR (medidas, na.rm =TRUE),\n                   ep = dp/sqrt(n),\n                   me = ep * qt(1 - (0.05/2), n - 1)) \nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 8\n  momento     n media    dp mediana   IIQ    ep    me\n  <fct>   <int> <dbl> <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 basal      15  1.31 0.427    1.26  0.48 0.110 0.236\n2 final      15  1.69 0.471    1.59  0.38 0.122 0.261\n```\n\n\n:::\n:::\n\n\n#### Visualização dos dados\n\nApenas, por uma questão didática, serão apresentadas maneiras de mostrar os dados visualmente. Podem ser usados qualquer um dos tipos a seguir, pois todos dão, praticamente, a mesma informação.\n\n[Boxplot]{.underline}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndadosL  |>  \n  ggplot(aes(x = momento, y = medidas, fill = momento)) +\n  geom_errorbar(stat = \"boxplot\", width = 0.1) +\n  geom_boxplot (outlier.color = \"red\", \n                outlier.shape = 1,\n                outlier.size = 1) +\n  scale_fill_manual(values = c(\"cyan4\",\"cyan3\")) +\n  ylab(\"Volume Forçado em 1 seg (L)\") +\n  xlab(\"Momento\") +\n  stat_summary(fun = mean, \n               geom = \"point\", \n               shape = 19, size = 2,  color=\"red\") +\n  theme_classic(base_size = 13) + \n  theme(text = element_text(size = 12)) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![Boxplots comparando o grupo antes e depois](14-teste-t_files/figure-html/fig-bp-1.png){#fig-bp fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nA altura da caixa dos boxplots (@fig-bp)) é o intervalo interquartil (IIQ) e corresponde a 50% dos dados. A linha que corta horizontalmente a caixa é a mediana. Os bigodes da caixa (*whiskers*) em suas extremidades são os limites inferior e superior dos dados, excluindo os valores atípicos (*outliers*), representado no boxplot final por um ponto vermelho, acima do limite superior. Os pontos em vermelho (dentro das caixas) representam as médias.\n\n[Gráfico de barra de erro]{.underline}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresumo |> \n  ggplot2::ggplot(aes(x=momento, y=media, group=1)) +\n  geom_line(linetype ='dashed') +\n  geom_errorbar(aes(ymin=media - me,\n                    ymax=media + me),\n                width=0.1,\n                linewidth = 1,\n                col = c(\"cyan4\",\"cyan3\")) +\n  geom_point(size = 3, color = c(\"cyan4\", \"cyan3\")) +\n  theme_classic(base_size = 13)+\n  labs(x='Momento',\n       y='Volume Forçado em 1 seg (L)')\n```\n\n::: {.cell-output-display}\n![Gráfico de barra de erro comparando o grupo antes e depois](14-teste-t_files/figure-html/fig-lin-1.png){#fig-lin fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nEste gráfico de barra de erro associado a uma linha (@fig-lin) mostra uma diferença entre os valores basais e finais.\n\nA escolha do tipo de gráfico depende da ênfase do autor sobre os dados.\n\n#### Criação de uma variável que represente a diferença entre as médias\n\nEm amostras pareadas, a diferença entre os dois valores de dados para cada elemento das duas amostras é denotada por *d*. Esse valor *d* é chamado de **diferença pareada**.\\\nOs valores da média e do desvio padrão, $\\overline{d}$ e $s_d$, das diferenças pareadas para duas amostras são calculados como:\n\n$$\\overline{d} = \\frac{\\sum d}{n}$$\n\n$$s_{d} = \\sqrt \\frac{\\sum \\left ( d - \\overline{d} \\right )^2}{n - 1}$$\n\nPara criar essa diferença entre as média basal (\"antes\") e final (\"depois\"), `d`, será usado o banco de dados amplo (`dados`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$d <- dados$basal - dados$final\n\nhead (dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n     id basal final     d\n  <dbl> <dbl> <dbl> <dbl>\n1     1  1.3   1.53 -0.23\n2     2  1.47  1.63 -0.16\n3     3  2.06  2.35 -0.29\n4     4  1.95  2.7  -0.75\n5     5  1.47  2.01 -0.54\n6     6  1.13  1.53 -0.4 \n```\n\n\n:::\n:::\n\n\n::: callout-caution\n## Atenção\n\nO banco de dados, agora, apresenta uma nova variável representando a diferença `d`, que permite calcular o foco do teste *t* pareado, a média das diferenças.\n:::\n\n[Resumo da variável `d`]{.underline}\n\nAo resumo será atribuído ao nome `resumo_d` :\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo_d <- dados |> \n  dplyr::summarise(media = mean (d, na.rm = TRUE),\n                   dp = sd (d, na.rm = TRUE),\n                   mediana = median (d, na.rm = TRUE),\n                   IIQ = IQR (d, na.rm = TRUE),\n                   min = min (d, na.rm = TRUE),\n                   max = max (d, na.rm = TRUE))\nresumo_d\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n   media    dp mediana   IIQ   min     max\n   <dbl> <dbl>   <dbl> <dbl> <dbl>   <dbl>\n1 -0.377 0.218   -0.38 0.285 -0.75 -0.0400\n```\n\n\n:::\n:::\n\n\nExiste uma diferença de 0.38L entre o VEF1 basal e o final.\n\n::: callout-important\n## Pergunta a ser respondida\n\nExiste uma diferença estatisticamente significativa entre a avaliação da função pulmonar inicial e a final?\n:::\n\nOs gráficos sugerem que sim!\n\n### Definição das hipóteses estatísticas\n\nSerá usado um teste bicaudal. Se a intervenção não produz efeito, então:\n\n$$H_{0}: \\mu_{d} = 0  $$\n\nSe a intervenção produz efeito, então:\n\n$$H_{1}: \\mu_{d} \\neq 0$$\n\n### Regra de decisão\n\nO nível significância, $\\alpha$, escolhido é igual a 0,05. A distribuição da estatística do teste, sob a $H_{0}$, é a distribuição *t* que é dependente dos graus de liberdade. O número de graus de liberdade é igual ao número de observações menos 1, neste caso são o número de pares menos 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(dados$d)\ngl <- n - 1\ngl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14\n```\n\n\n:::\n:::\n\n\nPara um $\\alpha = 0,05$, o valor crítico de *t* para gl = 14 para uma hipótese alternativa bicaudal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\np <- 1 - alpha/2\nround(qt(p, 14), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.145\n```\n\n\n:::\n:::\n\n\nPortanto, se\n\n$$\\mid t_{calculado}\\mid < \\mid t_{crítico}\\mid -> não \\quad rejeitar \\quad H_{0} \\\\ \\mid t_{calculado}\\mid > \\mid t_{crítico}\\mid -> rejeitar \\quad H_{0}$$\n\n### Teste estatístico\n\n#### Lógica do teste\n\nA estatística do teste *t* dependente é a mesma do teste *t* independente é dada por:\n\n$$t = \\frac{\\bar{d} - \\mu_{d}}{EP_{d}}$$\n\nComo na equação do teste *t* para amostras independentes, sob a hipótese nula igual a zero, $\\mu_{d} = 0$, assim, a equação fica:\n\n$$T = \\frac{\\bar{d}}{EP_{d}}$$\n\nA estimativa do erro padrão das diferenças é dada por:\n\n$$EP_{d}=\\frac{s_{d}}{\\sqrt{n}}$$\n\nO desvio padrão das diferenças, $s_{d}$ , é dado pela fórmula, vista acima, do $s_{d}$.\n\nDa mesma maneira que no teste *t* para grupos independentes, essa demonstração serve para uma melhor compreensão de como o teste funciona, mas para executar este teste *t* não há necessidade disso, basta saber como encaminhar ao R, como será visto adiante.\n\n#### Pressupostos do teste\n\nO teste *t* pareado assume que os seguintes pressupostos devem ser atendidos:\n\n(1) Os dados devem ser dependentes;\n(2) A variável desfecho deve estar em uma escala contínua;\n(3) As diferenças entre os pares devem ter distribuição normal.\n\nAo usar um teste *t* pareado, a variação entre os pares de medidas é a estatística mais importante e a variação entre os participantes, como no teste t de duas amostras independentes, é de pouco interesse, não havendo necessidade de se verificar se as variâncias dos grupos são iguais.\n\nPara testar o pressuposto de *normalidade* das diferenças, usa-se a variável criada da diferença entre os pares, *d*. Verifica-se a normalidade dessa variável com o teste Shapiro-Wilk, usando a função `shapiro_test()` do pacote `rstatix`, já usada no teste *t* de amostras independentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro <- dados  |>  \n   rstatix::shapiro_test(d)\nshapiro\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  variable statistic     p\n  <chr>        <dbl> <dbl>\n1 d            0.942 0.410\n```\n\n\n:::\n:::\n\n\nO teste de Shapiro-Wilk retorna um valor *p* \\> 0,05, mostrando que não se pode rejeitar a hipótese nula de sua normalidade.\n\nAlém disso, um gráfico Q-Q (@fig-qq) pode ser usado para avaliar a normalidade, com a função `ggqqplot()` do pacote `ggpubr` [@kassambara2022ggpubr] que produz um gráfico QQ normal com uma linha de referência, acompanhada de área sombreada, correspondente ao IC95%\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggqqplot(dados, \n                 x = \"d\", \n                 color = \"steelblue\") +\n  labs(y = \"Diferença Basal-Final\", \n       x = \"Quantis teóricos\") +\n  theme_classic(base_size = 13) \n```\n\n::: {.cell-output-display}\n![Gráfico QQ para avaliar a normalidade](14-teste-t_files/figure-html/fig-qq-1.png){#fig-qq fig-align='center' width=60% height=60%}\n:::\n:::\n\n\nOs resultados do teste de Shapiro-Wilk e o gráfico QQ, mostram que a $H_{0}$ de normalidade da variável *d* não é rejeitada, apesar de haver uma pequena assimetria à esquerda que não impede o prosseguimento da análise.\n\n#### Execução do teste estatístico\n\nO cálculo do teste *t* pareado pode usar a mesma função do teste *t* para amostras independentes, `t_test()`, do pacote `rstatix`, mudando o argumento `paired = FALSE` (padrão) por `paired = TRUE`. Assim:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteste_par <- dadosL |> \n  rstatix:: t_test(formula = medidas ~ momento,\n                   paired = TRUE,\n                   detailed = TRUE) \nprint(teste_par, n = Inf, width = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 13\n  estimate .y.     group1 group2    n1    n2 statistic         p    df conf.low\n*    <dbl> <chr>   <chr>  <chr>  <int> <int>     <dbl>     <dbl> <dbl>    <dbl>\n1   -0.377 medidas basal  final     15    15     -6.70 0.0000102    14   -0.497\n  conf.high method        alternative\n*     <dbl> <chr>         <chr>      \n1    -0.256 Paired t-test two.sided  \n```\n\n\n:::\n:::\n\n\nObserve que foi usado o conjunto de dados de formato longo (`dadosL`) para usar a fórmula (`x ~ grupo`).\n\nDa mesma maneira do que o teste *t* para amostras independentes, é possível ver os resultados do teste *t* , usando o objeto `teste_par` que os recebeu. Por exemplo, os limites inferior (`conf.low`) e superior (`conf.high`) do intervalo de confiança de 95% da estimativa de diferença (*D*) entre as médias\n\n\n::: {.cell}\n\n```{.r .cell-code}\nIC95 <- round(c(teste_par$conf.low, teste_par$conf.high),3)\nIC95\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.497 -0.256\n```\n\n\n:::\n:::\n\n\n### Tamanho do Efeito\n\nPara o teste *t* pareado, a medida de tamanho do efeito mais recomendada e utilizada é o $d$ de Cohen para amostras pareadas, referido como $d_{z}$ (baseado no escore de diferença) ou $d_{p}$ (pareado). Diferente do teste *t* para amostras independentes, aqui o foco é a magnitude da mudança dentro do mesmo grupo.\n\nA fórmula básica para o cálculo manual é a média das diferenças dividida pelo desvio padrão dessas diferenças:\n\n$$d_{z} = \\frac{\\bar{d}}{s_{d}}$$\n\nA forma mais prática de obter esse valor é através da função `cohens_d()` do pacote `effectsize`, usando as variáveis `dados$basal` e `dados$final`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndz <- effectsize::cohens_d(dados$final,dados$basal, paired = TRUE, rules = \"cohen1988\")\n\neffectsize::interpret_cohens_d(dz, rules = \"cohen1988\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI | Interpretation\n-----------------------------------------\n1.73      | [0.91, 2.53] |          large\n\n- Interpretation rule: cohen1988\n```\n\n\n:::\n:::\n\n\nAlém dessa forma de calcular a magnitude do efeito, o pacote `effectsize`, em estudos de medida repetidas, sugere o uso da função `repeated_measures_d()`, pois, às vezes, o *d* de Cohen \"clássico\" ($d_{z}$) pode superestimar o efeito por não considerar a correlação entre as medidas [@cumming2013understanding] [@dunlap1996meta]. A função `repeated_measures_d()` é uma versão mais robusta que permite escolher o denominador (o desvio padrão usado para padronizar o efeito). Existem duas opções:\n\n1.  $d_{rm}$ (**Repeated Measures**) : É o padrão da função. Ele ajusta o desvio padrão pela correlação entre o \"antes\" e o \"depois\". É ideal quando você quer uma estimativa que controle a variabilidade individual dos participantes.\n\n2.  $d_{av}$ (**Average**): Utiliza a média dos desvios padrão dos dois momentos. É muito recomendado quando o objetivo é comparar o resultado com estudos que usaram amostras independentes, pois torna os valores de $d$ mais comparáveis entre diferentes desenhos de pesquisa.\n\nQual escolher?\n\nSe a escolha é ser conservador e facilitar a comparação com outros estudos da literatura que não são pareados, usar o `method = \"av\"`.\\\nSe o interesse é puramente a magnitude da mudança dentro do seu próprio grupo, o $d$ clássico, já calculado (ou o `method = \"rm\"`) atende bem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrm <- effectsize::repeated_measures_d(dados$final,\n                                       dados$basal, \n                                       method = \"rm\")\nprint(drm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nd (rm) |       95% CI\n---------------------\n0.78   | [0.51, 1.04]\n\n- Adjusted for small sample bias.\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize::interpret_cohens_d(0.78, rules = \"cohen1988\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"medium\"\n(Rules: cohen1988)\n```\n\n\n:::\n:::\n\n\nO pacote aplicou automaticamente a correção de Hedges ($g$), que é uma versão mais precisa do $d$ para amostras pequenas (geralmente $n < 20$).\n\nNotar que o $d_z$ (1.73) é muito superior ao $d_{rm}$ (0.78). Isso acontece porque o $d_z$ não é diretamente comparável ao $d$ de amostras independentes, sendo uma medida da 'eficiência' estatística do teste, e não necessariamente da magnitude clínica da diferença.\\\nEmbora o software classifique 0.78 como 'médio' por uma questão de 0.02, em contextos práticos, esse valor demonstra um impacto substancial da intervenção, beirando o limiar de um efeito grande.\n\n### Conclusão\n\nConclui-se que o VEF1 dos escolares asmáticos se modificou significativamente entre o início e após 60 dias do uso de um novo medicamento com uma confiança de 95%. A diferença encontrada é estatisticamente significativa (t = -6.6969, gl = 14, *p* = 1.0156211\\times 10^{-5}), com uma confiança de 95%. Observe que o intervalo de confiança de 95% da diferença de -0.38 está todo abaixo de zero (-0.497, -0.256), confirmando a significância. Além disso, a magnitude do efeito pelo teste $d_{rm}$ = 0,78, considerado um efeito médio.\n\nOs resultados podem ser apresentados usando um gráfico de barra de erro (@fig-fim), aproveitando o resultado da função `t_test()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresumo |>  \n    ggplot2::ggplot(aes(x=momento, y=media, group=1)) +\n    geom_line(linetype ='dashed') +\n    geom_errorbar(aes(ymin=media - me, \n                      ymax=media + me), \n                  width=0.1,\n                  linewidth = 1,\n                  col = c(\"cyan4\",\"cyan3\")) +\n    geom_point(size = 2) +\n   labs(title=\"Avaliação do Uso de Corticosteroide Inalatório\",\n       subtitle = rstatix::get_test_label(stat.test = teste_par,\n                                          correction = \"none\",\n                                          detailed = TRUE,\n                                          type = \"expression\"),\n       x=\"Momento\", \n       y = \"Volume Expiratório Forçado em 1 seg (L)\",\n       caption = \"d Cohen = 0,84\")+\n   theme_bw() + \n   theme(legend.position=\"none\")\n```\n\n::: {.cell-output-display}\n![Gráfico de barra de erro, mostrando a diferença na resposta ao corticoide inalatório](14-teste-t_files/figure-html/fig-fim-1.png){#fig-fim fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nUma alternativa ao boxplot é usar o gráfico dotplot (@fig-fim2), função `geom_beeswarm()` e uma barra de erro e a significância\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dadosL, aes(x = momento, y = medidas)) +\n  geom_hline(yintercept = 0, \n             color= \"gray50\", \n             linetype = \"dashed\") +\n  ggbeeswarm::geom_beeswarm(method = \"center\",\n                            color = \"cadetblue\",\n                            cex = 4,\n                            alpha = 0.7) +\n  geom_errorbar(stat = \"summary\",\n                fun.data = \"mean_ci\",\n                width = 0.05,\n                linewidth = 0.8,\n                color = \"red\") +\n  geom_point(stat = \"summary\", fun = mean, color = \"red\", size = 3) +\n  geom_line(stat = \"summary\", \n            fun = mean, \n            aes(group = 1), \n            color = \"red\", \n            linewidth = 0.8,\n            linetype = \"dashed\") +\n  ggsignif::geom_signif(\n    comparisons = list(c(\"basal\", \"final\")),\n    test = \"t.test\",\n    test.args = list(paired = TRUE),\n    map_signif_level = TRUE,\n    textsize = 5,\n    tip_length = 0.01\n  ) +\n  scale_y_continuous(\n    breaks = seq(0, max(dadosL$medidas, na.rm = TRUE) + 1, by = 0.5), \n    labels = scales::label_number(decimal.mark = \",\")\n  ) +\n  labs(title=\"Avaliação do Uso de Corticosteroide Inalatório\",\n       subtitle = rstatix::get_test_label(stat.test = teste_par,\n                                          correction = \"none\",\n                                          detailed = TRUE,\n                                          type = \"expression\"),\n       x=\"Momento\", \n       y = \"Volume Expiratório Forçado em 1 seg (L)\",\n       caption = \"d Cohen = 0,78\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Gráfico dotplot, mostrando a diferença na resposta ao corticoide inalatório](14-teste-t_files/figure-html/fig-fim2-1.png){#fig-fim2 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOlhando para o resultado final, alguns pontos mostram que:\n\n- A linha de tendência, a conexão entre as médias em vermelho mostra claramente a inclinação positiva, deixando o efeito do corticoide visualmente óbvio;\\\n- O Beeswarm mostrou a distribuição individual. Note que no momento \"final\", existem alguns pacientes que responderam excepcionalmente bem (pontos no topo, acima de 2,5L), fato que não seria observado se fosse usado somente a diferença entre os escores.\n",
    "supporting": [
      "14-teste-t_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}