{
  "hash": "1b38bde2148f63a0988553f3698fa44c",
  "result": {
    "engine": "knitr",
    "markdown": "# Tabelas {#sec-tabelas}\n\nA apresentação tabular de dados, ou tabulação, é a organização dos dados por meio de tabelas. Uma tabela é uma disposição sistemática e lógica dos dados na forma de linhas e colunas com relação às características dos dados. É uma forma ordenada, compacta, autoexplicativa e eficiente de mostrar os dados levantados, facilitando a sua compreensão e interpretação. Permite identificar padrões, tendências e intuições valiosos.\\\nA tabela mais utilizada para descrever os dados é a **tabela de frequência**.\n\n## Componentes de uma tabela\n\nUma tabela bem estruturada é essencial para comunicar dados de forma clara e científica, especialmente em publicações acadêmicas. Os componentes fundamentais que uma tabela (@fig-tabela1) deve conter, para estar pronta para publicação, são os seguintes:\n\n1.  **Título da Tabela** - deve ser claro, conciso e informativo. Indica o conteúdo da tabela e o contexto do estudo. Deve estar no topo da tabela.\n\n2.  **Cabeçalho** - Identifica as variáveis apresentadas. Inclui unidades de medida quando necessário (ex: idade em anos, glicemia em mg/dL)\n\n3.  **Corpo da tabela** - Apresenta os valores estatísticos: média, mediana, desvio padrão, intervalo de confiança, etc. Pode incluir frequências absolutas e relativas (em proporção ou porcentagem). Os dados devem estar alinhados corretamente para facilitar a leitura.\n\n4.  **Notas de rodapé** - Explicações adicionais sobre abreviações, símbolos ou indicação de testes estatísticos aplicados (ex: teste *t* de Student, ANOVA, qui-quadrado). Pode incluir significância estatística (*p* \\< 0,05).\n\n5.  **Fonte dos dados** - Caso os dados sejam secundários ou provenientes de outra pesquisa, deve-se citar a fonte.\n\n![Elementos de uma tabela](images/tabela1.png){#fig-tabela1 fig-align=\"center\" width=\"16cm\"}\n\n## Tabelas de Frequências\n\nAs tabelas de frequências são essenciais em estatística para organizar e resumir dados. Ajudam a entender como os valores em um conjunto de dados se distribuem, mostrando a frequência com que cada valor ou intervalo de valores aparece.\\\nBasicamente, uma tabela de frequências responde a uma pergunta simples: \"Quantas vezes cada coisa aconteceu?\".\n\nDe um modo geral, uma tabela de frequência deve cumprir algumas finalidades:\n\n1.  **Clareza e Organização**: Elas transformam dados brutos e desorganizados em informações claras e fáceis de interpretar.\\\n2.  **Identificação de padrões**: Uma tabela deve ajudar a visualizar rapidamente os valores mais comuns (a moda) e a distribuição geral dos dados.\\\n3.  **Base para Outras Análises**: São o ponto de partida para criar gráficos como histogramas, polígonos de frequência e gráficos de setores, que oferecem uma representação visual ainda mais intuitiva.\\\n4.  **Tomada de decisão**: Permitem que se tire conclusões rápidas sobre um conjunto de dados. Por exemplo, na @tbl-droga, verifica-se que \"a maioria das gestantes, no Hospital Geral de Caxias do Sul, referem não ser drogaditas\" ou \"72% das gestantes, no Hospital Geral de Caxias do Sul, referem não ser drogaditas\".\n\n### Tipos de Frequências\n\nGeralmente, em uma tabela de frequência aparecem os seguintes tipos de frequência:\n\n#### Frequência Absoluta (f)\n\nÉ o número de vezes que um valor específico ocorre no conjunto de dados. Por exemplo, na @tbl-droga, 913 das parturientes referem não usar drogas. Podem ser:\n\n1.  [**Distribuição de frequência não agrupada**]{.underline}\\\n    As distribuições de frequência não agrupada listam cada valor individual de um conjunto de dados com a sua respetiva contagem (frequência), sendo ideais para conjuntos de dados pequenos ou com poucas categorias. A @tbl-droga mostra a frequência da variável drogadição na gestação, com os diferentes tipos de drogas usadas\n\n2.  [**Distribuição de frequência agrupada**]{.underline}\n\n    As distribuições de frequência agrupadas organizam os dados em intervalos ou classes, úteis para conjuntos de dados extensos, pois condensam a informação em grupos menores, como faixas etárias, estado nutricional da gestante na gravidez, usando o IMC categorizado, idade gestacional categorizada em pré-termo, termo e pós-termo.\n\n#### Frequência Relativa (fr)\n\nÉ a proporção da frequência absoluta em relação ao total de dados. É calculada dividindo a frequência absoluta pelo número total de observações ($fr=f/n$).\n\nA frequência relativa pode ser expressa como uma fração, decimal ou, mais comumente, como uma porcentagem (*frp*). É útil para comparar distribuições de dados com tamanhos totais diferentes. Por exemplo, na @tbl-droga, 2,13% das parturientes declararam ser alcoolistas.\\\n\n#### Frequência Absoluta Acumulada (F)\n\nÉ a soma das frequências absolutas até um determinado ponto na tabela. Ela mostra quantos dados estão abaixo ou iguais a um certo valor. Na @tbl-droga não tem importância, são variáveis nominais sem uma ordem estabelecida. Não faz sentido somar \"pessoas fumantes\" com \"pessoas não usuárias de drogas\". As frequências cumulativas não fazem sentido para variáveis nominais porque os valores não têm ordem — um valor não é maior ou menor que outro valor.\n\n#### Frequência Relativa Acumulada (Fr)\n\nÉ a soma das frequências relativas até um determinado ponto. Ela mostra a proporção de dados que estão abaixo ou iguais a um certo valor. Assim como a frequência absoluta acumulada, não faz sentido usar a frequência relativa acumulada com dados nominais, onde a ordem das categorias não tem valor.\n\n\n::: {#tbl-droga .cell tbl-cap='Distribuição de frequência de drogadição em gestantes'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"itjconogdr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#itjconogdr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#itjconogdr thead, #itjconogdr tbody, #itjconogdr tfoot, #itjconogdr tr, #itjconogdr td, #itjconogdr th {\n  border-style: none;\n}\n\n#itjconogdr p {\n  margin: 0;\n  padding: 0;\n}\n\n#itjconogdr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#itjconogdr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#itjconogdr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#itjconogdr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#itjconogdr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itjconogdr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itjconogdr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itjconogdr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#itjconogdr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#itjconogdr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#itjconogdr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#itjconogdr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#itjconogdr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#itjconogdr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#itjconogdr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#itjconogdr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#itjconogdr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#itjconogdr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#itjconogdr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itjconogdr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#itjconogdr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#itjconogdr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#itjconogdr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itjconogdr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#itjconogdr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#itjconogdr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itjconogdr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itjconogdr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#itjconogdr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itjconogdr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#itjconogdr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itjconogdr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itjconogdr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itjconogdr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itjconogdr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itjconogdr .gt_left {\n  text-align: left;\n}\n\n#itjconogdr .gt_center {\n  text-align: center;\n}\n\n#itjconogdr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#itjconogdr .gt_font_normal {\n  font-weight: normal;\n}\n\n#itjconogdr .gt_font_bold {\n  font-weight: bold;\n}\n\n#itjconogdr .gt_font_italic {\n  font-style: italic;\n}\n\n#itjconogdr .gt_super {\n  font-size: 65%;\n}\n\n#itjconogdr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#itjconogdr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#itjconogdr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#itjconogdr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#itjconogdr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#itjconogdr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#itjconogdr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#itjconogdr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#itjconogdr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:120px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style=\"color: #2E2E2E; font-family: Arial; font-size: medium; font-weight: bold;\">Drogadição em Gestantes<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Droga\">Droga</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"f\">Frequência Absoluta<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"frp\">Frequência Relativa (%)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Nenhuma</td>\n<td headers=\"f\" class=\"gt_row gt_center\">913</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">72.06</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Fumo</td>\n<td headers=\"f\" class=\"gt_row gt_center\">301</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">23.76</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Álcool</td>\n<td headers=\"f\" class=\"gt_row gt_center\">27</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">2.13</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Medicamentos</td>\n<td headers=\"f\" class=\"gt_row gt_center\">23</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">1.82</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Crack</td>\n<td headers=\"f\" class=\"gt_row gt_center\">2</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">0.16</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Cocaína</td>\n<td headers=\"f\" class=\"gt_row gt_center\">1</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">0.08</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_left\">Total</td>\n<td headers=\"f\" class=\"gt_row gt_center\">1267</td>\n<td headers=\"frp\" class=\"gt_row gt_center\">100.00</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> Hospital Geral de Caxias do Sul, RS, 2008</td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> 101 gestantes não informaram a condição de drogadição</td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"3\"><span data-qmd-base64=\"Rm9udGU6IE9saXZlaXJhIEZpbGhvLCBQRiAoMjAyNSk=\"><span class='gt_from_md'>Fonte: Oliveira Filho, PF (2025)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Regras gerais para construção de tabelas de frequência\n\nExistem algumas recomendações na construção de uma tabela de frequência [@arango2009tab]:\n\n- Deve ter um título na parte superior que responda as perguntas: “o que? quando? onde?” relativas ao fato estudado;\n\n- Deve ter um rodapé, na parte inferior da tabela, onde se coloca notas necessárias e a fonte dos dados;\n\n- As colunas externas da tabela devem ser abertas, o emprego de linhas verticais para a separação das colunas no corpo da tabela é opcional;\n\n- Na parte superior e inferior, as tabelas devem, ser fechadas por linhas horizontais;\n\n- Nenhuma casela deve ficar vazia, apresentando um número ou um símbolo. Se não se dispuser do dado, colocar reticências ... e a presença de um X representa que o dado foi omitido para evitar a identificação.\n\n- Tabelas devem ter, pelo menos, duas linhas no seu corpo e, prioritariamente, pelo menos três colunas. Tabelas com duas colunas devem ser evitadas, pois as informações contidas nelas podem, em geral, ser apresentadas no corpo do texto da obra.\n\n### Construção de tabelas de frequência no R {#sec-tabfreq}\n\n#### Dados para os exemplos {#sec-dados-cap7}\n\nPara os exemplos, o dataframe `dadosMater.xlsx` será acionado para fornecer dados, semelhante ao realizado na @sec-dados-cap6.\n\nApós carregar o dataframe, serão selecionadas as variáveis necessárias. As variáveis `uti_neo` e `sexo` serão convertidas em fatores; a variável `idade_mae` será categorizada em três níveis (\\<20 anos, 20-35 anos, \\>35 anos), criando uma nova variável `categIdade`. Além disso, será criada a variável `imc` que também será categorizada em uma nova variável `estato_nutri` em quatro níveis (Baixo Peso, Peso adequado, Sobrepeso, Obesidade). Por último, será extraída uma amostra de n = 200 e atribuída a um objeto `dados`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(readxl)\n\nset.seed(123)\ndados <- readxl::read_excel(\"dados/dadosMater.xlsx\") |> \n  select(idade_mae, peso, altura, anos_est, fumo, peso_rn, apgar1, uti_neo) |> \n  mutate(fumo = factor(fumo, \n                       levels = c(1,2), \n                       labels = c(\"fumante\", \"não fumante\")),\n         uti_neo = factor(uti_neo, \n                         levels = c(1,2), \n                         labels = c(\"sim\", \"não\")),\n         categIdade = case_when(\n           idade_mae < 20 ~ \"< 20 anos\",\n           idade_mae >= 20 & idade_mae <= 35 ~ \"20 a 35 anos\",\n           idade_mae > 35 ~ \"> 35 anos\"),\n         categIdade = factor(categIdade, \n                             levels = c(\"< 20 anos\", \"20 a 35 anos\", \"> 35 anos\")),\n         imc = peso/altura^2,\n         estado_nutri = case_when(\n           imc < 18.5 ~ \"Baixo Peso\",\n           imc >= 18.5 & imc < 25 ~ \"Peso adequado\", \n           imc >= 25 & imc < 30 ~ \"Sobrepeso\",\n           imc >= 30 ~ \"Obesidade\"),\n         estado_nutri = factor(estado_nutri, \n                           levels = c(\"Baixo Peso\", \"Peso adequado\", \n                                      \"Sobrepeso\", \"Obesidade\"))) |>\n  slice_sample(n=200) \n\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [200 × 11] (S3: tbl_df/tbl/data.frame)\n $ idade_mae   : num [1:200] 16 19 27 18 29 38 15 26 27 22 ...\n $ peso        : num [1:200] 68 49 64 53 76 55 64 81 62 59.5 ...\n $ altura      : num [1:200] 1.59 1.62 1.78 1.65 1.64 1.6 1.69 1.65 1.72 1.65 ...\n $ anos_est    : num [1:200] 9 11 13 7 11 4 7 6 8 11 ...\n $ fumo        : Factor w/ 2 levels \"fumante\",\"não fumante\": 2 2 1 2 2 2 1 2 2 2 ...\n $ peso_rn     : num [1:200] 2940 3060 1930 2790 1750 ...\n $ apgar1      : num [1:200] 8 9 NA 9 NA 4 9 8 8 9 ...\n $ uti_neo     : Factor w/ 2 levels \"sim\",\"não\": 2 2 2 2 1 2 2 2 2 2 ...\n $ categIdade  : Factor w/ 3 levels \"< 20 anos\",\"20 a 35 anos\",..: 1 1 2 1 2 3 1 2 2 2 ...\n $ imc         : num [1:200] 26.9 18.7 20.2 19.5 28.3 ...\n $ estado_nutri: Factor w/ 4 levels \"Baixo Peso\",\"Peso adequado\",..: 3 2 2 2 3 2 2 3 2 2 ...\n```\n\n\n:::\n:::\n\n\n#### Tabelas de frequência para dados categóricos\n\n[Função `table()` e função `prop.table()`]{.underline}\n\nO R básico possui uma função incorporada, `table()` que permite a verificação da frequência absoluta de variáveis categóricas de uma maneira bem simples. A função `table()` é a base para criar tabelas de frequência. Ela conta o número de ocorrências de cada valor em um vetor (ou coluna de um dataframe). Por exemplo, a frequência absoluta (`f`) em cada uma das categorias da variável `categIdade`: (idade das parturientes dividida em classes):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf  <- table (dados$categIdade)\nprint (f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   < 20 anos 20 a 35 anos    > 35 anos \n          33          144           23 \n```\n\n\n:::\n:::\n\n\nA função `prop.table()` é usada para calcular as frequências relativas a partir de uma tabela de frequência absoluta. Em outras palavras, ela transforma as contagens em proporções ou porcentagens. A função `round()` recebe a função `prop.table()` para arredondar para três dígitos a frequência relativa (`fr`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfr  <- round(prop.table(f), 3)\nprint(fr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   < 20 anos 20 a 35 anos    > 35 anos \n       0.165        0.720        0.115 \n```\n\n\n:::\n:::\n\n\nMultiplicando por 100 a `fr`, tem-se a frequência relativa em porcentagem – `frp` ou `fr(%)`. A operação será colocada dentro da função `round()`, como feito com a `fr`, arredondando o resultado para dois dígitos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfrp <- round(fr*100, 2)\nprint(frp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   < 20 anos 20 a 35 anos    > 35 anos \n        16.5         72.0         11.5 \n```\n\n\n:::\n:::\n\n\nEmbora as funções `table()` e `prop.table()` sejam separadas, é muito comum usá-las juntas para construir uma **tabela de frequência completa**. Portanto, os passos para a construção de uma tabela de frequência no R são os seguintes\n\nPara atingir este objetivo, a construção de uma tabela de frequência absoluta e de frequência relativa (%) deve ser o primeiro passo. Os passos seguintes são;\n\n**Passo 1**:Usar as funções `table()` e `prop.table()` juntas como feito acima, para construir as frequências absoluta e relativa.\n\n**Passo 2**: Criar um dataframe combinando as funções para uma melhor visualização:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_completa <- data.frame(\n     f = as.vector(f),\n     fr = as.factor(fr),\n    frp = as.vector(frp))\n\nprint(tab_completa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               f    fr  frp\n< 20 anos     33 0.165 16.5\n20 a 35 anos 144  0.72 72.0\n> 35 anos     23 0.115 11.5\n```\n\n\n:::\n:::\n\n\nEste último exemplo mostra a flexibilidade do R para manipular e apresentar dados de forma clara e organizada, combinando as saídas de funções básicas em uma única tabela.\n\nPara análises mais avançadas ou para variáveis quantitativas contínuas, pode-se usar a função `mutate()` , junto com a função `case_when()` [@geeks2025case_when] , usada para criar a variáveis `categIdade` e `estNutri`, na @sec-dados-cap7. Também é possível associar a função `mutate()` com a função `cut()`, como se verá a seguir.\n\n#### Tabelas de frequência para dados numéricos {#sec-freq}\n\nA construção de tabelas de frequência com dados agrupados em classes é crucial quando se lida com variáveis quantitativas contínuas, como idade, altura, peso do recém-nascido, renda, etc. Usar table() diretamente, nesses casos não faz sentido, pois cada valor pode ser único e o número de “categorias” seria imenso, tornando a tabela quase inútil. A solução é agrupar os dados em **intervalos** ou **classes**. Para realizar esta operação, pode-se acionar a mesma função `mutate()` associada a função `cut()`, que divide um vetor numérico em fatores com base em intervalos especificados.\n\n[**Passo a passo com a função cut()**]{.underline}\n\nComo exemplo prático, a variável de interesse será representada pelos pesos dos recém-nascidos (`peso_rn`) do conjunto de dados, `dados`, mencionado na (@sec-dados-cap7).\n\n**Passo 1**: [Definir os intervalos de classe]{.underline}\n\nAntes, as classes foram estabelecidas de acordo com algum critério escolhido pelo autor ou por algum critério relacionado à saúde, como por exemplo a idade materna, onde as gestante com idade abaixo de 20 anos e acima de 35 anos, gestantes com baixa escolaridade (\\< de 5 anos), situação conjugal insegura, etc., constituem fatores de risco na gravidez [@schirmer2000manual]. Em geral, quando não há um padrão pré-determinado, o número de classes é estabelecido de acordo com o tamanho da amostra. Este número pode ser escolhido lembrando-se das oscilações que ocorrem nos dados e do interesse do pesquisador em mostrar seus dados. Não existe uma regra totalmente eficiente para determinar o número de classes. É importante ter bom senso, de maneira que seja possível ver como os valores se distribuem. Uma regra geral é usar entre 5 e 15 classes [@Daniel_Cross_2013], mas isso pode variar. Com poucas classes, perde-se precisão e, com muitas classes, a tabela torna-se muito extensa. Uma forma comum é usar a *Regra de Sturges* [^07-tabelas-1], para estimar o número de classes. Baseado na regra de Sturges é sugerido usar a recomendação da [@tbl-sturges; @arango2009classes].\n\n[^07-tabelas-1]: Determina que o número de classes (*k*) pode ser calculado pela fórmula: $k = 1 + 3.322 * log10(n)$, onde *n* é igual ao número de observações.\n\n\n::: {#tbl-sturges .cell tbl-cap='Numero de classes, baseado em Sturges'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d5185cbe{}.cl-d5022066{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d502207a{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d502207b{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d513831a{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5138324{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d513a3ae{width:1.802in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3b8{width:1.216in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3b9{width:1.802in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3c2{width:1.216in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3c3{width:1.802in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3c4{width:1.216in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3c5{width:1.802in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d513a3cc{width:1.216in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d5185cbe'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d513a3ae\"><p class=\"cl-d513831a\"><span class=\"cl-d5022066\">Nº de observações (n)</span></p></th><th class=\"cl-d513a3b8\"><p class=\"cl-d513831a\"><span class=\"cl-d5022066\">Nº de classes</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">1</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">1</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">2</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">2</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">3 a 5</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">3</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">6 a 11</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">4</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">12 a 23</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">24 a 46</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">6</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">47 a 93</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">7</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">94 a 187</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">8</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3b9\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">188 a 376</span></p></td><td class=\"cl-d513a3c2\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">9</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d513a3c3\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">377 a 756</span></p></td><td class=\"cl-d513a3c4\"><p class=\"cl-d513831a\"><span class=\"cl-d502207a\">10</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"2\"class=\"cl-d513a3c5\"><p class=\"cl-d5138324\"><span class=\"cl-d502207b\">FONTE: Arango, H. G. (2009)</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nPara a variável `dados$peso_rn`, como existem 200 observações, pode-se, de acordo com a @tbl-sturges, usar ao redor de 9 classes. O R tem uma função `nclass.Sturges ()`, que também pode ser usada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- nclass.Sturges(dados$peso_rn)\nprint(k)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n\nO cálculo da função retorna o mesmo resultado.\n\n**Passo 2**: [Amplitude e limites das classes]{.underline}\n\nA classe possui um **limite inferior** e um **limite superior**. O importante é que os limites dos intervalos sejam mutuamente exclusivos, isto é, cada valor deve ser representado em um único intervalo. Além disso, os intervalos devem ser exaustivos, isto é, devem conter todos os valores possíveis entre o valor mínimo e o máximo. O recomendado é que as classes sejam homogêneas, ou seja, tenham a mesma amplitude[^07-tabelas-2]. A amplitude dos valores pode ser obtida com a função `range()`:\n\n[^07-tabelas-2]: Quando já existe um critério, como mostrado acima, ou o pesquisador tem um determinado interesse, as classes podem ter amplitudes diferentes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\namplitude <- range(dados$peso_rn) \namplitude\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  810 4670\n```\n\n\n:::\n:::\n\n\nUsando esta amplitude dos dados, é possível ter a largura das classes (*h*):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh <- round(diff(amplitude)/k, 0)\nh\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 429\n```\n\n\n:::\n:::\n\n\nA fórmula é apenas a diferença absoluta dos valores mínimos e máximo , calculada pela função `diff()` [^07-tabelas-3], dividida pelo número de classes (*k*), arredondado com a função `round()`.\n\n[^07-tabelas-3]: A função `diff()` no R calcula as diferenças entre elementos consecutivos de um vetor, matriz ou série temporal. Ela subtrai cada elemento do elemento seguinte, retornando um valor absoluto.\n\nA partir desses dados, é possível construir as classes: O limite inferior da primeira classe é 810 e o limite superior é 1239, exclusive; o limite inferior da segunda classe inclui o valor de 1239 e vai até 1668, excluindo-o, pois ele será limite inferior da terceira classe e assim por diante\n\n**Passo 3**: [Agrupar os dados usando `cut()`]{.underline}\n\nSeguir esse processo seria longo, tedioso e sujeito a erros. O R permite agilizar este trabalho com as funções `mutate()` e função `cut()`. Dentro da função `cut()`, pode ser acionada a função `seq()` para estabelecer os pontos de corte.\n\n1.  Criar uma sequência dos pontos de corte desejados, usando a função `seq()`:\n\n    ::: callout-tip\n    ### Sintaxe função seq()\n\n    Necessita os seguintes argumentos:\n\n    - **from** : valor inicial da sequência\n\n    - **to**: valor final da sequência\n\n    - **length.out**: número inteiro que especifica o comprimento desejado da sequência. Este último argumento é importante, pois se o objetivo é construir  9 classes, preciso de uma sequência de 10 valores.\n    :::\n\nComo os pontos de cortes precisam ser números inteiros, usa-se a função `round()` com 0 (zero) dígitos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalor_min <- min(dados$peso_rn)    # valor inicial\nvalor_max <- max(dados$peso_rn)    # valor final\nlength.out = k + 1                # 10 valores para obter 9 classes\n\ncortes <- round(seq(valor_min, valor_max, length.out = k + 1), 0) \ncortes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  810 1239 1668 2097 2526 2954 3383 3812 4241 4670\n```\n\n\n:::\n:::\n\n\n2.  Tendo os pontos de corte estabelecidos, basta agora criar a variável `pesoCateg`, ou seja a variável `peso_rn` numérica classificada em 9 classes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Criando rótulos personalizados com os valores exatos de 'cortes'\nrotulos <- paste0(\"[\", cortes[-length(cortes)], \", \", cortes[-1], \")\")\n\n# Categorizando a variável peso_rn\ndados <- dados |> \n  mutate(pesoCateg = cut(\n    peso_rn,\n    breaks = cortes,\n    include.lowest = TRUE,\n    right = FALSE,\n    ordered_result = TRUE,\n    labels = rotulos\n  ))\n```\n:::\n\n\n::: callout-note\n## Nota\n\nObserve a lógica para o último intervalo, que é fechado nos dois lados \\[ \\] , incluindo os valores no intervalo de classe. Os outros obedecem a lógica \\[ ), incluindo o valor limite inferior e excluindo o superior. A forma como isso ocorre é determinado pela função `cut()` , que cria os intervalos (variável `pesoCateg`), depende de dois argumentos lógicos:\n\n- **right = TRUE (padrão):** Os intervalos são do tipo (X, Y\\]. Isso significa que o valor X não é incluído, mas o valor Y é. O primeiro intervalo é a exceção, sendo \\[X, Y\\].\n\n- **right = FALSE:** Os intervalos são do tipo \\[X, Y), como no exemplo usado, \\[810,1239). Isso significa que o valor 810 é incluído, mas o valor 1239 não é. O último intervalo é a exceção, sendo \\[X, Y\\]. No exemplo, \\[4241,4670\\] e significa que os dois valores estão incluídos.\n\n- O argumento `include.lowest` entra em jogo, modificando o comportamento padrão:\n\nQuando se usa `right = FALSE` (como o código usado acima), o R cria intervalos \\[X, Y), no exemplo, igual a \\[810,1239). O argumento `include.lowest = TRUE` faz com que o primeiro intervalo seja \\[mínimo, Y), garantindo que o valor mínimo da variável - 810 - seja incluído no primeiro intervalo.\n\nResumindo:\n\n1\\) **right = FALSE e include.lowest = TRUE:**\n\n- **Intervalos:** \\[A, B), \\[C, D), \\[E, F), e assim por diante.\n\n- **O primeiro intervalo** (\\[min(x), ...) ) **inclui o valor mínimo**.\n\n- **O último intervalo** (\\[..., max(x)\\]) **inclui o valor máximo**.\n\n2\\) **right = TRUE** (padrão) **e include.lowest = FALSE** (padrão):\n\n- **Intervalos:** (A, C\\], (C, D\\], (E, F\\].\n\n- **O primeiro intervalo** \\[min(x), ...\\] **inclui o valor mínimo**.\n:::\n\n**Passo 4**: [Construção da tabela de frequência]{.underline}\n\nCom os dados agrupados em classes, agora, pode-se usar as funções `table()` e `prop.table()` para construir a tabela de frequência absoluta e relativa, como realizado anteriormente.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Frequência Absoluta\nf <- table(dados$pesoCateg)\nprint(f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n [810, 1239) [1239, 1668) [1668, 2097) [2097, 2526) [2526, 2954) [2954, 3383) \n           4            5           10           14           47           62 \n[3383, 3812) [3812, 4241) [4241, 4670) \n          42           12            4 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Frequência Relativa Percentual\nfrp <- prop.table(f) * 100\nprint(frp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n [810, 1239) [1239, 1668) [1668, 2097) [2097, 2526) [2526, 2954) [2954, 3383) \n         2.0          2.5          5.0          7.0         23.5         31.0 \n[3383, 3812) [3812, 4241) [4241, 4670) \n        21.0          6.0          2.0 \n```\n\n\n:::\n:::\n\n\n[Tabela de Frequência Completa]{.underline}\n\nPara uma apresentação mais clara, combinar tudo em um dataframe, adicionando as colunas de frequência acumulada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dataframe com as f e fr como vetores\ntab_frequencia <- data.frame(f = as.vector(f),\n                             frp = as.vector(frp))\n  \n# Adicionar Frequência Absoluta Acumulada\ntab_frequencia$F <- cumsum(tab_frequencia$f)\n\n# Adicionar Frequência Relativa Acumulada (%)\ntab_frequencia$Frp <- cumsum(tab_frequencia$frp)\n  \n# Adicionar os intervalos como uma coluna  \ntab_frequencia$Classes <- names(table(dados$pesoCateg))\n\n# Reorganizar as colunas para melhor visualização\ntab_frequencia <- tab_frequencia[c(5, 1, 2, 3, 4)]\n\nprint(tab_frequencia)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Classes  f  frp   F   Frp\n1  [810, 1239)  4  2.0   4   2.0\n2 [1239, 1668)  5  2.5   9   4.5\n3 [1668, 2097) 10  5.0  19   9.5\n4 [2097, 2526) 14  7.0  33  16.5\n5 [2526, 2954) 47 23.5  80  40.0\n6 [2954, 3383) 62 31.0 142  71.0\n7 [3383, 3812) 42 21.0 184  92.0\n8 [3812, 4241) 12  6.0 196  98.0\n9 [4241, 4670)  4  2.0 200 100.0\n```\n\n\n:::\n:::\n\n\nA saída retorna uma tabela de frequência completa, mostrando a distribuição dos pesos dos recém-nascidos por classes.\n\n::: callout-note\n## Nota\n\nA combinação de `mutate()`, `cut()`, `table()` e `prop.table()` é a abordagem padrão e mais robusta para criar tabelas de frequência com dados agrupados no R.\n:::\n\nMesmo que seja possível observar com clareza como os pesos dos recém-nascidos se distribuem, fica pouco intuitivo analisar, levando em conta as classificações recomendadas pela [Organização Mundial da Saúde](https://www.who.int/teams/maternal-newborn-child-adolescent-health-and-ageing/newborn-health/preterm-and-low-birth-weight) (OMS) e Ministério da Saúde do Brasil (MS), através do [Guia para os Profissionais de Saúde de Atenção à Saúde do Recém-Nascido](https://bvsms.saude.gov.br/bvs/publicacoes/atencao_saude_recem_nascido_profissionais_v1.pdf). Esta tabela de frequência serve mais para se observar o comportamento da variável `pesoRN`. Entretanto, essa ação é mais adequadamente realizada, utilizando-se um gráfico do tipo histograma (veja @sec-hist).\\\nA tabela construída será repetida ,usando para classificar, a função `case_when()` e a classificação dos recém-nascidos de acordo com a OMS.\n\n[**Passo a passo com a função case_when()**]{.underline}\n\nA função `cut()` foi já usada para classificar a variável `peso_rn`, entretanto, no início deste capítulo na @sec-dados-cap7 , para realizar esta ação, foi usada a função `case_when()` para agrupar a variável `idade_mae` e `imc` em classes. A principal diferença entre essas funções, é que cut`()` é especificamente projetada para agrupar dados em intervalos numéricos, enquanto `case_when()` é uma ferramenta mais generalista e poderosa do pacote `dplyr`, que permite criar classes com base em qualquer tipo de condição lógica. A função `case_when()` pode ser vantajosa por apresentar flexibilidade total, permitindo definir intervalos com bastante facilidade. Além disso para pessoas familiarizadas com a sintaxe do `tidyverse` (veja @sec-tidyverse), a estrutura `condição ~ valor` de `case_when()` é extremamente intuitiva e fácil de entender. Como faz parte do `tidyverse`, `case_when()` se encaixa perfeitamente em fluxos de trabalho que usam funções como `mutate()` e `group_by()`. Os dados dos pesos dos recém-nascidos (`peso_rn`) servirão como exemplo prático para criar uma tabela mais útil e comparação entre as duas funções.\n\n**Passo 1**: Criação da variável `classePeso`, usando o critério da OMS e das de frequência absoluta e relativa percentual:\n\n::: callout-note\n### Classificação dos recém-nascidos de acordo com o peso (OMS)\n\n**Extremo baixo peso ao nascer**: RNs com peso inferior a 1.000 gramas.\n\n**Muito baixo peso ao nascer**: RNs com peso inferior a 1.500 gramas.\n\n**Baixo peso ao nascer**: RNs com peso inferior a 2.500 gramas.\n\n**Adequado peso ao nascer**: RNs com peso entre 2500 e 4000 gramas.\n\n**Excesso de peso ao nascer**: RNs com peso ≥ 4000 gramas.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classificação dos RNs pelo critério da OMS -- classePeso\ndados <- dados |>  \n  mutate(classePeso = case_when(\n    peso_rn < 1000 ~ \"BP Extremo\",\n    peso_rn >= 1000 & peso_rn < 1500 ~ \"Muito BP\", \n    peso_rn >= 1500 & peso_rn < 2500 ~ \"Baixo Peso\",\n    peso_rn >= 2500 & peso_rn < 4000 ~ \"Peso Normal\",\n    peso_rn >= 4000 ~ \"Excesso de Peso\"\n  )) |> \n  mutate(classePeso = factor(classePeso, \n                             levels = c(\"BP Extremo\", \"Muito BP\", \"Baixo Peso\",\n                                        \"Peso Normal\", \"Excesso de Peso\")))  \n\n# Tabela de frequência absoluta\nf <- table(dados$classePeso)\nprint(f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     BP Extremo        Muito BP      Baixo Peso     Peso Normal Excesso de Peso \n              2               5              23             163               7 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Tabela de frequência relativa (em porcentagem)\nfrp <- round(prop.table(f) * 100, 1)\nprint(frp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     BP Extremo        Muito BP      Baixo Peso     Peso Normal Excesso de Peso \n            1.0             2.5            11.5            81.5             3.5 \n```\n\n\n:::\n:::\n\n\n**Passo 2**: Combinar as frequências em um dataframe\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_full <- data.frame(\n  f = as.vector(f),\n  frp = as.vector(frp))\n```\n:::\n\n\n**Passo 3**: Adicionar a frequência absoluta e a frequência relativa (em %) acumuladas\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Frequência Absoluta Acumulada\ntab_full$F <- cumsum(tab_full$f)\n\n# Frequência Relativa Acumulada (%)\ntab_full$Frp <- cumsum(tab_full$frp)\n```\n:::\n\n\n**Passo 4**: Adicionar os nomes das categorias como uma coluna\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_full$classePeso <- rownames (f)\n```\n:::\n\n\n**Passo 5**: Renomeie a coluna `classePeso` como \"Classificação\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\ntab_full <- tab_full |>\n  rename(\"Classificação\" = classePeso)\n```\n:::\n\n\n**Passo 6**: Reorganizar as colunas e exibir a tabela\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_full <- tab_full[c(\"Classificação\", \"f\", \"frp\", \"F\", \"Frp\")]\n\nprint(tab_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Classificação   f  frp   F   Frp\n1      BP Extremo   2  1.0   2   1.0\n2        Muito BP   5  2.5   7   3.5\n3      Baixo Peso  23 11.5  30  15.0\n4     Peso Normal 163 81.5 193  96.5\n5 Excesso de Peso   7  3.5 200 100.0\n```\n\n\n:::\n:::\n\n\nAssim, pode-se dizer que a prevalência de baixo peso na maternidade do Hospital Geral de Caxias do Sul é bem mais alta que a prevalência no Brasil que é de 6,1% (IC95%: 4,5-8,3%) [@viana2013birth].\n\n## Tabelas Prontas para Publicação\n\nO R possui várias alternativas para produzir tabelas científicas, bonitas e elegantes que possam ser publicadas. Neste livro, serão mostradas algumas dessas alternativas.\n\n### Pacote gt\n\nO pacote `gt` é um pacote que permite a apresentação de tabelas de maneira limpa e organizada [@iannone2020gt]. Funciona através do `tidyverse` com os comandos *pipe*, `|>` (nativo) ou `%>%` (necessita do `tidyverse`), o que facilita sua aplicação.\n\n#### Passos para criar uma tabela com o pacote gt\n\n**Passo 1**: Criar uma tabela base (dataframe ou tibble), como a tabela recém criada (`tab_full`) com os dados dos recém-nascidos. Verificar se os dados são realmente um dataframe ou tibble:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(tab_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data.frame\"\n```\n\n\n:::\n:::\n\n\nA seguir, transformar o dataframe em uma tabela `gt` com a função `gt()`:\n\n\n::: {#tbl-tabgt1 .cell tbl-cap='Tabela simples com o pacote gt'}\n\n```{.r .cell-code}\nlibrary(gt)\ntab_gt <- gt(data = tab_full)\ntab_gt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uguzitfrqe\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uguzitfrqe table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uguzitfrqe thead, #uguzitfrqe tbody, #uguzitfrqe tfoot, #uguzitfrqe tr, #uguzitfrqe td, #uguzitfrqe th {\n  border-style: none;\n}\n\n#uguzitfrqe p {\n  margin: 0;\n  padding: 0;\n}\n\n#uguzitfrqe .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uguzitfrqe .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uguzitfrqe .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uguzitfrqe .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uguzitfrqe .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uguzitfrqe .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uguzitfrqe .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uguzitfrqe .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uguzitfrqe .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uguzitfrqe .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uguzitfrqe .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uguzitfrqe .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uguzitfrqe .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uguzitfrqe .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uguzitfrqe .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uguzitfrqe .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uguzitfrqe .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uguzitfrqe .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uguzitfrqe .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uguzitfrqe .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uguzitfrqe .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uguzitfrqe .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uguzitfrqe .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uguzitfrqe .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uguzitfrqe .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uguzitfrqe .gt_left {\n  text-align: left;\n}\n\n#uguzitfrqe .gt_center {\n  text-align: center;\n}\n\n#uguzitfrqe .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uguzitfrqe .gt_font_normal {\n  font-weight: normal;\n}\n\n#uguzitfrqe .gt_font_bold {\n  font-weight: bold;\n}\n\n#uguzitfrqe .gt_font_italic {\n  font-style: italic;\n}\n\n#uguzitfrqe .gt_super {\n  font-size: 65%;\n}\n\n#uguzitfrqe .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uguzitfrqe .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uguzitfrqe .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uguzitfrqe .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uguzitfrqe .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uguzitfrqe .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uguzitfrqe .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uguzitfrqe .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uguzitfrqe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classificação\">Classificação</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"f\">f</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"frp\">frp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frp\">Frp</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">BP Extremo</td>\n<td headers=\"f\" class=\"gt_row gt_right\">2</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">1.0</td>\n<td headers=\"F\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">1.0</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Muito BP</td>\n<td headers=\"f\" class=\"gt_row gt_right\">5</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">2.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">3.5</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Baixo Peso</td>\n<td headers=\"f\" class=\"gt_row gt_right\">23</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">11.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">30</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">15.0</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Peso Normal</td>\n<td headers=\"f\" class=\"gt_row gt_right\">163</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">81.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">193</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">96.5</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Excesso de Peso</td>\n<td headers=\"f\" class=\"gt_row gt_right\">7</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">200</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">100.0</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nA @tbl-tabgt1 mostra duas partes, os rótulos das colunas e o corpo da tabela. Entretanto, o pacote `gt` permite de maneira fácil modificar ou acrescentar outras partes.\\\nAs partes que constituem a tabela `gt` são nomeadas de forma semelhante ao mostrado na @fig-tabela1: cabeçalho (*table header*), rótulo das linhas (*stub*), corpo (*body*) e rodapé (*footer*). Reconhecer essas partes é importante para a adição outras características da tabela.\n\n**Passo 2**: Personalizar o estilo (@tbl-tabgt2)\n\nA família de funções `tab_*()` permite adicionar outras partes. O título e subtítulo podem ser adicionados com a função `tab_header()`. Alterações de estilo são feitas pela função `tab_style()`. Essa função define a formatação a ser aplicada, que pode ser `cell_text()` para formatar texto e `locations =` que define quais células ou áreas da tabela devem receber o estilo. As opções incluem:\n\n• `cells_column_labels()`: Para os cabeçalhos das colunas.\\\n• `cells_title()`: Para o título da tabela.\\\n• `cells_stub()`: Para o cabeçalho da linha.\\\n• `cells_body()`: Para o corpo da tabela.\\\n• E outras funções específicas, como `cells_row_groups()`.\n\nPara maiores detalhes consulte [Create beautiful tables with gt](https://gt.rstudio.com/) ou [Introduction to Creating gt Tables](https://gt.rstudio.com/articles/gt.html).\n\n\n::: {#tbl-tabgt2 .cell tbl-cap='Tabela com o pacote gt personalizada'}\n\n```{.r .cell-code}\ntab_gt <- tab_gt |>\n  tab_header(\n    title = \"Classificação dos Pesos ao Nascer, de acordo com a OMS\",\n    subtitle = \"Hospital Geral de Caxias do Sul, 2008\") |>\n  tab_style(\n    style = cell_text(\n      weight = \"bold\",\n      size = \"medium\",\n      font = \"Arial\",\n      color = \"gray18\"),\n    locations = cells_title(groups = \"title\")) |>\n  tab_style(\n    style = cell_text(\n      weight = \"bold\"),\n    locations = cells_column_labels()) |> \n  tab_style(\n    style = cell_text(color = \"red\"),\n    locations = cells_body(\n      columns = Frp,\n      rows = near(Frp, 15))) |>\n    cols_width(\n      1 ~ px(150),\n      2:5 ~ px(80)\n    ) |> \n  tab_source_note(source_note = md(\"Fonte: Oliveira Filho, PF (2025)\")) |> \n  tab_footnote(\n    footnote = \"BP = Baixo Peso\",\n    locations = cells_body(columns = Classificação, rows = c(1,2))\n  )\n\ntab_gt\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ytcynabdja\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ytcynabdja table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ytcynabdja thead, #ytcynabdja tbody, #ytcynabdja tfoot, #ytcynabdja tr, #ytcynabdja td, #ytcynabdja th {\n  border-style: none;\n}\n\n#ytcynabdja p {\n  margin: 0;\n  padding: 0;\n}\n\n#ytcynabdja .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ytcynabdja .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ytcynabdja .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ytcynabdja .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ytcynabdja .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ytcynabdja .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ytcynabdja .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ytcynabdja .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ytcynabdja .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ytcynabdja .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ytcynabdja .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ytcynabdja .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ytcynabdja .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ytcynabdja .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ytcynabdja .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytcynabdja .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ytcynabdja .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ytcynabdja .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ytcynabdja .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytcynabdja .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ytcynabdja .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytcynabdja .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ytcynabdja .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytcynabdja .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ytcynabdja .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ytcynabdja .gt_left {\n  text-align: left;\n}\n\n#ytcynabdja .gt_center {\n  text-align: center;\n}\n\n#ytcynabdja .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ytcynabdja .gt_font_normal {\n  font-weight: normal;\n}\n\n#ytcynabdja .gt_font_bold {\n  font-weight: bold;\n}\n\n#ytcynabdja .gt_font_italic {\n  font-style: italic;\n}\n\n#ytcynabdja .gt_super {\n  font-size: 65%;\n}\n\n#ytcynabdja .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ytcynabdja .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ytcynabdja .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ytcynabdja .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ytcynabdja .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ytcynabdja .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ytcynabdja .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ytcynabdja .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ytcynabdja div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:80px;\"/>\n    <col style=\"width:80px;\"/>\n    <col style=\"width:80px;\"/>\n    <col style=\"width:80px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal\" style=\"color: #2E2E2E; font-family: Arial; font-size: medium; font-weight: bold;\">Classificação dos Pesos ao Nascer, de acordo com a OMS</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"5\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Hospital Geral de Caxias do Sul, 2008</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Classificação\">Classificação</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"f\">f</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"frp\">frp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"F\">F</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Frp\">Frp</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">BP Extremo<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></td>\n<td headers=\"f\" class=\"gt_row gt_right\">2</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">1.0</td>\n<td headers=\"F\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">1.0</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Muito BP<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></td>\n<td headers=\"f\" class=\"gt_row gt_right\">5</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">2.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">3.5</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Baixo Peso</td>\n<td headers=\"f\" class=\"gt_row gt_right\">23</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">11.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">30</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\" style=\"color: #FF0000;\">15.0</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Peso Normal</td>\n<td headers=\"f\" class=\"gt_row gt_right\">163</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">81.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">193</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">96.5</td></tr>\n    <tr><td headers=\"Classificação\" class=\"gt_row gt_left\">Excesso de Peso</td>\n<td headers=\"f\" class=\"gt_row gt_right\">7</td>\n<td headers=\"frp\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"F\" class=\"gt_row gt_right\">200</td>\n<td headers=\"Frp\" class=\"gt_row gt_right\">100.0</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> BP = Baixo Peso</td>\n    </tr>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"5\"><span data-qmd-base64=\"Rm9udGU6IE9saXZlaXJhIEZpbGhvLCBQRiAoMjAyNSk=\"><span class='gt_from_md'>Fonte: Oliveira Filho, PF (2025)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Passo 3**: Explicação do código\n\n1.  [Estrutura geral]{.underline}: inicialmente foi construída uma tabela `gt` com os dados da `tab_completa`. A partir daí foi encadeado, através do operador `pipe`, várias funções.\n\n2.  [Cabeçalho da tabela]{.underline}: a função `tab_header()` adiciona um título e subtítulo à tabela.\n\n    - Aplicado estilo ao título principal com a função `tab_style()` - negrito (`bold`), tamanho médio, fonte arial e cor cinza escura (`gray18`)\n\n3.  [Estilo dos rótulos das colunas]{.underline}: deixa os nomes das colunas em negrito, dando maior destaque.\n\n4.  [Destaque condicional no corpo da tabela]{.underline}: aplica cor vermelha à células da coluna `Frp` (frequência relativa acumulada em porcentagem) somente onde o valor está próximo de 15. Isto indica que 15% dos recém-nascidos têm peso ao nascer igual ou abaixo deste valor. A função `near()` é útil para destacar valores com tolerância numérica.\n\n5.  [Largura das colunas]{.underline}: define a largura das colunas, onde a primeira coluna tem 150 px e as demais (2 a 5) 80 px (pixels). Podem ser usadas duas unidades de medidas: pixels ou pct (percentual de largura da tabela). A conversão de pixels (px) para centímetros (cm) depende da resolução da tela medida em pixels por polegada (PPI). O padrão mais comum é 96 PPI.\n\n    $$cm = (px \\ \\times 2.54)/PPI$$\n\n    Com base em 96 PPI, $150 px \\approx 4$ cm.\n\n6.  Por último se incluiu a fonte e uma nota explicativa.\n\n### Pacote flextable\n\nO pacote `flextable` fornece uma estrutura para criar facilmente tabelas elegantes e personalizadas para relatórios e publicações [@gohel2025flextable].\n\nAs finalidades básicas do pacote `flextable` são:\n\n- Constrói tabelas a partir de **dataframes** ou **tibbles**.\n\n- Permite **formatar títulos, subtítulos, rodapés, cabeçalhos e corpo** da tabela.\n\n- Dá suporte a estilos avançados:\n\n  - cores de células e bordas;\n\n  - alinhamento (horizontal e vertical);\n\n  - negrito/itálico;\n\n  - largura das colunas e altura das linhas;\n\n  - mesclagem de células;\n\n  - numeração e percentuais formatados.\n\n- Gera tabelas que podem ser **dinâmicas** (em R Markdown, Quarto).\n\n#### Passos para criar uma tabela com o pacote flextable\n\n**Passo 1**: Da mesma forma como nas tabelas criadas pelo pacote `gt`, o `flextable` também necessita de tabela base (dataframe ou tibble) [@navarro2024flextable]. Será usada a mesma tabela (`tab_full`). Uma tabela simples (@tbl-ft1) pode ser facilmente gerada:\n\n\n::: {#tbl-ft1 .cell tbl-cap='Tabela simples com o pacote flextable'}\n\n```{.r .cell-code}\nlibrary(flextable)\nlibrary(dplyr)\n\nft <- flextable(data = tab_full)\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d5b5be82{}.cl-d5a4c348{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d5abf082{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5abf096{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5ac1ef4{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5ac1efe{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5ac1f08{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5ac1f09{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5ac1f12{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5ac1f1c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d5b5be82'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d5ac1ef4\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">Classificação</span></p></th><th class=\"cl-d5ac1efe\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">f</span></p></th><th class=\"cl-d5ac1efe\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">frp</span></p></th><th class=\"cl-d5ac1efe\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">F</span></p></th><th class=\"cl-d5ac1efe\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">Frp</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5ac1f08\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">BP Extremo</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">2</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">1.0</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">2</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5ac1f08\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">Muito BP</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">5</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">2.5</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">7</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5ac1f08\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">Baixo Peso</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">23</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">11.5</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">30</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5ac1f08\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">Peso Normal</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">163</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">81.5</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">193</span></p></td><td class=\"cl-d5ac1f09\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5ac1f12\"><p class=\"cl-d5abf082\"><span class=\"cl-d5a4c348\">Excesso de Peso</span></p></td><td class=\"cl-d5ac1f1c\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">7</span></p></td><td class=\"cl-d5ac1f1c\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">3.5</span></p></td><td class=\"cl-d5ac1f1c\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">200</span></p></td><td class=\"cl-d5ac1f1c\"><p class=\"cl-d5abf096\"><span class=\"cl-d5a4c348\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n**Passo 2**: As colunas podem ter sua largura ajustadas de forma manual, passando para o argumento `width()` um vetor com as larguras em polegadas.\n\n\n::: {#tbl-ft2 .cell tbl-cap='Ajuste das colunas'}\n\n```{.r .cell-code}\nft <- ft |> width(width = c(2, 1.5, 1.5, 1.5, 1.5))\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d5d51476{}.cl-d5c230a4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d5cba1ca{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5cba1de{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5cbf184{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5cbf198{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5cbf1a2{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5cbf1a3{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5cbf1ac{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5cbf1b6{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d5d51476'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d5cbf184\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">Classificação</span></p></th><th class=\"cl-d5cbf198\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">f</span></p></th><th class=\"cl-d5cbf198\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">frp</span></p></th><th class=\"cl-d5cbf198\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">F</span></p></th><th class=\"cl-d5cbf198\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">Frp</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5cbf1a2\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">BP Extremo</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">2</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">1.0</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">2</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5cbf1a2\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">Muito BP</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">5</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">2.5</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">7</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5cbf1a2\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">Baixo Peso</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">23</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">11.5</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">30</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5cbf1a2\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">Peso Normal</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">163</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">81.5</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">193</span></p></td><td class=\"cl-d5cbf1a3\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5cbf1ac\"><p class=\"cl-d5cba1ca\"><span class=\"cl-d5c230a4\">Excesso de Peso</span></p></td><td class=\"cl-d5cbf1b6\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">7</span></p></td><td class=\"cl-d5cbf1b6\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">3.5</span></p></td><td class=\"cl-d5cbf1b6\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">200</span></p></td><td class=\"cl-d5cbf1b6\"><p class=\"cl-d5cba1de\"><span class=\"cl-d5c230a4\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nO controle manual pode ser útil e fácil. A @tbl-ft2 melhorou o aspecto da @tbl-ft1, mas as colunas ficaram muito largas. O processo de tentativa e erro para encontrar as larguras ideais torna-se tedioso, irritante. Felizmente, o `flextable` permite que se ignore esse procedimento com a função `autofit()`, que tenta selecionar larguras de coluna adequadas automaticamente.\n\n\n::: {#tbl-ft3 .cell tbl-cap='Ajuste automático das colunas'}\n\n```{.r .cell-code}\nft <- ft |> autofit()\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d6043f4e{}.cl-d5f15082{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d5f8fe04{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5f8fe18{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d5f95cc8{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95cdc{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95ce6{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95cf0{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95cf1{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95cfa{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d04{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d0e{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d18{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d19{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d22{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d5f95d2c{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d6043f4e'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d5f95cc8\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">Classificação</span></p></th><th class=\"cl-d5f95cdc\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">f</span></p></th><th class=\"cl-d5f95ce6\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">frp</span></p></th><th class=\"cl-d5f95cdc\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">F</span></p></th><th class=\"cl-d5f95cf0\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">Frp</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5f95cf1\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">BP Extremo</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">2</span></p></td><td class=\"cl-d5f95d04\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">1.0</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">2</span></p></td><td class=\"cl-d5f95d0e\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5f95cf1\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">Muito BP</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">5</span></p></td><td class=\"cl-d5f95d04\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">2.5</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">7</span></p></td><td class=\"cl-d5f95d0e\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5f95cf1\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">Baixo Peso</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">23</span></p></td><td class=\"cl-d5f95d04\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">11.5</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">30</span></p></td><td class=\"cl-d5f95d0e\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5f95cf1\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">Peso Normal</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">163</span></p></td><td class=\"cl-d5f95d04\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">81.5</span></p></td><td class=\"cl-d5f95cfa\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">193</span></p></td><td class=\"cl-d5f95d0e\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d5f95d18\"><p class=\"cl-d5f8fe04\"><span class=\"cl-d5f15082\">Excesso de Peso</span></p></td><td class=\"cl-d5f95d19\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">7</span></p></td><td class=\"cl-d5f95d22\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">3.5</span></p></td><td class=\"cl-d5f95d19\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">200</span></p></td><td class=\"cl-d5f95d2c\"><p class=\"cl-d5f8fe18\"><span class=\"cl-d5f15082\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nAgora, a @tbl-ft3 já apresenta um layout bem mais bonito e , dependendo, do contexto, quase pronta para publicação.\n\n**Passo 3**: Ajuste do cabeçalho e rótulos das colunas. Dependendo da necessidade os rótulos do cabeçalho podem ser facilmente modificados com a função `set_header_labels ()`:\n\n\n::: {#tbl-ft4 .cell tbl-cap='Ajuste do cabeçalho'}\n\n```{.r .cell-code}\nft <- ft |> \n  autofit() |> \n  set_header_labels(\n    frp = \"fr (%)\",\n    Frp = \"Fr (%)\"\n  )\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d631b866{}.cl-d6234bdc{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d6290842{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d6290856{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d62935ce{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935d8{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935d9{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935e2{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935e3{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935ec{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935ed{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935f6{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d62935f7{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6293600{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d629360a{width:0.583in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d629360b{width:0.668in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d631b866'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d62935ce\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">Classificação</span></p></th><th class=\"cl-d62935d8\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">f</span></p></th><th class=\"cl-d62935d9\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">fr (%)</span></p></th><th class=\"cl-d62935d8\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">F</span></p></th><th class=\"cl-d62935e2\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">Fr (%)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d62935e3\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">BP Extremo</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">2</span></p></td><td class=\"cl-d62935ed\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">1.0</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">2</span></p></td><td class=\"cl-d62935f6\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d62935e3\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">Muito BP</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">5</span></p></td><td class=\"cl-d62935ed\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">2.5</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">7</span></p></td><td class=\"cl-d62935f6\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d62935e3\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">Baixo Peso</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">23</span></p></td><td class=\"cl-d62935ed\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">11.5</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">30</span></p></td><td class=\"cl-d62935f6\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d62935e3\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">Peso Normal</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">163</span></p></td><td class=\"cl-d62935ed\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">81.5</span></p></td><td class=\"cl-d62935ec\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">193</span></p></td><td class=\"cl-d62935f6\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d62935f7\"><p class=\"cl-d6290842\"><span class=\"cl-d6234bdc\">Excesso de Peso</span></p></td><td class=\"cl-d6293600\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">7</span></p></td><td class=\"cl-d629360a\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">3.5</span></p></td><td class=\"cl-d6293600\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">200</span></p></td><td class=\"cl-d629360b\"><p class=\"cl-d6290856\"><span class=\"cl-d6234bdc\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA @tbl-ft4 mudou pouca coisa, está mais ajustada.\n\n**Passo 4**: O `flextable` possui vários temas (`theme`) que possibilitam customizar o estilo da tabela. Esses temas oferecem diferentes aparências para as tabelas. É possível combinar esses temas com outros comandos de formatação, para criar um visual personalizado!\n\n\n::: {#tbl-ft5 .cell tbl-cap='Modificando o tema da tabela flextable'}\n\n```{.r .cell-code}\nft <- ft |> \n  autofit() |> \n  set_header_labels(\n    frp = \"fr (%)\",\n    Frp = \"Fr (%)\"\n  ) |> \n  theme_vanilla()\nft\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d6538978{}.cl-d647aa4a{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d647aa54{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d64e3856{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d64e386a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d64e5dc2{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5dcc{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5dd6{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5de0{width:0.709in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5de1{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5dea{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5deb{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5df4{width:0.709in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5df5{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5dfe{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5dff{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5e08{width:0.709in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5e09{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5e0a{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5e12{width:0.659in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d64e5e13{width:0.709in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d6538978'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d64e5dc2\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa4a\">Classificação</span></p></th><th class=\"cl-d64e5dcc\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa4a\">f</span></p></th><th class=\"cl-d64e5dd6\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa4a\">fr (%)</span></p></th><th class=\"cl-d64e5dcc\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa4a\">F</span></p></th><th class=\"cl-d64e5de0\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa4a\">Fr (%)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d64e5de1\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa54\">BP Extremo</span></p></td><td class=\"cl-d64e5dea\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">2</span></p></td><td class=\"cl-d64e5deb\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">1.0</span></p></td><td class=\"cl-d64e5dea\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">2</span></p></td><td class=\"cl-d64e5df4\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d64e5df5\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa54\">Muito BP</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">5</span></p></td><td class=\"cl-d64e5dff\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">2.5</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">7</span></p></td><td class=\"cl-d64e5e08\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d64e5df5\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa54\">Baixo Peso</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">23</span></p></td><td class=\"cl-d64e5dff\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">11.5</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">30</span></p></td><td class=\"cl-d64e5e08\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d64e5df5\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa54\">Peso Normal</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">163</span></p></td><td class=\"cl-d64e5dff\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">81.5</span></p></td><td class=\"cl-d64e5dfe\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">193</span></p></td><td class=\"cl-d64e5e08\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d64e5e09\"><p class=\"cl-d64e3856\"><span class=\"cl-d647aa54\">Excesso de Peso</span></p></td><td class=\"cl-d64e5e0a\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">7</span></p></td><td class=\"cl-d64e5e12\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">3.5</span></p></td><td class=\"cl-d64e5e0a\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">200</span></p></td><td class=\"cl-d64e5e13\"><p class=\"cl-d64e386a\"><span class=\"cl-d647aa54\">100.0</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA @tbl-ft5 já está ótima, mas outros temas podem ser usados como `theme_booktabs()` (padrão), `theme_vader()`, `theme_apa()`, `theme_zebra()`, `theme_box()`, `theme_tron_legacy ()`.\n\n::: callout-tip\n## Exercício\n\nTeste a aparência da tabela com diferentes temas.\n:::\n\n**Passo 5**: Uma nota de rodapé pode ser adicionada, usando-se uma função específica, a`dd_footer_lines()` junto com as funções que determinam o tamanho da fonte:\n\n\n::: {#tbl-ft6 .cell tbl-cap='Tabela com nota de rodapé'}\n\n```{.r .cell-code}\nft1 <- ft |> \n  autofit() |> \n  set_header_labels(\n    frp = \"fr (%)\",\n    Frp = \"Fr (%)\"\n  ) |>  \n  theme_vanilla() |> \n  add_footer_lines(value = \"FONTE: Hospital Geral, Caxias do Sul, RS, 2008\") |> \n  fontsize(size = 9, part = \"footer\") \n\nft1\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d672bd16{}.cl-d668e9b2{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d668e9bc{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d668e9c6{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d66c610a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d66c6114{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d66c8b8a{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8b94{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8b9e{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8b9f{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8ba0{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8ba8{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8ba9{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8baa{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bb2{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bb3{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bb4{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bbc{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bbd{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bbe{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bc6{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bc7{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bd0{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bd1{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bd2{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d66c8bda{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d672bd16'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d66c8b8a\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9b2\">Classificação</span></p></th><th class=\"cl-d66c8b94\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9b2\">f</span></p></th><th class=\"cl-d66c8b9e\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9b2\">fr (%)</span></p></th><th class=\"cl-d66c8b94\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9b2\">F</span></p></th><th class=\"cl-d66c8b9f\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9b2\">Fr (%)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d66c8ba0\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9bc\">BP Extremo</span></p></td><td class=\"cl-d66c8ba8\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">2</span></p></td><td class=\"cl-d66c8ba9\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">1.0</span></p></td><td class=\"cl-d66c8ba8\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">2</span></p></td><td class=\"cl-d66c8baa\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d66c8bb2\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9bc\">Muito BP</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">5</span></p></td><td class=\"cl-d66c8bb4\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">2.5</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">7</span></p></td><td class=\"cl-d66c8bbc\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d66c8bb2\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9bc\">Baixo Peso</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">23</span></p></td><td class=\"cl-d66c8bb4\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">11.5</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">30</span></p></td><td class=\"cl-d66c8bbc\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d66c8bb2\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9bc\">Peso Normal</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">163</span></p></td><td class=\"cl-d66c8bb4\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">81.5</span></p></td><td class=\"cl-d66c8bb3\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">193</span></p></td><td class=\"cl-d66c8bbc\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d66c8bbd\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9bc\">Excesso de Peso</span></p></td><td class=\"cl-d66c8bbe\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">7</span></p></td><td class=\"cl-d66c8bc6\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">3.5</span></p></td><td class=\"cl-d66c8bbe\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">200</span></p></td><td class=\"cl-d66c8bc7\"><p class=\"cl-d66c6114\"><span class=\"cl-d668e9bc\">100.0</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-d66c8bd0\"><p class=\"cl-d66c610a\"><span class=\"cl-d668e9c6\">FONTE: Hospital Geral, Caxias do Sul, RS, 2008</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nA @tbl-ft6 é igual a @tbl-ft5 adicionada de um rodapé.\n\n**Passo 6**: Muitas vezes, é útil definir regras de formatação que se aplicam apenas a um subconjunto da tabela. Por exemplo, algumas linhas ou colunas devam aparecer em uma cor diferente por um motivo ou outro. Todas as tabelas flexíveis são compostas por três partes: cabeçalho (**header**) na parte superior, uma grade de células no corpo (**body**) da tabela e um conjunto de linhas de rodapé (**footer**) na parte inferior. Muitas funções na tabela flexível têm um argumento que se pode usar para selecionar uma (ou todas) essas três partes. Por exemplo, a função `bg()` é usada para definir a cor de fundo. Pode-se adicionar um conteúdo extra ao cabeçalho, `add_header_lines()` e colorir o fundo:\n\n\n::: {#tbl-ft7 .cell tbl-cap='Tabela com nota de rodapé'}\n\n```{.r .cell-code}\nft2 <- ft |> \n  autofit() |> \n  set_header_labels(\n    frp = \"fr (%)\",\n    Frp = \"Fr (%)\"\n  ) |>  \n  theme_booktabs() |> \n  add_footer_lines(value = \"FONTE: Hospital Geral, Caxias do Sul, RS, 2008\") |> \n  fontsize(size = 9, part = \"footer\") |> \n  add_header_lines(\"TABELA 1: Pesos dos RN de acordo com a OMS\") |> \n  bg(bg = \"gray30\", part =\"header\") |> \n  color(part = \"header\", color = \"ghostwhite\")\n\nft2\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d6975d10{}.cl-d68b1460{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(248, 248, 255, 1.00);background-color:transparent;}.cl-d68b146a{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d68b146b{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d68f802c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d68f8036{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d68fa96c{width:1.466in;background-color:rgba(77, 77, 77, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa976{width:0.54in;background-color:rgba(77, 77, 77, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa980{width:0.676in;background-color:rgba(77, 77, 77, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa98a{width:0.718in;background-color:rgba(77, 77, 77, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa994{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa995{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa996{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa99e{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9a8{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9a9{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9b2{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9bc{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9c6{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9c7{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9c8{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9c9{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9d0{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9d1{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9d2{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d68fa9d3{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d6975d10'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"5\"class=\"cl-d68fa96c\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b1460\">TABELA 1: Pesos dos RN de acordo com a OMS</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d68fa96c\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b1460\">Classificação</span></p></th><th class=\"cl-d68fa976\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b1460\">f</span></p></th><th class=\"cl-d68fa980\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b1460\">fr (%)</span></p></th><th class=\"cl-d68fa976\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b1460\">F</span></p></th><th class=\"cl-d68fa98a\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b1460\">Fr (%)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d68fa994\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146a\">BP Extremo</span></p></td><td class=\"cl-d68fa995\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">2</span></p></td><td class=\"cl-d68fa996\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">1.0</span></p></td><td class=\"cl-d68fa995\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">2</span></p></td><td class=\"cl-d68fa99e\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d68fa9a8\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146a\">Muito BP</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">5</span></p></td><td class=\"cl-d68fa9b2\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">2.5</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">7</span></p></td><td class=\"cl-d68fa9bc\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d68fa9a8\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146a\">Baixo Peso</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">23</span></p></td><td class=\"cl-d68fa9b2\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">11.5</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">30</span></p></td><td class=\"cl-d68fa9bc\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d68fa9a8\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146a\">Peso Normal</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">163</span></p></td><td class=\"cl-d68fa9b2\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">81.5</span></p></td><td class=\"cl-d68fa9a9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">193</span></p></td><td class=\"cl-d68fa9bc\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d68fa9c6\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146a\">Excesso de Peso</span></p></td><td class=\"cl-d68fa9c7\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">7</span></p></td><td class=\"cl-d68fa9c8\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">3.5</span></p></td><td class=\"cl-d68fa9c7\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">200</span></p></td><td class=\"cl-d68fa9c9\"><p class=\"cl-d68f8036\"><span class=\"cl-d68b146a\">100.0</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-d68fa9d0\"><p class=\"cl-d68f802c\"><span class=\"cl-d68b146b\">FONTE: Hospital Geral, Caxias do Sul, RS, 2008</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nA @tbl-ft7 mostra um título com fundo escuro e letras brancas.\n\n**Passo 7**: Se for especificado uma seleção de linha e uma seleção de coluna, a regra de formatação será aplicada às células que satisfizerem ambos os critérios. Por exemplo, será selecionada a coluna 5 (frequência relativa acumulada ) e as linhas 1 a 3 coloridas em um gradiente de azul para representar todos os recém-nascidos abaixo de 2500 g (baixo peso).\n\nAntes cria-se uma função geradora de cores numéricas, criada com a função `col_numeric()` do pacote `scales` que cria um mapeamento de cores para valores numéricos. A paleta define um gradiente de cores que vai do transparente para o azul. O intervalo de valores é definido pelo argumento `domain = c(0,50)`. Isto significa que qualquer número é convertido em uma cor proporcional dentro do gradiente. Os valores mais baixos serão transparentes (próximo a 0) e os valores mais altos (próximos a 50) serão azuis (@tbl-ft8).\n\n\n::: {#tbl-ft8 .cell tbl-cap='Tabela com seleção especial de células'}\n\n```{.r .cell-code}\nlibrary(scales)\ncores <- scales::col_numeric(\n  palette = c(\"transparent\", \"deepskyblue4\"),\n  domain = c(0, 50))\n\nft3<- ft |> \n  autofit() |> \n  set_header_labels(\n    frp = \"fr (%)\",\n    Frp = \"Fr (%)\"\n  ) |>  \n  theme_booktabs() |> \n  add_footer_lines(value = \"FONTE: Hospital Geral, Caxias do Sul, RS, 2008\") |> \n  fontsize(size = 9, part = \"footer\") |> \n  add_header_lines(\"TABELA 1: Pesos dos RN de acordo com a OMS\") |> \n  bg(i = 1:3, j = 5, bg = cores)\n\nft3\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-d6ca7a9c{}.cl-d6c00f9e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d6c00fa8{font-family:'Arial';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-d6c4595a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d6c4596e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-d6c482f4{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c482fe{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48308{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48309{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48312{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48313{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4831c{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48326{width:0.718in;background-color:rgba(251, 252, 253, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48327{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48330{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4833a{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4833b{width:0.718in;background-color:rgba(240, 244, 247, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4833c{width:0.718in;background-color:rgba(189, 207, 219, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48344{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48345{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4834e{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48358{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48359{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4835a{width:1.466in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48362{width:0.54in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c48363{width:0.676in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-d6c4836c{width:0.718in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-d6ca7a9c'><thead><tr style=\"overflow-wrap:break-word;\"><th  colspan=\"5\"class=\"cl-d6c482f4\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">TABELA 1: Pesos dos RN de acordo com a OMS</span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-d6c482f4\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">Classificação</span></p></th><th class=\"cl-d6c482fe\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">f</span></p></th><th class=\"cl-d6c48308\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">fr (%)</span></p></th><th class=\"cl-d6c482fe\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">F</span></p></th><th class=\"cl-d6c48309\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">Fr (%)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d6c48312\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">BP Extremo</span></p></td><td class=\"cl-d6c48313\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">2</span></p></td><td class=\"cl-d6c4831c\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">1.0</span></p></td><td class=\"cl-d6c48313\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">2</span></p></td><td class=\"cl-d6c48326\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">1.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d6c48327\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">Muito BP</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">5</span></p></td><td class=\"cl-d6c4833a\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">2.5</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">7</span></p></td><td class=\"cl-d6c4833b\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">3.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d6c48327\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">Baixo Peso</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">23</span></p></td><td class=\"cl-d6c4833a\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">11.5</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">30</span></p></td><td class=\"cl-d6c4833c\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">15.0</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d6c48327\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">Peso Normal</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">163</span></p></td><td class=\"cl-d6c4833a\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">81.5</span></p></td><td class=\"cl-d6c48330\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">193</span></p></td><td class=\"cl-d6c48344\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">96.5</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-d6c48345\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00f9e\">Excesso de Peso</span></p></td><td class=\"cl-d6c4834e\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">7</span></p></td><td class=\"cl-d6c48358\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">3.5</span></p></td><td class=\"cl-d6c4834e\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">200</span></p></td><td class=\"cl-d6c48359\"><p class=\"cl-d6c4596e\"><span class=\"cl-d6c00f9e\">100.0</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"5\"class=\"cl-d6c4835a\"><p class=\"cl-d6c4595a\"><span class=\"cl-d6c00fa8\">FONTE: Hospital Geral, Caxias do Sul, RS, 2008</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nMuitas outras funções existem para alterar o layout, dependendo do que o pesquisador deseja mostrar. Para isso, o `flextable` tem funções para altera as bordas, as fontes, formato, cores, alinhamento, etc. que podem ser pesquisadas na [documentação](https://cran.r-project.org/web/packages/flextable/flextable.pdf) do pacote.\n\n### Pacote gtsummary {#sec-gtsummary}\n\nO pacote `gtsummary` foi criado [@daniel2021gtsummary] como complemento do pacote `gt`. Para usar o pacote , ele deve estar instalado e carregado:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\n```\n:::\n\n\nO pacote `gtsummary` possui uma função `tbl_summary()` que permite sumarizar um dataframe.\\\nEla calcula e apresenta automaticamente estatísticas resumidas para variáveis contínuas, categóricas e dicotômicas dentro de uma estrutura de dados, formatadas para tabelas prontas para publicação. Detecta automaticamente os tipos de variáveis e aplica estatísticas resumidas padrão apropriadas (por exemplo, mediana e intervalo interquartil, média e desvio padrão para variáveis contínuas, contagens e porcentagens para variáveis categóricas).\\\nPara maiores detalhes consulte a [vinheta](https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html) da função.\n\n#### Dados para o exemplo\n\nComo exemplo, será usado um dataframe originário do conjunto de dados `dadosMater.xlsx` (veja @sec-dados-cap7), contento uma amostra de 200 observações com as seguintes variáveis relacionadas aos recém-nascidos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(readxl)\n\nset.seed(1234)\ndados <- readxl::read_excel(\"dados/dadosMater.xlsx\") |> \n  filter(ig >= 37 & ig < 42) |> \n  mutate(\n    baixo_peso = case_when(\n      peso_rn < 2500 ~ \"Sim\",\n      peso_rn >= 2500 ~ \"Não\"),\n    baixo_peso = as.factor(baixo_peso),\n    estado_civil = factor(estado_civil, \n                          levels = c(1,2), \n                          labels = c(\"Sem companheiro\", \"Com companheiro\")),\n    tipo_parto = factor(tipo_parto, \n                        levels = c(1,2), \n                        labels = c(\"Normal\", \"Cesareo\")),\n    fumo = factor(fumo, \n                  levels = c(1,2), \n                  labels = c(\"Fumante\", \"Não fumante\")),\n    uti_neo = factor(uti_neo, \n                     levels = c(1,2), \n                     labels = c(\"Sim\", \"Não\")),\n    categIdade = case_when(\n      idade_mae < 20 ~ \"< 20 anos\",\n      idade_mae >= 20 & idade_mae <= 35 ~ \"20 a 35 anos\",\n      idade_mae > 35 ~ \"> 35 anos\"),\n    categIdade = factor(categIdade, \n                        levels = c(\"< 20 anos\", \"20 a 35 anos\", \"> 35 anos\")),\n    sexo = factor(sexo, \n                  levels = c(1,2), \n                  labels = c(\"Masculino\", \"Feminino\"))\n  ) |> \n  dplyr::select(baixo_peso, categIdade, estado_civil, anos_est, renda, fumo, tipo_parto, sexo, apgar1, uti_neo) |> \n  slice_sample(n=200)\n```\n:::\n\n\n#### Construção da tabela\n\n\n::: {#tbl-baixopeso .cell tbl-cap='Análise bivariada de fatores de risco para baixo peso ao nascer (< 2500g).'}\n\n```{.r .cell-code}\nlibrary(forcats)\n\ndados$baixo_peso <- fct_rev(dados$baixo_peso)\n\ntbl_summary(dados, \n            by = baixo_peso,\n            missing = \"ifany\",\n            type = list(renda ~ \"continuous2\"),\n            label = list(categIdade ~ \"Faixa Etária\",\n                         estado_civil ~ \"Estado Civil\",\n                         anos_est ~\"Anos de estudo completos\",\n                         renda ~ \"Renda Familiar (SM)\",\n                         fumo ~ \"Tabagismo\",\n                         tipo_parto ~\"Tipo de Parto\",\n                         sexo ~\"Sexo\",\n                         apgar1 ~ \"Apgar primeiro min\",\n                         uti_neo ~\"Encaminhado à UTINeo\")) |> \n  add_n() |> \n  add_p(test = all_continuous() ~ \"t.test\",\n        pvalue_fun = ~style_pvalue(., digits = 2)) |> \n  modify_header(label = \"**Variáveis**\") |> \n  modify_spanning_header(c(stat_1, stat_2) ~ \"**Baixo Peso ao Nascer**\") |>\n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xahhvjetlj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xahhvjetlj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xahhvjetlj thead, #xahhvjetlj tbody, #xahhvjetlj tfoot, #xahhvjetlj tr, #xahhvjetlj td, #xahhvjetlj th {\n  border-style: none;\n}\n\n#xahhvjetlj p {\n  margin: 0;\n  padding: 0;\n}\n\n#xahhvjetlj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xahhvjetlj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xahhvjetlj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xahhvjetlj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xahhvjetlj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xahhvjetlj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xahhvjetlj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xahhvjetlj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xahhvjetlj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xahhvjetlj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xahhvjetlj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xahhvjetlj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xahhvjetlj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xahhvjetlj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xahhvjetlj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xahhvjetlj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xahhvjetlj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xahhvjetlj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xahhvjetlj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xahhvjetlj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xahhvjetlj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xahhvjetlj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xahhvjetlj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xahhvjetlj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xahhvjetlj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xahhvjetlj .gt_left {\n  text-align: left;\n}\n\n#xahhvjetlj .gt_center {\n  text-align: center;\n}\n\n#xahhvjetlj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xahhvjetlj .gt_font_normal {\n  font-weight: normal;\n}\n\n#xahhvjetlj .gt_font_bold {\n  font-weight: bold;\n}\n\n#xahhvjetlj .gt_font_italic {\n  font-style: italic;\n}\n\n#xahhvjetlj .gt_super {\n  font-size: 65%;\n}\n\n#xahhvjetlj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xahhvjetlj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xahhvjetlj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xahhvjetlj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xahhvjetlj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xahhvjetlj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xahhvjetlj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xahhvjetlj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xahhvjetlj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipWYXJpw6F2ZWlzKio=\"><span class='gt_from_md'><strong>Variáveis</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"n\"><span data-qmd-base64=\"KipOKio=\"><span class='gt_from_md'><strong>N</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"level 1; stat_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipCYWl4byBQZXNvIGFvIE5hc2Nlcioq\"><span class='gt_from_md'><strong>Baixo Peso ao Nascer</strong></span></span></div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipTaW0qKiAgCk4gPSAxMg==\"><span class='gt_from_md'><strong>Sim</strong><br />\nN = 12</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipOw6NvKiogIApOID0gMTg4\"><span class='gt_from_md'><strong>Não</strong><br />\nN = 188</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Faixa Etária</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.49</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    &lt; 20 anos</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3 (25%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">32 (17%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    20 a 35 anos</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">9 (75%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">134 (71%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    &gt; 35 anos</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0 (0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (12%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Estado Civil</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.51</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Sem companheiro</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48 (26%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Com companheiro</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">140 (74%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Anos de estudo completos</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5.50 (4.00, 7.00)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8.00 (6.00, 10.00)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.047</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Renda Familiar (SM)</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Median (Q1, Q3)</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1.57 (1.24, 1.92)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">1.93 (1.45, 2.41)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Tabagismo</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.24</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Fumante</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">33 (18%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Não fumante</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">155 (82%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Tipo de Parto</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">>0.99</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Normal</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">128 (68%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Cesareo</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">60 (32%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sexo</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.58</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Masculino</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">7 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (50%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Feminino</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5 (42%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (50%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Apgar primeiro min</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8.00 (8.00, 9.00)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">8.00 (8.00, 9.00)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.90</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Encaminhado à UTINeo</td>\n<td headers=\"n\" class=\"gt_row gt_center\">200</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.026</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Sim</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4 (33%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17 (9.0%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Não</td>\n<td headers=\"n\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">8 (67%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">171 (91%)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk7IE1lZGlhbiAoUTEsIFEzKQ==\"><span class='gt_from_md'>n (%); Median (Q1, Q3)</span></span></td>\n    </tr>\n    <tr class=\"gt_footnotes\">\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"RmlzaGVyJ3MgZXhhY3QgdGVzdDsgV2VsY2ggVHdvIFNhbXBsZSB0LXRlc3Q7IFBlYXJzb24ncyBDaGktc3F1YXJlZCB0ZXN0\"><span class='gt_from_md'>Fisher’s exact test; Welch Two Sample t-test; Pearson’s Chi-squared test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nA @tbl-baixopeso mostra como construir uma tabela de comparação binária. O objetivo não é fazer um estudo sobre causas de baixo peso ao nascer, mas apenas mostrar os recurso de construção com este excelente pacote.\n",
    "supporting": [
      "07-tabelas_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}