{
  "hash": "ebf6354511acab8eaea228de4172c62e",
  "result": {
    "engine": "knitr",
    "markdown": "# Distribuições Amostrais {#sec-cap11}\n\n## Pacotes necessários para este capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(e1071, \n               knitr, \n               readxl,\n               tidyverse)\n```\n:::\n\n\n## Dados para este capítulo\n\nOs dados deste capítulo são provenientes do conjunto de dados `dadosMater.xlsx` (@sec-dadosMater), considerando apenas as variáveis `altura`, `renda` e `fumo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"dados/dadosMater.xlsx\") |> \n  dplyr::select(altura, renda, fumo) |> \n  mutate(fumo = factor(fumo, \n                       levels = c(1,2), \n                       labels = c(\"Fumante\", \"Não fumante\")))\n```\n:::\n\n\n## Distribuições populacional e amostral\n\nMétricas como a média, a mediana e o desvio padrão são medidas numéricas de resumo. Quando calculadas a partir de dados de uma amostra são denominadas **estatísticas amostrais**. Por outro lado, as mesmas medidas numéricas de resumo calculadas para dados populacionais são chamadas de **parâmetros populacionais** [@oliveira2022estparam].\n\nUm parâmetro populacional é sempre uma constante, enquanto uma estatística de amostra é sempre uma variável aleatória. Como cada variável aleatória deve possuir uma distribuição de probabilidade, cada estatística de amostra possui uma distribuição de probabilidade. A distribuição de probabilidade de uma estatística de amostra é mais comumente chamada de **distribuição amostral**. Os conceitos abordados neste capítulo são a base da **estatística inferencial** [@zar2014popsamples].\n\n### Distribuição populacional\n\nA distribuição populacional é a distribuição de probabilidade derivada das informações sobre todos os elementos de uma **população**.\n\nPara fins de raciocínio didático, o conjunto de dados das 1368 observações de puérperas e recém-nascidos da Maternidade-escola do Hospital Geral de Caxias do Sul, RS, será considerado uma população. O gráfico da @fig-histbxp, da @sec-assimetria, mostra a distribuição da `altura` das puérperas dessa ‘população’. Os parâmetros ($\\mu$ e $\\sigma$) dessa \"*população*\" são:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n media = mean(dados$altura, na.rm = TRUE)\n round(media, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.598\n```\n\n\n:::\n\n```{.r .cell-code}\n dp = sd(dados$altura, na.rm = TRUE)\n round(dp, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.065\n```\n\n\n:::\n:::\n\n\n### Distribuição amostral {#sec-dam}\n\nConforme mencionado no início deste capítulo, o valor de um parâmetro da população é sempre constante. Por exemplo, para qualquer conjunto de dados populacionais, há apenas um valor para a média populacional, $\\mu$.\n\nNo entanto, não se pode dizer o mesmo sobre a média amostral. Amostras diferentes do mesmo tamanho, retiradas da mesma população, produzem valores diferentes da média amostral, $\\bar{x}$. O valor da média amostral, para qualquer amostra, dependerá dos elementos incluídos nessa amostra. Em decorrência, a média amostral é uma variável aleatória. Portanto, como outras variáveis aleatórias, a média amostral possui uma distribuição de probabilidade, que é mais comumente chamada de **distribuição amostral da média** [@callegari2003dam].\n\nOutras estatísticas de amostra, como mediana, moda e desvio padrão, também possuem distribuições amostrais. Em geral, a distribuição de probabilidades de uma amostra é denominada de **distribuição amostral**.\n\nUsar a variável `altura` das puérperas da Maternidade do HGCS como a população de interesse é apenas uma estratégia didática. Raramente, na vida real, é possível obter dados da população inteira. Reunir essa informação costuma ser muito custoso ou impossível. Por essa razão, a prática é selecionar apenas uma amostra da população e a usar para compreender as suas características.\n\nA função `slice_sample()` do pacote `dplyr`extrairá uma amostra [^11-distamostrais-1] de n = 30 da população. As funções `mean()` e `sd()` calcularão a média e o desvio padrão, respectivamente:\n\n[^11-distamostrais-1]: Para que a cada nova amostragem retorne o mesmo conjunto de dados, é usado a função `set.seed()`(veja @sec-rnorm)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(234)\namostra1 <- dados |> \n  dplyr::slice_sample(n = 30)\n\nmedia1 <- mean(amostra1$altura, na.rm =TRUE)\ndp1 <-  sd(amostra1$altura, na.rm =TRUE)\nprint(c(media1, dp1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.59266667 0.06073875\n```\n\n\n:::\n:::\n\n\nSe este processo for repetido várias vezes, a cada amostra aleatória [^11-distamostrais-2], serão gerados médias e desvios padrão diferentes.\n\n[^11-distamostrais-2]: Observe que o número da \"semente\" foi modificado para 236. Poderia ser qualquer outro número, isto garante que o sorteio seja diferente, mas ainda reprodutível.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(236)\namostra2 <- dados |> \n  dplyr::slice_sample(n = 30)\n\nmedia2 <- mean(amostra2$altura, na.rm =TRUE)\ndp2 <-  sd(amostra2$altura, na.rm =TRUE)\nprint(c(media2, dp2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.60633333 0.06960397\n```\n\n\n:::\n:::\n\n\nÀ medida que o número de amostras possíveis forem aumentando, elas constituem uma distribuição cuja média, média das médias, $\\bar{x}_{\\bar{x}}$, é igual a média populacional, $\\mu$. Essa distribuição, no caso da média, recebe o nome de **distribuição amostral das médias**.\n\nAgora, para exemplificar este conceito, serão geradas 5000 amostras e calculada a média de cada uma das amostras de n = 30 que constituirão a distribuição, mostrada no gráfico da @fig-dam.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# extraindo 5000 amostras\namostras5000 <- rep (0, 5000)\nfor (i in 1:5000) {\n  amostra <- dados |> dplyr::slice_sample (n = 30) \n  amostras5000 [i] <- mean(amostra$altura)\n}\n```\n:::\n\n\nMédia e desvio padrão das 5000 amostras:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- round (mean (amostras5000), digits = 3)\nsigma <- round (sd (amostras5000), digits = 3)\nprint(c(mu, sigma))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.598 0.012\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição amostral das médias de 5000 amostras de n = 30](11-distAmostrais_files/figure-html/fig-dam-1.png){#fig-dam fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nSe a média, $\\bar{x}_{\\bar{x}}$, dessas 5000 amostras de n = 30, for comparada com a média populacional, $\\mu$, observa-se que até 3 dígitos decimais não há uma diferença. Entretanto, o desvio padrão é bem menor (0.012) que o da população (0.065).\n\n## Erros amostrais e não amostrais\n\nAmostras diferentes selecionadas da mesma população darão resultados diferentes porque contêm elementos diferentes. Isso é evidente nas médias das amostra1 e amostra2, 1.593m e 1.606m, respectivamente, comparadas com a média da população igual a 1.598m .\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerro1 <- abs(mean(amostra1$altura, na.rm =TRUE) - mean(dados$altura, na.rm =TRUE))\nerro2 <- abs(mean(amostra2$altura, na.rm =TRUE) - mean(dados$altura, na.rm =TRUE))\nprint(c(erro1, erro2), digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0053 0.0084\n```\n\n\n:::\n:::\n\n\nSe outras amostras forem extraídas, o resultado obtido de qualquer amostra geralmente será diferente do resultado obtido da população correspondente. A diferença entre o valor de uma estatística amostral obtida de uma amostra e o valor do parâmetro populacional correspondente, é chamado de **erro amostral**. Observe que essa diferença representa o erro amostral apenas se a amostra for aleatória e não houver nenhum erro não amostral. Caso contrário, apenas uma parte dessa diferença será devido ao erro amostral.\n\n$$ erro \\quad amostral = \\bar{x}_{i} - \\mu  $$\n\nÉ importante lembrar que o erro amostral ocorre devido ao acaso. Não é possível evitar o erro amostral. É possível limitar o seu valor através da seleção de uma amostra adequada. Os erros que ocorrem por outros motivos, como erros cometidos durante a coleta, registro e tabulação dos dados, são chamados de **erros não amostrais**. Esses erros ocorrem, em geral, por causa de erros humanos e não por acaso.\n\n## Média e desvio padrão da média\n\nA média e o desvio padrão calculados para a distribuição amostral da média são chamados de *média (*$\\mu_{\\bar{x}}$) e *desvio padrão (*$\\sigma_{\\bar{x}}$) da média. Na verdade, a média e o desvio padrão da média são, respectivamente, a média e o desvio padrão das médias de todas as amostras do mesmo tamanho selecionadas de uma população. O desvio padrão da média é, comumente, chamado de **erro padrão da média** ($\\sigma_{\\bar{x}}$).\n\nA média amostral, $\\bar{x}$, é chamada de *estimador* da média da população, $\\mu$. Quando o valor esperado (ou média) de uma estatística amostral é igual ao valor do parâmetro populacional correspondente, essa estatística amostral é considerada um estimador não enviesado, consistente.\\\nPara a média amostral $\\bar{x}$, $\\mu_{\\bar{x}} = \\mu$. Logo, $\\bar{x}$, é um estimador imparcial de $\\mu$. Esta é uma propriedade muito importante que um estimador deve possuir. No entanto, o desvio padrão da média, $\\sigma_{\\bar{x}}$, não é igual ao desvio padrão, $\\sigma$, da distribuição populacional (a menos que n = 1). O desvio padrão da média amostral é igual ao desvio padrão da população dividido pela raiz quadrada do tamanho amostral:\n\n$$\\sigma_{\\bar{x}} = \\frac {\\sigma}{\\sqrt{n}}$$\n\nA dispersão da distribuição amostral da média é menor do que dispersão da distribuição populacional correspondente, como mostrado acima. Em outras palavras, $\\sigma_{\\bar{x}} < \\sigma$. Isso é visível na fórmula do $\\sigma_{\\bar{x}}$ . Quando *n* é maior que 1, o que geralmente é verdadeiro, o denominador em $\\frac {\\sigma}{\\sqrt{n}}$ é maior que 1. Desta forma, $\\sigma_{\\bar{x}}$ é menor que $\\sigma$. O desvio padrão da distribuição amostral da média diminui à medida que o tamanho amostral aumenta.\n\nSempre que o *n* for grande, em geral \\> 30 [@pagano2000sampling], pode ser assumido que a distribuição será uma curva normal e que o desvio padrão da amostra (*s*) é um estimador não enviesado do desvio padrão populacional ($\\sigma$). Então, o erro padrão da média ($\\sigma_{\\bar{x}}$) pode ser estimado pelo $EP_{\\bar{x}}$:\n\n$$EP_{\\bar{x}} = \\frac {s}{\\sqrt{n}}$$\n\n## Teorema Central do Limite (TCL) {#sec-tcl}\n\nNa maioria das vezes, a população da qual as amostras são extraídas não é normalmente distribuída. Em tais casos, a forma da distribuição amostral de X é inferida de um teorema muito importante chamado *teorema central do limite* . De acordo com este teorema para um grande tamanho de amostra (em geral, acima de 30), a distribuição amostral da média é aproximadamente normal, independentemente da forma da distribuição da população [@pagano2000sampling]. Esta aproximação tornar-se-á mais acurada à medida que aumenta o tamanho amostral:\n\n- a média da distribuição amostral, $\\mu_{\\bar{x}}$, é igual a média populacional, $\\mu$;\n- desvio padrão da distribuição amostral, $\\sigma_{\\bar{x}}$, é igual a $\\frac {\\sigma}{\\sqrt{n}}$;\n- o erro padrão da média, $\\sigma_{\\bar{x}}$, é sempre menor (@fig-standard) que o desvio padrão populacional, $\\sigma$.\n\n![Erro Padrão versus Desvio Padrão](images/erro_desvio_padrao.png){#fig-standard fig-align=\"center\" width=\"12cm\"}\n\n### Exemplo com uma variável assimétrica\n\nComo exemplo, será explorada a variável `renda`, do conjunto de dados `dadosMater.xlsx`, que representa a renda familiar em salários mínimos (*sm*). Como foi feito anteriormente, suponha que essa variável seja a \"população\" de estudo. Ela tem as seguintes medidas resumidoras e de assimetria:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosMater.xlsx\")\nresumo <- dados |> \n  select (renda) |> \n  dplyr::summarise (media = mean (dados$renda, na.rm = TRUE),\n                    dp = sd(dados$renda, na.rm = TRUE),\n                    mediana = median(dados$renda, na.rm = TRUE),\n                    assimetria = e1071::skewness(dados$renda),\n                    curtose = e1071::kurtosis(dados$renda))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  media    dp mediana assimetria curtose\n  <dbl> <dbl>   <dbl>      <dbl>   <dbl>\n1  2.22  1.23    1.92       2.22    8.21\n```\n\n\n:::\n:::\n\n\nO desvio padrão é grande em relação à média, com um coeficiente de variação de 55.1% e uma mediana < média. Estas métricas junto com os coeficientes de assimetria e curtose apontam para a assimetria positiva da variável `renda`. O gráfico da @fig-skewpos confirma esta afirmação:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição assimétrica positiva](11-distAmostrais_files/figure-html/fig-skewpos-1.png){#fig-skewpos fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOs valores da média e do desvio padrão calculados para a distribuição de probabilidade dessa população fornecem os valores dos parâmetros populacionais $\\mu$ e $\\sigma$. Esses valores são $\\mu$ =2.22 *sm* [^11-distamostrais-3] e $\\sigma$ =1.23 *sm*.\\\nSe extrairmos múltiplas amostras dessa população, observa-se a modificação do formato da distribuição à medida que aumenta o tamanho amostral, se aproximando progressivamente do modelo normal, com um número grande de amostras.\n\n[^11-distamostrais-3]: Salários mínimos\n\n[Extração de múltiplas amostras(1000)]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\namostras1000 <- rep (0, 1000)\nfor (i in 1:1000) {\n  amostra.sm <- sample (dados$renda, 30) \n  amostras1000 [i] <- mean(amostra.sm)\n}\n```\n:::\n\n\n[Média e desvio padrão das 1000 amostras]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- round (mean (amostras1000), digits = 3)\nsigma <- round (sd (amostras1000), digits = 3)\nmd <- round (median(amostras1000), digits = 3)\nprint(c(mu, sigma, md))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.231 0.236 2.224\n```\n\n\n:::\n:::\n\n\n[Assimetria e curtose]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1 <- e1071::skewness(amostras1000)\nb2 <- e1071::kurtosis(amostras1000)\nprint(c(b1, b2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4357889 0.2241975\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição praticamente normal](11-distAmostrais_files/figure-html/fig-semskew-1.png){#fig-semskew fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOu seja, extraindo-se 1000 amostras de n = 30 e calculando as mesmas métricas anteriores, observa-se que, embora a distribuição populacional original seja assimétrica, a distribuição amostral da média se aproxima bastante da distribuição gaussiana (@fig-semskew) (veja também @sec-rnorm).\n\n::: callout-important\n## Importância do Teorema Central do Limite\n\nO TCL é um dos pilares da inferência estatística [@massad2004inferencia]. Entender a sua importância é como destrancar a porta para aplicar testes, construir intervalos de confiança e fazer previsões com segurança, mesmo quando os dados parecem confusos.\n\nO TCL afirma que:\n\n> A distribuição das médias amostrais tende a ser normal, mesmo que a população original não seja, desde que o tamanho da amostra seja suficientemente grande.\n:::\n\n## Proporções populacional e amostral {#sec-popamostra}\n\nO conceito de proporção é o mesmo que o conceito de frequência relativa e o conceito de probabilidade de sucesso em um experimento binomial, discutidos anteriormente, na distribuição binomial.\n\nA frequência relativa de uma categoria ou classe dá a proporção da amostra ou população que pertence a essa categoria ou classe. Da mesma forma, a probabilidade de sucesso em um experimento binomial representa a proporção da amostra ou população que possui uma determinada característica.\n\nA proporção populacional, representada por *p*, é obtida considerando a razão entre o número de elementos em uma população com uma característica específica e o número total de elementos na população. A proporção amostral, denotada por $\\hat{p}$ (pronuncia-se p-chapéu), fornece uma proporção semelhante para uma amostra.\n\n$$p = \\frac{X}{N} \\quad e \\quad \\hat{p}= \\frac{x}{n}$$ onde,\n\n- *N* $\\to$ número total de elementos em uma população\n- *n* $\\to$ número total de elementos em uma amostra\n- *X* $\\to$ número de elementos na população que possui determinada característica\n- *x* $\\to$ número de elementos na amostra que possui determinada característica\n\nComo no caso da média, a diferença entre a proporção amostral e a proporção populacional correspondente, determina o *erro amostral*, assumindo que a amostra é aleatória e nenhum erro não amostral foi cometido. Ou seja,\n\n$$erro \\quad amostral = \\hat{p} - p$$\n\nA **distribuição amostral de uma proporção** é a distribuição das proporções de todas as amostras possíveis de tamanho *n* retiradas de uma população.\n\nDe acordo com o Teorema Central do Limite, para amostras suficientemente grandes, a distribuição de $\\hat{p}$ se aproxima de uma distribuição normal, mesmo que os dados originais sejam binomiais (sucesso/fracasso), desde que: $np \\geq 5$ e $n(1 - p) \\geq 5$.\n\nAssim,\n\n$$E(\\hat{p})=\\mu_{\\hat{p}}$$\n\n$$Var(\\hat{p})=\\sigma^2_{\\hat{p}}=\\frac{\\hat{p}(1-\\hat{p})}{n}$$ Logo,\n\n$$\\sigma_{\\hat{p}}=\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\nDessa forma, a distribuição amostral de $\\hat{p}$ será:\n\n$$\\hat{p} \\sim N(\\hat{p}, \\frac{\\hat{p}(1-\\hat{p})}{n})$$\n\nQuando não conhecemos a proporção populacional *p*, pode-se usar $\\hat{p}$ como estimativa dessa proporção, desde que as condições acima sejam satisfeitas.\n\nDessa forma, pode-se calcular probabilidades aproximadas por uma distribuição normal com média $μ = n \\times p$ e $σ = \\sqrt{(n×p(1-p))}$ (veja também @sec-mudpbinom).\n\nConsiderando a \"população\", usada neste capítulo, o conjunto de dados `dadosMater.xlsx`, será verificado a proporção de mulheres fumantes. Inicialmente, a variável `fumo`, que está como variável numérica, será transformada em fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read_excel(\"dados/dadosMater.xlsx\") |> \n  select(fumo) |> \n  mutate(fumo = factor(fumo, \n                       levels = c(1,2), \n                       labels = c(\"Fumante\", \"Não fumante\")))\n```\n:::\n\n\nA proporção de fumantes, frequência relativa (*fr*) é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfumo <- with(dados, table(fumo))\nfr.fumo <- prop.table(fumo)\nfr.fumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfumo\n    Fumante Não fumante \n  0.2200292   0.7799708 \n```\n\n\n:::\n:::\n\n\nA saída retorna que a proporção de fumantes entre as mulheres desse arquivo é 0.22. Esta será considerada a proporção *p* da ‘população’. Agora, imagine que esse resultado fosse desconhecido. Então, para saber a qual a proporção de fumantes dessa ‘população’, seria necessário extrair uma amostra adequada. Foi selecionada uma amostra de n = 100 da ‘população’ alvo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n set.seed(134)\n amostra.fumo <- dados |> dplyr::slice_sample(n = 100)\n```\n:::\n\n\nUsando a `amostra.fumo`, calcula-se a proporção de fumantes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n tabagismo <- with(amostra.fumo, table(fumo))\n fr <- prop.table(tabagismo)\n fp <- fr*100\n\n tab.fumo <- cbind(n = tabagismo,\n                   fr = round(fr, 2),\n                   fp = round(fp, 2))\n tab.fumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             n  fr fp\nFumante     20 0.2 20\nNão fumante 80 0.8 80\n```\n\n\n:::\n:::\n\n\nA proporção de uma amostra é uma variável aleatória: varia de amostra para amostra de uma forma que não pode ser prevista com certeza. O Teorema Central do Limite se aplica em proporções. À medida que novas amostras forem extraídas, o valor da proporção amostral $\\hat{p}$ se aproxima da proporção populacional *p*. Na \"população\" *p* = 0,22; na amostra de n = 100, $\\hat{p}$ = 0.2. Para amostras grandes, a proporção amostral tem distribuição aproximadamente normal com as seguinte características mencionadas acima em relação a $\\mu_{\\hat{p}}$ e $\\sigma_{\\hat{p}}$.\\\nComo verificar se uma amostra é grande?\n\nUma amostra é grande se o intervalo\n\n$$[\\hat{p}-3 \\times \\sigma_{\\hat{p}} , \\quad \\hat{p}+3 \\times \\sigma_{\\hat{p}}]$$\n\nestiver totalmente dentro do intervalo \\[0,1\\].\n\nNa prática, *p* não é conhecido, portanto, $\\sigma_{\\hat{p}}$ também não é. Nesse caso, para verificar se a amostra é suficientemente grande, substitui-se o valor de *p* pelo valor conhecido de $\\hat{p}$. Isso significa verificar se o intervalo\n\n$$\\hat{p}-3\\times\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}},\\quad \\hat{p}+3\\times\\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}}$$\n\nencontra-se totalmente dentro do intervalo \\[0,1\\].\n\nTransportando os dados da amostra de gestantes, para a fórmula e usando o *R* para o cálculo, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np.chapeu <- tab.fumo[1,2]\nn <- tab.fumo[1,1] + tab.fumo[2,1]\n\nli <- p.chapeu - 3*sqrt((p.chapeu*(1-p.chapeu))/n)\nls <- p.chapeu + 3*sqrt((p.chapeu*(1-p.chapeu))/n)\nprint(c(li, ls), digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08 0.32\n```\n\n\n:::\n:::\n\n\nComo os limites ficam no intervalo \\[0, 1\\], chega-se à conclusão de que a amostra de *n* = 100 é aceitável para estimar a proporção populacional.\n\n::: callout-tip\n## Exercício\n\nUma amostra com tamanho n = 40 é suficiente?\n:::\n\n[Resposta]{.underline}:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 40\nli <- p.chapeu - 3*sqrt((p.chapeu*(1-p.chapeu))/n) \nls <- p.chapeu + 3*sqrt((p.chapeu*(1-p.chapeu))/n)\nprint(c(li, ls), digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0103 0.3897\n```\n\n\n:::\n:::\n\n\nSim, é aceitável uma amostra de n = 40.\n",
    "supporting": [
      "11-distAmostrais_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}