{
  "hash": "13f66dfa8639f3dc02a5a8937a365878",
  "result": {
    "engine": "knitr",
    "markdown": "# Avaliação de testes diagnósticos\n\n## Pacotes necessários neste capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(epiR,\n               flextable,\n               knitr,\n               pROC,\n               readxl,\n               vcd)\n```\n:::\n\n\n## Raciocínio Bayesiano no diagnóstico médico {#sec-diagbayes}\n\nO processo diagnóstico é o centro da atenção da atividade médica na busca de reduzir as incertezas e reconhecer a que classe pertence determinado paciente. Portanto, é extremamente importante saber quão bem os testes diagnósticos podem prever que um indivíduo é portador de certa condição ou doença. Entende-se aqui como teste diagnóstico todo o processo diagnóstico, desde o exame clínico até o mais sofisticado exame de imagem ou laboratorial. A ideia é saber como o teste diagnóstico se comporta para separar um \"doente\" e um \"não doente\"; qual a sua validade neste processo?\n\nDeve-se sempre ter em mente que o estabelecimento do diagnóstico é um processo imperfeito que resulta em uma probabilidade ao invés de uma certeza de estar correto. Ou seja, cada vez mais os médicos têm que aplicar as leis da probabilidade na avaliação de testes diagnósticos e sinais clínicos.\n\nA abordagem Bayesiana denomina de **probabilidade a priori** a probabilidade estabelecida inicialmente, baseada apenas na experiência do médico, em seu conhecimento em relação a doença suspeitada. Diante de uma evidência de doença, pode ser solicitado um teste diagnóstico. Quando ele recebe um teste positivo para uma doença, a probabilidade muda, passa a ser uma probabilidade condicional, probabilidade da doença dado que o teste é positivo, denominada **probabilidade a posteriori**.\n\nUm teste que define corretamente quem é doente e quem não é doente é denominado de **padrão-ouro** ou **padrão de referência**. Algumas vezes, o teste padrão de referência é simples e barato. Outras vezes, é caro, difícil de obter, tecnicamente complexo, arriscado ou pouco prático. Inclusive, pode não haver padrão-ouro. Em função dessas limitações, outros testes são usados e, como consequência, podem ocorrer erros. Em outras palavras, no processo diagnóstico podem ocorrer **falsos positivos** e **falsos negativos**. Esta incerteza, na utilização de testes diagnósticos, gera a necessidade de o médico conferir a probabilidade de falsos positivos e falsos negativos na elaboração de um diagnóstico ao receber o resultado positivo ou negativo de um exame. Uma maneira simples de mostrar as relações de um teste diagnóstico e o verdadeiro diagnóstico, é mostrada na tabela de contingência $2\\times2$ (@fig-fpfn).\n\n![Erros diagnósticos](images/fpfn.png){#fig-fpfn fig-align=\"center\" width=\"15cm\"}\n\n## Sensibilidade e Especificidade\n\nAs estatísticas mais utilizadas para descrever a validade dos testes de diagnóstico em contextos clínicos são sensibilidade e a especificidade.\n\n**Sensibilidade** é a habilidade do teste em identificar corretamente quem tem a doença. É a taxa de verdadeiros positivos (VP) de um teste e corresponde a probabilidade de um indivíduo com a doença ter um teste positivo.\n\nUm teste sensível raramente deixará passar pessoas que tenham a doença. Testes com sensibilidade alta são úteis para *excluir* a presença de uma doença. Isto é, um teste negativo exclui virtualmente a possibilidade de o paciente ter a doença de interesse, pois tem pouca probabilidade de produzir resultados falsos negativos. Isto pode ser lembrado pelo mnemônico *SnNout*, do inglês: *High Sensivity, a Negative result rules out the diagnosis* [@straus2019screening].\n\n**Especificidade** é a habilidade do teste em identificar corretamente quem não tem a doença. É a taxa de verdadeiros negativos (VN) de um teste e corresponde a probabilidade de um indivíduo sem a doença ter um teste negativo. Um teste específico raramente classificará de forma errônea indivíduos sendo portadores da doença quando eles não são. Os testes muito específicos são usados para *confirmar* a presença da doença. Se o teste é altamente específico, um teste positivo sugere fortemente a presença da doença de interesse.\n\nDe forma similar que a sensibilidade pode-se usar o mnemônico *SpPin*, do inglês: *High Specificity, a Positive result rules in the diagnosis* [@straus2019screening].\n\nEstas estatísticas de diagnóstico podem ser calculadas a partir das equações, cujas letras representam as caselas da tabela $2 \\times 2$ da @fig-fpfn;\n\n$$Sensibilidade = \\frac {a}{\\left (a + c\\right )} \\quad \\quad Especificidade = \\frac {d}{\\left (b + d\\right )}$$\n\nA **taxa de falsos negativos** (TFN) é a proporção de indivíduos que têm a doença e que têm um resultado de teste negativo e a **taxa de falsos positivos** (TFP) é a proporção de pacientes que não possuem a doença e que apresentam resultados positivos. Podem ser expressas pelas equações:\n\n$$TFN= \\frac {c}{\\left (a + c\\right )} \\quad ou \\quad \\left (1 - sensibilidade\\right)$$\n\n$$TFP= \\frac {b}{\\left (b + d\\right )} \\quad ou \\quad \\left (1 - especificidade\\right)$$\n\nIdealmente, um teste de diagnóstico deveria ter altos níveis de sensibilidade e especificidade. No entanto, isso não é possível, pois existe um balanço entre sensibilidade e especificidade. À medida que a especificidade aumenta, a sensibilidade diminui e vice-versa. As curvas ROC podem ser usadas para identificar um ponto de corte em uma medição contínua que maximize a sensibilidade e a especificidade (veja @sec-rocurve).\n\nQuando um clínico tem um paciente cujo teste apresentou resultado positivo, a pergunta mais importante é a seguinte: dado que o teste é positivo, qual é a probabilidade de o paciente ter a doença? A sensibilidade do teste não responde a este questionamento, mas sim a probabilidade de um resultado positivo, dado que o paciente tem a doença [@altman1994diagnostic].\n\n### Dados do exemplo {#sec-exapendicite}\n\n::: callout-note\n## Cenário\n\nForam avaliados 156 pacientes com diagnóstico clínico de apendicite aguda, submetidos à ultrassonografia abdominal e apendicectomia laparoscópica, acompanhado de estudo anatomopatológico dos apêndices extirpados [@peixoto2011indices].\n:::\n\nOs dados estão contidos no conjunto de dados `dadosApendicite.xlsx` que pode ser obtido [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosApendicite.xlsx). Salve o mesmo em seu diretório de trabalho.\n\n#### Leitura e observação dos dados\n\nSerá usada a função `read_excel()` do pacote `readxl` para ler os dados e a função `str()` para observar a sua estrutura:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel (\"dados/dadosApendicite.xlsx\")\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [156 × 3] (S3: tbl_df/tbl/data.frame)\n $ id        : num [1:156] 1 2 3 4 5 6 7 8 9 10 ...\n $ apendicite: num [1:156] 1 1 1 1 1 1 1 1 1 1 ...\n $ eco       : num [1:156] 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nAs variáveis `apendicite` e `eco` foram exibidas como variáveis numéricas e serão transformadas em fatores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$apendicite <- factor(dados$apendicite,\n                           levels = c(1,2),\n                           labels = c(\"Presente\", \n                                      \"Ausente\"))\n\ndados$eco <- factor(dados$eco,\n                    levels = c(1,2),\n                    labels = c(\"Positivo\", \n                               \"Negativo\"))\n```\n:::\n\n\n#### Construção de uma tabela de contingência $2\\times2$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_ap <- with(dados, table(eco, apendicite, dnn = c (\"Eco\", \"Apendicite\")))\naddmargins(tab_ap, FUN = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargins computed over dimensions\nin the following order:\n1: Eco\n2: Apendicite\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Apendicite\nEco        Presente Ausente sum\n  Positivo       85       7  92\n  Negativo       46      18  64\n  sum           131      25 156\n```\n\n\n:::\n:::\n\n\n#### Avaliação do teste diagnóstico através da sensibilidade e da especificidade\n\nPode-se usar a função `epi.tests()` do pacote `epiR` [@stevenson2022epir] que calcula, junto com os intervalos de confiança exatos, a prevalência aparente e verdadeira, sensibilidade, especificidade, valores preditivos positivos e negativos e razões de probabilidade positivas e negativas a partir de dados de contagem fornecidos em uma tabela $2\\times2$. Utiliza os argumentos\n\n- **dat** $\\to$ dados sob a forma de vetor ou matriz\n- **conf.level** $\\to$ magnitude do intervalo de confiança, entre 0 e 1.\n\nOs resultados serão atribuídos a um objeto de nome `diag`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiag <- epiR::epi.tests(tab_ap, \n                        conf.level = 0.95)\nprint(diag)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Outcome +    Outcome -      Total\nTest +           85            7         92\nTest -           46           18         64\nTotal           131           25        156\n\nPoint estimates and 95% CIs:\n--------------------------------------------------------------\nApparent prevalence *                  0.59 (0.51, 0.67)\nTrue prevalence *                      0.84 (0.77, 0.89)\nSensitivity *                          0.65 (0.56, 0.73)\nSpecificity *                          0.72 (0.51, 0.88)\nPositive predictive value *            0.92 (0.85, 0.97)\nNegative predictive value *            0.28 (0.18, 0.41)\nPositive likelihood ratio              2.32 (1.22, 4.40)\nNegative likelihood ratio              0.49 (0.35, 0.68)\nFalse T+ proportion for true D- *      0.28 (0.12, 0.49)\nFalse T- proportion for true D+ *      0.35 (0.27, 0.44)\nFalse T+ proportion for T+ *           0.08 (0.03, 0.15)\nFalse T- proportion for T- *           0.72 (0.59, 0.82)\nCorrectly classified proportion *      0.66 (0.58, 0.73)\n--------------------------------------------------------------\n* Exact CIs\n```\n\n\n:::\n:::\n\n\nAssim, a sensibilidade é igual a 65% (IC95%: 56 – 73%) e a especificidade é igual a 72% (IC95%: 51 – 88%). Isto significa que um indivíduo com apendicite aguda tem 65% de probabilidade de ter uma ecografia alterada; um indivíduo sem apendicite aguda tem 72% de probabilidade de ter uma ecografia normal. O objetivo do teste de diagnóstico é usá-lo para fazer um diagnóstico, então há necessidade de saber a probabilidade que o teste fornece para um diagnóstico correto. A sensibilidade e a especificidade não fornecem esta informação. Para atingir esse objetivo, usa-se o **valor preditivo** [@altman1994predictive].\n\n## Valor Preditivo\n\nO propósito de um teste diagnóstico é usar seus resultados para fazer um diagnóstico, portanto, é necessário conhecer a probabilidade de que o resultado do teste forneça o diagnóstico correto [@altman1994predictive].\n\nOs valores preditivos positivo e negativo descrevem a probabilidade de um paciente ter doença, uma vez que os resultados de seus testes são conhecidos.\n\nO **valor preditivo positivo** (VPP) de um teste é definido como a proporção de pessoas com um resultado de teste positivo que realmente têm a doença.\n\nO **valor preditivo negativo** (VPN) é a proporção de pacientes com resultados de teste negativos que não têm doença.\n\nComo a sensibilidade e a especificidade, estas estatísticas de diagnóstico também podem ser calculadas a partir da tabela $2\\times2$, mostrada no início:\n\n$$VPP = \\frac {a}{\\left (a + b\\right )} \\quad \\quad VPN = \\frac {d}{\\left (c + d\\right )}$$\n\nObservando os resultados anteriores da função `epi.tests()`, verifica-se que 92% (85/92) dos indivíduos que tiveram teste positivo (ultrassonografia alterada) tinham doença (apendicite aguda). Isso significa que seu VPP é igual a 92% (IC95%: 85 – 97%), ou dito de outra forma, uma pessoa com ultrassonografia positiva tem 92% de probabilidade de ter a apendicite aguda. O VPP é também conhecido como **probabilidade pós-teste** de doença dado um teste positivo.\n\nDos 64 pacientes que tiveram ultrassonografia sem alterações, 18 não apresentaram apendicite aguda, portanto, um VPN de 28% (IC95%: 18 – 41%). Isso significa que uma pessoa quem tem um teste negativo tem 28,1% de probabilidade de não ter apendicite aguda.\n\nEntretanto, essas proporções são de validade limitada. Os valores preditivos de um teste, na prática clínica, dependem criticamente da prevalência da anormalidade nos pacientes testados. No estudo, a prevalência de apendicite aguda é igual a\n\n$$\\frac {total\\ de\\ casos\\ de \\ apendicite \\ aguda}{total\\ de\\ casos\\ no\\ estudo} = \\frac {131}{156} = 0,84\\ ou\\ 84\\% \\left(IC_{95\\%}:77\\ a\\ 89\\%\\right)$$\n\nLevando-se em consideração que a prevalência de apendicite aguda na população é de 7% [@lima2016perfil], mantendo a sensibilidade (65%) e a especificidade (72%) da ultrassonografia, entre 156 pacientes, selecionados aleatoriamente, se esperaria encontrar aproximadamente 11 casos (7% de 156) de apendicite aguda. Para facilitar a compreensão, observe a tabela $2\\times2$ (@fig-vpp):\n\n![Prevalência e valor preditivo](images/vpp.png){#fig-vpp fig-align=\"center\" width=\"15cm\"}\n\nO VPP e o VPN são iguais a:\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 7\nb <- 41\nc <- 4\nd <- 104\nvpp = a/(a + b)\nround(vpp, 3)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.6\n```\n\n\n:::\n\n```{.r .cell-code}\nvpn = d/(c + d)\nround(vpn, 3)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 96.3\n```\n\n\n:::\n:::\n\n\nAo se comparar o VPP obtido, agora, com o VPP do estudo, observa-se que o mesmo diminuiu bastante, de 92% para 14,6%. O contrário ocorre com a VPN que aumenta substancialmente de 28% para 96,3%, mostrando claramente a influência da prevalência.\n\nSe a prevalência diminui, o VPP diminui e o VPN aumenta. Portanto, será errado aplicar diretamente os valores preditivos publicados de um teste ao seu paciente, quando a prevalência da doença em sua população for diferente da prevalência da doença na população em que o estudo publicado foi realizado. Um teste pode ser útil em um lugar e não ter validade em outro onde a prevalência é muito baixa.\n\nPode-se chegar aos mesmos resultados, usando as equações:\n\n$$VPP =\\frac{sens \\times prev}{\\left(sens \\times prev\\right) + \\left [\\left (1- espec\\right) \\times \\left (1- prev\\right)\\right ]}$$\n\n$$VPN =\\frac{espec\\times \\left (1- prev\\right)}{\\left[\\left (1 - sens \\right)\\times prev\\right]+\\left[espec\\times \\left (1 - prev\\right)\\right]}$$\n\nA prevalência pode ser interpretada como a probabilidade antes da realização do teste, conhecida como *probabilidade pré-teste*. A diferença entre as probabilidades pré e pós-teste é uma forma de avaliar a utilidade do teste. Esta diferença pode ser mensurada pela **razão de probabilidade** (**likelihood ratio**).\n\n## Razão de Probabilidade\n\nA **Razão de Probabilidades** (*likelihood ratio*) é uma forma alternativa de descrever o desempenho de um teste diagnóstico. Alguns autores a denominam de razão de verossimilhança [^21-testesdiag-1].\n\n[^21-testesdiag-1]: Verossimilhança no sentido de a qualidade de algo que parece verdadeiro ou provável, que não contraria a verdade\n\nA razão de probabilidades para um resultado de teste é definida como a razão entre a probabilidade de observar aquele resultado em indivíduos com a doença em questão e a probabilidade desse resultado em indivíduos sem a doença [@halkin1998likelihood].\n\nRazões de probabilidade são, clinicamente, mais úteis do que sensibilidade e especificidade. Fornecem um resumo de quantas vezes mais (ou menos) a probabilidade de os indivíduos com a doença apresentarem aquele resultado específico do que os indivíduos sem a doença, e também podem ser usados para calcular a probabilidade de doença para pacientes individuais [@deeks2004likelihood]. Cada vez mais as razões de probabilidade estão se tornando populares para relatar a utilidade dos testes de diagnóstico.\n\nQuando os resultados do teste são relatados como sendo positivos ou negativos, dois tipos de razões de probabilidades podem ser descritos, a razão de probabilidades para um teste positivo (denotada LR +) e a razão de probabilidades para um teste negativo (denotada LR−).\n\nA *razão de probabilidades para um teste positivo* é definida como a probabilidade de um indivíduo com doença ter um teste positivo dividida pela probabilidade de um indivíduo sem doença ter um teste positivo. A fórmula para calcular LR + é\n\nOu seja,\n\n$$LR(+)=\\frac{sensibilidade}{1 - especificidade}$$\n\nRazão de probabilidades positiva maior que 1 significa que um teste positivo tem mais probabilidade de ocorrer em pessoas com a doença do que em pessoas sem a doença. De um modo geral, para os indivíduos que apresentam um resultado positivo, LR (+) \\> 10 aumenta significativamente a probabilidade de doença (“confirma” a doença), enquanto LR (+) \\< 0,1, virtualmente, exclui a probabilidade de uma pessoa ter a doença [@guyatt2015diagnostic].\n\nUsando os dados incluídos no objeto `diag`, obtido com a função `epi.tests()` do pacote `epiR`, tem-se que a LR (+) da ultrassonografia para o diagnóstico de apendicite aguda é igual 2.32 (IC95%: 1,22 – 4,40). Significa que uma pessoa com apendicite aguda tem cerca de 2,32 vezes mais probabilidade de ter um teste positivo do que uma pessoa que não tem a doença.\n\nA *razão de probabilidade negativa* é definida como a probabilidade de um indivíduo com doença ter um teste negativo dividido pela probabilidade de um indivíduo sem doença ter um teste negativo. A fórmula para calcular a LR− é:\n\nOu seja,\n\n$$LR(-)=\\frac{1-sensibilidade}{especificidade}$$\n\nRazão de probabilidade negativa menor que 1 significa que um teste negativo é menos provável de ocorrer em pessoas com a doença do que em pessoas sem a doença. Um LR muito baixo (abaixo de 0,1) praticamente exclui a chance de que uma pessoa tenha a doença [@guyatt2015diagnostic].\n\nVoltando aos dados anteriores, a LR (-) para a ultrassonografia é igual a 0.49 (IC95%: 0.35 - 0.68). Significa que a probabilidade de ter um teste negativo para indivíduos com doença é 0,49 vezes ou cerca de metade daqueles sem a doença. Dito de outra forma, os indivíduos sem a doença têm cerca do dobro da probabilidade de ter um teste negativo do que os indivíduos com a doença.\n\n### Estimando a probabilidade de doença\n\nUma grande vantagem das razões de probabilidade é que elas podem ser usadas para ajudar o médico a adaptar a sensibilidade e a especificidade dos testes aos pacientes individuais. Ao se atender um paciente em uma clínica, pode-se decidir realizar um teste específico, após uma anamnese e um exame físico. A decisão de fazer o teste baseia-se nos sintomas e sinais do paciente e na experiência pessoal. Existe suspeita de um determinado diagnóstico e o objetivo é excluir ou confirmar esse diagnóstico. Antes de solicitar o teste, geralmente existe uma estimativa aproximada da probabilidade do paciente de ter essa doença, conhecida como **probabilidade pré-teste** ou **a priori**, que geralmente é estimada com base na experiência pessoal do médico, dados de prevalência local e publicações científicas.\n\nA razão mais importante pela qual um teste é realizado é tentar modificar a probabilidade de doença. Um teste positivo pode aumentar a probabilidade pós-teste e um teste negativo pode reduzir essa probabilidade. A probabilidade pós-teste de doença é o que mais interessa aos médicos e pacientes, pois isso pode ajudar a decidir se devem confirmar, descartar um diagnóstico ou realizar outros testes.\n\nOs resultados dos testes clínicos são geralmente usados não para fazer ou excluir categoricamente um diagnóstico, mas para modificar a probabilidade do pré-teste a fim de gerar a probabilidade do pós-teste. O teorema de Bayes é uma relação matemática que permite estimar a probabilidade pós-teste.\n\nPara se compreender este conceito, é importante entender a diferença entre **probabilidade** e **odds** [@oliveira2022diagnostico].\n\n**Probabilidade** é a proporção de pessoas que apresentam uma determinada característica (teste positivo, sinal clínico).\\\n**Odds** (chance) representa a razão entre duas características complementares, ou seja, a probabilidade de um evento dividido pela probabilidade do não evento (1 – evento). Ambos contêm as mesmas informações de maneiras diferentes. Por exemplo, usando os dados da tabela `tab_ap` (veja @sec-exapendicite), verifica-se que a probabilidade (*p*) de uma ultrassonografia positiva para apendicite aguda é igual\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- tab_ap[1,1]\nb <- tab_ap[1,2]\nc <- tab_ap[2,1]\nd <- tab_ap[2,2]\np <- (a + b)/(a + b + c + d)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5897436\n```\n\n\n:::\n:::\n\n\ne que o *odds* da ultrassonografia positiva[^21-testesdiag-2] é\n\n[^21-testesdiag-2]: Existem duas maneiras de descrever uma estimativa de odds: ou como um número isolado, por exemplo, 0,25, subentendendo que expressa uma razão, 0,25:1,0, ou de forma clara como uma razão 1:4. Ou seja, para cada indivíduo com o fator existem quatro sem o fator. Tradicional e comumente usados no mundo das apostas em corridas de cavalos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n odds <- (a + b)/(c + d) \n odds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.4375\n```\n\n\n:::\n:::\n\n\nPara transformar a *odds* em probabilidades e vice-versa, procede-se da seguinte maneira:\n\n$$p=\\frac{odds}{1+odds}$$\n\nVoltando ao exemplo (@sec-exapendicite):\n\n\n::: {.cell}\n\n```{.r .cell-code}\np = odds/(1 + odds)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5897436\n```\n\n\n:::\n:::\n\n\ne\n\n$$odds=\\frac{p}{1-p}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodds = p/(1-p)\nodds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.4375\n```\n\n\n:::\n:::\n\n\nPelo teorema de Bayes, sabendo-se a *probabilidade a priori* ou *probabilidade pré-teste*, é possível obter a *probabilidade pós-teste* ou *a posteriori*, usando a razão de probabilidades.\n\nPara atingir este objetivo, basta, inicialmente, multiplicar o *odds pré-teste* pela razão de probabilidades:\n\n$$odds_{pos} = odds_{pre \\quad \\times \\quad LR}$$\n\nApós, para encontrar a probabilidade pós-teste, basta converter o *odds* pós-teste em probabilidade:\n\n$$p_{pos} = \\frac{odds_{pos}}{1-odds_{pos}}$$\n\nNo exemplo (@sec-exapendicite), foi verificado que o LR (+) é igual a 2,32 e a prevalência de apendicite aguda é em torno de 7% pode-se prever a probabilidade de haver apendicite aguda, diante de uma ultrassonografia alterada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprev <-  0.07\nLR <-  2.32\n\nodds_pre <-  0.07/(1 -0.07)\n\nodds_pos <- odds_pre * LR\n\np_pos <- odds_pos/(odds_pos +1)\n\nround(p_pos, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.149\n```\n\n\n:::\n:::\n\n\nOu, em outras palavras, diante de um teste positivo, a probabilidade de o paciente ter apendicite aguda passa de 7% antes do teste para praticamente 15%!\n\nEstes cálculos podem ser simplificados, utilizando o nomograma de Fagan [@fagan1975nomogram], extremamente fácil de se usar [@caraguel2013fagan], pois basta unir a probabilidade pré-teste ao LR que a reta apontará para a probabilidade pós-teste (@fig-fagan).\n\n![Nomograma de Fagan](images/fagan.png){#fig-fagan fig-align=\"center\" width=\"12cm\"}\n\n## Curva ROC {#sec-rocurve}\n\nNem sempre o resultado de um teste é dicotômico (positivo/negativo). Com frequência, trabalha-se com variáveis contínuas (pressão arterial, glicemia, dosagem do sódio, dosagens hormonais, etc.). Neste caso, não há um resultado “positivo” ou “negativo”. Um “ponto de corte” precisa ser criado, para definir quem será considerado positivo ou negativo.\n\nA escolha do ponto de corte depende das consequências de um resultado falso positivo ou de um falso negativo. Falsos positivos estão associados com custos (emocional ou financeiro) e com a dificuldade de “desrotular” alguém que recebeu o rótulo de “positivo”. Resultados falsos negativos podem “tranquilizar” pessoas doentes que não são seguidas ou tratadas precocemente.\n\nA distribuição dos níveis glicêmicos em diabéticos e não diabéticos não tem um ponto de corte bem nítido. As duas populações se sobrepõem (@fig-diabetes), gerando falso positivos ou falso negativos, dependendo do ponto de corte escolhido [@oliveira2022diagnostico].\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Populações de indivíduos normais (curva em azul) e diabéticos (curva em vermelho)](21-testesDiag_files/figure-html/fig-diabetes-1.png){#fig-diabetes fig-align='center' width=80%}\n:::\n:::\n\n\nSuponha que ao se examinar uma população fosse escolhido o ponto de corte de 80mg/dL, haveria um aumento no número de indivíduos com teste positivo com uma taxa de falsos positivos elevada, diminuindo a especificidade do teste. Se, por outro lado, o ponto de corte fosse elevado para 200mg/dL, o número de falsos negativos teria um grande aumento, reduzindo a sensibilidade. Esta oscilação entre a sensibilidade e a especificidade ocorre pelo fato de a localização do ponto de corte ser uma decisão arbitrária num contínuo entre o normal e anormal.\n\nAo se escolher um ponto de corte deve-se fazer um balanço entre a sensibilidade e a especificidade, levando em conta as consequências da escolha. Por exemplo, a triagem para fenilcetonúria em recém-nascidos valoriza a sensibilidade em vez de especificidade; o custo da perda de um caso é alto, pois existe tratamento eficaz. Uma desvantagem é que ocorre um grande número de testes falso positivos que causam angústia e a realização de mais testes.\n\nEm contraste, a triagem para o câncer de mama deve favorecer a especificidade sobre a sensibilidade, uma vez que uma avaliação mais aprofundada daquelas com teste positivo, implica em biopsias dispendiosas e invasivas.\n\nAs **curvas ROC** (*Receiver Operating Characteristic*) são uma ferramenta inestimável para encontrar o ponto de corte em uma medida com distribuição contínua que melhor prediz se uma condição está presente, por exemplo, se pacientes são positivos ou negativos para a presença de uma doença [@altman1994roc]. As curvas ROC são usadas para encontrar um ponto de corte que separa um resultado de teste \"normal\" de um \"anormal\" quando o resultado do teste é uma medida contínua. As curvas ROC são traçadas calculando a sensibilidade e a especificidade do teste na predição do diagnóstico para cada valor da medida. A curva permite determinar um ponto de corte para a medição que maximiza a taxa de verdadeiros positivos (sensibilidade) e minimiza a taxa de falsos positivos (1 – especificidade) e, portanto, maximiza a razão de probabilidades (*likelihood ratio*).\n\n### Dados do exemplo {#sec-exdadosTestes}\n\nO conjunto de dados `dadosTestes.xlsx` contém informações para os resultados hipotéticos de três testes bioquímicos diferentes e uma variável (`doença`) que indica se foi confirmada a doença (*padrão-ouro*). Para obter arquivo, clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosTestes.xlsx) e salve o mesmo em seu diretório de trabalho.\n\n#### Leitura e observação dos dados\n\nComo é um arquivo em Excel, a leitura será realizada pela função `read_excel()` do pacote `readxl`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntestes <- readxl::read_excel(\"dados/dadosTestes.xlsx\")\nstr(testes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [145 × 5] (S3: tbl_df/tbl/data.frame)\n $ id    : num [1:145] 1 2 3 4 5 6 7 8 9 10 ...\n $ teste1: num [1:145] 25 2.2 46.2 9.9 46.5 36.1 34.8 44.9 36.9 7.1 ...\n $ teste2: num [1:145] 25 2.2 15.6 20.4 15.7 35.7 34.8 55.4 36.9 7.1 ...\n $ teste3: num [1:145] 15 2.2 25 20.4 15.7 36.1 24 55.4 36.9 7.1 ...\n $ doenca: num [1:145] 2 2 1 1 2 2 2 1 2 2 ...\n```\n\n\n:::\n:::\n\n\nA variável `doença` será transformada em fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntestes$doenca <- as.factor(testes$doenca)\n```\n:::\n\n\nAs curvas ROC são usadas para avaliar qual teste é mais útil para prever quais pacientes serão positivos para a doença. A hipótese nula é que a área sob a curva ROC é igual a 0,5, ou seja, a habilidade do teste para identificar casos positivos e negativos é a esperada por acaso.\n\nA @fig-status123 mostra a quantidade de sobreposição na distribuição da medição dos testes bioquímicos contínuos em ambos os grupos doença positiva e doença negativa. No Teste 1, a sobreposição é completa e não haverá um ponto de corte que separe efetivamente os dois grupos. Nos Testes 2 e 3, há uma maior separação das medidas de teste entre os grupos, particularmente para Teste 3.\n\n![Resultado do teste vs doença](images/status123.png){#fig-status123 fig-align=\"center\" width=\"12.5cm\"}\n\n### Construção da curva ROC\n\nA validade dos testes, na distinção entre os grupos doença-positivo e doença-negativo, pode ser quantificada pelas curvas ROC, usando a função `roc()` do pacote `pROC` [@robin2011proc]. Este pacote tem várias funções:\n\n- **auc**: calcula a área da curva ROC;\n- **ci**: calcula o intervalo de confiança da curva ROC;\n- **ci.auc**: calcula o intervalo de confiança da AUC;\n- **ci.se**: calcula o intervalo de confiança de sensibilidades em determinadas especificidades;\n- **ci.sp**: calcula o intervalo de confiança de especificidades em determinadas sensibilidades;\n- **ci.thresholds**: calcula o intervalo de confiança dos limites;\n- **coords**: Retorna as coordenadas (sensibilidades, especificidades, pontos de corte) de uma curva ROC;\\\n- **roc**: Constroi uma curva ROC;\\\n- **roc.test**: Compara a AUC de duas curvas ROC correlacionadas;\\\n- **smooth**: suaviza a curva ROC\n\nUsar a função com os argumentos variável resposta (`doenca`), variável preditora (`teste3`, `teste2` e `teste1`), indicação de que o gráfico deve ser desenhado (`plot = TRUE`). Como por padrão o gráfico é plotado com a sensibilidade no eixo *x* e a especificidade no eixo *y*; deve-se acrescentar o argumento `legacy.axes = TRUE` para aparecer o seu complemento, os falsos positivos ($1 – especificidade$).\n\nAlém desses, pode-se usar vários outros argumentos como: `print.auc = TRUE`, que imprime no gráfico a `AUC` e `ci` que é o intervalo de confiança da AUC. Para que a sensibilidade e especificidade apareçam como uma percentagem, deve-se usar o argumento `percent = TRUE`, pois o padrão é `FALSE`. Os demais argumentos são os rótulos dos eixos, cor da curva, largura da curva (`lwd`).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nroc3 <- roc (testes$doenca,\n             testes$teste3, \n             plot=TRUE,\n             quiet = TRUE,\n             legacy.axes=TRUE, \n             print.auc=TRUE,\n             print.auc.y = 0.2,\n             ci = TRUE,\n             ylab=\"Sensibilidade\",\n             xlab=\"1 - Especificidade\",\n             col=\"steelblue\",\n             smooth = TRUE,\n             lwd=2) \n\nroc2 <- roc (testes$doenca,\n             testes$teste2, \n             plot=TRUE,\n             quiet = TRUE,\n             legacy.axes=TRUE, \n             print.auc=TRUE,\n             ci = TRUE,\n             print.auc.y=0.13,\n             col=\"chartreuse4\",\n             lwd=2,\n             smooth = TRUE,\n             add=TRUE)\n\nroc1 <- roc (testes$doenca,\n             testes$teste1, \n             plot=TRUE,\n             quiet = TRUE,\n             legacy.axes=TRUE, \n             print.auc=TRUE,\n             ci = TRUE,\n             print.auc.y=0.06,\n             col=\"tomato\",\n             lwd=2,\n             smooth = TRUE,\n             add=TRUE)\n\n# Legendas das curvas ROC\ntext (0.73,0.80,\"Teste 3\", col=\"steelblue\", cex = 1)\ntext (0.53,0.73,\"Teste 2\", col=\"chartreuse4\", cex = 1)\ntext (0.35,0.65,\"Teste 1\", col=\"tomato\", cex = 1) \n```\n\n::: {.cell-output-display}\n![Curvas ROC para os Testes 1, 2 e 3](21-testesDiag_files/figure-html/fig-roc-1.png){#fig-roc fig-align='center' width=80% height=80%}\n:::\n:::\n\n\n#### Interpretação do resultado\n\nEm uma curva ROC, a sensibilidade é calculada usando cada valor do teste no conjunto de dados como um ponto de corte e é plotada em relação à (1 – especificidade) correspondente nesse ponto, como mostrado na @fig-roc.\n\nAssim, a curva são os *Verdadeiros Positivos* (VP) plotados em relação aos *Falsos Positivos* (FP), calculados usando cada valor do teste como ponto de corte. A reta diagonal indica onde o teste cairia se os resultados não fossem melhores do que o acaso para predizer a presença de uma doença. O Teste 1 está próximo desta reta, confirmando que ele tem pouca capacidade de discriminar os pacientes doentes e não doentes.\n\nA área abaixo da reta diagonal é equivalente a 0,5 da área total. Quanto maior a área sob a curva ROC, mais útil é o teste para predizer os pacientes que têm a doença. Uma curva que cai substancialmente abaixo da linha diagonal indica que o teste tem pouca capacidade de diagnosticar a doença. Quando há uma separação perfeita dos valores dos dois grupos, isto é, sem sobreposição das distribuições, a área sob a curva ROC é igual a 1 (a curva ROC alcançará o canto superior esquerdo do gráfico).\n\nA área sob a curva (*Area Under the Curve* – AUC) e seu intervalo de confiança de 95% podem ser obtidos com os comandos usados na construção da @fig-roc ou separadamente usando as funções `auc()` e `ci.auc()` do pacote `pROC`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauc (roc1) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.5891\n```\n\n\n:::\n\n```{.r .cell-code}\nci.auc (roc1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: 0.4908-0.6844 (2000 stratified bootstrap replicates)\n```\n\n\n:::\n\n```{.r .cell-code}\nauc(roc2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.7616\n```\n\n\n:::\n\n```{.r .cell-code}\nci.auc(roc2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: 0.6741-0.8367 (2000 stratified bootstrap replicates)\n```\n\n\n:::\n\n```{.r .cell-code}\nauc (roc3) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.898\n```\n\n\n:::\n\n```{.r .cell-code}\nci.auc(roc3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: 0.8347-0.9396 (2000 stratified bootstrap replicates)\n```\n\n\n:::\n:::\n\n\nA acurácia geral de um teste pode ser descrita como a área sob a curva; quanto maior for a área, melhor será o teste. Na @fig-roc, o Teste 3 tem uma AUC maior que os outros dois testes.\\\nUsa-se a seguinte estimativa (@tbl-roc1) para avaliar a acurácia de um teste ou da capacidade de identificar corretamente uma condição usando curva ROC [@borges2016accuracy]:\n\n\n::: {#tbl-roc1 .cell tbl-cap='Acurácia do teste diagnóstico'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-b04c5a3a{}.cl-b042fbc0{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b042fbe8{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b047cf06{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b047f90e{width:1.05in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b047f918{width:1.619in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b047f922{width:1.05in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b047f923{width:1.619in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b047f92c{width:1.05in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b047f936{width:1.619in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b04c5a3a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b047f90e\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbc0\">AUC</span></p></th><th class=\"cl-b047f918\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbc0\">Qualidade do Teste</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f922\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">&gt;0,90</span></p></td><td class=\"cl-b047f923\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">excelente</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f922\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">0,80 a 0,90</span></p></td><td class=\"cl-b047f923\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">muito bom</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f922\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">0,70 a 0,80</span></p></td><td class=\"cl-b047f923\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">bom</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f922\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">0,60 a 0,70</span></p></td><td class=\"cl-b047f923\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">suficiente</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f922\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">0,50 a 0,60</span></p></td><td class=\"cl-b047f923\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">ruim</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b047f92c\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">&lt;0,50</span></p></td><td class=\"cl-b047f936\"><p class=\"cl-b047cf06\"><span class=\"cl-b042fbe8\">ignorar teste</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nDesta forma, o Teste 3 pode ser considerado um bom teste e o Teste 1 é um teste ruim.\n\n[Comparando duas curvas]{.underline}\n\nPode-se comparar duas curvas ROC com a função `roc.test()`, por exemplo, comparando as curvas dos Teste 3 e 2 [@delong1988comparing]:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc.test(roc3, roc2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBootstrap test for two correlated ROC curves\n\ndata:  roc3 and roc2\nD = 4.8466, boot.n = 2000, boot.stratified = 1, p-value = 1.256e-06\nalternative hypothesis: true difference in AUC is not equal to 0\nsample estimates:\nSmoothed AUC of roc1 Smoothed AUC of roc2 \n           0.8980454            0.7616201 \n```\n\n\n:::\n:::\n\n\nO Teste 3 tem uma AUC que o caracteriza como um bom teste e o teste de DeLong, entregue na saída do `roc.test()`, resultou que a diferença entre ele e o Teste 2 é estatisticamente significativa (*P* \\< 0,0001).\n\n#### Melhor ponto de corte\n\nO melhor ponto de corte (*Best Critical Value*), que às vezes é chamado de *ponto de diagnóstico ótimo* ou *de Youden*, é o ponto da curva mais próximo da parte superior do eixo *y* (@fig-roc, Teste 3). Este é o ponto em que a taxa de verdadeiros positivos é otimizada e a taxa de falsos positivos é minimizada. O melhor ponto de corte para o Teste 3 é mostrado na @fig-roc3. Este melhor ponto de corte pode ser identificado a partir dos pontos de coordenadas da curva, usando a função `roc()` com os seguintes argumentos:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbest <- roc (testes$doenca, \n     testes$teste3,\n     plot = TRUE,\n     ci=TRUE,\n     thresholds=\"best\", \n     print.thres=\"best\",\n     legacy.axes=TRUE,\n     main=\"\",\n     ylab=\"Sensibilidade\",\n     xlab=\"1 - Especificidade\",\n     col=\"steelblue\",\n     lwd=2)\nbest\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nroc.default(response = testes$doenca, predictor = testes$teste3,     ci = TRUE, plot = TRUE, thresholds = \"best\", print.thres = \"best\",     legacy.axes = TRUE, main = \"\", ylab = \"Sensibilidade\", xlab = \"1 - Especificidade\",     col = \"steelblue\", lwd = 2)\n\nData: testes$teste3 in 48 controls (testes$doenca 1) > 97 cases (testes$doenca 2).\nArea under the curve: 0.8973\n95% CI: 0.8444-0.9502 (DeLong)\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Melhor ponto de corte](21-testesDiag_files/figure-html/fig-roc3-1.png){#fig-roc3 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nAssim, para o *Teste 3*, o ponto de corte ideal é 24,8, onde a especificidade é igual a 0,854 e a sensibilidade é igual a 0,845. Estes dados, fornecem um LR para um resultado positivo igual a:\n\n$$LR \\left(+\\right) = \\frac{0.845}{\\left (1-0.854\\right)} = 5,79$$\n\nAs coordenadas da curva ROC podem ser obtida com a seguinte programação, a partir de uma sensibilidade e especificidade acima de 0 (zero):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoordenadas <- testes |> roc(doenca, teste3) |> coords (transpose = F)\nhead(coordenadas, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   threshold specificity sensitivity\n1        Inf  0.00000000           1\n2      57.50  0.02083333           1\n3      54.65  0.04166667           1\n4      53.45  0.06250000           1\n5      52.80  0.08333333           1\n6      51.30  0.10416667           1\n7      49.65  0.12500000           1\n8      48.65  0.16666667           1\n9      47.50  0.18750000           1\n10     46.50  0.35416667           1\n```\n\n\n:::\n:::\n\n\nA *estatística J de Youden* [@youden1950index] é calculada deduzindo 1 a partir da soma de sensibilidade e especificidade do teste e não é expressa como porcentagem, mas como parte de um número inteiro: $\\left (sensibilidade + especificidade\\right) - 1$. A estatística J de Youden no melhor ponto de corte do Teste 3 é igual a $\\left (0,845+ 0,854\\right) - 1 = 0,699$.\n\nEste é o maior valor de todos os valores das coordenadas (91 valores) usadas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyouden <- max(coordenadas$sensitivity + coordenadas$specificity) - 1\nyouden\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6995275\n```\n\n\n:::\n:::\n\n\nA @fig-roc3 mostra o ponto de corte ideal. Ele também pode ser obtido com a função `coords()` do pacote `pRoc`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroc3 <- testes |> roc(doenca, teste3)\ncoords(roc3, x = \"best\", ret=\"threshold\", transpose = FALSE, \n       best.method=\"youden\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  threshold\n1      24.8\n```\n\n\n:::\n:::\n\n\nO método para obter o melhor ponto de corte (`best.method`) pode ser pelo método de `youden` ou `closest.topleft`. No exemplo, o resultado é o mesmo. Para maiores detalhes consulte a ajuda da função `coord()`, do pacote `pROC`.\n\n## Estatística *kappa*\n\nA estatística de concordância *kappa* (*k*) de Cohen é utilizada para descrever a concordância entre dois ou mais avaliadores quando realizam uma avaliação nominal ou ordinal de uma mesma amostra [@cohen1960coefficient]. A estatística *kappa* corrige a chance do acaso nas avaliações e é obtida pela fórmula igual a:\n\n$$k= \\frac{p_{o} - p_{e}}{1 - p_{e}}$$\n\nOnde $p_{o}$ = proporção observada de concordância e $p_{e}$ = proporção esperada de concordância apenas pelo acaso.\n\nPor exemplo, dois radiologistas podem revisar independentemente uma série de radiografias do tórax de pacientes para determinar a presença ou ausência de pneumonia. Para avaliar o grau de concordância entre as classificações dos dois médicos, pode ser relatado o percentual de concordância entre os avaliadores (por exemplo, 50% dos avaliadores responderam \"sim\" nas duas ocasiões). No entanto, esse percentual pode ser enganoso, pois não leva em conta o nível de concordância entre os dois avaliadores que pode ocorrer por acaso. A estatística *kappa* pode ser usada para avaliar a concordância das respostas para dois ou mais avaliadores após considerar a concordância casual. Portanto, a estatística *kappa* é uma estimativa da proporção de concordância entre avaliadores que excede a concordância que ocorreria por acaso.\n\nA interpretação dos valores de *kappa* é mostrada na [@tbl-kappa; @landis1977measurement]. Quando a proporção observada de concordância é menor que a esperada por acaso, o *kappa* terá um valor negativo indicando não concordância. Um valor de *kappa* igual a 0 indica que a concordância observada é igual à concordância casual.\n\nO teste de hipóteses testa a hipótese de que a concordância entre os dois avaliadores seja puramente aleatória. Quando o valor *P* é menor que 0,05, rejeitamos a hipótese de que a concordância foi puramente aleatória. As premissas para o *kappa* de Cohen são que os participantes ou itens a serem classificados são independentes e também que os avaliadores e categorias são independentes.\n\n\n::: {#tbl-kappa .cell tbl-cap='Valor Kappa e nível de concordância'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-b4da1808{}.cl-b4ce118e{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b4ce11a2{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-b4d26c7a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b4d26c84{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-b4d2bd2e{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b4d2bd42{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b4d2bd4c{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b4d2bd56{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b4d2bd57{width:1.101in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-b4d2bd60{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-b4da1808'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-b4d2bd2e\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce118e\">Valor kappa</span></p></th><th class=\"cl-b4d2bd42\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce118e\">Concordância</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd4c\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">&lt;0,00</span></p></td><td class=\"cl-b4d2bd56\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">pobre</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd4c\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">0,00 - 0,20</span></p></td><td class=\"cl-b4d2bd56\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">leve</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd4c\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">0,21 - 0,40</span></p></td><td class=\"cl-b4d2bd56\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">razoável</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd4c\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">0,41 - 0,60</span></p></td><td class=\"cl-b4d2bd56\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">moderada</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd4c\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">0,61 - 0,80</span></p></td><td class=\"cl-b4d2bd56\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">substancial</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-b4d2bd57\"><p class=\"cl-b4d26c84\"><span class=\"cl-b4ce11a2\">0,81 - 1,00</span></p></td><td class=\"cl-b4d2bd60\"><p class=\"cl-b4d26c7a\"><span class=\"cl-b4ce11a2\">quase perfeita</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nExistem diferentes tipos de estatísticas *kappa*. Para dados com três ou mais categorias possíveis (por exemplo, concordo, concordo parcialmente, discordo) ou para dados categóricos ordenados, o *kappa* ponderado deve ser usado para que as respostas que estão mais distantes da concordância tenham maior peso do que aquelas próximas à concordância. No exemplo usado, as categorias possíveis são dicotômicas (sim e não), portanto, o kappa não ponderado (*unweighted*) e o ponderado (*weighted*) retornam o mesmo resultado.\n\n### Dados do exemplo {#sec-exkappa}\n\n::: callout-note\n## Cenário\n\nCinquenta e quatro crianças com suspeita de pneumonia realizaram radiografias de tórax para confirmar o diagnóstico. Essas radiografias foram avaliadas por dois radiologistas.\n:::\n\nO arquivo `dadosPneumonia.xlsx` contém os dados dos diagnósticos independentes dos dois radiologistas. O objetivo foi medir a concordância diagnóstica dos dois profissionais. Para o cálculo do coeficiente *kappa*, será usada a função `Kappa()` do pacote `vcd` [@zeileis2007residual]. Essa função tem os seguintes argumentos:\n\n- **x** $\\longrightarrow$ matriz ou tabela\n- **weights** $\\longrightarrow$ matriz especificada pelo usuário com as mesmas dimensões de *x*, desnecessário para *kappa* não ponderado.\n\nNa impressão do *kappa* pode-se usar `print (k, digits = 3, CI = TRUE, level = 0.95)`. Onde *k* é o coeficiente de *kappa*, calculado pela função `Kappa()`, *CI* é o intervalo de confiança e o nível de confiança padrão é 95%.\n\n#### Leitura e exploração dos dados\n\nO conjunto de dados `dadosPneumonia.xlsx` pode ser obtido [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosPneumonia.xlsx). Após salvar o arquivo em seu diretório, ele pode ser carregado com a função `read_excel()` do pacote `readxl`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosPneumonia.xlsx\")\n```\n:::\n\n\n#### Construção da tabela\n\nO cálculo do *kappa* com a função `Kappa()` exige uma tabela, onde os dados dos dois radiologistas são cruzados. As variáveis a serem cruzadas são `rx1` e `rx2`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$rx1 <- factor(dados$rx1,\n                        ordered=TRUE,\n                        levels = c(\"sim\", \"não\"))                           \ndados$rx2 <- factor(dados$rx2,\n                        ordered=TRUE,\n                        levels = c(\"sim\", \"não\"))\n\ntabk <- with(dados, table(rx1, rx2, dnn = c (\"Radiologista 1\", \"Radiologista 2\")))\naddmargins(tabk, FUN = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMargins computed over dimensions\nin the following order:\n1: Radiologista 1\n2: Radiologista 2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Radiologista 2\nRadiologista 1 sim não sum\n           sim  32   5  37\n           não   3  14  17\n           sum  35  19  54\n```\n\n\n:::\n:::\n\n\n#### Cálculo do *kappa*\n\nO *kappa* é dado pela execução da função:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- vcd::Kappa(tabk)\nprint (k, \n       digits= 3, \n       CI=TRUE, \n       level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           value   ASE    z Pr(>|z|) lower upper\nUnweighted 0.667 0.107 6.21 5.42e-10 0.456 0.878\nWeighted   0.667 0.107 6.21 5.42e-10 0.456 0.878\n```\n\n\n:::\n:::\n\n\nA saída exibe o *kappa* pontual e os intervalos de confiança de 95%, podendo-se concluir, desses resultados, que existe uma boa confiabilidade nos diagnósticos dos radiologistas (k = 0,67, concordância substancial, de acordo com a @tbl-kappa).\n",
    "supporting": [
      "21-testesDiag_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}