{
  "hash": "32ba976f4f6a43db6cd3449a643ced1c",
  "result": {
    "engine": "knitr",
    "markdown": "# Estimação {#sec-estimacao}\n\n## Pacotes necessários\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(DescTools, \n               flextable,\n               knitr,\n               Rmisc, \n               tidyverse)\n```\n:::\n\n\n## Introdução\n\nA estatística inferencial é o ramo da estatística que utiliza resultados amostrais para tomar decisões e tirar conclusões sobre a população da qual a amostra foi extraída. A estimação de parâmetros e os testes de hipóteses, em conjunto, constituem a base da **inferência estatística**.\\\nA estimação é o procedimento pelo qual valores numéricos são atribuídos a um parâmetro populacional com base nas informações de uma amostra. Na inferência, $\\mu$\\$\\\\mu\\$ representa a média populacional e $p$ denota a proporção populacional. Existem diversos outros parâmetros, como mediana, moda, variância, desvio padrão.\\\nSe fosse viável realizar um censo (uma pesquisa que inclua toda a população de interesse), os procedimentos de estimação seriam desnecessários. O cenário seria equivalente ao de uma eleição: basta contar todos os votos para declarar o vencedor. No entanto, na área da saúde, realizar um censo é frequentemente um processo caro, demorado ou virtualmente impossível. Por isso, costuma-se extrair uma amostra da população para calcular as estatísticas amostrais apropriadas. Com base nelas, são atribuídos valores ao parâmetro de interesse.\\\nA função estatística usada para estimar um parâmetro é denominada **estimador**. Assim, a média da amostra, $\\bar{x}$, é o estimador da média populacional, $\\mu$; e a proporção da amostra, $\\hat{p}$, é o estimador da proporção populacional, $p$. Já a estimativa é o valor numérico específico que o estimador assume para uma dada amostra.\\\nA estimação pontual — como usar $\\bar{x}$ para estimar $\\mu$ — é intuitiva e útil, mas tem uma limitação óbvia: **não informa o grau de incerteza associado ao valor estimado**. Duas amostras diferentes, extraídas da mesma população, dificilmente produzirão a mesma média. Assim, confiar apenas em um número único pode transmitir uma falsa sensação de precisão.\n\nPara lidar com essa incerteza, a estatística inferencial introduz um conceito fundamental: **intervalos de confiança (ICs)**.\n\n## O que é um intervalo de confiança?\n\nUm intervalo de confiança é um **intervalo de valores plausíveis** para o parâmetro populacional, construído a partir dos dados amostrais [@altman2005ic]. Ele é composto por:\n\n- uma **estimativa pontual** (por exemplo, $\\bar{x}$ ou $\\hat p$),\n\n- um **erro padrão**, que mede a variabilidade do estimador,\n\n- um **coeficiente crítico**, que depende do nível de confiança desejado.\n\n::: callout-note\n## Fórmula Geral\n\n$$\\text{estimativa pontual} \\ \\pm \\text{coeficiente crítico} \\times \\text{erro padrão}$$\n:::\n\nO $\\text{coeficiente crítico} \\times \\text{erro padrão}$ é conhecido como **margem de erro** (@fig-intconf). O nível de confiança mais comum é 95%, mas nada impede o uso de 90%, 99% ou outros valores, dependendo do contexto.\n\n![Intervalo de Confiança](images/ic95-ic99.png){#fig-intconf fig-align=\"center\" width=\"11cm\"}\n\nA @fig-ic9599 ilustra como o aumento do nível de confiança amplia a margem de erro: o IC de 99% é mais largo do que o de 95%.\n\n![Comparação entre os intervalos de confiança de 95% e 99%](images/ic95-ic99.png){#fig-ic9599 fig-align=\"center\" width=\"11cm\"}\n\n## Intervalo de confiança com $\\sigma$ conhecido\n\nA *margem de erro* para a estimativa da média populacional, $\\mu$, quando se conhece o desvio padrão populacional ,$\\sigma$, e $n \\ge 30$ ou, mesmo que $n < 30$, mas a população de onde amostra foi selecionada tem distribuição normal, é a quantidade que é subtraída ou adicionada ao valor da média da amostra, $\\bar{x}$, para obter o intervalo de confiança para $\\mu$. Desta forma, a margem de erro é igual a:\n\n$$me = z_{(1-\\frac{\\alpha}{2})} \\times \\frac{\\sigma }{\\sqrt{n}}$$\n\nLogo, o intervalo de confiança para a média populacional, $\\mu$, para um nível de confiança (1 - $\\alpha \\times 100$)%, é igual a:\n\n$$IC_{(1-\\alpha)}(\\mu) \\rightarrow  \\bar{x} \\pm  me$$\n\nSe objetivo é construir um intervalo de confiança de 95%, a última equação passa a ser:\n\n$$IC_{(1-\\alpha)}(\\mu) \\rightarrow  \\bar{x} \\pm  z_{(0,975)} \\times me$$\n\nOnde *z* é o valor crítico para o nível de confiança escolhido, obtido da tabela de distribuição normal padrão, e *me* é a margem de erro ($z_{0,975} \\times erro \\quad padrao$). Um intervalo de confiança de 95% significa que a área total sob a curva normal entre dois pontos em torno da média populacional, $\\mu$, é igual a 95%, ou 0,95. A área das caudas é $\\alpha$, ou seja, cada cauda é igual a $\\frac{\\alpha}{2}$ (@fig-twotailed).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição normal padrão com IC de 95%: área central (1 − α = 0,95) e caudas (α/2 = 0,025 cada)](12-estimacao_files/figure-html/fig-twotailed-1.png){#fig-twotailed fig-align='center' width=480}\n:::\n:::\n\n\nPara encontrar o valor de *z* para um nível de confiança de 95%, primeiro encontram-se as áreas à esquerda desses dois pontos, $z_1$ e $z_2$. Esses dois valores de *z* serão iguais, mas com sinais opostos. A área total sob a curva é igual a 1. A área entre $z_1$ e $z_2$ é igual a $1 - \\alpha = 0,95$.\n\nA área a esquerda de $z_1$ é igual a 0,025 e a área a esquerda de $z_2$ é igual a 1 – 0,025 = 0,975. No *R*, os valores $z_1$ e $z_2$ podem facilmente ser obtidos com a função `qnorm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(c(qnorm(0.025),qnorm(0.975)), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.96  1.96\n```\n\n\n:::\n:::\n\n\nDessa maneira, para uma confiança de 95%, é usado um $z = 1.96$, onde:\n\n$$p(-1,96 \\le z \\le 1,96) = 0,95$$\n\nLogo,\n\n$$IC_{95\\%}(\\mu) \\rightarrow  \\bar{x} \\pm  (1.96 \\times \\sigma_{\\bar{x}})$$\n\nou\n\n$$IC_{95\\%}(\\mu) \\rightarrow  \\bar{x} \\pm  (1.96 \\times \\frac{\\sigma}{\\sqrt{n}})$$\n\n### Cálculo do intervalo de confiança com $\\sigma$ conhecido {#sec-dadosic}\n\nSerão usados dados do dataframe `dadosMater.xlsx` [^12-estimacao-1], selecionando as variáveis de interesse (`fumo`, `ig`, `peso_rn`) e filtrando para os recém-nascidos a termo (37 a 41 semanas de idade gestacional):\n\n[^12-estimacao-1]: Os dados podem ser baixados no seu diretório de trabalho a partir do repositório do autor no [GitHub](https://github.com/petronioliveira/Arquivos/blob/main/dadosMater.xlsx).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\namostra1 <- readxl::read_excel(\"dados/dadosMater.xlsx\") |>  \n  dplyr::select(fumo, ig, peso_rn) |> \n  dplyr::filter(ig>=37 & ig<42)  |> \n  dplyr::mutate(fumo = factor(fumo, \n                       levels = c(1,2), \n                       labels = c(\"Fumante\", \"Não fumante\"))) |> \n  dplyr::slice_sample(n = 50)\n```\n:::\n\n\nA partir de uma população de recém-nascidos, cujo desvio padrão ($\\sigma$) é igual a 459,2 g [^12-estimacao-2], foi extraída uma amostra (`amostra1`) de n = 50, média ($\\bar{x}$) de 3335.8g e desvio padrão ($s$) de 512.9. Se forem extraídas outras amostras, espera-se que elas produzam estimativas diferentes da `amostra1`. Assim, o valor atribuído a média populacional, com base em uma **estimativa pontual** depende de qual das amostras está sendo usada. Consequentemente, a estimativa pontual atribui um valor a $\\mu$ que quase sempre difere da mesma.\n\n[^12-estimacao-2]: A média da população também é conhecida ($\\mu = 3218g$), vai-se ignorar, por questões didáticas, este fato.\n\n[Dados do exemplo para o cálculo]{.underline}\n\nCom 95% de confiança a margem de erro é igual ao $z_{crítico}$ vezes o erro padrão da média:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n n <- 50\n x_barra <- mean(amostra1$peso_rn)\n sigma <- 459.2 \n me <- 1.96 * sigma/sqrt(n)\n  round(me, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 127.28\n```\n\n\n:::\n:::\n\n\nBasta, agora, adicionar e subtrair a margem de erro da média:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlim_inf <- x_barra - me\nlim_sup <- x_barra + me\n\nround(c(lim_inf, lim_sup), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3208.52 3463.08\n```\n\n\n:::\n:::\n\n\nAssim, tem-se uma confiança de 95% de que a verdadeira média, esteja incluída no intervalo. O nome para isso é *intervalo de confiança de 95% para a média populacional*.\n\n### Função para o cálculo o IC com $\\sigma$ conhecido\n\nO cálculo manual é simples, mas enfadonho, nos tempos dos computadores. Em decorrência, como o R não tem uma função para encontrar os intervalos de confiança para a média de dados com distribuição normal quando o desvio padrão da população é conhecido, foi criada uma função (`ic_z [meuPacote]`) para cumprir essa ação. Esta função, criada pelo autor, encontra-se no pacote `meuPacote`, que pode ser instalado a partir do `GitHUb`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nremotes::install_github(\"petronioliveira/meuPacote\")\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n* checking for file 'C:\\Users\\petro\\AppData\\Local\\Temp\\RtmpcrXvOe\\remotes577c500a876\\petronioliveira-meuPacote-be9fe1d/DESCRIPTION' ... OK\n* preparing 'meuPacote':\n* checking DESCRIPTION meta-information ... OK\n* checking for LF line-endings in source and make files and shell scripts\n* checking for empty or unneeded directories\n* building 'meuPacote_0.1.0.tar.gz'\n```\n\n\n:::\n\n```{.r .cell-code}\n# Ou alternativamente\n#install.packages(\"pak\")\n#pak::pak(\"petronioliveira/meuPacote\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeuPacote::ic_z(amostra1$peso_rn,sigma = 459.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95%: [3208.5 ; 3463.1] \n```\n\n\n:::\n:::\n\n\n### Interpretação do intervalo de confiança\n\nSe fossem extraídas todas as possíveis amostras de *n* = 50 da população de recém-nascidos a termo e construído para cada uma delas um intervalo de confiança de 95% em torno de cada média amostral, espera-se que 95% desses intervalos incluirão a média populacional e 5% não incluirão. O IC95% informa sobre a *precisão* com que a média amostral estima a média populacional desconhecida [^12-estimacao-3].\n\n[^12-estimacao-3]: A media populacional de onde foi extraída a amostra1 é igual a 3218g. Sabe-se porque foi usada uma população conhecida por uma questão didática. A regra é não se conhecer a média populacional, razão da importância do intervalo de confiança\n\nNa @fig-vinte, são mostradas 20 amostras diferentes de tamanho *n* = 50, dessa população. Junto aparecem os intervalos de confiança de 95% construídos em torno dessas amostras. Observa-se que apenas uma amostra (em vermelho)[^12-estimacao-4] não inclui a média populacional (linha tracejada vertical em azul). Pode-se afirmar com 95% de confiança que se forem extraídas muitas amostras do mesmo tamanho de uma população e construído intervalos de confiança de 95% em torno das médias dessas amostras, 95% desses intervalos de confiança incluirão a média populacional.\n\n[^12-estimacao-4]: Entretanto, aleatoriamente, poderiam aparecer mais de uma.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Intervalos de confiança de 95% que mostra 20 replicações simuladas de amostras de n = 50 do peso do recém-nascido. Apenas um intervalo (em vermelho) não inclui a média populacional (linha vertical azul)](12-estimacao_files/figure-html/fig-vinte-1.png){#fig-vinte fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n::: callout-warning\n## O que o IC **não** significa\n\nÉ frequente a interpretação equivocada dos intervalos de confiança. O IC95% **não** significa que há 95% de probabilidade de a média populacional estar dentro do intervalo calculado — $\\mu$ é um valor fixo (embora desconhecido), não uma variável aleatória.\n\nO correto é: **se o mesmo procedimento fosse repetido muitas vezes**, 95% dos intervalos construídos dessa forma conteriam a verdadeira média populacional. O intervalo que calculamos *pode ou não* conter $\\mu$ — mas foi obtido por um método que acerta em 95% das vezes.\n:::\n\n### Exercício 1 {.unnumbered}\n\n::: callout-note\n## Exercício — IC com $\\sigma$ conhecido\n\nA partir da `amostra1`, calcule o intervalo de confiança para a **idade gestacional média** dos recém-nascidos a termo. Registros históricos da mesma maternidade indicam que o desvio padrão populacional é $\\sigma = 1{,}2$ semanas.\n\n1.  Qual é a margem de erro com 95% de confiança?\n2.  Construa também o IC de 99% e compare a largura dos dois intervalos. O que muda e por quê?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\n# 1. IC de 95%\nmeuPacote::ic_z(amostra1$ig, sigma = 1.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95%: [38.8 ; 39.5] \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\n# 2. IC de 99% — margem de erro maior, intervalo mais largo\nmeuPacote::ic_z(amostra1$ig, sigma = 1.2, conf_level = 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 99%: [38.7 ; 39.6] \n```\n\n\n:::\n:::\n\n\nElevar o nível de confiança de 95% para 99% aumenta o coeficiente crítico de $z = 1{,}96$ para $z = 2{,}58$, ampliando a margem de erro em cerca de **32%**. Maior confiança implica menor precisão — não há como ter as duas simultaneamente sem aumentar o tamanho amostral.\n\n## Cálculo do intervalo de confiança com $\\sigma$ desconhecido\n\nNa prática, a regra é $\\sigma$ ser desconhecido e precisa ser estimado pela amostra e a estimação da média populacional ($\\mu$) é feita usando a **distribuição *t* de Student**. Em amostras pequenas ($\\le 30$), usar o modelo normal para construir intervalos de confiança, pode gerar um erro, pois os pressupostos do teorema do limite central não são respeitados. Dessa forma, a distribuição de Student também deve ser usada.\n\n### Distribuição *t* de Student {#sec-dist_t}\n\nA distribuição *t*, desenvolvida por *William Sealy Gosset*, em 1908, é semelhante à distribuição normal. Como a curva de distribuição normal, a curva de distribuição *t* é unimodal, simétrica (em forma de sino) em torno da média e nunca encontra o eixo horizontal. A área total sob uma curva de distribuição *t* é 1 ou 100%. A curva da distribuição *t* é mais plana do que a curva de distribuição normal padrão. Em outras palavras, ela é mais achatada e mais espalhada. No entanto, conforme o tamanho da amostra aumenta, a distribuição *t* aproxima-se da distribuição normal padrão.\n\nO formato de uma curva de distribuição *t* particular depende do número de graus de liberdade. O número de graus de liberdade (*gl*) para uma distribuição *t* é igual ao tamanho da amostra menos um, ou seja, $gl=n-1$, veja @sec-variancia.\n\nO número de graus de liberdade é o único parâmetro da distribuição *t*. Há uma diferente distribuição *t* para cada número de graus de liberdade, portanto, a distribuição *t* se constitui em uma família de distribuições (@fig-familia).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Curvas de distribuição t conforme o grau de liberdade comparadas à distribuição normal](12-estimacao_files/figure-html/fig-familia-1.png){#fig-familia fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nDa mesma maneira que a distribuição normal padrão, a média da distribuição padrão *t* é 0. Entretanto, ao contrário da distribuição normal padrão, cujo desvio padrão é 1, o desvio padrão de uma distribuição *t* é $\\sqrt{\\frac{gl}{gl-2}}$ , para *gl* \\> 2, sempre é maior do que 1. Assim, o desvio padrão de uma distribuição *t* é maior do que o desvio padrão da distribuição normal padrão.\\\nOs valores de ${t}_{crítico}$ podem ser obtidos usando a função `qt()` que usa os seguintes argumentos:\n\n- **p** $\\to$ probabilidade, igual a $1 - \\frac{\\alpha}{2}$, considerando-se bicaudal e $1 - \\alpha$ quando unicaudal;\n- **df** $\\to$ graus de liberdade;\n- **lower.tail** $\\to$ lógico; se TRUE, informa a probabilidade da cauda inferior. O padrão é TRUE.\n\nAssim, o valor do ${t}_{crítico}$ para $gl=10$ é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha  <-  0.05\np <- 1 - (alpha/2)\ngl = 10\nt <- qt(p = p, df = 10, lower.tail = TRUE)\nround(t, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.23\n```\n\n\n:::\n:::\n\n\nA área compreendida entre $\\pm$ 2.23 é igual a 95% (@fig-bilateral):\n\n$$p(-2,23\\le t\\le 2,23)=0,95$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição t com gl = 10, bilateral](12-estimacao_files/figure-html/fig-bilateral-1.png){#fig-bilateral fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nQuando se considera apenas uma das caudas (unicaudal ou unilateral), o valor do ${t}_{crítico}$ para $gl=10$ é\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- qt(p = 0.95, df = 10, lower.tail = TRUE)\nround(t1, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.81\n```\n\n\n:::\n:::\n\n\nAssim, a área abaixo de 1.81 é igual a 95% (@fig-unilateral).\n\n$$p(t \\le 1,81)=0,95$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição t com gl = 10, unilateral](12-estimacao_files/figure-html/fig-unilateral-1.png){#fig-unilateral fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n### Cálculo do intervalo de confiança com $\\sigma$ desconhecido\n\nSerão utilizados os mesmos dados do cálculo do intervalo de confiança com desvio padrão conhecido [^12-estimacao-5] , obtidos na @sec-dadosic. Os dados serão atribuídos à `amostra2` .\n\n[^12-estimacao-5]: Os valores são conhecidos, mas serão ignorados, por enquanto, imagine que eles não existem.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\namostra2 <- readxl::read_excel(\"dados/dadosMater.xlsx\") |>  \n  dplyr::select(ig, peso_rn) |> \n  dplyr::filter(ig>=37 & ig<42) |> \n  dplyr::slice_sample(n = 50)\n\nx_barra2 <- mean(amostra2$peso_rn, na.rm = TRUE)\ndp2 <- sd(amostra2$peso_rn, na.rm = TRUE)\nprint(round(c(x_barra2, dp2),3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3335.800  512.925\n```\n\n\n:::\n:::\n\n\nA maneira mais intuitiva de estimar a média da população com base na amostra, é, simplesmente, calcular a média e o desvio padrão. Entretanto, para uma maior precisão, é sempre importante calcular o intervalo de confiança.\n\n#### Cálculo manual do IC\n\nO desvio padrão da amostra ($s$) será usado no lugar do desvio padrão da população ($\\sigma$) quando este não é conhecido, respeitando os pressupostos [@motulsky2010ci]. Então, o erro padrão da média ($\\sigma_{\\bar{x}}$) pode ser estimado pelo $EP_{\\bar{x}}$.\n\n$$EP_{\\bar{x}}=\\frac{s}{\\sqrt{n}}$$\n\nO intervalo de confiança para a $\\mu$ para um nível de confiança (*NC*) de $(1 – \\alpha) \\times100$% é igual a:\n\n$$IC_{NC}(\\mu)\\rightarrow \\bar{x} \\pm \\left(t_{\\left(1-\\frac{\\alpha}{2},\\, gl\\right)} \\times \\frac{s}{\\sqrt{n}}\\right)$$\n\nQuando o tamanho amostral é grande, o valor de *t* se aproxima do valor de *z*, portanto, em situações em que não se conhece o desvio padrão populacional, não há muita diferença se houver uma aproximação de *t* para *z* (@tbl-tabtz).\n\n\n::: {#tbl-tabtz .cell tbl-cap='Comparação dos valores z e t(gl)'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-8611281c{}.cl-86060f4a{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-86060f5e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-860a5186{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-860a91be{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-860a91c8{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-860a91d2{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-8611281c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-860a91be\"><p class=\"cl-860a5186\"><span class=\"cl-86060f4a\">n</span></p></th><th class=\"cl-860a91be\"><p class=\"cl-860a5186\"><span class=\"cl-86060f4a\">gl</span></p></th><th class=\"cl-860a91be\"><p class=\"cl-860a5186\"><span class=\"cl-86060f4a\">z</span></p></th><th class=\"cl-860a91be\"><p class=\"cl-860a5186\"><span class=\"cl-86060f4a\">t</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">5</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">4</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">2.57</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">10</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">9</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">2.23</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">30</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">29</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">2.04</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">50</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">49</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">2.01</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">100</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">99</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.98</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">200</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">199</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.97</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">500</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">499</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91c8\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-860a91d2\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1,000</span></p></td><td class=\"cl-860a91d2\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">999</span></p></td><td class=\"cl-860a91d2\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td><td class=\"cl-860a91d2\"><p class=\"cl-860a5186\"><span class=\"cl-86060f5e\">1.96</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA `amostra2` de *n* = 50, $\\overline x$ = 3335.8g e $s$ = 512.925g. Essas estimativas servirão para o cálculo do intervalo de confiança, usando uma distribuição *t* bicaudal e um nível de significância $\\alpha = 0,05$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <-  length(amostra2$peso_rn)\nalpha <- 0.05\np <- 1 - alpha/2\n# Graus de liberdade  \ngl <- n - 1\n# Valor t crítico  \ntc <-  qt(p, gl, lower.tail = TRUE)\n# Erro padrão\nEP <- round(dp2/sqrt(n),3)\nprint(round(c(tc, EP),3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2.010 72.539\n```\n\n\n:::\n:::\n\n\nCom esses dados, calcula-se o intervalo de confiança de 95%:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nme2 <- tc * EP\nlim_inf2 <- x_barra2 - me2\nlim_sup2 <- x_barra2 + me2\nic95 <- c(lim_inf2, lim_sup2)\nround(ic95, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3190.03 3481.57\n```\n\n\n:::\n:::\n\n\n#### Cálculo usando uma função do R\n\nO R possui algumas funções que calculam o intervalo de confiança para variáveis numéricas, baseadas na distribuição *t*. Entre elas, a função `MeanCI()`, incluída no pacote `DescTools` [@signorell2025desctools]. Leia mais sobre a função na ajuda (?DescTools::MeanCI()).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDescTools::MeanCI(amostra2$peso_rn, conf.level = 0.95, \n                  sides = \"two.sided\", method = \"classic\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    mean   lwr.ci   upr.ci \n3335.800 3190.028 3481.572 \n```\n\n\n:::\n:::\n\n\nComo alternativa, a função `ic_t()` do `meuPacote` produz o mesmo resultado com saída detalhada:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeuPacote::ic_t(amostra2$peso_rn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95%: [3190.0 ; 3481.6] \n```\n\n\n:::\n:::\n\n\n### Exercício 2 {.unnumbered}\n\n::: callout-note\n## Exercício — IC com $\\sigma$ desconhecido\n\nUsando a `amostra1`, compare o IC95% do **peso ao nascer** entre recém-nascidos de mães **não fumantes** e **fumantes**.\n\n1.  Calcule os dois intervalos com `ic_t()`.\n2.  O que a diferença de largura entre os intervalos revela sobre o papel do tamanho amostral?\n3.  Com base nos intervalos, há evidência de diferença no peso médio entre os grupos?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nnao_fumantes <- amostra1 |> dplyr::filter(fumo == \"Não fumante\")\nfumantes     <- amostra1 |> dplyr::filter(fumo == \"Fumante\")\n\ncat(\"Não fumantes (n =\", nrow(nao_fumantes), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNão fumantes (n = 41 )\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nmeuPacote::ic_t(nao_fumantes$peso_rn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95%: [3193.7 ; 3530.7] \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\ncat(\"Fumantes (n =\", nrow(fumantes), \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFumantes (n = 9 )\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nmeuPacote::ic_t(fumantes$peso_rn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95%: [2902.0 ; 3529.1] \n```\n\n\n:::\n:::\n\n\nO IC das fumantes é substancialmente mais largo porque o grupo tem apenas 9 observações — o desvio padrão amostral aumenta e o valor $t_{crítico}$ cresce com poucos graus de liberdade. Como os dois intervalos se sobrepõem, **não há evidência suficiente** para concluir diferença significativa com apenas esses dados.\n\n## Intervalo de Confiança para uma proporção populacional\n\n### Cálculo do intervalo de confiança para a proporção {#sec-ICproporcao}\n\nOs dados extraidos para constituir `amostra1` (@sec-dadosic) servirão, utilizando a variável fumo, para os cálculos do intervalo de confiança de uma proporção.\n\n**Cálculo da estimativa pontual da proporção de fumantes**\n\nNa `amostra1`, a proporção de fumantes é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab <- table(amostra1$fumo)\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Fumante Não fumante \n          9          41 \n```\n\n\n:::\n\n```{.r .cell-code}\ntabFumo <- round (prop.table (tab), 3)\ntabFumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Fumante Não fumante \n       0.18        0.82 \n```\n\n\n:::\n:::\n\n\nA proporção de mulheres fumantes na `amostra1` é igual a 18%.\n\n**Cálculo manual com aproximação normal**\n\n*1ª etapa*: verificar a premissa de que quando a proporção populacional é desconhecida a proporção pontual ($\\hat p$) e o seu complemento ($\\hat q = 1 - \\hat p$) multiplicados, cada um, por $n$, devem ser maior do que 5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(amostra1$fumo)\ntabFumo[1]*n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFumante \n      9 \n```\n\n\n:::\n\n```{.r .cell-code}\n(1 - tabFumo[1])*n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFumante \n     41 \n```\n\n\n:::\n:::\n\n\nComo se observa, ambos os valores são maiores do que 5.\n\n*2ª Etapa*: O intervalo pode ser estimado pela distribuição normal e é necessário calcular o *z_crítico*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha <- 0.05\np <-  1 - alpha/2\nzc <- qnorm (p, mean = 0, sd = 1)\nround(zc, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.96\n```\n\n\n:::\n:::\n\n\n*3ª Etapa*: Cálculo do erro padrão da proporção ($\\sqrt \\frac {\\hat p \\times \\hat q}{n}$) e da margem de erro:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extração da proporção amostral do tabFumo\nprop <- tabFumo [1]\n\n# Cálculo do EP amostral\nEP <- sqrt((prop * (1 - prop))/n)\n\n# Cálculo da margem de erro(me)\nme <- zc * EP\n\n# dados necessários para o cálculo do IC95%\nprint(c(prop, me), digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFumante Fumante \n  0.180   0.106 \n```\n\n\n:::\n:::\n\n\n*4ª Etapa*: Intervalo de confiança\n\n\n::: {.cell}\n\n```{.r .cell-code}\nic_prop <- c((prop - me), (prop + me))\nround(ic_prop, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFumante Fumante \n  0.074   0.286 \n```\n\n\n:::\n:::\n\n\n**Cálculo usando uma função**\n\nO chamado *Intervalo de Confiança Exato* corrigem as deficiências da aproximação normal. O R tem uma função para este cálculo: `BinomCI()` do pacote `DescTools` [@signorell2025desctools]. É preferível usar o método de Clopper e Pearson que fornece o IC exato.\n\nOs argumentos da função `BinomCI()` são:\n\n- **x** $\\to$ é o número de desfechos, sucessos;\n- **n** $\\to$ é o tamanho da amostra, número de ensaios;\n- **p** $\\to$ probabilidade, hipótese nula; se ignorada o padrão é 0,50;\n- **conf.level** $\\to$ nível de confiança, o padrão é 0.95;\n- **method** $\\to$ possui vários métodos para calcular intervalos de confiança para uma proporção binomial como: “clopper-pearson” (exact interval), \"wilson\", \"wald\", \"agresti-coull\", \"jeffreys\", \"modified wilson\", \"modified jeffreys\", \"arcsine\", \"logit\", \"witting\", \"pratt\". O método padrão é o de “wilson”. Qualquer outro método, há necessidade de solicitar;\n- **sides** $\\to$ hipótese alternativa padrão “two.sided” (bilateral), mas pode ser “right” ou “left” (unilateral a direita ou a esquerda, respectivamente).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <-  tab[1]\nIC <- BinomCI (x, \n               n, \n               conf.level = 0.95, \n               method = \"clopper-pearson\")\nround(IC, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      est lwr.ci upr.ci\n[1,] 0.18  0.086  0.314\n```\n\n\n:::\n:::\n\n\nObserve que existe uma pequena diferença entre os valores da aproximação normal e o exato, com o método de “clopper-pearson”\n\n### Exercício 3 {.unnumbered}\n\n::: callout-note\n## Exercício — IC para uma proporção\n\nExtraia uma amostra maior (`amostra3`, $n = 200$) do mesmo banco de dados (`dadosMater.xlsx`), restrita a recém-nascidos a termo.\n\n1.  Qual é a proporção estimada de mães fumantes?\n2.  Calcule o IC de 95% pelo método exato de Clopper-Pearson.\n3.  Recalcule para 99% e compare a largura dos dois intervalos.\n4.  A premissa de usar a aproximação normal ($n\\hat{p} > 5$ e $n\\hat{q} > 5$) é satisfeita?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nset.seed(5271)\namostra3 <- readxl::read_excel(\"dados/dadosMater.xlsx\") |>\n  dplyr::select(fumo, ig) |>\n  dplyr::filter(ig >= 37 & ig < 42) |>\n  dplyr::mutate(fumo = factor(fumo,\n                              levels = c(1, 2),\n                              labels = c(\"Fumante\", \"Não fumante\"))) |>\n  dplyr::slice_sample(n = 200)\n\ntab3  <- table(amostra3$fumo)\nprop3 <- tab3[1] / sum(tab3)\n\n# 4. Verificação da premissa da aproximação normal\ncat(\"n * p_hat =\", round(sum(tab3) * prop3),\n    \"| n * q_hat =\", round(sum(tab3) * (1 - prop3)), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn * p_hat = 33 | n * q_hat = 167 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\n# 2. IC 95% — método exato\ncat(\"IC 95% (Clopper-Pearson):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIC 95% (Clopper-Pearson):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nprint(round(DescTools::BinomCI(tab3[1], sum(tab3),\n                               conf.level = 0.95,\n                               method = \"clopper-pearson\"), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       est lwr.ci upr.ci\n[1,] 0.165  0.116  0.224\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\n# 3. IC 99%\ncat(\"\\nIC 99% (Clopper-Pearson):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nIC 99% (Clopper-Pearson):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Ver solução\"}\nprint(round(DescTools::BinomCI(tab3[1], sum(tab3),\n                               conf.level = 0.99,\n                               method = \"clopper-pearson\"), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       est lwr.ci upr.ci\n[1,] 0.165  0.104  0.243\n```\n\n\n:::\n:::\n\n\nCom $n = 200$, ambas as premissas da aproximação normal são satisfeitas. O IC de 99% é cerca de **25% mais largo** que o de 95%, ilustrando a mesma relação entre confiança e precisão observada nos exercícios anteriores — agora aplicada a proporções.\n",
    "supporting": [
      "12-estimacao_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}