{
  "hash": "ce4bbe7cda9815c49b1866e61d3ff711",
  "result": {
    "engine": "knitr",
    "markdown": "# Introdução à Teoria das Probabilidades {#sec-probabilidades}\n\n## Pacotes necessários neste capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(dplyr, readxl, scales, ggplot2)\n```\n:::\n\n\n## Introdução\n\nA teoria das probabilidades é a base sobre a qual a estatística é desenvolvida. Os jogos de azar deram um grande impulso ao conhecimento da moderna teoria das probabilidades, principalmente, pelo trabalho de Blaise Pascal (1623-1662), em parceria com Pierre de Fermat (1601-1665). Eles foram estimulados por um escritor francês e matemático amador, Antoine Gombaud (1607-1684), conhecido como Chevalier de Méré, que era muito interessado em jogos de azar [@debnath2015short].\n\nA Teoria das probabilidades permite que seja possível modelar populações, experimentos ou qualquer situação que possa ser considerada aleatória. Estes modelos possibilitam fazer inferência sobre populações a partir da observação de uma amostra dessa população. Ao usar apenas uma parte da população, inevitavelmente, é cometido um erro, o **erro amostral**. Este erro amostral pode ser dimensionado pela teoria das probabilidades.\n\nExistem duas interpretações alternativas de probabilidades: a **frequentista** e a **bayesiana** [@menezes2004probabilidade]. Neste livro, será discutida, basicamente, a definição de probabilidade frequentista. O processo bayesiano de formulação de um modelo probabilístico faz uso do conhecimento subjetivo, estabelecendo uma especificação **a priori**, combinado com a informação objetiva ou empírica. A teoria bayesiana é a estrutura integradora dessas duas fontes de informação, derivando como resultado a distribuição **a posteriori** dos parâmetros de interesse. Na @sec-diagbayes, sobre análise de testes diagnósticos, serão abordados alguns aspectos relacionados à teoria bayesiana em medicina.\n\n## Processo aleatório\n\nUm processo ou experimento é dito **aleatório** quando em uma situação se sabe quais os resultados que podem acontecer, mas não se sabe qual resultado particular irá acontecer. Por exemplo, quando uma moeda é lançada, se conhece que a probabilidade de o desfecho `cara` ocorrer é de 50%, mas se desconhece o que irá ocorrer até que a moeda esteja no chão.\n\nO número de caras que podem surgir em vários lançamentos da moeda é chamado de **variável aleatória**, ou seja, uma variável que pode assumir mais de um valor com determinadas probabilidades [@pagano2000random]. Da mesma forma, um dado lançado pode mostrar seis faces, numeradas de um a seis, com igual probabilidade de 16,7%. Portanto, quando a probabilidade é associada a todos os conjuntos de valores possíveis de uma variável, diz-se que ela é aleatória. O conjunto de todos os possíveis resultados de um experimento aleatório é denominado **espaço amostral**.\n\nNa área da saúde, trabalha-se com uma infinidade de variáveis aleatórias, por exemplo, o número de filhos de uma mulher, o número de mortos diários em uma epidemia, o número de vacinados em uma campanha, etc. Essas variáveis são variáveis aleatórias discretas, pois apenas permitem ser quantificadas por processo de contagem. Por outro lado, o peso ou a altura de uma mulher são ditos variáveis aleatórias contínuas, pois podem assumir qualquer valor real entre uma medida e outra, dependendo da precisão do aparelho usado.\n\nEm geral, variáveis aleatórias são representadas por letras maiúsculas, como X, Y e Z e sua probabilidade, por exemplo, pode ser denotada por: $P(X)$.\n\n## Definição frequentista\n\nA probabilidade se relaciona a eventos futuros ou que ainda não ocorreram, desta forma a probabilidade pode ser entendida como uma medida de incerteza em relação ao evento. A probabilidade de um evento ocorrer, em determinadas circunstâncias, pode ser definida como a proporção de vezes que o evento é observado quando o experimento é repetido um número infinitamente grande de vezes [@menezes2004probabilidade]. Pode-se dizer que a visão frequentista define a probabilidade como uma **frequência de longo prazo**.\n\nA chamada **Lei dos Grandes Números** diz que à medida que múltiplas observações são coletadas, a proporção observada de ocorrências de um determinado desfecho, após *n* ensaios, converge para a probabilidade real P desse desfecho. Ou seja, quanto mais vezes for repetido uma experiência, a melhor estimativa de probabilidade tende a ocorrer. Suponha que seja lançada uma moeda honesta repetidas vezes. Por definição, essa é uma moeda que tem $P(cara)=0,5$. O que se observaria? O autor fez 20 lançamentos seguidos com uma mesma moeda e obteve o seguinte resultado, onde 1 = cara (@fig-moeda20):\n\n![Vinte lançamentos consecutivos de uma moeda onde P(cara) = 0,5 e 1 = sucesso.](images/moeda_20.png){#fig-moeda20 fig-align=\"center\" width=\"16.5cm\" height=\"1.4cm\"}\n\nNeste caso, 10 (50%) desses lançamentos resultaram em cara. Agora, suponha que foram feitos registros do número de caras ($n_1$) dos primeiros lançamentos (*N*) e calculadas as proporções de caras ($n_1⁄N$) todas as vezes. O resultado está na @fig-propmoeda.\n\n![Proporção de caras (n/N) em cada um dos 20 lançamentos](images/moeda_proporcao_20.png){#fig-propmoeda fig-align=\"center\" width=\"16.5cm\"}\n\nObserva-se, nessa sequência, que a proporção de caras flutua muito, variando de 0,17 a 0,75. Se o número de lançamentos for aumentando tem-se a sensação de que a proporção se aproxima da \"correta\". Por exemplo, com 100 jogadas, obteve-se 53 caras (0,53); com 150 jogadas, 79 (0,53) e com 200 jogadas, 111 (0,56). Quando N se aproximar do infinito ($N \\to\\infty$) a proporção de caras convergirá para 0,50. A definição frequentista de probabilidade segue essa definição. Ninguém consegue um número infinito de lançamentos de moedas, mas um computador pode simular milhares de lançamentos. A @fig-nmoeda mostra o que acontece com a proporção $n_1⁄N$ à medida que *N* aumenta em lançamentos de moedas. As simulações foram repetidas 4 vezes somente para ter certeza de que o que aconteceu não foi obra do acaso.\n\n![Proporção de caras à medida que o N aumenta em lançamentos de moedas.](images/moeda_prop_caras.png){#fig-nmoeda fig-align=\"center\" width=\"17cm\"}\n\nEmbora nenhuma das simulações tenha realmente terminado com um valor exato de 0,5, elas se aproximaram, oscilando muito pouco em torno desse valor.\n\n### Aplicando a visão frequentista no dia a dia {#sec-aplicafreq}\n\nA definição frequentista também pode ser aplicada no cotidiano. Utilizando a altura de 1368 mulheres, uma medida numérica contínua, incluída no conjunto de dados `dadosMater.xlsx` (veja @sec-dadosMater). Essas alturas serão selecionadas e colocadas em um objeto, denominado `dados`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel(\"dados/dadosMater.xlsx\") |>\n  dplyr::select(altura)\n```\n:::\n\n\nUsando a função `summary()`, será feito um resumo da variável `altura`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(dados$altura)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.400   1.550   1.600   1.598   1.650   1.850 \n```\n\n\n:::\n:::\n\n\nA mediana da altura das gestantes é 1.6 m. Em um longo conjunto de sorteios, a probabilidade de uma mulher ter altura acima deste valor é 50%. O percentil 75 (3º quartil) é igual a 1.65 m, a probabilidade de estar acima deste valor, portanto, é 25%. É possível encontrar a probabilidade de a altura estar acima, abaixo ou entre quaisquer valores. Quando se faz a mensuração de uma variável contínua, fica-se limitado ao método usado. Portanto, quando se diz que uma mulher tem 160 cm, significa dizer que está entre 159,5 e 160,5 cm, dependendo da precisão do instrumento de medição. Dessa maneira, o interesse está na probabilidade de a variável aleatória assumir valores entre certos limites.\n\nA probabilidade de encontrar um valor exatamente igual à média (159.8 cm) é, teoricamente, **igual a zero**. Essa é uma propriedade fundamental das distribuições contínuas: como os valores podem assumir qualquer número real em um intervalo, nenhum ponto isolado tem probabilidade positiva — apenas intervalos têm. Para ilustrar, pode-se calcular a probabilidade em um intervalo extremamente estreito em torno da média[^09-probabilidades-1]:\n\n[^09-probabilidades-1]: Hospital Geral de Caxias do Sul, Hospital de Ensino da Universidade de Caxias do Sul, RS\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmedia <- mean(dados$altura, na.rm = TRUE)\nepsilon <- 1e-6   # intervalo de ±0,000001 m\np_pontual <- pnorm(media + epsilon, mean = media, sd = sd(dados$altura, na.rm = TRUE)) -\n             pnorm(media - epsilon, mean = media, sd = sd(dados$altura, na.rm = TRUE))\np_pontual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.218541e-05\n```\n\n\n:::\n:::\n\n\nMesmo em um intervalo de apenas 0,000001 m em torno da média, a probabilidade é muito próxima de zero. À medida que o intervalo se aproxima de zero, a probabilidade converge exatamente para zero. É por isso que, para variáveis contínuas, trabalha-se sempre com probabilidades associadas a intervalos, nunca a valores exatos.\n\n## Propriedades das probabilidades\n\nAs seguintes propriedades simples decorrem da definição de probabilidade.\n\nSendo `E` um evento aleatório, a $P[E]$ está entre 0 e 1, ou seja $0\\le P[E]\\le 1$. Quando o evento certamente não ocorre, a probabilidade é 0, quando sempre ocorre a probabilidade é 1. Quando a probabilidade for igual a 0,50 tem-se máxima incerteza.\n\n1.  *Regra de adição (regra do \"ou\")*\n\nDois eventos A e B são mutuamente exclusivos, ou seja, quando A acontece, B não pode acontecer. Então, a probabilidade de que um ou outro aconteça é a soma de suas probabilidades. Por exemplo, um dado lançado pode mostrar um ou dois, mas não ambos. A probabilidade de mostrar um ou dois é igual a $1/6 + 1/6 = 1/3$.\n\n$$P[A ou B]=P[A]+P[B]$$\n\nSe A e B não são mutuamente exclusivos, ou seja, quando A acontece pode também ocorrer B. Por exemplo, o nascimento de uma menina pode ser concomitante com o fato de ser branca.\n\n$$P[A ou B]=P[A]+P[B]-P[A \\space e \\space B]$$\n\n2.  *Regra de multiplicação (regra do \"e\")*\n\nSuponha que dois eventos (A e B) sejam independentes, ou seja, saber que um aconteceu não nos diz nada sobre se o outro aconteceu. Então, a probabilidade de que ambos aconteçam é o produto de suas probabilidades. Por exemplo, suponha que jogamos duas moedas. Uma moeda não influencia a outra, portanto os resultados dos dois lançamentos são independentes e a probabilidade de ocorrerem duas caras é 0,50 × 0,50 = 0,25.\n\n$$P[A \\quad e\\quad B]=P[A]×P[B]$$\n\nSe os eventos são dependentes, a probabilidade que ambos aconteçam é igual a:\n\n$$P[A \\quad e \\quad B]=P[A]×P[B \\rvert A]$$ Com essas propriedades simples e outras mais complexas, é possível construir algumas ferramentas matemáticas extremamente poderosas, mas isso não faz parte do objetivo deste livro e não se entrará em detalhes.\n\n## Distribuição de Probabilidades {#sec-distprob}\n\nUm conjunto de eventos que são mutuamente excludentes e que inclui todos os eventos que podem acontecer, é chamado de exaustivo. A soma de suas probabilidades é 1. O conjunto dessas probabilidades constitui uma *distribuição de probabilidade*.\n\nExistem diversos modelos probabilísticos que procuram descrever vários tipos de variáveis aleatórias discretas ou contínuas. Estas distribuições também são chamadas de *modelos probabilísticos estocásticos* que são definidas por duas funções matemáticas: a *função de probabilidade* (fp) para variáveis discretas, que atribui a cada valor a sua probabilidade de ocorrência (`P(X=x`)) e *função densidade de probabilidade* (`fdp`) para variáveis contínuas.\n\nA função de probabilidade é a função que atribui probabilidades a cada um dos possíveis valores da variável aleatória discreta, usando, em geral, as frequências relativas, apresentadas em uma tabela de frequência. O *modelo de Bernoulli* ou *Binomial* e o *modelo de Poisson* são exemplos de modelo probabilístico de variáveis discretas.\n\nA função densidade de probabilidade é a função que atribui probabilidade a qualquer intervalo de número reais, ou seja, um conjunto de valores não enumerável (infinito). Não é possível atribuir probabilidades para um determinado valor, é possível apenas para um intervalo. Por exemplo, o peso dos recém-nascidos. Para atribuir probabilidade a intervalos de valores é utilizada uma função e as probabilidades são representadas por áreas. Existem diversos modelos contínuos de probabilidade, mas o mais importante deles, é o *modelo normal*, também conhecido como *modelo gaussiano*.\n\n## Distribuição Normal {#sec-normal}\n\nO *modelo probabilístico normal* ou *gaussiano* é extremamente importante em estatística, pois serve como um fundamento para técnicas de inferência. Variáveis como os pesos dos recém-nascidos a termo, as alturas das mulheres adultas, a renda familiar em reais e muitas outras variáveis, na natureza, se ajustam ao modelo da distribuição normal.\n\nO modelo de distribuição normal sempre descreve uma curva simétrica, unimodal e em forma de sino (@fig-curvanormal).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Curva Normal](09-probabilidades_files/figure-html/fig-curvanormal-1.png){#fig-curvanormal fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nUma distribuição normal é descrita por meio de dois parâmetros: a média da distribuição $\\mu$ e o desvio padrão da distribuição $\\sigma$. Em função dessa informação, observe como a distribuição normal funciona se esses parâmetros forem alterados.\n\nComo é fácil prever, alterar a média desloca a curva de sino para a esquerda ou para a direita, enquanto a alteração do desvio padrão estende ou achata a curva, ou seja, muda a dispersão da distribuição.\n\nA @fig-threecurves, mostra a distribuição normal com média 0 e desvio padrão 1, na curva à direita, a distribuição normal com média 1.5 e desvio padrão 1. Sobrepondo-se à curva da esquerda observa-se uma curva mais achatada (verde) que tem média 0 e desvio padrão 1.5. Observa-se, como mencionado, que modificando os parâmetros da curva, altera-se a posição ou o formato da mesma.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Curvas normais com modificação dos parâmetros](09-probabilidades_files/figure-html/fig-threecurves-1.png){#fig-threecurves fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n### Características da distribuição normal\n\nA curva normal apresenta as seguintes características:\n\n- A média e o desvio padrão descrevem exatamente uma distribuição normal, eles são chamados de parâmetros da distribuição. Se uma distribuição normal tem média $\\mu$ e desvio padrão $\\sigma$, pode-se escrever a distribuição como $N (\\mu,\\sigma)$. As três distribuições dos gráficos da @fig-threecurves podem ser escritas como:\n\n  - Curva azul $\\to$ $N(\\mu = 0,\\sigma = 1)$\n  - Curva verde $\\to$ $N(\\mu = 0,\\sigma = 1.5)$\n  - Curva vermelha $\\to$ $N(\\mu = 1.5,\\sigma = 1)$\n\n- Na distribuição normal, a média, a mediana e a moda coincidem.\n\n- A curva normal é simétrica em torno da média ($\\mu$).\n\n- As extremidades da curva, em ambos os lados da média, se estendem cada vez mais próximas do eixo *x* (abscissa) sem jamais tocá-lo. É assintótica.\n\n- Os pontos de inflexão da curva são $\\mu - \\sigma$ e $\\mu + \\sigma$.\n\n- A área total sob a curva é 1 ou 100%.\n\n### Distribuição normal padronizada {#sec-dnp}\n\nCada variável aleatória contínua tem a sua média e seu desvio padrão e, portanto, a sua curva normal correspondente.\n\nPara facilitar a comparação entre variáveis, foi criado o conceito de **curva normal padronizada**, que é uma curva normal com média 0 e desvio padrão 1. A distribuição normal padrão também pode ser chamada de *distribuição normal centrada* ou *reduzida*.\n\nPara calcular probabilidades associadas a distribuição normal, costuma-se converter a variável aleatória original *X*, em unidades reduzidas ou padronizadas, denominadas de **escore Z** ou **escore padrão**. Essa transformação é realizada pela equação que indica o número de desvios padrão envolvidos no afastamento do valor *x* em relação à média da população:\n\n$$Z =\\frac{x-\\mu}{\\sigma}$$ onde:\n\n- *Z* $\\to$ escore Z\\\n- *x* $\\to$ valor qualquer da variável aleatória *X*\\\n- $\\mu$ $\\to$ média da variável *X*\\\n- $\\sigma$ $\\to$ desvio padrão da variável *X*\n\nQualquer distribuição de uma variável aleatória normal pode ser padronizada, usando o escore *Z*. Isto permite que se calcule a probabilidade de se encontrar determinados intervalos de valores [@gonzalez2021normal].\n\nComo exemplo, se retornará à `altura` das mulheres. É, praticamente, impossível saber o valor da média populacional, por isso costuma-se usar a média aritmética como um estimador da média populacional. Dessa forma, a variável `dados$altura` poderá ser utilizada como estimativa da média populacional. Em primeiro lugar, se construirá um `tibble` de nome `resumo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dados |>\n  dplyr::summarise(n = n(),\n                   media = mean(altura, na.rm = TRUE),\n                   dp = sd(altura, na.rm = TRUE),\n                   min = min(altura, na.rm = TRUE),\n                   max = max(altura, na.rm = TRUE))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n      n media     dp   min   max\n  <int> <dbl>  <dbl> <dbl> <dbl>\n1  1368  1.60 0.0655   1.4  1.85\n```\n\n\n:::\n:::\n\n\nAssim, pode-se verificar quantos desvios padrão uma mulher, pertencente a essa amostra, com 1,75 m está afastada da média:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nZ <- (1.75 - resumo$media) / resumo$dp\nround(Z, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.32\n```\n\n\n:::\n:::\n\n\nEsta mulher está distante mais de 2 desvios padrão acima da média da sua população. Portanto, ela é considerada alta. Por que?\n\nPara responder a essa pergunta, há necessidade de calcular a probabilidade de encontrar uma mulher com esta altura, nesta população. Primeiro, calcula-se a probabilidade de encontrar uma mulher com esta altura, nesta amostra. No *R*, existem as funções `dnorm()`, `pnorm()` e `qnorm()`, que permitem calcular a densidade de probabilidade, a distribuição cumulativa e a função quantílica da distribuição normal para um conjunto de valores. Além dessas, há a função `rnorm()` que permite obter observações aleatórias que seguem uma distribuição normal [@jain_2022norm].\n\n#### Função pnorm()\n\nA função `pnorm()` fornece a *Função de Distribuição Cumulativa* (CDF) da distribuição Normal, que é a probabilidade de que a variável *X* contenha um valor menor ou igual a *x*.\n\n[Argumentos]{.underline}:\n\n- **q** $\\rightarrow$ vetor de quantis\\\n- **mean** $\\rightarrow$ média\\\n- **sd** $\\rightarrow$ desvio padrão\\\n- **lower.tail** $\\rightarrow$ Se `TRUE`, as probabilidades são $P(X\\le x)$, caso contrário $P(X > x)$\n\nSe for usado $mean = 0$ e $sd = 1$, o valor de q = Z, caso contrário, toma-se os valores da média, o desvio padrão da população e o valor de *x*. Com esta função, é possível responder a pergunta feita anteriormente em relação a probabilidade de encontrar uma mulher com mais de 1,75 m, equivalente a 2.32 desvios padrão acima da média, em uma população com média = 1.5979678 e desvio padrão = 0.0654787.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- pnorm(Z, mean = 0, sd = 1, lower.tail = FALSE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01012028\n```\n\n\n:::\n:::\n\n\nOu, usando os valores originais diretamente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.75, mean = resumo$media, sd = resumo$dp, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01012028\n```\n\n\n:::\n:::\n\n\nObserva-se que, nesta amostra, apenas 1% das mulheres têm acima de 1,75 m, razão de ser considerada uma mulher alta. Ou seja, é pouco provável encontrar mulheres acima dessa altura, nesta amostra.\n\nPara representar graficamente essa pequena probabilidade, será construída uma curva com essa pequena área sombreada, colorida em azul claro. Para isso, uma função própria, denominada `normal_intervalo_sombreado()` plotará a figura. Os argumentos dessa função são: `a = limite inferior do intervalo`; `b = limite superior do intervalo`; `mean = média (padrão = 0)`; `sd = desvio padrão (padrão = 1)`. Ela pode ser obtida [aqui](https://github.com/petronioliveira/Arquivos/blob/main/normal_intervalo_sombreado.R) para ser baixada em seu diretório de trabalho para uso posterior [^09-probabilidades-2]. Para carregar a função para uso usa-se a função nativa `source()` que serve para executar o código contido em um arquivo com a extensão `.R`.\n\n[^09-probabilidades-2]: Veja @sec-funcpropria como se constrói uma função. A função apresentada aqui é mais complexa.\n\nA @fig-prob1725 representa com clareza esta pequena probabilidade[^09-probabilidades-3].\n\n[^09-probabilidades-3]: Arbritariamente, foi estabelecido um limite superior de 2 m (valor muito alto), simplesmente para função ser executada.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Probabilidade de encontrar mulheres entre 1,75 e 2.00 m](09-probabilidades_files/figure-html/fig-prob1725-1.png){#fig-prob1725 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n#### Função qnorm()\n\nA função `qnorm()` permite encontrar o quantil *q* para qualquer probabilidade *p*. Portanto, a função `qnorm` é o inverso da função `pnorm()`.\n\n[Argumentos]{.underline}:\n\n- *p* $\\to$ vetor de probabilidades\\\n- *mean* $\\to$ média\\\n- *sd* $\\to$ desvio padrão\\\n- *lower.tail* $\\to$ Se `TRUE`, as probabilidades são ($P \\le x$), caso contrário $P(X > x)$\n\nNo exemplo anterior, a probabilidade de se encontrar mulheres, na maternidade, com mais de 1,75 m foi de 1%. Poderia ser calculado com a função `qnorm()` qual o escore *Z* correspondente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(p, mean = 0, sd = 1, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.321858\n```\n\n\n:::\n:::\n\n\n#### Função dnorm()\n\nEssa função retorna o valor da *função de densidade de probabilidade* (pdf) da distribuição normal dada uma certa variável aleatória X, uma média populacional $\\mu$ e o desvio padrão populacional $\\sigma$.\n\n[Argumentos]{.underline}:\n\n- **x** $\\to$ vetor de quantis\\\n- **mean** $\\to$ média\\\n- **sd** $\\to$ desvio padrão\n\nEmbora *x* represente a variável independente da *pdf* para a distribuição normal, também é útil pensar em *x* como um escore *Z*. Por exemplo, a densidade de probabilidade quando *x* = 0 é igual:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndnorm(x = 0, mean = 0, sd = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3989423\n```\n\n\n:::\n:::\n\n\nPara se construir uma curva de densidade de probabilidades normal ( $X \\sim N(\\mu=0,\\sigma=1)$), basta aplicar a função `dnorm()` a uma sequência contínua de escores *Z*. O vetor de escores Z é obtido com a função `seq()`, como mostrado a seguir:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nescores_z <- seq(-3, 3, by = 0.05)\nescores_z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] -3.00 -2.95 -2.90 -2.85 -2.80 -2.75 -2.70 -2.65 -2.60 -2.55 -2.50 -2.45\n [13] -2.40 -2.35 -2.30 -2.25 -2.20 -2.15 -2.10 -2.05 -2.00 -1.95 -1.90 -1.85\n [25] -1.80 -1.75 -1.70 -1.65 -1.60 -1.55 -1.50 -1.45 -1.40 -1.35 -1.30 -1.25\n [37] -1.20 -1.15 -1.10 -1.05 -1.00 -0.95 -0.90 -0.85 -0.80 -0.75 -0.70 -0.65\n [49] -0.60 -0.55 -0.50 -0.45 -0.40 -0.35 -0.30 -0.25 -0.20 -0.15 -0.10 -0.05\n [61]  0.00  0.05  0.10  0.15  0.20  0.25  0.30  0.35  0.40  0.45  0.50  0.55\n [73]  0.60  0.65  0.70  0.75  0.80  0.85  0.90  0.95  1.00  1.05  1.10  1.15\n [85]  1.20  1.25  1.30  1.35  1.40  1.45  1.50  1.55  1.60  1.65  1.70  1.75\n [97]  1.80  1.85  1.90  1.95  2.00  2.05  2.10  2.15  2.20  2.25  2.30  2.35\n[109]  2.40  2.45  2.50  2.55  2.60  2.65  2.70  2.75  2.80  2.85  2.90  2.95\n[121]  3.00\n```\n\n\n:::\n:::\n\n\nAgora, usando a função `dnorm()`, será construído conjunto de valores de densidade de probabilidade correspondentes aos escores *Z* obtidos anteriormente:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalores_d <- dnorm(escores_z, mean = 0, sd = 1)\n```\n:::\n\n\nEstes valores serão plotados para construir a curva normal (@fig-pdf):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Função densidade de probabilidade](09-probabilidades_files/figure-html/fig-pdf-1.png){#fig-pdf fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nComo se pode ver, `dnorm()` fornece a \"altura\" do *pdf* da distribuição normal em qualquer escore *Z* que se forneça como argumento.\n\n#### Função rnorm() {#sec-rnorm}\n\nA função `rnorm()` gera *n* números aleatórios com distribuição normal com média $\\mu$ e desvio padrão $\\sigma$.\n\n[Argumentos]{.underline}:\n\n- **n** $\\to$ número de observações a serem geradas\\\n- **mean** $\\to$ média\\\n- **sd** $\\to$ desvio padrão\n\nCom esta função é possível, por exemplo, gerar 10 observações de uma distribuição normal:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrnorm(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  0.55968921 -0.89788934 -0.25758821 -0.20119257 -0.07439059 -1.16866741\n [7] -3.25109773  1.27265000  0.20021286 -0.61148970\n```\n\n\n:::\n:::\n\n\nNo entanto, deve-se notar que, se uma \"semente\" (`seed`) não for especificada, a saída não será reproduzível, ou seja, cada vez que o comando for executado, retornará um novo conjunto de observações:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrnorm(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  0.007877182  1.440624230  0.324091827 -0.177531970  2.436022031\n [6] -0.220226299 -0.396800955  0.806624615 -0.602612932  0.612238688\n```\n\n\n:::\n:::\n\n\nPara tornar o código reproduzível, retornando o mesmo conjunto de valores, deve-se usar uma \"semente\" (*seed*), usando a função *set.seed()*, cujo argumento é um número que identificará a série gerada, no exemplo, pela função `rnorm()`. O valor do número (\"semente\") não é importante, é apenas um identificador. Para ilustrar, serão construídos dois conjuntos de 10 números que serão recebidos pelos objetos *x* e *y*. Para gerar o conjunto de números *x*, será usado o número `123` como \"semente\". A \"semente\" funciona como uma espécie de marca. Para o *y* não será usada a função `set.seed()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- 10\nset.seed(123)\nx <- rnorm(n)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499\n [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197\n```\n\n\n:::\n\n```{.r .cell-code}\ny <- rnorm(n)\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1.2240818  0.3598138  0.4007715  0.1106827 -0.5558411  1.7869131\n [7]  0.4978505 -1.9666172  0.7013559 -0.4727914\n```\n\n\n:::\n:::\n\n\nComparando os conjuntos com a função `identical()` do R base, observa-se que os conjuntos são diferentes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\nAgora, repetindo os mesmos comandos, mas usando antes a mesma \"semente\", observa-se que os conjuntos são idênticos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nx <- rnorm(n)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499\n [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(123)\ny <- rnorm(n)\ny\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] -0.56047565 -0.23017749  1.55870831  0.07050839  0.12928774  1.71506499\n [7]  0.46091621 -1.26506123 -0.68685285 -0.44566197\n```\n\n\n:::\n\n```{.r .cell-code}\nidentical(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n[Outros usos da função `rnorm()`]{.underline}:\n\nA função `rnorm()` será usada para gerar três vetores diferentes de números aleatórios de uma distribuição normal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nn10 <- rnorm(10, mean = 0, sd = 1)\nn100 <- rnorm(100, mean = 0, sd = 1)\nn10000 <- rnorm(10000, mean = 0, sd = 1)\n```\n:::\n\n\nEm sequência, serão construídos histogramas (@fig-pdf1), onde se pode observar que, aumentando o número de observações, tem-se gráficos que irão progressivamente se aproximando da verdadeira função de densidade normal.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histogramas construídos com amostras geradas pela função rnorm](09-probabilidades_files/figure-html/fig-pdf1-1.png){#fig-pdf1 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nObserve também que à medida que *n* aumenta, a distribuição dos dados caracteriza-se como uma distribuição normal. Na @sec-dam, este assunto voltará à cena.\n\n### Regra Empírica 68-95-99.7\n\nA regra empírica diz que, para qualquer distribuição normal com média $\\mu$ e desvio padrão $\\sigma$, aproximadamente 68%, 95% e 99,7% dos valores encontram-se, respectivamente, dentro de $\\mu \\pm 1\\sigma$, $\\mu \\pm 2\\sigma$ e $\\mu \\pm 3\\sigma$. No caso particular da distribuição normal padrão ($X \\sim N(\\mu=0, \\sigma=1)$), esses intervalos correspondem a $\\pm 1$, $\\pm 2$ e $\\pm 3$.\n\nEssa regra pode ser usada para descrever uma população e ajudar a decidir se uma amostra de dados veio de uma distribuição normal. Se uma amostra é grande o suficiente e a observação do histograma tem um formato parecido com um sino, é possível verificar se os dados seguem as especificações 68-95-99,7%. Se sim, é razoável concluir que os dados vieram de uma distribuição normal.\n\n[Exemplo]{.underline}:\n\nCom a função `rnorm()`, será gerado um vetor de 1000 números e um histograma com curva normal sobreposta:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Histograma com curva normal sobreposta](09-probabilidades_files/figure-html/fig-histdp-1.png){#fig-histdp fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nNo histograma (@fig-histdp), a probabilidade entre os escores Z - 1 e + 1 (entre as duas linhas tracejadas A e B) é igual a aproximadamente 68%. Pode-se calcular isto facilmente, usando a função `pnorm()`:\n\n[Probabilidade abaixo de z = 1, abaixo do ponto B]{.underline}:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB <- pnorm(1, 0, 1)\nB <- round(B, 3) * 100\nB\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 84.1\n```\n\n\n:::\n:::\n\n\n[Probabilidade abaixo de z = -1, abaixo do ponto A]{.underline}:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- pnorm(-1, 0, 1)\nA <- round(A, 3) * 100\nA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.9\n```\n\n\n:::\n:::\n\n\nLogo, a área abaixo da curva entre A e B é igual a:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob <- B - A\nprob\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 68.2\n```\n\n\n:::\n:::\n\n\n### Calculando probabilidades em uma distribuição normal\n\n::: callout-tip\n## Exemplo 1\n\nA variável `dados$altura`, mostrada na @sec-aplicafreq, tem uma média (1.598), mediana de (1.6) e um coeficiente de variação (CV) muito pequeno de 4.1%. Isso caracteriza uma variável com uma distribuição praticamente simétrica. Usando esses dados ($X\\sim N(\\mu=$ 1,598, $\\sigma=$ 0,065$)$), pode-se calcular probabilidades, dadas pela área sob a curva.\n\nBaseado nessas informações, qual a probabilidade de se encontrar mulheres com altura entre 1,47 e 1,73 m?\n:::\n\n**Resposta**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados\nmu <- resumo$media\nsigma <- resumo$dp\nlinf <- 1.47\nlsup <- 1.73\n\n# Solução\nz1 <- (linf - mu) / sigma\nz2 <- (lsup - mu) / sigma\n\np1 <- pnorm(linf, mu, sigma)\np2 <- pnorm(lsup, mu, sigma)\n\np2 - p1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9527915\n```\n\n\n:::\n:::\n\n\nnormal_intervalo_sombreado(a = 1.47, b = 1.73, mean = resumo$media, sd = resumo$dp )\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Probabilidade de encontrar mulheres entre 1,47 e 1,73 m](09-probabilidades_files/figure-html/fig-normal954-1.png){#fig-normal954 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nA probabilidade de alturas entre 1,47 m e 1,73 m é igual a 95.3%, como mostrado na @fig-normal954.\n\n::: callout-tip\n## Exemplo 2\n\nOs dados de uma pesquisa mostram informações sobre o tempo de cirurgia para reconstrução do ligamento cruzado anterior (LCA). A distribuição de probabilidades se ajusta à distribuição normal com o tempo médio de cirurgia de 129 minutos com um desvio padrão de 14 minutos.\n\n1.  Qual a probabilidade de uma cirurgia de reconstrução do LCA requerer um tempo de 60 minutos, mas menor do que 100 minutos?\n\n2.  Qual a probabilidade de uma cirurgia do LCA demandar 120 a 180 minutos?\n:::\n\n**Resposta 1:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados\nmu <- 129\nsigma <- 14\nlinf <- 60\nlsup <- 100\n\n# Solução\nz1 <- (linf - mu) / sigma\nz2 <- (lsup - mu) / sigma\n\np1 <- pnorm(linf, mu, sigma)\np2 <- pnorm(lsup, mu, sigma)\n\np2 - p1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01915897\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Probabilidade do tempo de cirurgia de LCA menor ou igual a 100 minutos](09-probabilidades_files/figure-html/fig-normal192-1.png){#fig-normal192 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nDe acordo com a distribuição, 1,9% das cirurgias irão demandar quantidade de tempo entre 60 e 100 minutos (@fig-normal192).\n\n**Resposta 2:**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados\nmu <- 129\nsigma <- 14\nlinf <- 120\nlsup <- 180\n\n# Solução\nz1 <- (linf - mu) / sigma\nz2 <- (lsup - mu) / sigma\n\np1 <- pnorm(linf, mu, sigma)\np2 <- pnorm(lsup, mu, sigma)\n\np2 - p1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7397068\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Probabilidade do tempo de cirurgia de LCA ser entre 2 e 3 horas](09-probabilidades_files/figure-html/fig-normal134-1.png){#fig-normal134 fig-align='center' width=80% height=80%}\n:::\n:::\n\n\nDe acordo com a distribuição, 74% das cirurgias irão demandar quantidade de tempo entre 2 a 3 horas (@fig-normal134).\n\n::: callout-tip\n## Exemplo 3\n\nSupondo que em uma determinada ilha hipotética existam duas populações etnicamente diferentes onde as mulheres têm as seguintes medidas de altura: população 1 tem μ = 160 cm e σ = 6,6 cm e a população 2 tem μ = 140 cm e σ = 6,6 cm. As alturas de ambas as populações têm distribuição normal. Essas duas populações têm o mesmo aspecto físico, podendo ser distinguidas apenas geneticamente.\n\n1.  Qual a probabilidade de uma mulher com 150 cm pertencer à população 1?\n\n2.  Qual a probabilidade de uma mulher com 150 cm pertencer à população 2?\n:::\n\n**Resposta 1**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados\nmu <- 160\nsigma <- 6.6\nx <- 150\n\n# Solução\nz <- (x - mu) / sigma\n\np <- pnorm(x, mu, sigma, lower.tail = TRUE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06486702\n```\n\n\n:::\n:::\n\n\nNa população 1, 6,5% das mulheres tem altura $\\le 1{,}50$ m . Em outras palavras, existe pouca probabilidade dessa mulher pertencer à população 1.\n\n**Resposta 2**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dados\nmu <- 140\nsigma <- 6.6\nx <- 150\n\n# Solução\nz <- (x - mu) / sigma\n\np <- pnorm(x, mu, sigma, lower.tail = TRUE)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.935133\n```\n\n\n:::\n:::\n\n\nNa população 2, 93,5% das mulheres tem altura $\\le 1{,}50$ m . Concluindo, ela pode pertencer a qualquer uma das populações. Pode ser uma mulher alta da população 2 ou uma \"baixinha\" da população 1!\n\n::: callout-note\n## Resumo: Distribuição Normal\n\n| Parâmetro | Descrição                 |\n|-----------|---------------------------|\n| $\\mu$     | Média (posição da curva)  |\n| $\\sigma$  | Desvio padrão (dispersão) |\n\n**Notação:** $X \\sim N(\\mu, \\sigma)$\n\n**Regra empírica:** $\\mu \\pm 1\\sigma \\approx 68\\%$; $\\mu \\pm 2\\sigma \\approx 95\\%$; $\\mu \\pm 3\\sigma \\approx 99{,}7\\%$\n\n| Função R             | O que retorna                     |\n|----------------------|-----------------------------------|\n| `dnorm(x, mean, sd)` | Densidade de probabilidade em *x* |\n| `pnorm(q, mean, sd)` | $P(X \\le q)$                      |\n| `qnorm(p, mean, sd)` | Quantil para probabilidade *p*    |\n| `rnorm(n, mean, sd)` | *n* valores aleatórios            |\n:::\n\n## Distribuição Binomial\n\nA distribuição normal padrão é apenas um dos exemplos de distribuição de probabilidade. Uma boa parte das situações se ajustam a ela. Entretanto, diversas situações reais muitas vezes se aproximam de outras distribuições estocásticas definidas por algumas hipóteses. Daí a importância de se conhecer e manipular algumas destas distribuições. Entre elas, a **distribuição binomial**.\n\nQuando um experimento aleatório resulta em um de dois, mutuamente exclusivos, desfechos, tais como vivo/morto, positivo/negativo, sim/não, masculino/feminino é denominado de *Ensaio de Bernoulli*. Recebeu esta denominação em homenagem ao matemático suíço, Jacob Bernoulli (1654-1705), considerado fundador do cálculo e da teoria da probabilidade [@robertson2022bernoulli].\n\nA distribuição de frequências que descreve as proporções de um ensaio de Bernoulli, chama-se **Distribuição Binomial**. A probabilidade binomial dá a probabilidade de determinado desfecho ocorrer em determinado número de ensaios independentes. Uma sequência de ensaios de Bernoulli forma um **Processo de Bernoulli**.\n\nA distribuição binomial é importante para variáveis discretas. Existem poucas condições que precisam ser atendidas para distribuição binomial:\n\n- Cada ensaio resulta em um de dois desfechos, mutuamente exclusivos, denominados, arbitrariamente, de sucesso e fracasso;\n- A probabilidade de sucesso é fixa, igual a *p*, constante em cada ensaio, e a probabilidade de fracasso é igual a *1 – p*;\n- O número de repetições *n* em um ensaio é fixo;\n- Os ensaios são independentes.\n\nA distribuição binomial é na verdade uma família de distribuições, cujos membros são definidos pelos valores de *n* e *p* (parâmetros da distribuição binomial).\n\nA probabilidade de sucesso [^09-probabilidades-4], em uma distribuição binomial, é dada pela fórmula:\n\n[^09-probabilidades-4]: *Sucesso*, aqui, não está no sentido de vitória, êxito, triunfo, glória e sim com a conotação de obter o desfecho esperado. Por exemplo, se uma moeda é lançada e se espera obter cara, sucesso significa um resultado igual a cara.\n\n$$P(X = x)= C \\times p^x \\times (1 - p)^{n-x}$$\n\nonde *n* = ensaios, *x* = sucessos, *p* = probabilidade de um sucesso e *C* representa o número possível de combinações em um ensaio.\n\nO número de combinações, *C* de *x* sucessos entre *n* repetições podem ser computado pela fórmula:\n\n$$C = \\frac{n!}{x!(n - x)!}$$\n\nou, no R, com a função `choose(n, x)`.\n\nO modelo de distribuição binomial trata de encontrar a probabilidade de sucesso de um evento que tem apenas dois resultados possíveis em uma série de experimentos. Usando dados de uma distribuição binomial, é possível calcular os valores esperados de uma variável aleatória conforme ela passa por tentativas independentes. Em outras palavras, é possível prever o número exato de caras ou coroas que se deve esperar ao jogar uma moeda um certo número de vezes.\n\nTambém, pode-se usar a probabilidade binomial cumulativa para encontrar a probabilidade de obter um determinado intervalo de resultados. Por exemplo, saber a probabilidade do nascimento de até três meninos em 10 nascimentos consecutivos quando a probabilidade de nascer um menino é 0,50.\n\nO *R* tem quatro funções embutidas para gerar distribuição binomial. Elas são descritas a seguir.\n\n### Funções da distribuição binomial\n\n#### Função pbinom()\n\nEsta função retorna o valor da *função de distribuição cumulativa* (CDF) da distribuição binomial dada uma certa variável aleatória *q*, número de tentativas (*size*) e probabilidade de sucesso em cada tentativa (*prob*).\n\n[Argumentos]{.underline}:\n\n- **q** $\\to$ vetor de quantis\\\n- **size** $\\to$ número de ensaios\\\n- **prob** $\\to$ probabilidade de sucesso em cada ensaio\\\n- **lower.tail** $\\to$ Se `TRUE`, as probabilidades são ($P \\le x$), caso contrário $P(X > x)$\n\nPor exemplo, qual é a probabilidade de nascer até três meninos em cinco nascimentos, sabendo que a probabilidade de nascer um menino é igual a 0,50?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(3, 5, 0.50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8125\n```\n\n\n:::\n:::\n\n\nIsso corresponde à soma das probabilidades de nascer nenhum menino, um menino, dois meninos e três meninos (@fig-menino3). Isto é calculado pela equação $P(X = x)$, vista anteriormente.\\\nColocando no *R*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 5\np = 0.50\nx <- 0:5\n# Probabilidades individuais de cada número de meninos\nFx <- (factorial(n) / (factorial(x) * factorial(n - x))) * p^x * (1 - p)^(n - x)\nFx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03125 0.15625 0.31250 0.31250 0.15625 0.03125\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição binomial, mostrando a P (x < 4) com n = 5 e p = 0,50](09-probabilidades_files/figure-html/fig-menino3-1.png){#fig-menino3 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n#### Função qbinom()\n\nEsta função retorna a função quantílica (inversa da CDF) da distribuição binomial dada uma probabilidade *p*, número de tentativas (*size*) e probabilidade de sucesso em cada tentativa (*prob*). Com o uso desta função, podemos descobrir o quantil da distribuição binomial.\n\n[Argumentos]{.underline}:\n\n- **p** $\\to$ probabilidade ou vetor de probabilidades\\\n- **size** $\\to$ número de ensaios\\\n- **prob** $\\to$ probabilidade de sucesso em cada ensaio\\\n- **lower.tail** $\\to$ Se `TRUE`, as probabilidades são ($P \\le x$), caso contrário $P(X > x)$\n\nPor exemplo, quantos meninos nascerão em 5 partos com 81.25% de probabilidade cumulativa?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqbinom(0.8125, size = 5, prob = 0.50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n:::\n\n\n#### Função rbinom()\n\nA função `rbinom()` permite extrair *n* observações aleatórias de uma distribuição binomial. Os argumentos da função são descritos abaixo:\n\n[Argumentos]{.underline}:\n\n- **n** $\\to$ número de observações aleatórias a ser gerado\\\n- **size** $\\to$ número de ensaios\\\n- **prob** $\\to$ probabilidade de sucesso em cada ensaio\n\nPara fazer uma simulação de 1000 amostras, aleatoriamente, de tamanho 5 e com probabilidade de nascer menino igual a 0,50, usa-se [^09-probabilidades-5]:\n\n[^09-probabilidades-5]: Deve ser especificado uma \"semente\" (seed) antes de executar a função, senão será obtido um conjunto diferente de observações aleatórias a cada execução. Teste para verificar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(23)\nmenino <- rbinom(n = 1000, size = 5, prob = 0.5)\n```\n:::\n\n\nCada amostra de n = 5 exibe o número de meninos nascidos. Pode-se fazer a média que representa o valor esperado do número de sucessos (nascimento de menino, no exemplo) em um conjunto de ensaios independentes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(menino)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.515\n```\n\n\n:::\n:::\n\n\nQuanto maior o número de variáveis aleatórias criadas, mais próximo a média do número de sucessos estará do número esperado de sucessos que é igual ao número de sucessos vezes a probabilidade de sucesso em cada ensaio (5 x 0,50 = 2,5).\n\nEstranho, não é? Dois meninos e meio, em média por ensaio! É, a média é assim, uma estimativa, expectativa matemática! Não é real...\n\n#### Função dbinom()\n\nEssa função retorna o valor da função de densidade de probabilidade (*pdf*) da distribuição binomial dada uma determinada variável aleatória X, número de tentativas (*size*) e probabilidade de sucesso em cada tentativa (*prob*). A função tem a seguinte sintaxe:\n\n[Argumentos]{.underline}:\n\n- **x** $\\to$ vetor de números\\\n- **size** $\\to$ número de ensaios\\\n- **prob** $\\to$ probabilidade de sucesso em cada ensaio\n\nA função é usada para encontrar a probabilidade de um determinado valor para dados que seguem a distribuição binomial, ou seja, encontra $P(X=x)$, probabilidade de *x* sucessos em tentativas de tamanho (*size*) *n* quando a probabilidade (*p*) de sucesso é *prob*. Obtém o mesmo resultado da fórmula:\n\n$$P(X = x)= C \\times p^x \\times (1 - p)^{n-x}$$\n\nPor exemplo, no nascimento de uma criança, as duas possibilidades, menino ou menina, são mutuamente excludentes e esses são os únicos eventos que podem acontecer. A probabilidade de nascimento de menino, como visto, é 0,50, qual seria a probabilidade de nascerem 4 meninos em 5 partos consecutivos não gemelares (@fig-menino5)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(4, size = 5, prob = 0.50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.15625\n```\n\n\n:::\n:::\n\n\nAs probabilidades de nascerem meninos em 5 nascimentos são:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFx <- dbinom(0:5, 5, 0.50)\nFx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03125 0.15625 0.31250 0.31250 0.15625 0.03125\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribuição binomial para P (x = 4) com n = 5 e p = 0,50](09-probabilidades_files/figure-html/fig-menino5-1.png){#fig-menino5 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n### Média e desvio padrão da distribuição binomial {#sec-mudpbinom}\n\nQuando o número de repetições é grande, geralmente há necessidade de resumir as probabilidades. A distribuição binomial pode ser descrita por sua *média* e *variância*.\n\nA média é o valor médio da variável aleatória em um longo número de repetições. É também chamada de *valor esperado* ou *expectativa*. A expectativa de uma variável aleatória X, geralmente, é denotada por $E(X)$ e obtida pela multiplicação do número de ensaios independentes (*n*) pela probabilidade (*p*) de sucesso em cada ensaio:\n\n$$\\mu = E(X) = n \\times p$$\n\nPortanto, a expectativa (esperança) de nascimento de meninos em 5 partos é $E(X)=5 \\times 0{,}50 = 2{,}5$, como visto na função `rbinom()`. Observe que o valor esperado de uma variável aleatória discreta não tem um valor que a variável aleatória pode realmente assumir.\n\nPor exemplo, para o número médio de meninos em um parto, ou não se tem menino ou se tem 1 menino, cada uma possibilidade com probabilidade de 0,50 e o valor esperado é (0 × 0,50) + (1 × 0,50) = 0,50. O número de meninos deve ser 0 ou 1, mas o valor esperado é a metade, a média que se obteria no longo prazo.\n\nA variância de uma variável aleatória discreta *X* é igual a\n\n$$\\sigma^2=var(X) = n\\times p \\times (1-p)$$\n\nConsequentemente, o desvio padrão é igual a\n\n$$\\sigma = \\sqrt{var(X)} = \\sqrt{n\\times p \\times (1-p)}$$\n\nPara o exemplo de 5 nascimentos, a média foi de 2,5 meninos e o desvio padrão\n\n$$\\sigma =\\sqrt{5\\times 0{,}50 \\times (1-0{,}50)}=\\sqrt{2{,}5 \\times 0{,}50}= 1{,}12$$\n\nPortanto, se espera que ocorram em média 2,5 ($\\sigma$ = 1,12) nascimentos de meninos em 5 partos.\n\n::: callout-note\n## Resumo: Distribuição Binomial\n\n| Parâmetro | Descrição                               |\n|-----------|-----------------------------------------|\n| $n$       | Número de ensaios                       |\n| $p$       | Probabilidade de sucesso em cada ensaio |\n\n**Notação:** $X \\sim B(n, p)$\n\n**Fórmula:** $P(X = x) = \\dbinom{n}{x}\\, p^x\\, (1-p)^{n-x}$\n\n**Média:** $\\mu = n \\cdot p$ $\\quad$ **Desvio padrão:** $\\sigma = \\sqrt{n \\cdot p \\cdot (1-p)}$\n\n| Função R                | O que retorna                  |\n|-------------------------|--------------------------------|\n| `dbinom(x, size, prob)` | $P(X = x)$                     |\n| `pbinom(q, size, prob)` | $P(X \\le q)$                   |\n| `qbinom(p, size, prob)` | Quantil para probabilidade *p* |\n| `rbinom(n, size, prob)` | *n* valores aleatórios         |\n:::\n\n## Distribuição de Poisson\n\nA **Distribuição de Poisson** é usada para modelar a **contagem de eventos que ocorrem em um intervalo fixo** de tempo, espaço, área ou volume.\n\nEnquanto a Binomial conta o número de sucessos em um número *fixo de tentativas* (*n*), a Poisson conta quantas vezes um evento raro acontece em uma *janela contínua* de tempo ou espaço (por exemplo: número de casos de covid-19 por dia, número de acidentes em um cruzamento por mês, número de gestantes infectadas por ano).\n\n### Condições da Distribuição de Poisson\n\nPara que uma variável *X* siga uma distribuição de Poisson, $X \\sim \\text{Poisson}(\\lambda)$, é preciso que:\n\n1.  **Eventos independentes:** a ocorrência de um evento não altera a chance de outro ocorrer.\n\n2.  **Taxa média constante (**$\\lambda$**):** o evento ocorre a uma taxa média conhecida ($\\lambda$) ao longo do tempo/espaço.\n\n3.  **Eventos isolados:** dois eventos não podem acontecer exatamente ao mesmo tempo/ponto.\n\n### Função de Probabilidade\n\nA chance de observarmos exatamente *k* eventos no intervalo é dada por:\n\n$$p(X = k)= \\frac{e^{-\\lambda}\\times \\lambda^{k}}{k!}$$\n\nOnde:\n\n- $\\lambda$ (lambda) é a **taxa média de eventos** por intervalo.\n- $e \\approx 2{,}71828$ (base do logaritmo natural).\n- $k\\in \\left\\{0,1,2,3,... \\right\\}$ é o número de contagens.\n\nNa distribuição de Poisson, a **média** e a **variância** são exatamente iguais ao parâmetro $\\lambda$: $$\\mu = \\lambda \\quad e \\quad \\sigma^{2} = \\lambda$$\n\n### Funções Nativas\n\nAssim como na Binomial, o R fornece quatro funções padrão alterando o prefixo antes de `pois`:\n\n| Função | O que faz? | Exemplo de uso |   |\n|------------------------|------------------------|------------------------|------------------------|\n| **dpois(x, lambda)** | **P(X = x):** Probabilidade exata | Probabilidade de ocorrer **exatamente 3 casos de sarampo** em 2 dias |  |\n| **ppois(q, lambda)** | **P(X ≤ q):** Probabilidade acumulada | Probabilidade de ocorrer **no máximo 3 casos de sarampo** nos próximos 2 dias |  |\n| **qpois(p, lambda)** | Quantil inverso (valor que cobre p%) | **Quantos casos** ficam abaixo de **95%** da distribuição. |  |\n| **rpois(n, lambda)** | Simulação de n valores | Simular **10 dias** de número de casos de sarampo, usando a taxa λ. |  |\n\n### Exemplos\n\nImagine um hospital que recebe, em média, $\\lambda = 4$ **emergências por hora**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Chance de chegar EXATAMENTE 4 pacientes na próxima hora: P(X = 4)\nlambda <- 4 \n\ndpois(x = 4, lambda = lambda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1953668\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. Chance de chegar NO MÁXIMO 2 pacientes: P(X <= 2)\n\nppois(q = 2, lambda = lambda) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2381033\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. Chance de chegar MAIS de 6 pacientes (sobrecarga): P(X > 6)\n\nppois(q = 6, lambda = lambda, lower.tail = FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.110674\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4. Simulando 1.000 horas do hospital e visualizando\nlibrary(ggplot2)\n\nset.seed(42)\nhoras_simuladas <- rpois(n = 1000, lambda = lambda)\ndados <- data.frame(atendimentos = factor(horas_simuladas))\n# Gráfico de barras da contagem de ocorrências\nggplot(dados, aes(x = atendimentos)) +\n  geom_bar(fill = \"forestgreen\", color = \"black\", alpha = 0.8) +\n  theme_minimal() +\n  labs(\n    title = \"Simulação de Atendimentos de Emergência (Lambda = 4/hora)\",\n    x = \"Número de Chegadas por Hora\",\n    y = \"Frequência em 1.000 Horas\")\n```\n\n::: {.cell-output-display}\n![](09-probabilidades_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n[O que o gráfico revela]{.underline}?\n\n1.  **Pico em torno de 3 e 4 chegadas** Os maiores valores de frequência estão em 3 e 4 atendimentos por hora. Isso é exatamente o que a teoria prevê:\n\n- Na Poisson, o valor mais provável é o próprio (aqui, 4).\n\n- O valor imediatamente anterior (3) também costuma ser muito frequente.\n\n2.  **Simetria levemente enviesada à direita** A distribuição tem uma cauda que se estende para valores maiores (6, 7, 8…). Isso é típico da Poisson:\n\n- Não é simétrica como a normal.\n\n- Tem uma **assimetria positiva**, com alguns valores mais altos ocorrendo raramente.\n\n3.  **Baixa frequência de eventos extremos** Valores como 0, 1, 7, 8 aparecem poucas vezes. Isso mostra que:\n\n- É raro ter **nenhum atendimento** em uma hora.\n\n- Também é raro ter **muitos atendimentos** (7 ou mais).\n\n4.  **A soma das barras deve ser \\~1000** Cada barra representa quantas vezes aquele número de chegadas ocorreu nas 1.000 horas simuladas. Se somarmos todas as frequências, chegamos perto de 1.000 — o que confirma que o gráfico representa uma simulação de 1.000 observações.\n\n[Interpretação estatística]{.underline}\n\nA distribuição observada está coerente com uma Poisson():\n\n- Média ≈ 4\n\n- Variância ≈ 4 (na Poisson, média = variância)\n\n- Maior probabilidade em torno de $\\lambda$\n\n- Cauda longa para a direita\n\n- Eventos raros (0, 7, 8) aparecem pouco\n\nIsso indica que o processo simulado segue bem o comportamento de um processo de chegadas aleatórias com taxa constante.\n\n[Interpretação prática (emergência hospitalar)]{.underline}\n\nSe isso representa chegadas por hora em uma emergência:\n\n- A equipe deve esperar **3 a 5 atendimentos por hora** na maior parte do tempo.\n\n- Horas com **0 ou 1 atendimento** são incomuns.\n\n- Horas com **7 ou mais atendimentos** são raras, mas possíveis — e representam momentos de sobrecarga.\n\n## Resumo: Distribuição de Poisson\n\n::: callout-note\n| Parâmetro | Descrição                                 |\n|-----------|-------------------------------------------|\n| $\\lambda$ | Número médio de ocorrências por intervalo |\n\n**Notação:** $X \\sim \\text{Poisson}(\\lambda)$\n\n**Fórmula:** $P(X = x) = \\dfrac{e^{-\\lambda}\\, \\lambda^x}{x!}$\n\n**Média e variância:** $\\mu = \\sigma^2 = \\lambda$\n\n**Quando usar:** Preferível à Binomial quando $n \\ge 20$ e $n \\times p < 5$\n\n| Função R           | O que retorna                  |\n|--------------------|--------------------------------|\n| `dpois(x, lambda)` | $P(X = x)$                     |\n| `ppois(q, lambda)` | $P(X \\le q)$                   |\n| `qpois(p, lambda)` | Quantil para probabilidade *p* |\n| `rpois(n, lambda)` | *n* valores aleatórios         |\n:::\n",
    "supporting": [
      "09-probabilidades_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}