{
  "hash": "b4f03e85c232c3d456a4a2b27f82438f",
  "result": {
    "engine": "knitr",
    "markdown": "# Medidas de ocorrência de doença {#sec-ocorrencia}\n\n## Pacotes necessários neste capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!requireNamespace(\"BiocManager\", quietly = TRUE)) install.packages(\"BiocManager\")\nif (!requireNamespace(\"limma\", quietly = TRUE)) BiocManager::install(\"limma\")\n\npacman::p_load(BiocManager,\n               dplyr,\n               epiR,\n               epitools,\n               flextable,\n               knitr,\n               limma,\n               officer,\n               pROC,\n               readxl,\n               vcd)\n```\n:::\n\n\n## Medidas de frequência\n\n### Prevalência {#sec-prevalencia}\n\nA prevalência, ou mais adequadamente, a *prevalência pontual* de uma doença é a proporção da população portadora da doença em um determinado ponto do tempo. É uma medida instantânea por excelência e fornece uma medida estática da frequência da doença. É também conhecida como *taxa de prevalência* e é expressa em percentagem ou por $10^{n}$ habitantes. As medidas de prevalência geram informações úteis para o planejamento e administração de serviços de saúde.\n\nA *prevalência por período* descreve os casos que estavam presentes em qualquer momento durante um determinado período de tempo. Diz o número total de casos de uma doença que se sabe haver existido durante um período de tempo.\n\nUm tipo especial de prevalência de período é a prevalência ao longo da vida, que mede a frequência cumulativa ao longo da vida de um resultado até o momento presente (ou seja, a proporção de pessoas que tiveram o evento em qualquer momento no passado).\n\nAs doenças, quanto a sua duração, podem ser agudas e de longa duração ou crônicas. A prevalência é proporcional ao tempo de duração da doença. Hipoteticamente, se o surgimento de novos casos de doença ocorre em ritmo constante e igual para doenças agudas e crônicas, estas últimas acumularão casos, aumentando a prevalência. As doenças agudas tenderão a manter uma prevalência constante. A terapêutica, diminuindo o tempo de duração das doenças, também reduz a prevalência. A prevalência é dada pela razão:\n\n$$prevalência = \\frac{número \\ de \\ casos \\ conhecidos \\ da \\ doença}{total \\ da \\ População} \\times 10^{n}$$\n\n#### Exemplo\n\nComo exemplo, será verificada a frequência de tabagismo entre as puérperas da maternidade do HGCS. O banco de dados `dadosMater.xlsx` contém informação de 1368 nascimentos e pode ser consultado na @sec-dadosMater. Clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosMater.xlsx) para baixar e depois de salvar em seu diretório de trabalho, carregue-o com a função `read_excel()` do pacote `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel (\"dados/dadosMater.xlsx\")\n```\n:::\n\n\nInicialmente, será verificado quantas fumantes existem. O conjunto de dados contém uma variável `fumo`, onde `1 = fumante` e `2 = não fumante`. Portanto, há necessidade de transformar a variável numérica em um fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$fumo <- factor (dados$fumo,\n                      ordered = TRUE, \n                      levels = c(1,2),\n                      labels = c(\"fumante\", \"não fumante\"))\n \ntabFumo <- with(data = dados, table(fumo))\naddmargins(tabFumo, FUN = sum)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfumo\n    fumante não fumante         sum \n        301        1067        1368 \n```\n\n\n:::\n:::\n\n\nAlém de relatar a estimativa pontual da frequência da doença, é importante fornecer uma indicação da incerteza em torno dessa estimativa pontual. A função `epi.conf()`, do pacote `epiR` [@stevenson2022epir], permite calcular intervalos de confiança para prevalência, motivo da escolha dessa função.\n\nA função `epi.conf()` usa os seguintes argumentos:\n\n- **dat** $\\longrightarrow$ matriz ou tabela;\n- **ctype** $\\longrightarrow$ tipo de intervalo de confiança a ser calculado. Opções: *mean.single*, *mean.unpair*, *mean.pair*, *prop.single*, *prop.unpaired*, *prevalence*, *inc.risk*, *inc.rate*, *odds* e *smr* (*standardized mortality rate*);\\\n- **method** $\\longrightarrow$ método a ser usado. Quando `ctype = \"inc.risk\"` ou `ctype = \"prevalence\"`, as opções são `exact`, `wilson` e `fleiss`. Quando `ctype = \"inc.rate\"`, as opções são `exact` e `byar`;\n- **N** $\\longrightarrow$ tamanho da população;\n- **conf.level** $\\longrightarrow$ magnitude do intervalo de confiança retornado. Deve ser um único número entre 0 e 1.\n\n[Construção da matriz]{.underline}\n\nCom os dados da `tabFumo`, constrói-se uma matriz de duas colunas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- tabFumo[1]\nN1 <- tabFumo[1] + tabFumo[2]\nmat1 <- as.matrix(cbind (n1, N1))\nmat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         n1   N1\nfumante 301 1368\n```\n\n\n:::\n:::\n\n\n[Cálculo da prevalência]{.underline}\n\nUsando a função `epi.conf()`, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.conf(mat1, \n               ctype = \"prevalence\", \n               method = \"exact\", \n               conf.level = 0.95) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        est     lower     upper\n1 0.2200292 0.1983313 0.2429365\n```\n\n\n:::\n:::\n\n\nA saída mostra que a prevalência de fumantes entre as puérperas do HGCS é igual a 22,0% (IC~95%~: 19,8 – 24,3%).\n\n### Incidência\n\nA incidência fornece uma medida da frequência com que os indivíduos suscetíveis se tornam casos de doenças, à medida que são observados ao longo do tempo.\\\nUm caso incidente ocorre quando um indivíduo deixa de ser suscetível e passa a ser doente. A contagem de casos incidentes é o número de tais eventos que ocorrem em uma população durante um período de acompanhamento definido. Existem duas maneiras de expressar a incidência:\n\nA *incidência cumulativa* (risco) é a proporção de indivíduos inicialmente suscetíveis em uma população que se tornam novos casos durante um período de acompanhamento definido.\n\nPara calcular a incidência cumulativa, é necessário primeiro identificar os doentes e após acompanhar por um determinado tempo os não doentes (@fig-incidencia).\n\n![Incidência](images/incidencia.png){#fig-incidencia fig-align=\"center\" width=\"13cm\" height=\"4.7cm\"}\n\nA *taxa de incidência* (densidade de incidência ou taxa de incidência) é o número de novos casos da doença que ocorrem por unidade de tempo em risco durante um período de acompanhamento definido. Este período é expresso como *pessoas-tempo* (pessoas-ano, por exemplo).\n\nO conceito de pessoas-tempo pode ser ilustrado com o seguinte exemplo: a @fig-incidencia1 representa um estudo epidemiológico hipotético com duração de cinco anos, onde D é o desfecho e C representa os sujeitos que deixaram o estudo por migração ou morte (censurados) por causa não relacionada ao desfecho.\n\n![Pessoas-tempo (estudo epidemiológico hipotético)](images/incidencia_1.png){#fig-incidencia1 fig-align=\"center\" width=\"10cm\"}\n\nNesse estudo hipotético, o indivíduo 1 permaneceu no estudo 3,5 anos; o indivíduo 2, ficou 5 anos; o indivíduo 3, 4,5 anos e, assim por diante, totalizando 32,5 pessoas-anos. Em outras palavras, ocorreram 4 desfechos durante os 5 anos do estudo, consequentemente, a taxa de incidência (TI) foi de\n\n$$TI = \\frac{4}{32,5} \\times 1000 = \\frac{123}{1000\\ pessoas-ano} $$\n\nIsto significa que se fossem acompanhadas 1000 pessoas por um ano, 123 delas apresentariam o desfecho D.\n\n#### Exemplo\n\nAparentemente, pessoas cegas têm uma menor incidência de câncer e esse efeito parece ser mais pronunciado em pessoas totalmente cegas do que em pessoas com deficiência visual grave.\n\nPara testar essa hipótese, foi identificada uma coorte de 1.567 pessoas totalmente cegas e 13.292 sujeitos com deficiência visual grave. As informações sobre a incidência de câncer foram obtidas do Registro Sueco de Câncer [@feychting1998reduced]. Foram diagnosticados 136 casos de câncer em 22050 pessoas-ano em risco totalmente cegas e 1709 casos de câncer em 127650 pessoas-anos em risco com deficiência visual grave.\n\nA taxa de incidência pode ser calculada, usando-se a mesma função `epi.conf()`, usada para o cálculo da prevalência, mudando o argumento `ctype = “prevalence”` para `ctype = “inc.rate”`, conforme recomendado:\n\n[Pessoas totalmente cegas]{.underline}\n\nInicialmente, constrói-se a matriz:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn2 <- 136\nN2 <- 22050\nmat2 <- as.matrix(cbind (n2, N2))\nmat2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      n2    N2\n[1,] 136 22050\n```\n\n\n:::\n:::\n\n\nLogo, a incidência de câncer nos totalmente cegos é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.conf(mat2, \n               ctype = \"inc.rate\", \n               method = \"exact\", \n               conf.level = 0.95)*1000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      est    lower    upper\nn2 6.1678 5.174806 7.295817\n```\n\n\n:::\n:::\n\n\n[Pessoas com grave deficiência visual]{.underline}\n\nInicialmente, constrói-se a matriz:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn3 <- 1709\nN3 <- 127650\nmat3 <- as.matrix(cbind (n3, N3))\nmat3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       n3     N3\n[1,] 1709 127650\n```\n\n\n:::\n:::\n\n\nLogo, a incidência de câncer nos com grave deficiência visual é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.conf(mat3, \n               ctype = \"inc.rate\", \n               method = \"exact\", \n               conf.level = 0.95)*1000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        est    lower    upper\nn3 13.38817 12.76088 14.03832\n```\n\n\n:::\n:::\n\n\nAs saídas mostram que para cada 1000 pessoas cegas (a função foi multiplicada por 1000) acompanhadas por um ano, ocorreram 6,2 (IC~95%~: 5,2 – 7,3) casos de câncer. Uma taxa de incidência, praticamente, metade da taxa de incidências das pessoas com deficiência visual grave. Os IC~95%~ não são coincidentes, o que significa que essa diferença é significativa. Houve, na amostra, uma incidência menor de câncer entre os indivíduos totalmente cegos, sugerindo que a melatonina possa ser um fator protetor contra o câncer.\n\n#### Relação entre prevalência e incidência\n\nA incidência é uma medida de risco. A prevalência, por não levar em consideração o tempo de duração da doença (*t*), não tem esta capacidade. Em uma população onde a situação da doença encontra-se em estado estacionário (ou seja, sem grandes migrações ou mudanças ao longo do tempo na incidência/prevalência), a relação entre prevalência e incidência e duração da doença pode ser expressa pela seguinte fórmula [@szklo2019measuring]:\n\n$$prevalência \\ pontual = incidência \\times duração \\ da \\ doença \\ (t)$$\n\nPor exemplo, se a incidência da doença for de 0,8% ao ano e sua duração média (sobrevida após o diagnóstico) for de 10 anos, a prevalência pontual será de aproximadamente 8%.\n\n## Medidas de associação\n\n### *Odds Ratio* {#sec-or}\n\n**Odds Ratio** (OR) é a razão entre dois *odds*. A *Odds Ratio*, traduzida como *Razão de Chances*, está associada, usualmente, com estudos retrospectivos tipo caso-controle com desfechos dicotômicos.\n\nA *odds ratio* (OR) expressa a *odds* de exposição entre os que têm o desfecho (casos) pela *odds* de exposição nos livres de desfecho (controles).\n\n\n::: {#tbl-tab_2x2 .cell layout-align=\"center\" tbl-cap='Tabela de contingência 2 x 2'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-0f7ba48c{}.cl-0f722466{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(255, 255, 255, 1.00);background-color:transparent;}.cl-0f722484{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0f72248e{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0f75cdf0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0f75cdfa{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0f76093c{width:1.236in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760946{width:1.219in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760947{width:1.202in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760950{width:1.164in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760951{width:1.236in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f76095a{width:1.219in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f76095b{width:1.202in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760964{width:1.164in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760965{width:1.236in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760966{width:1.219in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f76096e{width:1.202in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f76096f{width:1.164in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760978{width:1.236in;background-color:rgba(240, 244, 248, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760982{width:1.219in;background-color:rgba(240, 244, 248, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760983{width:1.202in;background-color:rgba(240, 244, 248, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0f760984{width:1.164in;background-color:rgba(240, 244, 248, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0f7ba48c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-0f76093c\"><p class=\"cl-0f75cdf0\"><span class=\"cl-0f722466\">Exposição</span></p></th><th class=\"cl-0f760946\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722466\">Com Doença</span></p></th><th class=\"cl-0f760947\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722466\">Sem Doença</span></p></th><th class=\"cl-0f760950\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722466\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0f760951\"><p class=\"cl-0f75cdf0\"><span class=\"cl-0f722484\">Expostos</span></p></td><td class=\"cl-0f76095a\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">a</span></p></td><td class=\"cl-0f76095b\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">b</span></p></td><td class=\"cl-0f760964\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">a + b</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0f760965\"><p class=\"cl-0f75cdf0\"><span class=\"cl-0f722484\">Não Expostos</span></p></td><td class=\"cl-0f760966\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">c</span></p></td><td class=\"cl-0f76096e\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">d</span></p></td><td class=\"cl-0f76096f\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f722484\">c + d</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-0f760978\"><p class=\"cl-0f75cdf0\"><span class=\"cl-0f72248e\">Total</span></p></td><td class=\"cl-0f760982\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f72248e\">a + c</span></p></td><td class=\"cl-0f760983\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f72248e\">b + d</span></p></td><td class=\"cl-0f760984\"><p class=\"cl-0f75cdfa\"><span class=\"cl-0f72248e\">a + b + c + d</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nUsando a @tbl-tab_2x2, a fórmula $odds =\\frac{p}{1 -p}$ e que\n\n$$p_{exp \\ doentes} = \\frac{a}{a+c}$$\n\n$$p_{exp \\ não \\ doentes} = \\frac{b}{b+d}$$ tem-se:\n\n$$odds_{exp} \\ {casos} = \\frac{\\frac{a}{a+c}}{1- \\frac{a}{a+c}}=\\frac{a}{c}$$\n\n$$odds_{exp} \\ {controles} = \\frac{\\frac{b}{b+d}}{1- \\frac{b}{b+d}}=\\frac{b}{d}$$\n\nPortanto, a OR é igual a:\n\n$$OR = \\frac{odds_{exp}\\ {casos}}{odds_{exp}\\ {controles}}=\\frac{\\frac{a}{c}}{\\frac{b}{d}}=\\frac{a \\times d}{c \\times b} $$\n\nEm decorrência da última fórmula, a OR é definida como a razão dos produtos cruzados em uma tabela de contingência 2×2.\n\n#### Exemplo\n\n::: callout-note\n## Cenário\n\nEm um estudo de caso-controle hipotético, a distribuição das exposições entre os casos e um grupo de pessoas saudáveis (“controles”) é comparada entre si. Os casos correspondem a um tipo raro de câncer, onde se suspeita que exista uma associação à exposição a um determinado fator de risco.\n:::\n\nOs dados desse estudo hipotético estão no arquivo `dadosCasoControle.xlsx`. O conjunto de dados pode ser obtido [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosCasoControle.xlsx). Depois de salvo em seu diretório de trabalho, ele pode ser carregado com a função `read_excel()` do pacote `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncc <- readxl::read_excel (\"dados/dadosCasoControle.xlsx\")\n```\n:::\n\n\nAs variáveis `cc$exposto` e `cc$desfecho` devem ser transformadas em fatores e na ordem `sim`, `não`, uma vez que o R coloca em ordem alfabética (`não`, `sim`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncc$exposto <- factor (cc$exposto,\n                      levels = c(\"sim\", \"não\"))\n\ncc$desfecho <- factor (cc$desfecho,\n                       levels = c(\"sim\", \"não\"))\n```\n:::\n\n\nApós essa etapa, construir uma tabela $2 \\times 2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_cc <- table (cc$exposto, \n                 cc$desfecho, \n                 dnn = c(\"Exposição\", \"Desfecho\"))\naddmargins(tab_cc)         \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Desfecho\nExposição sim não Sum\n      sim  48  20  68\n      não  12  40  52\n      Sum  60  60 120\n```\n\n\n:::\n:::\n\n\nA OR será obtida utilizando a função `epi.2by2()` do pacote `epiR` [@stevenson2022epir]. Esta função tem os seguintes argumentos:\n\n- **dat** $\\longrightarrow$ tabela de contingência $2 \\times 2$;\n- **method** $\\longrightarrow$ as opções são “cohort.count”, “cohort.time”, “case.control” ou “cross.sectional”;\n- **conf.level** $\\longrightarrow$ padrão = 0.95;\n- **units** $\\longrightarrow$ multiplicador para incidência e prevalência;\n- **outcome** $\\longrightarrow$ indicação de como a variável desfecho é representada na tabela de contingência (“as.columns” ou “as.rows”).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.2by2(tab_cc, \n               method = \"case.control\", \n               conf.level = 0.95, \n               units = 100, \n               outcome = \"as.columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Outcome+    Outcome-      Total                 Odds\nExposed +          48          20         68  2.40 (1.43 to 4.23)\nExposed -          12          40         52  0.30 (0.13 to 0.53)\nTotal              60          60        120  1.00 (0.69 to 1.45)\n\nPoint estimates and 95% CIs:\n-------------------------------------------------------------------\nExposure odds ratio                            8.00 (3.49, 18.34)\nAttrib fraction (est) in the exposed (%)      87.50 (71.51, 94.51)\nAttrib fraction (est) in the population (%)   70.00 (63.46, 81.10)\nE-value                                        5.10 (3.14, NA)\n-------------------------------------------------------------------\nUncorrected chi2 test that OR = 1: chi2(1) = 26.606 Pr>chi2 = <0.001\nFisher exact test that OR = 1: Pr>chi2 = <0.001\nWald confidence limits\nCI: confidence interval \n```\n\n\n:::\n:::\n\n\nA saída exibe os dados em uma tabela $2 \\times 2$, mostrando as `odds` e os IC~95%~ e outras estatísticas epidemiológicas relacionadas.\n\nA OR varia de zero ao infinito. Quando o valor da OR se aproxima de 1, a doença e o fator de risco não estão associados. Acima de 1 significa que existe associação e valores menores de 1 indicam uma associação negativa (efeito protetor).\n\nNo exemplo hipotético, os indivíduos que se expuseram ao fator de risco têm uma chance 8 vezes maior de apresentar este tipo de câncer. O valor *p* do qui-quadrado é altamente significativo (*p* \\< 0,001).\n\n### Risco Relativo {#sec-rr}\n\nO *Risco relativo* (RR) é a razão entre a incidência de desfecho em indivíduos expostos e a incidência de desfecho em indivíduos não expostos. O RR estima a magnitude da associação entre a exposição e o desfecho (doença). Em outras palavras, compara a probabilidade de ocorrência do desfecho entre os indivíduos expostos com a probabilidade de ocorrência do desfecho nos indivíduos não expostos.\n\nA partir da tabela de contingência $2 \\times 2$ ( @tbl-tab_2x2), tem-se que o estimador do RR é dado por:\n\n$$RR = \\frac{incidência_{exp}}{incidência_{não \\ exp}}=\\frac{\\frac{a}{a + b}}{\\frac{c}{c + d}} $$\n\n#### Exemplo\n\n::: callout-note\n## Cenário\n\nEm 18 de abril de 1940, ocorreu um surto de gastroenterite, após um jantar, em uma igreja (@fig-oswego), na vila de Lycoming, Condado de Oswego, Nova York. Das 80 pessoas que compareceram ao jantar, 46 das 75 entrevistadas desenvolveram posteriormente doença gastrointestinal aguda. Devido à sua natureza direta, o incidente tornou-se um estudo de caso de ensino padrão para gerações de epidemiologistas.\n\n![Igreja de Oswego, 1940](images/oswego.png){#fig-oswego fig-align=\"center\" width=\"8cm\"}\n:::\n\nAs taxas de ataque (incidência) foram calculadas para aqueles que comeram e não comeram cada um dos 14 itens alimentares consumidos na ceia [@gross1976oswego]. O pacote `epitools` [@aragon2020epitools] contém os dados desta investigação no arquivo `oswego`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(oswego)\nstr(oswego)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t75 obs. of  21 variables:\n $ id                 : int  2 3 4 6 7 8 9 10 14 16 ...\n $ age                : int  52 65 59 63 70 40 15 33 10 32 ...\n $ sex                : chr  \"F\" \"M\" \"F\" \"F\" ...\n $ meal.time          : chr  \"8:00 PM\" \"6:30 PM\" \"6:30 PM\" \"7:30 PM\" ...\n $ ill                : chr  \"Y\" \"Y\" \"Y\" \"Y\" ...\n $ onset.date         : chr  \"4/19\" \"4/19\" \"4/19\" \"4/18\" ...\n $ onset.time         : chr  \"12:30 AM\" \"12:30 AM\" \"12:30 AM\" \"10:30 PM\" ...\n $ baked.ham          : chr  \"Y\" \"Y\" \"Y\" \"Y\" ...\n $ spinach            : chr  \"Y\" \"Y\" \"Y\" \"Y\" ...\n $ mashed.potato      : chr  \"Y\" \"Y\" \"N\" \"N\" ...\n $ cabbage.salad      : chr  \"N\" \"Y\" \"N\" \"Y\" ...\n $ jello              : chr  \"N\" \"N\" \"N\" \"Y\" ...\n $ rolls              : chr  \"Y\" \"N\" \"N\" \"N\" ...\n $ brown.bread        : chr  \"N\" \"N\" \"N\" \"N\" ...\n $ milk               : chr  \"N\" \"N\" \"N\" \"N\" ...\n $ coffee             : chr  \"Y\" \"Y\" \"Y\" \"N\" ...\n $ water              : chr  \"N\" \"N\" \"N\" \"Y\" ...\n $ cakes              : chr  \"N\" \"N\" \"Y\" \"N\" ...\n $ vanilla.ice.cream  : chr  \"Y\" \"Y\" \"Y\" \"Y\" ...\n $ chocolate.ice.cream: chr  \"N\" \"Y\" \"Y\" \"N\" ...\n $ fruit.salad        : chr  \"N\" \"N\" \"N\" \"N\" ...\n```\n\n\n:::\n:::\n\n\nExistem 75 observações de 21 variáveis, algumas características dos indivíduos como idade, sexo, etc. Importante para a análise é a variável `ill` (Y – sim, doente; N – não doente) e a variáveis relacionadas aos alimentos ingeridos durante o jantar na igreja. O sorvete de baunilha foi considerado o principal responsável pelo surto.\n\nA seguir, as variáveis `oswego$vanilla.ice.cream` e `oswego$ill` [^22-medidasocorrencia-1] serão transformadas em fator e os níveis colocados na ordem `Y`, `N`, uma vez que o R coloca em ordem alfabética (`N`, `Y`) :\n\n[^22-medidasocorrencia-1]: Foi mantido o nome das variáveis em inglês, pois no banco de dados `oswego` elas estão nessa língua.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noswego$ill <- factor (oswego$ill,\n                      levels = c (\"Y\", \"N\"))\noswego$vanilla.ice.cream <- factor (oswego$vanilla.ice.cream,\n                                    levels = c (\"Y\", \"N\"))\n```\n:::\n\n\nRealizada essa etapa, será construída uma tabela para o cálculo do RR:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_vanilla <- table (oswego$vanilla.ice.cream, \n                      oswego$ill, \n                      dnn = c (\"Vanilla\", \"Ill\"))\ntab_vanilla            \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Ill\nVanilla  Y  N\n      Y 43 11\n      N  3 18\n```\n\n\n:::\n:::\n\n\nO RR será obtido, utilizando a função `epi.2by2()` do pacote `epiR`, cujos argumentos foram mostrados no cálculo da OR, mudando a tabela para `tab_vanilla` e `method = “cohort.count”`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.2by2(tab_vanilla, \n               method = \"cohort.count\", \n               conf.level = 0.95, \n               units = 100, \n               outcome = \"as.columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Outcome+    Outcome-      Total                 Inc risk *\nExposure+          43          11         54     79.63 (66.47 to 89.37)\nExposure-           3          18         21      14.29 (3.05 to 36.34)\nTotal              46          29         75     61.33 (49.38 to 72.36)\n\nPoint estimates and 95% CIs:\n-------------------------------------------------------------------\nInc risk ratio                                 5.57 (1.94, 16.03)\nInc odds ratio                                 23.45 (5.84, 94.18)\nAttrib risk in the exposed *                   65.34 (46.92, 83.77)\nAttrib fraction in the exposed (%)            82.06 (55.87, 93.79)\nAttrib risk in the population *                47.05 (28.46, 65.63)\nAttrib fraction in the population (%)         76.71 (49.78, 93.83)\nE-value                                        10.62 (3.29, NA)\n-------------------------------------------------------------------\nUncorrected chi2 test that OR = 1: chi2(1) = 27.223 Pr>chi2 = <0.001\nFisher exact test that OR = 1: Pr>chi2 = <0.001\nWald confidence limits\nCI: confidence interval\n* Outcomes per 100 population units \n```\n\n\n:::\n:::\n\n\nOs resultados da saída indicam que os indivíduos que ingeriram sorvete de baunilha (n = 54) tiveram um risco maior de desenvolver gastrenterite aguda quando comparado aos que não ingeriram (n = 21). Dividindo o risco dos indivíduos expostos (incidência = 79,6%) pelo risco dos não expostos (incidência = 14,3%), encontra-se o RR = 5,57. Isso confirma que o sorvete de baunilha foi o principal responsável.\n\nQuanto maior o RR mais forte é a associação entre a doença em questão e a exposição ao fator de risco. Um RR = 1 indica que a doença e a exposição ao fator de risco não estão associadas. Valores \\< 1 indicam uma associação negativa entre o fator de risco e a doença (efeito protetor).\n\n### *Odds Ratio* vs Risco Relativo\n\nA OR não deve ser entendida como uma medida aproximada do RR, exceto para doenças raras (doenças, em geral com prevalência menor do que 10%). Caso contrário, a OR tenderá a superestimar a magnitude da associação e o OR afasta-se da hipótese nula da não associação (OR = 1), independentemente de ser um fator de risco ou de proteção. A discrepância (d)[^22-medidasocorrencia-2] entre as estimativas do RR e OR pode ser definido como a razão entre o OR e o RR estimados [@szklo2019associations]. Em outras palavras, a discrepância corresponde a uma proporção do RR [@davies1998can].\n\n[^22-medidasocorrencia-2]: em inglês, *built-in bias*\n\n$$d = \\frac {1- p_{não \\ exp}}{1- p_{exp}}= \\frac{\\frac{c}{c + d}}{\\frac{a}{a + b}}$$\n\nLogo,\n\n$$OR = RR \\times d$$\n\nPara finalizar, uma comparação entre OR e RR é mostrada na [@tbl-magnitude] [@hopkins2016scales].\n\n\n::: {#tbl-magnitude .cell tbl-cap='Força de associação do RR comparado com a OR.'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-10134ca6{}.cl-10071b3e{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-10071b48{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-100be4a2{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-100c2674{width:0.727in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c2688{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c2689{width:0.727in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c2692{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c2693{width:0.727in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-100c2694{width:1.253in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-10134ca6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-100c2674\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b3e\">OR</span></p></th><th class=\"cl-100c2674\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b3e\">RR</span></p></th><th class=\"cl-100c2688\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b3e\">Magnitude</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">1,0</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">1,0</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">insignificante</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">1,5</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">1,2</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">pequena</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">3,5</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">1,9</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">moderada</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">9,0</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">3,0</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">grande</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">32</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">5,7</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">muito grande</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">360</span></p></td><td class=\"cl-100c2689\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">19</span></p></td><td class=\"cl-100c2692\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">quase perfeita</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-100c2693\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">infinito</span></p></td><td class=\"cl-100c2693\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">infinito</span></p></td><td class=\"cl-100c2694\"><p class=\"cl-100be4a2\"><span class=\"cl-10071b48\">perfeita</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n### Razão de Prevalência\n\nQuando dados transversais estão disponíveis, muitas vezes as associações são avaliadas, usando a *razão de prevalência pontual* (RPP).\n\nTendo o mesmo princípio das duas medidas anteriores, a razão de prevalência (RPP) compara a prevalência do desfecho entre os expostos com a prevalência do desfecho entre os não expostos.\n\nMatematicamente, a RPP é calculada de maneira semelhante ao RR. Apenas, deve-se ter em mente que o desfecho e a exposição foram medidos no mesmo momento, enquanto para o cálculo do RR há necessidade de calcular a incidência.\n\nTomando como base a estrutura da tabela de contingência 2 x 2 , @tbl-tab_2x2, tem-se:\n\n$$RPP = \\frac{prevalência \\ de \\ doença_{exp}}{prevalência \\ de \\ doença_{não \\ exp}}=\\frac{\\frac{a}{a + b}}{\\frac{c}{c + d}} $$\n\nTambém é possível verificar a prevalência de exposição entre doentes e não doentes:\n\n$$RPP = \\frac{prevalência \\ de \\ exposição_{doentes}}{prevalência \\ de \\ exposição_{não \\ doentes}}=\\frac{\\frac{a}{a + c}}{\\frac{b}{b + d}} $$\n\n#### Exemplo\n\n::: callout-note\n## Cenário\n\nEm um estudo transversal [@madi2010prevalence], foi verificada a prevalência de infecções congênitas entre as puérperas com idade igual ou acima de 20 anos comparadas às mulheres com menos de 20 anos (adolescentes). A hipótese foi de que as adolescentes tinham uma prevalência maior de infecções.\n:::\n\nParte dos dados estão no arquivo `dadosMater.xlsx`, que contém, como já mencionado, informações de 1368 nascimentos. Entre essas, tem-se a idade das mães (`idade_mae`) e se foi diagnosticada infecção congênita (`inf_cong`).\n\nO arquivo pode ser obtido [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosMater.xlsx). Depois de salvo em seu diretório de trabalho, ele pode ser carregado com a função `read_excel()` do pacote `readxl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- readxl::read_excel (\"dados/dadosMater.xlsx\")\n```\n:::\n\n\nA partir da variável `idade_mae`, criar a variável `faixaEtaria`, dividindo as parturientes em menores de 20 anos (adolescentes) e ≥ 20 anos. Para isso, usou-se a função `cut()` do pacote base. Revise os argumentos desta função.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$faixaEtaria <- cut (dados$idade_mae,\n                          breaks=c(13,20,46),\n                          labels = c(\"<20a\",\"=>20a\"),\n                          right = FALSE,\n                          include.lowest = TRUE)\n```\n:::\n\n\nA variável `inf_cong` encontra-se como uma variável numérica e deve ser transformada em fator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados$inf_cong <- factor (dados$inf_cong,\n                         ordered = TRUE, \n                         levels = c (1,2),\n                         labels = c (\"sim\", \"não\"))\n```\n:::\n\n\nApós estes procedimentos, constrói-se uma tabela $2 \\times 2$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_infCong <- table(dados$faixaEtaria,\n                     dados$inf_cong,\n                     dnn = c(\"Faixa Etária\", \"Inf. Cong.\"))\naddmargins(tab_infCong)            \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Inf. Cong.\nFaixa Etária  sim  não  Sum\n       <20a     7  212  219\n       =>20a  119 1030 1149\n       Sum    126 1242 1368\n```\n\n\n:::\n:::\n\n\n[Cálculo da RPP]{.underline}\n\nUsando a tabela `tab_infCong` com a função `epi.2by2()` do pacote `epiR`, cujos argumentos foram mostrados no cálculo da OR e RR, e mudando a tabela para `tab_infCong` e `method = “cross.sectional”`, obtem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nepiR::epi.2by2(tab_infCong, \n               method = \"cross.sectional\", \n               conf.level = 0.95, \n               units = 100, \n               outcome = \"as.columns\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Outcome+ Outcome- Total               Prev risk *\nExposure+        7      212   219       3.20 (1.29 to 6.47)\nExposure-      119     1030  1149     10.36 (8.65 to 12.26)\nTotal          126     1242  1368      9.21 (7.73 to 10.87)\n\nPoint estimates and 95% CIs:\n-------------------------------------------------------------------\nPrev risk ratio                                0.31 (0.15, 0.65)\nPrev odds ratio                                0.29 (0.13, 0.62)\nAttrib prev in the exposed *                   -7.16 (-10.08, -4.24)\nAttrib fraction in the exposed (%)            -224.02 (-577.43, -57.46)\nAttrib prev in the population *                -1.15 (-3.48, 1.19)\nAttrib fraction in the population (%)         -12.45 (-12.85, -11.96)\nE-value                                        5.93 (NA, 2.44)\n-------------------------------------------------------------------\nUncorrected chi2 test that OR = 1: chi2(1) = 11.278 Pr>chi2 = <0.001\nFisher exact test that OR = 1: Pr>chi2 = <0.001\nWald confidence limits\nCI: confidence interval\n* Outcomes per 100 population units \n```\n\n\n:::\n:::\n\n\nA saída exibe várias informações. Foi feita a hipótese de uma maior prevalência entre as mulheres com menos de 20 anos. Por este motivo, elas aparecem como as expostas (`Exposed +`) e tem uma prevalência de 3,20/100, enquanto as mulheres com mais de 20 anos tiveram uma prevalência de 10,36/100. Isto mostra que a razão de prevalência é igual a 0,31 (IC~95%~: 0,15-0,65)[^22-medidasocorrencia-3], ou seja, abaixo de 1, sugerindo que ao contrário da hipótese inicial, as adolescentes têm, neste estudo, uma menor prevalência de infecções congênitas.\n\n[^22-medidasocorrencia-3]: Observem que todo o intervalo de confiança de ~95%~ encontra-se abaixo de 1, indicando que existe significância estatística.\n\n## Medidas de impacto\n\n### Risco Atribuível\n\nO *Risco Atribuível* (RA) possui características de medida de impacto. O RA, ao invés de concentrar-se na associação em si, refere-se mais às consequências e às repercussões da exposição sobre a ocorrência do desfecho.\n\nO RA é a medida do excesso ou acréscimo absoluto de risco que pode ser atribuído à exposição [@szklo2019ar]. Com o RA é possível estimar o número de casos que podem ser prevenidos se a exposição for eliminada e assim estimar a magnitude do impacto, em termos de saúde pública, imposto por esta exposição.\n\nO risco de desenvolver o desfecho (incidência) está aumentado em RA nos indivíduos expostos em comparação com os que não estão expostos. Nos estudos de coorte, costuma-se usar mais a expressão *Risco Atribuível* ou *Diferença de Risco*. Nos ensaios clínicos, usa-se mais a expressão *Redução Absoluta do Risco* (RAR), pois se espera que a intervenção reduza o risco.\n\nCalcula-se o RA ou a RAR pela diferença absoluta entre as incidências dos expostos e não expostos:\n\n$$RA = \\left|I_{expostos} - I_{não \\ expostos}\\right|$$\n\nUtilizando a tabela de contingência $2 \\times 2$ ( @tbl-tab_2x2), o RA fica expresso da seguinte maneira:\n\n$$RA = \\left|\\frac{a}{a + b} -\\frac{c}{c + d}\\right|$$\n\nNo exemplo do Risco Relativo, o RA pode ser calculado usando a mesma tabela de contingência, repetida aqui para facilitar a leitura (@tbl-vanilla):\n\n\n::: {#tbl-vanilla .cell layout-align=\"center\" tbl-cap='Taxa de ataque de gastrenterite com sorvete de baunilha - Oswego'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-1076e13a{}.cl-1069f8ee{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(255, 255, 255, 1.00);background-color:transparent;}.cl-1069f902{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-106fc88c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-106fc896{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-106ff276{width:1.321in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff280{width:1.206in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff281{width:1.168in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff28a{width:0.65in;background-color:rgba(43, 76, 126, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff294{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff295{width:1.206in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff29e{width:1.168in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff29f{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff2a8{width:1.321in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff2b2{width:1.206in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff2b3{width:1.168in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-106ff2bc{width:0.65in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-1076e13a'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-106ff276\"><p class=\"cl-106fc88c\"><span class=\"cl-1069f8ee\"></span></p></th><th class=\"cl-106ff280\"><p class=\"cl-106fc896\"><span class=\"cl-1069f8ee\">Desfecho (+)</span></p></th><th class=\"cl-106ff281\"><p class=\"cl-106fc896\"><span class=\"cl-1069f8ee\">Desfecho (-)</span></p></th><th class=\"cl-106ff28a\"><p class=\"cl-106fc896\"><span class=\"cl-1069f8ee\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-106ff294\"><p class=\"cl-106fc88c\"><span class=\"cl-1069f902\">Comeu sorvete</span></p></td><td class=\"cl-106ff295\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">43</span></p></td><td class=\"cl-106ff29e\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">11</span></p></td><td class=\"cl-106ff29f\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">54</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-106ff2a8\"><p class=\"cl-106fc88c\"><span class=\"cl-1069f902\">Não comeu</span></p></td><td class=\"cl-106ff2b2\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">3</span></p></td><td class=\"cl-106ff2b3\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">18</span></p></td><td class=\"cl-106ff2bc\"><p class=\"cl-106fc896\"><span class=\"cl-1069f902\">21</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nLogo,\n\n$$RA = \\left|\\frac{43}{43 + 11} -\\frac{3}{3 + 18}\\right| = \\left|0,796 - 0,143\\right| = 0,653$$\n\nO risco atribuível na exposição mede o excesso de risco associado a uma determinada categoria de exposição. Por exemplo, com base no exemplo, a incidência cumulativa de gastrenterite aguda entre os indivíduos que comeram o sorvete de baunilha é de 79,6% e para os que não ingeriram o sorvete (categoria de referência ou não exposta) foi de 14,3%. Desta forma, o risco excessivo associado à exposição 79,6 – 14,3 = 65,3%. Ou seja, assumindo uma associação causal (sem confusão ou viés), a não ocorrência da festa diminuiria o risco no grupo exposto de 79,6% para 14,3%.\n\nO RA expresso em relação à incidência nos expostos e apresentado em percentual é denominado de *Risco Atribuível Proporcional* (RAP) ou *Fração Atribuível nos Expostos*.\n\nO RAP informa qual a proporção de desfecho, expresso em percentagem, entre os expostos que poderia ter sido prevenida se a exposição fosse eliminada. É dado pela fórmula:\n\n$$RAP = \\left(\\frac{I_{expostos} - I_{não \\ expostos}}{I_{expostos}}\\right) \\times 100$$\n\nNo exemplo do surto de gastrenterite aguda no jantar da igreja de Oswego (@sec-rr), tem-se:\n\n$$RAP = \\left(\\frac{0,796 - 0,143}{0,796}\\right) \\times 100 = 82,06 \\%$$\n\nSe a causalidade foi estabelecida, essa medida pode ser interpretada como a porcentagem do risco total de gastrenterite aguda que é atribuível à ingesta de sorvete de baunilha.\n\nOutra maneira de se chegar a este mesmo resultado é através do RR, usando a seguinte fórmula\n\n$$RAP = \\left(\\frac{I_{expostos} - I_{não \\ expostos}}{I_{expostos}}\\right) \\times 100$$\n\n$$RAP = \\left(\\frac{I_{expostos}}{I_{expostos}} - \\frac{I_{não \\ expostos }}{I_{expostos}}\\right) \\times 100$$\n\n$$RAP = \\left(1 - \\frac{1}{\\frac{I_{expostos }}{I_{não \\ expostos}}}\\right) \\times 100$$\n\n$$RAP = \\left(1 - \\frac{1}{RR}\\right) \\times 100$$\n\n$$RAP = \\left(\\frac{RR - 1}{RR}\\right) \\times 100$$\n\nNo exemplo, o RR é igual a 5,57, logo:\n\n$$RAP = \\left(\\frac{5,57 - 1}{5,57}\\right) \\times 100 = 82,05\\%$$\n\n### Redução Relativa do Risco\n\nQuando se avalia um tratamento ou alguma intervenção em que se suponha haver uma redução do risco — por exemplo, o uso da aspirina para reduzir a ocorrência de infarto agudo do miocárdio —, o termo *Risco Atribuível* é substituído por *Redução do Risco Atribuível* e é calculado da mesma forma apresentada na equação do Risco Atribuível.\n\nNeste caso, ao invés de usar o Risco Atribuível Proporcional (RAP), onde se pressupõe que a exposição é um fator de risco para a doença e o RR $>$ 1, usa-se a *Redução Relativa do Risco*, pois a exposição é supostamente um fator protetor, como se espera que ocorra nos ensaios clínicos.\n\nEsta medida, análoga ao RAP, é também chamada de *Eficácia*, definida como a proporção da incidência nos indivíduos não tratados (por exemplo, o grupo controle) que é reduzida pela intervenção [@szklo2019rrr].\n\nO cálculo da **Redução Relativa do Risco** (RRR) é semelhante ao Risco Atribuível Proporcional (RAP), onde a incidência nos expostos é a incidência no grupo que recebeu a intervenção (ou taxa de eventos no grupo tratamento) e a incidência nos não expostos é incidência nos controles (ou taxa de eventos nos controles – TEC). Como se supõe que a incidência nos controles seja maior que a incidência no grupo de tratamento, a equação fica:\n\n$$RRR = \\left(\\frac{I_{controle} - I_{tratamento}}{I_{controle}}\\right) \\times 100$$\n\nAlternativamente, a RRR pode ser estimada pela equação:\n\n$$RRR = \\left(1 - RR\\right) \\times 100$$\n\nO *Physicians' Health Study* [@steering1989final] é um ensaio clinico randomizado controlado, duplo cego, desenhado com o objetivo de determinar se uma dose baixa de aspirina (325 mg a cada 48 horas) diminui a mortalidade cardiovascular e se o betacaroteno reduz a incidência de câncer. Participaram deste estudo 22071 indivíduos por uma média de 60,2 meses.\n\nO estudo do componente aspirina mostrou os seguintes resultados (@tbl-aspirina):\n\n\n::: {#tbl-aspirina .cell layout-align=\"center\" tbl-cap='Physicians\\' Health Study, componente aspirina e IAM'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-10a85288{}.cl-109d046e{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-109d0478{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-10a1baae{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-10a1e3b2{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3bc{width:0.565in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3c6{width:0.973in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3c7{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3d0{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3d1{width:0.565in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3d2{width:0.973in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3da{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3db{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3e4{width:0.565in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3ee{width:0.973in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-10a1e3ef{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-10a85288'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-10a1e3b2\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\"></span></p></th><th  colspan=\"2\"class=\"cl-10a1e3bc\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\">Eventos por ano</span></p></th><th class=\"cl-10a1e3c7\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\"></span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-10a1e3d0\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\">Grupo</span></p></th><th class=\"cl-10a1e3d1\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\">IAM</span></p></th><th class=\"cl-10a1e3d2\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\">Sem_IAM</span></p></th><th class=\"cl-10a1e3da\"><p class=\"cl-10a1baae\"><span class=\"cl-109d046e\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-10a1e3db\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">Aspirina</span></p></td><td class=\"cl-10a1e3e4\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">139</span></p></td><td class=\"cl-10a1e3ee\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">10.898</span></p></td><td class=\"cl-10a1e3ef\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">11.037</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-10a1e3d0\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">Placebo</span></p></td><td class=\"cl-10a1e3d1\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">239</span></p></td><td class=\"cl-10a1e3d2\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">10.795</span></p></td><td class=\"cl-10a1e3da\"><p class=\"cl-10a1baae\"><span class=\"cl-109d0478\">11.034</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA incidência cumulativa de Infarto Agudo de Miocárdio (IAM) em ambos os grupos foi:\n\n$$Incidencia_{aspirina} = \\frac{139}{11037} = 0,0126$$\n\n$$Incidencia_{placebo} = \\frac{239}{11034} = 0,0217$$\n\n$$RR = \\frac{0,0126}{0,0217} = 0,58$$\n\nLogo, a RRR é igual a:\n\n$$RRR = \\left(1 - 0,58\\right) \\times 100 = 42\\%$$\n\nOu seja, houve uma redução de 42% no risco de IAM no grupo que usou aspirina e a conclusão dos autores foi que este ensaio clínico demonstrou, em relação à prevenção primária de doença cardiovascular, uma diminuição no risco de IAM.\n\nEstes cálculos podem ser realizados com a função `risks()` do pacote `MKmisc` [@kohl2019package]. Esta função calcula o risco relativo (RR), odds ratio (OR), redução relativa do risco (RRR) e outras estatísticas epidemiológicas, como RAR, NNT.\n\nA função `risks()` usa como argumento:\n\n- **p0** $\\longrightarrow$ incidência do desfecho de interesse no grupo não exposto;\n- **p1** $\\longrightarrow$ incidência do desfecho de interesse no grupo exposto.\n\nAlém disso, para o seu funcionamento, deve-se ter instalado o pacote `BiocManager` para poder instalar o pacote `limma`, necessário para a execução do pacote `MKmisc`. Veja início do capítulo em pacotes usados neste capítulo.\n\nA função `risks()` será usada dentro da função `round()` para reduzir o número de dígitos decimais:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0 <- 0.0217\np1 <- 0.0126\nround(MKmisc::risks(p0,p1), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      p0       p1       RR       OR      RRR      ARR      NNT \n  0.0217   0.0126   0.5806   0.5753   0.4194   0.0091 109.8901 \n```\n\n\n:::\n:::\n\n\n### Número Necessário para Tratar\n\nOs resultados da função `risks()` entregam junto o *Número Necessário para Tratar* (NNT) que deve ser arredondado para o número inteiro mais próximo (no caso, 110) e significa a estimativa do número de indivíduos que devem receber uma intervenção terapêutica, durante um período específico de tempo, para evitar um efeito adverso ou produzir um desfecho positivo.\n\nO NNT equivale à recíproca do RAR (Redução Absoluta do Risco ou Diferença de Risco):\n\n$$NNT = \\frac{1}{RAR} = \\frac{1}{I_{não \\ expostos} - I_{expostos}}$$\n\nNo exemplo do *Physicians' Health Study* @steering1989final, o RAR é igual a:\n\n$$RA = \\left|I_{expostos} - I_{não \\ expostos}\\right| = \\left|0,0126 - 0,0217\\right| = 0,0091$$\n\n$$NNT = \\frac{1}{0,0091} = 109,89 \\simeq 110$$\n\nPode-se calcular os IC~95%~, calculando o NNT para os limites do RAR usando a seguinte equação [@bender2001calculating]:\n\n$$IC_{95\\%} \\longrightarrow RAR \\pm z_{\\left({1 - \\frac{\\alpha}{2}}\\right)} \\times EP_{RAR}$$ Onde,\n\n$$EP_{RAR} = \\sqrt{\\frac{p0\\left(1 - p0\\right)}{n_{1}}+\\frac{p1\\left(1 - p1\\right)}{n_{2}}}$$\n\nUsando esses dados, pode-se criar um *script* no *RStudio* para os cálculos:\n\n[Vetor dos dados]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 139\nb <- 10898\nc <- 239\nd <- 10795\ndados <- c (a, b, c, d)\n```\n:::\n\n\n[Matriz dos dados]{.underline}[^22-medidasocorrencia-4]\n\n[^22-medidasocorrencia-4]: Aproveite para revisar como construir matriz\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmat_iam <- matrix (dados, byrow = TRUE, nrow = 2)\ntratamento <- c (\"aspirina\", \"placebo\")\ndesfecho <- c (\"IAM\", \"s/IAM\")\nrownames (mat_iam) <- tratamento\ncolnames (mat_iam) <- desfecho\nmat_iam\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         IAM s/IAM\naspirina 139 10898\nplacebo  239 10795\n```\n\n\n:::\n:::\n\n\n[Cálculo das incidências no grupo tratamento e no grupo placebo]{.underline}\n\nNa matriz o que está entre colchetes \\[1,1\\] significa: linha 1 e coluna 1, ou seja, o valor 139.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <-mat_iam [1,1] + mat_iam [1,2]\nn1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11037\n```\n\n\n:::\n\n```{.r .cell-code}\np1 <- mat_iam [1,1] / n1\nround (p1, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0126\n```\n\n\n:::\n\n```{.r .cell-code}\nn0 <- mat_iam [2,1] + mat_iam [2,2]\nn0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11034\n```\n\n\n:::\n\n```{.r .cell-code}\np0 <- mat_iam [2,1] / n0\nround (p0, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0217\n```\n\n\n:::\n:::\n\n\nOs resultados da matriz de dados e o cálculo das incidências *p0* (incidência no grupo placebo) e *p1* (incidência no grupo de tratamento) já eram conhecidos e foram repetidos apenas para entrar na programação do cálculo do IC~95%~.\n\n[Cálculo do erro padrão da RAR]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRAR <- abs(p0 - p1)\nNNT <- 1/RAR\n\nalpha <- 0.05\nz <- qnorm (1 - (alpha/2))\nround (z, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.96\n```\n\n\n:::\n\n```{.r .cell-code}\nEP_RAR <- sqrt((((p0*(1-p0)) / n0)) + (((p1*(1-p1)) / n1)))\n\n# Limite inferior\nli_RAR <- RAR - (z * EP_RAR)\nround (li_RAR, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0056\n```\n\n\n:::\n\n```{.r .cell-code}\n# Limite superior\nls_RAR <- RAR + (z * EP_RAR)\nround (ls_RAR, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0125\n```\n\n\n:::\n\n```{.r .cell-code}\nround(c(li_RAR, RAR, ls_RAR), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0056 0.0091 0.0125\n```\n\n\n:::\n:::\n\n\nPortanto, a Redução Absoluta do Risco foi igual a 0,0091 (IC~95%~: 0,0056-0,0125). A partir destes resultados, pode-se calcular o intervalo de confiança para o NNT:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nli_NNT <- 1/ls_RAR\nls_NNT <- 1/li_RAR\n\nli_NNT \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 80.07881\n```\n\n\n:::\n\n```{.r .cell-code}\nls_NNT\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 177.1497\n```\n\n\n:::\n:::\n\n\nConcluindo, o uso da aspirina no *Physicians' Health Study* reduziu o risco de infarto agudo do miocárdio em 42% (RRR), ou seja, foi eficaz. Por outro lado, para ter este impacto será necessário tratar 110 (IC~95%~: 80-177) pacientes para que um tenha benefício. Este NNT é grande; o ideal é um NNT \\< 10. Apesar disso, como a aspirina tem baixo custo e seus benefícios suplantam os efeitos adversos, seu uso pode estar justificado.\n\n### Número Necessário para Causar Dano\n\nDeve-se comparar o NNT com o *Número Necessário para causar Dano* (NND), em inglês, *Number Needed to Harm* (NNH). Deve ser interpretado como o número de pacientes tratados para que um deles apresente um efeito adverso.\n\nO NND é calculado pela recíproca do aumento absoluto do risco (ARA), equivalente a diferença de risco ou redução absoluta do risco:\n\n$$NND = \\frac{1}{ARA} = \\frac{1}{I_{expostos} - I_{não \\ expostos}}$$\n\n#### Exemplo\n\nNo *Physicians' Health Study* [@steering1989final] sobre o uso de aspirina na prevenção de IAM, foi verificado também os efeitos colaterais da aspirina, como acidentes vasculares cerebrais (AVC), @tbl-avc.\n\n\n::: {#tbl-avc .cell layout-align=\"center\" tbl-cap='Physicians\\' Health Study, componente aspirina e AVC.'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-11082320{}.cl-10f9f354{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-10f9f368{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-11000a8c{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-110054c4{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054ce{width:0.608in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054d8{width:1.015in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054e2{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054e3{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054e4{width:0.608in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054ec{width:1.015in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054ed{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054f6{width:0.837in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-110054f7{width:0.608in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-11005500{width:1.015in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-11005501{width:0.752in;background-color:transparent;vertical-align: middle;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-11082320'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-110054c4\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\"></span></p></th><th  colspan=\"2\"class=\"cl-110054ce\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\">Eventos por ano</span></p></th><th class=\"cl-110054e2\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\"></span></p></th></tr><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-110054e3\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\">Grupo</span></p></th><th class=\"cl-110054e4\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\">AVC</span></p></th><th class=\"cl-110054ec\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\">Sem_AVC</span></p></th><th class=\"cl-110054ed\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f354\">Total</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-110054f6\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">Aspirina</span></p></td><td class=\"cl-110054f7\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">119</span></p></td><td class=\"cl-11005500\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">10.918</span></p></td><td class=\"cl-11005501\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">11.037</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-110054e3\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">Placebo</span></p></td><td class=\"cl-110054e4\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">98</span></p></td><td class=\"cl-110054ec\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">10.936</span></p></td><td class=\"cl-110054ed\"><p class=\"cl-11000a8c\"><span class=\"cl-10f9f368\">11.034</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n[Cálculo das incidências]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0 <- 98/11034\nround(p0, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0089\n```\n\n\n:::\n\n```{.r .cell-code}\np1 <- 119/11037\nround(p1, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0108\n```\n\n\n:::\n:::\n\n\nPara o cálculo do NND, usa-se a função `risks()`, como mencionado antes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np0 <- 0.0089\np1 <- 0.0108\nround (MKmisc::risks (p0, p1), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      p0       p1       RR       OR      RRI      ARI      NNH \n  0.0089   0.0108   1.2135   1.2158   0.2135   0.0019 526.3158 \n```\n\n\n:::\n:::\n\n\nOs resultados mostram que o NND[^22-medidasocorrencia-5] é igual a 526. Ou seja, para evitar um IAM há necessidade de tratar 110 pacientes e a cada 526 tratados espera-se um caso de AVC, havendo um benefício bem maior quando comparado ao risco de AVC.\n\n[^22-medidasocorrencia-5]: Em inglês, NNH (number needed to harm).\n",
    "supporting": [
      "22-medidasOcorrencia_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}