{
  "hash": "b2c5272886ade8b3ec85851e9cba0572",
  "result": {
    "engine": "knitr",
    "markdown": "# Anova de Medidas Repetidas\n\n## Pacotes usados neste capítulo\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(afex, \n               effectsize,\n               emmeans,\n               flextable,  \n               ggbeeswarm,\n               ggpubr, \n               ggsci, \n               knitr, \n               readxl, \n               rstatix, \n               tidyverse)\n```\n:::\n\n\n## Anova de Medidas Repetidas com um Fator\n\n### Introdução\n\nA ANOVA de medidas repetidas (*Repeated Measures ANOVA*) é uma técnica estatística usada quando o mesmo grupo de participantes é medido várias vezes, seja ao longo do tempo ou sob diferentes condições. Ela é ideal para dados longitudinais ou experimentos intra-sujeitos, onde cada sujeito serve como seu próprio controle. São exemplos típicos:\n\n• Medir a qualidade de vida de crianças asmáticas em vários momentos para avaliar o impacto de um programa de atenção ao asmático;\n\n• Testar tempos de reação em um teste em três tempos em um mesmo grupo;\n\n• Testar a autoestima de um mesmo grupo após a introdução de um tipo especial de dieta.\n\nA @tbl-compare mostra algumas diferenças importantes entre a ANOVA e a ANOVA de Medidas Repetidas:\n\n\n::: {#tbl-compare .cell tbl-cap='Comparação entre ANOVA e ANOVA de medidas repetidas'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-fec10ef6{}.cl-feb3ba26{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-feb3ba44{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-feb97f10{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-feb9f27e{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-feb9f288{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-feb9f292{width:2.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-fec10ef6'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-feb9f27e\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba26\">Característica</span></p></th><th class=\"cl-feb9f27e\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba26\">ANOVA (entre sujeitos)</span></p></th><th class=\"cl-feb9f27e\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba26\">ANOVA de Medidas Repetidas (intra-sujeitos)</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Tipo de Amostra</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Grupos independentes</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Mesmos sujeitos em diferentes condições</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Controle da variabilidade individual</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Não controla</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Controla (cada sujeito é seu próprio controle)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Sensibilidade estatística</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Menor</span></p></td><td class=\"cl-feb9f288\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Maior (reduz o erro residual)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-feb9f292\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Suposição de esfericidade</span></p></td><td class=\"cl-feb9f292\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Não se aplica</span></p></td><td class=\"cl-feb9f292\"><p class=\"cl-feb97f10\"><span class=\"cl-feb3ba44\">Necessária (testada com o teste de Mauchly)</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA ANOVA de medidas repetidas é mais poderosa estatisticamente porque reduz a variabilidade entre sujeitos, focando nas mudanças dentro de cada indivíduo. A ANOVA de medidas repetidas pode ser entendida como uma expansão da ANOVA [@anunciacao2021anovarep].\n\nA **ANOVA de medidas repetidas de um fator** é uma técnica estatística que compara as médias de três ou mais grupos relacionados, onde os mesmos participantes são medidos repetidamente em diferentes momentos ou condições para avaliar a mudança em uma variável dependente. É uma extensão do teste *t* pareado para mais de dois grupos e, por avaliar o mesmo grupo ao longo do tempo, controla diferenças individuais.\n\n### Dados usados no exemplo {#sec-dadoscap16}\n\n::: callout-note\n### Cenário do exemplo\n\nUm estudo, realizado em um ambulatório de Doenças Respiratórias Pediátricas, avaliou a função pulmonar de um grupo de crianças por um período de 3 meses (0, 45 dias, 90 dias) usando um novo corticoide inalatório. Todas as crianças tinham idade entre 7 e 15 anos e a medida avaliadora foi PFE (Pico de Fluxo Expiratório) que corresponde a taxa máxima de ar expelida pelos pulmões durante uma expiração forçada, indicador importante da função pulmonar, especialmente no monitoramento de asma.\n:::\n\nOs dados podem ser obtidos [aqui](https://github.com/petronioliveira/Arquivos/blob/main/dadosAsma.xlsx). Baixe no seu diretório de trabalho e carregue com a função `read_excel()` do pacote `readxl`. Na ANOVA de medidas repetidas de um fator, será usado apenas o grupo, denominado de `caso`, que usou o medicamento testado.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_uni <- readxl::read_excel(\"dados/dadosAsma.xlsx\")  |>  \n  dplyr::filter(grupo == \"caso\") |> \n  dplyr::select(id, t0, t1, t2)\n\nstr(dados_uni)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [41 × 4] (S3: tbl_df/tbl/data.frame)\n $ id: num [1:41] 1 2 3 4 5 6 7 8 9 10 ...\n $ t0: num [1:41] 170 100 160 180 250 180 170 180 240 200 ...\n $ t1: num [1:41] 180 140 180 180 300 200 180 200 320 200 ...\n $ t2: num [1:41] 220 100 220 250 240 280 220 250 350 250 ...\n```\n\n\n:::\n:::\n\n\n#### Exploração e transformação dos dados\n\nObservando a saída da função `str()`, verifica-se os dados se encontram no formato amplo (a variável tempo está colocada em três colunas, t~0~, t~1~, t~2~) e a ANOVA de medidas repetidas necessita de que os dados estejam no formato longo. Isso significa que, ao invés de ter cada medida repetida em uma coluna separada, haverá uma coluna para o identificador (`id`) do indivíduo, uma coluna para o `tempo/condição` (fator de medidas repetidas), e uma coluna para o valor da variável dependente (`VD = escores`).\n\nPara fazer esta transformação será realizada pela função `pivot_longer()`[^16-anovarep-1]do pacote `tidyr` [@wickham2022tidyr]. Nesta função, no argumento `data`, coloca-se o nome do conjunto de dados; em `cols`, há necessidade informar as colunas do formato amplo que serão reunidas. No argumento `names_to`, nomear a coluna que conterá as colunas unificadas e em `values_to`, especificar o nome da variável no formato longo que conterá os valores. A variável `id` e a nova variável `tempo` devem ser convertida para fatores e o novo conjunto de dados será atribuído a um objeto nomeado `dadosL_uni`:\n\n[^16-anovarep-1]: Veja a @sec-pivot para mais detalhes da função\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_uni <- dados_uni  |> \n  tidyr::pivot_longer(cols = c(t0, t1, t2),\n                      names_to = \"tempo\",\n                      values_to = \"escores\")  |>  \n  convert_as_factor(id, tempo)\n\nstr(dadosL_uni)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [123 × 3] (S3: tbl_df/tbl/data.frame)\n $ id     : Factor w/ 41 levels \"1\",\"2\",\"3\",\"4\",..: 1 1 1 2 2 2 3 3 3 4 ...\n $ tempo  : Factor w/ 3 levels \"t0\",\"t1\",\"t2\": 1 2 3 1 2 3 1 2 3 1 ...\n $ escores: num [1:123] 170 180 220 100 140 100 160 180 220 180 ...\n```\n\n\n:::\n:::\n\n\n#### Sumarização dos dados\n\nEstatísticas descritivas dos escores espirométricos por grupos (`tempo`) podem ser obtidas com as funções `group_by()` e `summarise()` do pacote `dplyr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dadosL_uni  |> \n  dplyr::group_by(tempo) |> \n  dplyr::summarise(n = n(),\n                   média = mean(escores, na.rm =TRUE),\n                   dp = sd(escores, na.rm = TRUE))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  tempo     n média    dp\n  <fct> <int> <dbl> <dbl>\n1 t0       41  174.  42.8\n2 t1       41  205.  53.2\n3 t2       41  229.  56.1\n```\n\n\n:::\n:::\n\n\nO resumo mostra que a média aumenta do momento inicial (t~0~) para o final (t~2~).\n\n#### Visualização dos dados\n\nGraficamente, pode-se observar os dados através de um conjunto de boxplots (@fig-bxppfe), usando o pacote `ggpubr` com a função `ggboxplot()`. Este gráfico permite visualizar a variação dos escores com o tempo e a variabilidade em cada um dos momentos.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggboxplot (dadosL_uni,\n                   bxp.errorbar = TRUE,\n                   bxp.errorbar.width = 0.1, \n                   x = \"tempo\", \n                   y = \"escores\", \n                   color = \"black\",\n                   fill = \"lightblue\",\n                   ylab = \"Pico de Fluxo Expiratório (l/min)\",\n                   xlab = \"Tempo\",\n                   outliers = TRUE,\n                   ggtheme = theme_classic(),\n                   legend = \"none\") + \n  geom_jitter(\n    width = 0.15,\n    size = 1.8,\n    alpha = 0.6,\n    color = \"darkblue\"\n  ) +\n  theme (text = element_text (size = 12))\n```\n\n::: {.cell-output-display}\n![Boxplots mostrando o impacto de uma medicação através do tempo](16-anovaRep_files/figure-html/fig-bxppfe-1.png){#fig-bxppfe fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOutra maneira de obter praticamente as mesmas informações visuais é através de um gráfico de linha (@fig-linepfe), usando a função `geom_beeswarm` do pacote `ggbeeswarm` que mostra bem o comportamento dos escores com o tempo e em cada momento:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dadosL_uni, aes(x = tempo, y = escores, group = 1)) +\n  ggbeeswarm::geom_beeswarm(method = \"swarm\", color = \"cadetblue\",cex = 2,\n                            alpha = 0.5, size = 2) +\n  geom_errorbar(stat = \"summary\", fun.data = \"mean_sd\", width = 0.1, linewidth = 0.8) +\n  geom_point(stat = \"summary\", fun = \"mean\", color = \"tomato\", size = 3) +\n  geom_line(stat = \"summary\", fun = \"mean\", linetype = \"dashed\") +\n  labs(y = \"Pico de Fluxo Expiratório (l/min)\",\n       x= \"Tempo\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![Gráfico mostrando o impacto de uma medicação através do tempo](16-anovaRep_files/figure-html/fig-linepfe-1.png){#fig-linepfe fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nAmbas as figuras exibem uma modificação dos escores espirométricos (melhora nitidamente!) à medida que o tempo passa, utilizando a medicação.\n\n### Criação do modelo de ajuste {#sec-anova1model}\n\nPara a maioria dos casos, recomenda-se a função `aov_ez()` do pacote `afex` [@singmann2025afex] que fornece uma abordagem de alta robustez estatística e libera o teste de Mauchly com as correções de esfericidade.\n\n::: callout-note\n## Sintaxe do modelo aov_ez\n\n\n::: {.cell}\n\n```{.r .cell-code}\naov_ez(\n  id       = \"sujeito\",\n  dv       = \"resposta\",\n  data     = dataframe,\n  between  = \"grupo\",\n  within   = \"tempo\"\n)\n```\n:::\n\n:::\n\nPortanto, no exemplo em estudo, a sintaxe para o ajuste do modelo é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_ez <- afex::aov_ez(\n  id = \"id\",\n  dv = \"escores\",\n  data = dadosL_uni,\n  within = \"tempo\"\n)\n```\n:::\n\n\nEsse comando cria um objeto `modelo_ez` [^16-anovarep-2] que contém os resultados da ANOVA de medidas repetidas (tabela da ANOVA do tipo III) e outras informações, como o teste de Mauchly. Para ver a partição da variância e o teste F, usa-se a função `summary()`:\n\n[^16-anovarep-2]: Objeto da classe \"afex_aov\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modelo_ez)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnivariate Type III Repeated-Measures ANOVA Assuming Sphericity\n\n             Sum Sq num Df Error SS den Df F value    Pr(>F)    \n(Intercept) 5052075      1   250720     40 806.011 < 2.2e-16 ***\ntempo         61417      2    61853     80  39.718 1.047e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nMauchly Tests for Sphericity\n\n      Test statistic p-value\ntempo        0.97503  0.6107\n\n\nGreenhouse-Geisser and Huynh-Feldt Corrections\n for Departure from Sphericity\n\n       GG eps Pr(>F[GG])    \ntempo 0.97564  1.879e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n        HF eps   Pr(>F[HF])\ntempo 1.025029 1.047466e-12\n```\n\n\n:::\n:::\n\n\nA saída do modelo mostra a Tabela da ANOVA de Medidas repetidas de um fator (tempo) e resume os resultados do teste de esfericidade de Mauchly e as correções de Greenhouse-Geisser (GG) e Huynh-Feldt (HF) [^16-anovarep-3].\n\n[^16-anovarep-3]: Observe que, no sumário, o HF eps = 1.025029, ou seja, $> 1$, o que não faz sentido matematicamente, porque o epsilon deve estar no intervalo $0 \\le \\epsilon \\le 1$. Não existe consequências negativas, inclusive reforça que a suposição de esfericidade foi atendida.\n\nO **teste de Mauchly** avalia a suposição de esfericidade, que é o pressuposto de que as variâncias das diferenças entre todos os pares de níveis de repetição (os três momentos de medição) são iguais. Como o valor *p* = 0,6107 não se rejeita a H~0~ e se conclui que a esfericidade é válida e podemos confiar nos resultados da ANOVA univariada tipo III sem necessidade de correção. As correções de Greenhouse-Geisser e Huynh-Feldt confirmam a forte significância do efeito de tempo , entretanto, embora apresentadas, não são estritamente necessárias neste caso (veja mais sobre esfericidade na @sec-esphericity).\n\nA tabela principal da ANOVA univariada Tipo III, assumindo esfericidade, testa a hipótese nula de que não há diferença entre as médias das medições do PFE nos três momentos de tempo.\n\n- O intercepto foi significativo ($p < 0,001$), indicando que média geral é significativamente diferente de zero. Este resultado não é importante para o efeito do tratamento.\n\n- O efeito do **tempo** foi significativo (F = 39,72; $p < 0,001$), o que significa rejeitar a H~0~ de igualdade das médias através do tempo.\n\n  - O Quadrado Médio(QM) é obtido dividindo a Soma dos Quadrados(SQ) pelos respectivos graus de liberdade (gl) :\n\n  $$QM_{tempo} = \\frac{SQ_{tempo}}{gl_{tempo}}= \\frac{61417}{2}=30708,5$$\n\n  $$QM_{erro} = \\frac{SQ_{erro}}{gl_{erro}}=\\frac{61853}{80}=773,162$$\n\n  - Logo, *F* é igual a:\n\n    $$F = \\frac{QM_{tempo}}{QM_{erro}}=\\frac{30708,5}{773,162}=39,718$$\n\n**Existe uma diferença estatisticamente significativa** nas medições de *Peak Flow Meter* das crianças asmáticas ao longo dos três momentos distintos (0, 45 e 90 dias). Isto apenas indica que *pelo menos dois* momentos são diferentes, haverá necessidade de realizar testes *post hoc*.\n\nUma outra maneira de obter os resultados do modelo_ez é utilizando o objeto `modelo_ez` que au ser executado retorna a Tabela da ANOVA, incluindo o tamanho do efeito generalizado (`ges`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_ez\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: escores\n  Effect          df    MSE         F  ges p.value\n1  tempo 1.95, 78.05 792.47 39.72 *** .164   <.001\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1\n\nSphericity correction method: GG \n```\n\n\n:::\n:::\n\n\n### Avaliação dos pressupostos\n\n#### Obtenção dos resíduos\n\nNo `afex`, o `$lm` é um modelo multivariado: os resíduos são uma matriz com uma coluna por tempo. Para verificar os pressupostos do modelo, é necessário analisar esses resíduos.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresiduos <- residuals(modelo_ez$lm)\nhead(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          t0         t1         t2\n1  -4.390244 -24.585366   -9.02439\n2 -74.390244 -64.585366 -129.02439\n3 -14.390244 -24.585366   -9.02439\n4   5.609756 -24.585366   20.97561\n5  75.609756  95.414634   10.97561\n6   5.609756  -4.585366   50.97561\n```\n\n\n:::\n:::\n\n\nOs resíduos estão em formato largo (matriz 41×3). É preciso pivotá-los para longo e depois fazer um `left_join` pelo `id` e `tempo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresiduos_long <- as.data.frame(residuos) |>\n  tibble::rownames_to_column(\"id\") |>\n  tidyr::pivot_longer(cols = c(t0, t1, t2),\n                      names_to = \"tempo\",\n                      values_to = \"residuos\") |>\n  dplyr::mutate(id = factor(id, levels = levels(dadosL_uni$id)))\n\ndadosL_uni <- dplyr::left_join(dadosL_uni, residuos_long, by = c(\"id\", \"tempo\"))\n\nhead(dadosL_uni)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  id    tempo escores residuos\n  <fct> <chr>   <dbl>    <dbl>\n1 1     t0        170    -4.39\n2 1     t1        180   -24.6 \n3 1     t2        220    -9.02\n4 2     t0        100   -74.4 \n5 2     t1        140   -64.6 \n6 2     t2        100  -129.  \n```\n\n\n:::\n:::\n\n\nA coluna tempo perdeu a classe fator ao juntar os dadosL_uni com residuos_long e, portanto, precisa ser convertida de volta para fator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_uni <- dadosL_uni |> \n  dplyr::mutate(tempo = factor(tempo))\n\nstr(dadosL_uni)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [123 × 4] (S3: tbl_df/tbl/data.frame)\n $ id      : Factor w/ 41 levels \"1\",\"2\",\"3\",\"4\",..: 1 1 1 2 2 2 3 3 3 4 ...\n $ tempo   : Factor w/ 3 levels \"t0\",\"t1\",\"t2\": 1 2 3 1 2 3 1 2 3 1 ...\n $ escores : num [1:123] 170 180 220 100 140 100 160 180 220 180 ...\n $ residuos: num [1:123] -4.39 -24.59 -9.02 -74.39 -64.59 ...\n```\n\n\n:::\n:::\n\n\nAgora, `dadosL_uni` tem a coluna `residuos` com os resíduos do modelo, e `tempo` volta a ser fator. Essa coluna pode ser usada para avaliar os pressupostos.\n\n#### Avaliação da normalidade\n\nA suposição de normalidade dos resíduos é fundamental para a validade dos testes estatísticos em modelos lineares. Em modelos com medidas repetidas, essa suposição pode variar ao longo dos diferentes momentos de avaliação. Para verificar essa condição, será aplicado o teste de Shapiro-Wilk, usando a função `shapiro_test()` do pacote `rstatix` e gerados gráficos QQ dos resíduos por tempo (t~0~, t~1~, t~2~), com o `ggplot2`.\n\nComo um exercício pedagógico, teste de Shapiro-Wilk será aplicado aos resíduos do modelo e nos dados brutos:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsw_brutos <- dadosL_uni |>\n  dplyr::group_by(tempo) |>\n  rstatix::shapiro_test(escores) |>\n  dplyr::mutate(fonte = \"dados brutos\")\n\nsw_residuos <- dadosL_uni |>\n  dplyr::group_by(tempo) |>\n  rstatix::shapiro_test(residuos) |>\n  dplyr::mutate(fonte = \"resíduos\")\n\ndplyr::bind_rows(sw_brutos, sw_residuos) |>\n  dplyr::select(fonte, tempo, statistic, p) |>\n  dplyr::arrange(tempo, fonte)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  fonte        tempo statistic      p\n  <chr>        <fct>     <dbl>  <dbl>\n1 dados brutos t0        0.958 0.129 \n2 resíduos     t0        0.958 0.129 \n3 dados brutos t1        0.950 0.0728\n4 resíduos     t1        0.950 0.0728\n5 dados brutos t2        0.972 0.391 \n6 resíduos     t2        0.972 0.391 \n```\n\n\n:::\n:::\n\n\nOs resultados são idênticos! E isso faz sentido matematicamente. Neste modelo, os resíduos por tempo são simplesmente o resultado de cada escore menos a média do seu tempo.\n\n$$res_{ij}= y_{ij} - \\bar{y}_j$$\n\nÉ uma centralização, e o teste de Shapiro-Wilk é não varia com translações e re-escalamentos — a forma da distribuição não muda. Portanto, testar normalidade nos dados brutos por grupo ou nos resíduos por grupo **produz resultados equivalentes neste delineamento**.\\\nA diferença entre as duas abordagens só apareceria em modelos mais complexos, como ANCOVA ou ANOVA mista, onde os resíduos removem também o efeito de covariáveis ou fatores entre-sujeitos.\n\nTodos os três momentos não violam normalidade (todos p \\> 0.05), com t~1~ sendo o mais próximo do limiar (p = 0.073).\n\nPode-se observar isso, gerando o `QQ plot` dos resíduos com o `ggplot2`, usando o `stat_qq()` e `stat_qq_line()`, separado por `tempo` com `facet_wrap()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dadosL_uni, \n       aes(sample = residuos, \n           color = tempo)) +\n  stat_qq() +\n  stat_qq_line() +\n  facet_wrap(~ tempo) +\n  labs(\n    title = \"QQ Plot dos Resíduos por Tempo\",\n    x = \"Quantis Teóricos\",\n    y = \"Quantis Amostrais\"\n  ) +\n  theme_bw() +\n  theme(legend.position = \"none\") \n```\n\n::: {.cell-output-display}\n![Gráfico QQ para verificar a normalidade por momento](16-anovaRep_files/figure-html/fig-qqpef-1.png){#fig-qqpef fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nOs três painéis (@fig-qqpef) mostram aderência razoável à linha de referência na região central, com algum afastamento nas caudas — padrão consistente com o Shapiro-Wilk (t~1~ foi o mais próximo do limiar). Os agrupamentos horizontais visíveis nos painéis refletem a natureza discreta do PFE, que é medido em valores inteiros, e não indicam violação de normalidade.\n\nNo geral, o pressuposto de normalidade dos resíduos é satisfatório nos três momentos.\n\n#### Identificação de valores atípicos\n\nNão deve haver valores atípicos extremos nos resíduos. Pode-se verificar a presença de valores atípicos, usando a função `identify_outliers()` do pacote `rstatix`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_uni |>\n  dplyr::group_by(tempo) |>\n  rstatix::identify_outliers(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] tempo      id         escores    residuos   is.outlier is.extreme\n<0 linhas> (ou row.names de comprimento 0)\n```\n\n\n:::\n:::\n\n\nNenhum valor atípico detectado nos resíduos em nenhum dos três momentos. O pressuposto é atendido.\n\nVale lembrar que `identify_outliers()` usa o critério do IQR: valores além de $Q_{1}-1,5\\times IQR$ ou $Q_{3}+1,5\\times IQR$ são classificados como atípicos, e além de $3\\times IQR$ como extremos. Apenas os extremos (*extreme*) costumam ser problemáticos para a ANOVA.\n\nIsso também pode ser verificado na @fig-bxppfe dos boxplots.\n\n#### Teste de esfericidade {#sec-esphericity}\n\nA esfericidade é a versão da homocedasticidade para medidas repetidas, é avaliada como foi visto (@sec-anova1model) pelo teste de Mauchly. O teste de Mauchly é uma avaliação da matriz de covariância das diferenças entre os níveis do fator. A matriz de covariância é a ferramenta que avalia se a variação nas mudanças ao longo do tempo é consistente. O teste de Mauchly podes ser obtido ajustando o modelo unifatorial de medidas repetidas (tempo), usando a função `aov_ez()` do pacote `afex`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modelo_ez)$sphericity.tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Test statistic p-value\ntempo        0.97503  0.6107\n```\n\n\n:::\n:::\n\n\nA saída do teste de Mauchly exibiu um valor *p* $> 0,05$, indicando que o pressuposto da esfericidade não foi violado, não havendo necessidade de recorrer às correções da esfericidade, que seriam obtidas da seguinte maneira:\n\n::: callout-note\n## Lógica do teste de Mauchly\n\nO teste de Mauchly é uma avaliação da matriz de covariância das diferenças entre os níveis do fator. O que isto significa?\n\nO exemplo usado na ANOVA de medidas repetidas corresponde a medida de Pico de Fluxo Expiratório (PFE) em três momentos (t~0~, t~1~ e t~2~, respectivamente, basal, 45 dias e 90 dias).\n\nPara saber se o tratamento funciona, não se está interessado apenas na medida do PFE em cada tempo, mas sim na **mudança** que o tratamento causou. Se quer saber se a PFE no tempo 1 é diferente da PFE no tempo 0, e se o PFE no tempo 2 é diferente do PFE nos tempos anteriores.\n\nAs \"mudanças\" são as **diferenças** entre os níveis do fator, ou seja:\n\n- Dif 1: (t1−t0)\n- Dif 2: (t2−t0)\n- Dif 3: (t2−t1)\n\nA ANOVA de medidas repetidas assume que essas diferenças têm uma relação especial entre si. Ela assume que a **variância de cada uma dessas diferenças é aproximadamente a mesma** e que a **correlação (ou covariância) entre elas também é a mesma**.\n\n[Matriz de Covariância das Diferenças]{.underline}\n\nImagine-se que se calculou a variância de cada uma dessas diferenças. A matriz de covariância das diferenças é uma tabela que organiza esses resultados em uma matriz quadrada (3 x 3) e simétrica:\n\n![](images/matriz_covar.png){fig-align=\"center\" width=\"15.5cm\"}\n\nA suposição de **esfericidade** (que o teste de Mauchly avalia) é que todos os valores nessa matriz devem ser aproximadamente **iguais**. • As variâncias diagonais devem ser iguais; • As covariâncias fora da diagonal também devem ser **iguais**.\n\n[Importância do Teste de Mauchly]{.underline}\n\nO teste de Mauchly verifica se essa suposição de esfericidade é verdadeira. • Se o **teste de Mauchly for não significativo** (*p* \\> 0,05): Significa que a matriz das diferenças é \"esférica\" e a suposição de esfericidade foi mantida. Se pode confiar no resultado da ANOVA. • Se o **teste de Mauchly for significativo** (*p* \\< 0,05): Significa que a suposição de esfericidade foi violada. As variâncias das diferenças não são iguais, e isso pode inflar a taxa de erro do Tipo I (a chance de encontrar um resultado significativo quando não existe um de verdade).\n\nQuando a esfericidade é violada, é calculada as correções de **Greenhouse-Geisser (GGe)** ou **Huynh-Feldt (HFe)**, que ajustam os graus de liberdade e tornam o teste mais conservador, garantindo que o seu resultado final seja confiável. Huynh e Feldt [@huynh1976epsilon] relataram que quando a correção $\\epsilon$ de Greenhouse-Geisser é \\> 0,75 muitas hipóteses nulas falsas deixam de ser rejeitadas, isto é, o teste é muito conservador, propondo outra correção dos graus de liberdade. É recomendado o uso da correção de Greenhouse-Geisser para o ajuste dos graus de liberdade quando $\\epsilon$ \\< 0,75 ou nada se sabe a respeito da esfericidade [@girden1992epsilon]. Avaliando o poder destes testes, Muller [@muller1989sphericity] verificou que a correção de Greenhouse-Geisser fornece um controle adicional do erro Tipo I, enquanto o poder é maximizado.\n:::\n\n#### Resumo da avaliação dos pressupostos\n\nTodos os pressupostos foram atendidos. Vale notar que o QQ plot mostra leve afastamento nas caudas — os dados têm uma distribuição um pouco mais achatada que a normal — mas o Shapiro-Wilk não detectou violação significativa em nenhum dos três momentos, e com n=41 a ANOVA de medidas repetidas é razoavelmente robusta a pequenos desvios de normalidade.\n\n### Análise *post hoc*\n\nA ANOVA de medidas repetidas indicou uma modificação significativa nos escores de PEF ao longo do tempo com o uso da medicação. No entanto, esse teste apenas revela que há diferenças entre os tempos, sem especificar entre quais pares de momentos essas diferenças ocorrem. Para identificar onde essas diferenças são estatisticamente significativas, é necessário realizar uma análise *post hoc*.\n\n#### Médias marginais estimadas por `tempo`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm <- emmeans(modelo_ez, ~ tempo)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n tempo emmean   SE df lower.CL upper.CL\n t0       174 6.69 40      161      188\n t1       205 8.31 40      188      221\n t2       229 8.76 40      211      247\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n#### Comparações pareadas com correção de Bonferroni\n\nOptou-se pelo método de Bonferroni por ser mais conservador e reduzir o risco de falsos positivos, mesmo que sacrifique o poder estatístico. Em contextos com muitos grupos, métodos como Holm ou Benjamini-Hochberg (BH) podem ser preferidos por sua maior sensibilidade.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(emm, adjust = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast estimate   SE df t.ratio p.value\n t0 - t1     -30.2 5.84 40  -5.168 <0.0001\n t0 - t2     -54.6 5.95 40  -9.185 <0.0001\n t1 - t2     -24.4 6.61 40  -3.700  0.0019\n\nP value adjustment: bonferroni method for 3 tests \n```\n\n\n:::\n:::\n\n\nTodos os três pares diferem significativamente após correção de Bonferroni:\n\n\n::: {#tbl-posthoc .cell tbl-cap='Comparações pareadas post-hoc (correção de Bonferroni)'}\n\n```{.r .cell-code}\npairs(emm, adjust = \"bonferroni\") |>\n  as.data.frame() |>\n  dplyr::mutate(\n    contrast = c(\"t0 vs t1\", \"t0 vs t2\", \"t1 vs t2\"),\n    estimate = round(estimate, 1),\n    SE       = round(SE, 2),\n    t.ratio  = round(t.ratio, 3),\n    p.value  = dplyr::case_when(\n      p.value < 0.001 ~ \"< 0,001\",\n      TRUE ~ format(round(p.value, 3), nsmall = 3)\n    )\n  ) |>\n  dplyr::select(contrast, estimate, SE, df, t.ratio, p.value) |>\n  flextable() |>\n  set_header_labels(\n    contrast = \"Contraste\",\n    estimate = \"Diferença (l/min)\",\n    SE       = \"EP\",\n    df       = \"gl\",\n    t.ratio  = \"t\",\n    p.value  = \"p\"\n  ) |>\n  theme_booktabs() |>\n  align(align = \"center\", part = \"all\") |>\n  align(j = 1, align = \"left\", part = \"all\") |>\n  bold(part = \"header\") |>\n  width(j = 1, width = 2) |>\n  width(j = 2:6, width = 1.2) |>\n  add_footer_lines(\"Correção de Bonferroni; EP = erro padrão; gl = graus de liberdade.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-00b68e5c{}.cl-00abeed4{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00abeee8{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00b05410{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-00b05424{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-00b0a73a{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a744{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a745{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a74e{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a74f{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a758{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a759{width:2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00b0a762{width:1.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-00b68e5c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-00b0a73a\"><p class=\"cl-00b05410\"><span class=\"cl-00abeed4\">Contraste</span></p></th><th class=\"cl-00b0a744\"><p class=\"cl-00b05424\"><span class=\"cl-00abeed4\">Diferença (l/min)</span></p></th><th class=\"cl-00b0a744\"><p class=\"cl-00b05424\"><span class=\"cl-00abeed4\">EP</span></p></th><th class=\"cl-00b0a744\"><p class=\"cl-00b05424\"><span class=\"cl-00abeed4\">gl</span></p></th><th class=\"cl-00b0a744\"><p class=\"cl-00b05424\"><span class=\"cl-00abeed4\">t</span></p></th><th class=\"cl-00b0a744\"><p class=\"cl-00b05424\"><span class=\"cl-00abeed4\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00b0a745\"><p class=\"cl-00b05410\"><span class=\"cl-00abeee8\">t0 vs t1</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-30.2</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">5.84</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">40</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-5.168</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">&lt; 0,001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00b0a745\"><p class=\"cl-00b05410\"><span class=\"cl-00abeee8\">t0 vs t2</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-54.6</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">5.95</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">40</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-9.185</span></p></td><td class=\"cl-00b0a74e\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">&lt; 0,001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00b0a74f\"><p class=\"cl-00b05410\"><span class=\"cl-00abeee8\">t1 vs t2</span></p></td><td class=\"cl-00b0a758\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-24.4</span></p></td><td class=\"cl-00b0a758\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">6.61</span></p></td><td class=\"cl-00b0a758\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">40</span></p></td><td class=\"cl-00b0a758\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">-3.700</span></p></td><td class=\"cl-00b0a758\"><p class=\"cl-00b05424\"><span class=\"cl-00abeee8\">0.002</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"6\"class=\"cl-00b0a759\"><p class=\"cl-00b05410\"><span class=\"cl-00abeee8\">Correção de Bonferroni; EP = erro padrão; gl = graus de liberdade.</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\nO PFE aumentou progressivamente em todos os momentos — a melhora de t0 para t2 foi a maior (\\~55 l/min), e mesmo entre t1 e t2 houve ganho adicional significativo, sugerindo que o efeito do corticoide continuou se acumulando ao longo dos 90 dias.\n\n### Tamanho do Efeito Padronizado\n\nO tamanho do efeito é uma medida da magnitude da diferença entre grupos, independente do tamanho da amostra. O tamanho do efeito na ANOVA pode ser obtido usando o parâmetro $\\eta^2$ (eta ao quadrado), parcial ou generalizado, que está disponível no pacote `afex`, usado para ajustar o modelo (@sec-anova1model). Na ANOVA de medidas repetidas, é calculado o eta ao quadrado generalizado, pois o parcial pode superestimar o efeito. O eta ao quadrado generalizado mede a proporção da variância explicada por um fator em relação a variância total. Usando o `modelo_ez`, o tamanho do efeito pode ser obtido da seguinte forma usando a função `eta_squared()` do pacote `effectsize`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_g <- effectsize::eta_squared (modelo_ez, generalized = TRUE)\neffectsize::interpret_eta_squared(eta_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type III)\n\nParameter | Eta2 (generalized) |       95% CI | Interpretation\n--------------------------------------------------------------\ntempo     |               0.16 | [0.05, 1.00] |          large\n\n- Observed variables: All\n- One-sided CIs: upper bound fixed at [1.00].\n- Interpretation rule: field2013\n```\n\n\n:::\n:::\n\n\n$\\eta^2_{G} = 0,16$, considerado efeito grande pelos critérios de Cohen (pequeno ≥ 0,01; médio ≥ 0,06; grande ≥ 0,14). Esse valor coincide com o `ges` já reportado na tabela do `afex`, mas agora com a incerteza quantificada.\n\n\n::: {#tbl-anova .cell tbl-cap='ANOVA de medidas repetidas — efeito do tempo sobre o PFE'}\n\n```{.r .cell-code}\neta_g |> as.data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Parameter Eta2_generalized   CI     CI_low CI_high\n1     tempo        0.1642203 0.95 0.04985749       1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(modelo_ez) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Efeito\") |>\n  dplyr::mutate(\n    gl        = paste0(round(`num Df`, 2), \", \", round(`den Df`, 2)),\n    MSE       = round(MSE, 2),\n    F         = round(F, 3),\n    eta2G     = round(eta_g$Eta2_generalized, 3),\n    IC95      = paste0(\"[\", round(eta_g$CI_low, 2), \", 1.00]\"),\n    p.value   = ifelse(`Pr(>F)` < 0.001, \"< 0,001\", round(`Pr(>F)`, 3))\n  ) |>\n  dplyr::select(Efeito, gl, MSE, F, eta2G, IC95, p.value) |>\n  flextable() |>\n  set_header_labels(\n    Efeito  = \"Efeito\",\n    gl      = \"gl (GG)\",\n    MSE     = \"QME\",\n    F       = \"F\",\n    eta2G   = \"\\u03b7\\u00b2G\",\n    IC95    = \"IC 95%\",\n    p.value = \"p\"\n  ) |>\n  theme_booktabs() |>\n  align(align = \"center\", part = \"all\") |>\n  align(j = 1, align = \"left\", part = \"all\") |>\n  bold(part = \"header\") |>\n  width(j = 1, width = 1.5) |>\n  width(j = 2, width = 1.8) |>\n  width(j = 3:7, width = 1.1) |>\n  add_footer_lines(\"QME = quadrado médio do erro; η²G = eta quadrado generalizado; IC = intervalo de confiança.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-00f34838{}.cl-00e3a734{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00e3a752{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-00ebe2a0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-00ebe2aa{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-00ec0c4e{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c58{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c59{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c62{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c6c{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c76{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c77{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c78{width:1.8in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-00ec0c80{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-00f34838'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-00ec0c4e\"><p class=\"cl-00ebe2a0\"><span class=\"cl-00e3a734\">Efeito</span></p></th><th class=\"cl-00ec0c58\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">gl (GG)</span></p></th><th class=\"cl-00ec0c59\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">QME</span></p></th><th class=\"cl-00ec0c59\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">F</span></p></th><th class=\"cl-00ec0c59\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">η²G</span></p></th><th class=\"cl-00ec0c59\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">IC 95%</span></p></th><th class=\"cl-00ec0c59\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a734\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-00ec0c62\"><p class=\"cl-00ebe2a0\"><span class=\"cl-00e3a752\">tempo</span></p></td><td class=\"cl-00ec0c6c\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">1.95, 78.05</span></p></td><td class=\"cl-00ec0c76\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">792.47</span></p></td><td class=\"cl-00ec0c76\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">39.718</span></p></td><td class=\"cl-00ec0c76\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">0.164</span></p></td><td class=\"cl-00ec0c76\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">[0.05, 1.00]</span></p></td><td class=\"cl-00ec0c76\"><p class=\"cl-00ebe2aa\"><span class=\"cl-00e3a752\">&lt; 0,001</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"7\"class=\"cl-00ec0c77\"><p class=\"cl-00ebe2a0\"><span class=\"cl-00e3a752\">QME = quadrado médio do erro; η²G = eta quadrado generalizado; IC = intervalo de confiança.</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n### Resultado Final\n\nA @tbl-resultados mostra os resultados finais da Anova de Medidas Repetidas:\n\n\n::: {#tbl-resultados .cell tbl-cap='ANOVA de medidas repetidas e comparações post-hoc para o PFE'}\n\n```{.r .cell-code}\n# --- ANOVA  ---\nanova_row <- anova(modelo_ez) |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"label\") |>\n  dplyr::transmute(\n    label  = label,\n    gl     = paste0(round(`num Df`, 2), \"; \", round(`den Df`, 2)),\n    stat2  = format(round(MSE, 2), nsmall = 2, big.mark = \".\"),\n    stat3  = format(round(F, 2), nsmall = 2),\n    efeito = paste0(\"η²G = \", round(eta_g$Eta2_generalized, 2)),\n    ic     = paste0(\"[\", round(eta_g$CI_low, 2), \"; 1,00]\"),\n    p      = \"< 0,001\"\n  )\n\n# --- Post-hoc ---\nph_df <- pairs(emm, adjust = \"bonferroni\") |> as.data.frame()\n\nd_rm_t0_t1 <- effectsize::repeated_measures_d(dados_uni$t1, dados_uni$t0, method = \"rm\")\nd_rm_t0_t2 <- effectsize::repeated_measures_d(dados_uni$t2, dados_uni$t0, method = \"rm\")\nd_rm_t1_t2 <- effectsize::repeated_measures_d(dados_uni$t2, dados_uni$t1, method = \"rm\")\n\ndrm_list <- list(as.data.frame(d_rm_t0_t1),\n                 as.data.frame(d_rm_t0_t2),\n                 as.data.frame(d_rm_t1_t2))\n\nph_rows <- data.frame(\n  label  = c(\"t0 vs t1\", \"t0 vs t2\", \"t1 vs t2\"),\n  gl     = as.character(ph_df$df),\n  stat2  = format(round(ph_df$SE, 2), nsmall = 2),\n  stat3  = format(round(ph_df$t.ratio, 2), nsmall = 2),\n  efeito = paste0(\"d_rm = \", sapply(drm_list, \\(x) format(round(x$d_rm, 2), nsmall = 2))),\n  ic     = sapply(drm_list, \\(x) paste0(\"[\", round(x$CI_low, 2), \"; \", round(x$CI_high, 2), \"]\")),\n  p      = dplyr::case_when(\n    ph_df$p.value < 0.001 ~ \"< 0,001\",\n    TRUE ~ format(round(ph_df$p.value, 3), nsmall = 3)\n  )\n)\n\n# --- Título das seções ---\nblank <- data.frame(label=\"\", gl=\"\", stat2=\"\", stat3=\"\", efeito=\"\", ic=\"\", p=\"\")\nsec1  <- blank |> dplyr::mutate(label = \"ANOVA\")\nsec2  <- blank |> dplyr::mutate(label = \"Comparações post-hoc (Bonferroni)\")\n\n# --- Combinar no df final ---\ndf_final <- dplyr::bind_rows(sec1, anova_row, sec2, ph_rows)\n\nsec_rows <- c(1, 3)\n\n# --- Flextable ---\ndf_final |>\n  flextable() |>\n  set_header_labels(\n    label  = \"Fonte / Contraste\",\n    gl     = \"gl\",\n    stat2  = \"QME / EP\",\n    stat3  = \"F / t\",\n    efeito = \"Tamanho de efeito\",\n    ic     = \"IC 95%\",\n    p      = \"p\"\n  ) |>\n  theme_booktabs() |>\n  merge_h(i = sec_rows, part = \"body\") |>\n  bold(i = sec_rows, part = \"body\") |>\n  bg(i = sec_rows, bg = \"#eeeeee\", part = \"body\") |>\n  align(align = \"center\", part = \"all\") |>\n  align(j = 1, align = \"left\", part = \"all\") |>\n  bold(part = \"header\") |>\n  width(j = 1, width = 2.2) |>\n  width(j = 2:7, width = 1.1) |>\n  add_footer_lines(\"gl = graus de liberdade com correção de Greenhouse-Geisser (ANOVA) ou graus de liberdade do denominador (post-hoc); QME = quadrado médio do erro; EP = erro padrão; η²G = eta quadrado generalizado; d_rm = Cohen's d para medidas repetidas; IC = intervalo de confiança de 95%.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-0127d774{}.cl-011ce94a{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-011ce95e{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-01220c4a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-01220c54{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0122368e{width:2.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-01223698{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236a2{width:2.2in;background-color:rgba(238, 238, 238, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236a3{width:1.1in;background-color:rgba(238, 238, 238, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236ac{width:2.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236ad{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236b6{width:2.2in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236b7{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236c0{width:2.2in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-012236c1{width:1.1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0127d774'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-0122368e\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce94a\">Fonte / Contraste</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">gl</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">QME / EP</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">F / t</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">Tamanho de efeito</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">IC 95%</span></p></th><th class=\"cl-01223698\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\">p</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236a2\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce94a\">ANOVA</span></p></td><td  colspan=\"6\"class=\"cl-012236a3\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236ac\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce95e\">tempo</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">1.95; 78.05</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">792.47</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">39.72</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">η²G = 0.16</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">[0.05; 1,00]</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">&lt; 0,001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236a2\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce94a\">Comparações post-hoc (Bonferroni)</span></p></td><td  colspan=\"6\"class=\"cl-012236a3\"><p class=\"cl-01220c54\"><span class=\"cl-011ce94a\"></span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236ac\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce95e\">t0 vs t1</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">40</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">5.84</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">-5.17</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">d_rm = 0.60</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">[0.35; 0.84]</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">&lt; 0,001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236ac\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce95e\">t0 vs t2</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">40</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">5.95</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">-9.19</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">d_rm = 1.02</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">[0.75; 1.3]</span></p></td><td class=\"cl-012236ad\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">&lt; 0,001</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-012236b6\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce95e\">t1 vs t2</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">40</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">6.61</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">-3.70</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">d_rm = 0.44</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">[0.19; 0.68]</span></p></td><td class=\"cl-012236b7\"><p class=\"cl-01220c54\"><span class=\"cl-011ce95e\">0.002</span></p></td></tr></tbody><tfoot><tr style=\"overflow-wrap:break-word;\"><td  colspan=\"7\"class=\"cl-012236c0\"><p class=\"cl-01220c4a\"><span class=\"cl-011ce95e\">gl = graus de liberdade com correção de Greenhouse-Geisser (ANOVA) ou graus de liberdade do denominador (post-hoc); QME = quadrado médio do erro; EP = erro padrão; η²G = eta quadrado generalizado; d_rm = Cohen's d para medidas repetidas; IC = intervalo de confiança de 95%.</span></p></td></tr></tfoot></table></div>\n```\n\n:::\n:::\n\n\n### Gráfico final\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemm_df <- as.data.frame(emm)\n\npval_df <- data.frame(\n  group1     = c(\"t0\", \"t1\", \"t0\"),\n  group2     = c(\"t1\", \"t2\", \"t2\"),\n  label      = c(\"***\", \"**\", \"***\"),\n  y.position = c(255, 263, 273)\n)\n\nggplot(emm_df, aes(x = tempo, y = emmean, group = 1)) +\n  geom_line(linetype = \"dashed\", linewidth = 0.7) +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL),\n                width = 0.08, linewidth = 0.8) +\n  geom_point(size = 3.5) +\n  ggpubr::stat_pvalue_manual(pval_df,\n                             label = \"label\",\n                             tip.length = 0.01,\n                             bracket.size = 0.5) +\n  scale_x_discrete(labels = c(t0 = \"Basal (0 dias)\",\n                               t1 = \"45 dias\",\n                               t2 = \"90 dias\")) +\n  scale_y_continuous(limits = c(155, 285)) +\n  labs(x     = \"Momento de avaliação\",\n       y     = \"Pico de Fluxo Expiratório (l/min)\",\n       caption = \"Médias marginais estimadas com IC 95%; correção de Bonferroni: ** p < 0,01; *** p < 0,001\") +\n  theme_classic(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Gráfico mostrando o impacto de uma medicação através do tempo](16-anovaRep_files/figure-html/fig-end-1.png){#fig-end fig-align='center' width=70% height=70%}\n:::\n:::\n\n\n### Conclusão\n\nA ANOVA de medidas repetidas revelou efeito significativo do tempo sobre o pico de fluxo expiratório \\[F(1,95; 78,05) = 39,72; p \\< 0,001; η²G = 0,16; IC 95%: 0,05–1,00\\], indicando que os escores espirométricos variaram ao longo dos três momentos de avaliação. O teste de esfericidade de Mauchly não foi significativo (W = 0,975; p = 0,611), embora a correção de Greenhouse–Geisser tenha sido aplicada por padrão. As comparações post-hoc com correção de Bonferroni demonstraram diferenças significativas entre todos os pares de momentos. O PFE médio estimado aumentou de 174 l/min (IC 95%: 161–188) no momento basal para 205 l/min (IC 95%: 188–221) aos 45 dias (Δ = 30,2 l/min; t(40) = 5,17; p \\< 0,001; d~rm~ = 0,60; IC 95%: 0,35–0,84) e para 229 l/min (IC 95%: 211–247) aos 90 dias (Δ = 54,6 l/min; t(40) = 9,19; p \\< 0,001; d~rm~ = 1,02; IC 95%: 0,75–1,30). A comparação entre os momentos de 45 e 90 dias também revelou diferença significativa (Δ = 24,4 l/min; t(40) = 3,70; p = 0,002; d~rm~ = 0,44; IC 95%: 0,19–0,68), indicando que a melhora da função pulmonar continuou ao longo do segundo mês de tratamento. A evolução das médias marginais estimadas com os respectivos intervalos de confiança de 95% está ilustrada na @fig-end.\n\nO η²G = 0,16 corresponde a um efeito grande pelos critérios de Cohen (≥ 0,14), e os d~rm~ variam de moderado (0,44 para t1 vs t2) a grande (1,02 para t0 vs t2), evidenciando relevância clínica consistente em todas as comparações.\n\n## ANOVA Mista\n\nA ANOVA Mista é um tipo de análise de variância usada quando o estudo envolve simultaneamente um fator entre‑sujeitos (grupos diferentes de participantes) e um fator intra‑sujeitos (medidas repetidas nos mesmos participantes). Ela permite avaliar diferenças nas médias da variável dependente tanto entre os grupos quanto ao longo do tempo ou condições, além de verificar se a evolução dos grupos ao longo do tempo é diferente.\n\nO ponto central da ANOVA Mista é a interação entre os fatores. Uma interação significativa indica que o efeito do tempo (ou condição repetida) depende do grupo, ou que os grupos se comportam de maneira diferente ao longo das medições. Quando a interação é significativa, ela deve ser priorizada na interpretação, pois os efeitos principais isolados podem não refletir adequadamente o padrão real dos dados.\n\n### Dados usados no exemplo\n\nOs dados que servirão de exemplo são os mesmos da @sec-dadoscap16 sem usar o filtro para os 41 casos que correspondem às crianças de 5 a 15 anos que receberam um novo corticoide inalatório. Os controles são 41 crianças da mesma idade que receberam o tratamento habitual (@fig-trialAsma).\n\n![Ensaio Clínico](images/trial.png){#fig-trialAsma fig-align=\"center\" width=\"17cm\" height=\"4.3cm\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_mista <- readxl::read_excel(\"dados/dadosAsma.xlsx\")\nstr(dados_mista)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [82 × 5] (S3: tbl_df/tbl/data.frame)\n $ id   : num [1:82] 1 2 3 4 5 6 7 8 9 10 ...\n $ grupo: chr [1:82] \"caso\" \"caso\" \"caso\" \"caso\" ...\n $ t0   : num [1:82] 170 100 160 180 250 180 170 180 240 200 ...\n $ t1   : num [1:82] 180 140 180 180 300 200 180 200 320 200 ...\n $ t2   : num [1:82] 220 100 220 250 240 280 220 250 350 250 ...\n```\n\n\n:::\n:::\n\n\nAssim, como realizado com a ANOVA de medidas repetidas de um fator, os dados serão transformados para o formato longo e atribuídos a um objeto denominado `dadosL_mista`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista <- dados_mista |>\n  tidyr::pivot_longer(cols = c(t0, t1, t2),\n                      names_to = \"tempo\",\n                      values_to = \"escores\") |> \n  convert_as_factor(id, grupo, tempo)\n\ndadosL_mista |> sample_n_by(grupo, tempo, size = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  id    grupo    tempo escores\n  <fct> <fct>    <fct>   <dbl>\n1 11    caso     t0        140\n2 6     caso     t1        200\n3 37    caso     t2        150\n4 61    controle t0        100\n5 79    controle t1        200\n6 51    controle t2        250\n```\n\n\n:::\n:::\n\n\n#### Sumarização dos dados\n\nOs dados serão sumarizados por grupo e tempo e, em seguida, serão calculadas algumas estatísticas resumidas da variável de escore: média e sd (desvio padrão). Isso será realizado através das funções `group_by()` e `get_summary_stats()` do pacote `rstatix`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista |>\n  rstatix::group_by(grupo, tempo) |> \n  rstatix::get_summary_stats(escores, type = \"mean_sd\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  grupo    tempo variable     n  mean    sd\n  <fct>    <fct> <fct>    <dbl> <dbl> <dbl>\n1 caso     t0    escores     41  174.  42.8\n2 caso     t1    escores     41  205.  53.2\n3 caso     t2    escores     41  229.  56.1\n4 controle t0    escores     41  184.  43.6\n5 controle t1    escores     41  192.  37.5\n6 controle t2    escores     41  212.  40.9\n```\n\n\n:::\n:::\n\n\n#### Visualização dos dados\n\nPode-se observar os dados de diversas maneiras. Para ANOVA medidas repetidas de dois fatores, o gráfico de linha com barra de erro é bastante útil, pois além de permitir a visualização dos dados através do tempo, pode-se ver a existência ou não de interação entre os fatores. Para criar a (@fig-pfe2) serão usadas as funções `ggline()` do pacote `ggpubr`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpubr::ggline(dadosL_mista, \n               x = \"tempo\",\n               y = \"escores\",\n               color = \"grupo\",\n               palette = \"d3\",\n               linewidth = 0.7,\n               linetype = \"dashed\",\n               add = \"mean_ci\",\n               error.plot = \"errorbar\",\n               position = position_dodge(width = 0.3),\n               point.size = 1.5,\n               ylab = \"Pico de Fluxo Expiratório (l/min)\",\n               xlab = \"Momento\",\n               legend = \"top\",\n               ggtheme = theme_classic()) +\n  scale_x_discrete(limits = c(\"t0\", \"t1\", \"t2\"),\n                   labels = c(\"Basal\", \"45 dias\", \"90 dias\")) +\n  labs(color = NULL)\n```\n\n::: {.cell-output-display}\n![Efeito do novo corticoide inalatório nos escores de Pico de Fluxo Expiratório ao longo do tempo por grupo](16-anovaRep_files/figure-html/fig-pfe2-1.png){#fig-pfe2 fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nA observação da @fig-pfe2 mostra que ambos os grupos melhoraram a função respiratória com o tempo. O grupo `caso` teve uma melhora mais acentuada, o que pode indicar que a intervenção foi eficaz. O grupo `controle` manteve uma evolução positiva estável. A análise estatística (como ANOVA de medidas repetidas) poderia confirmar se essas diferenças são significativas ou apenas tendências visuais.\n\n### Criação do modelo misto {#sec-anovamista}\n\nEste modelo permite testar se há diferença no tempo, independentemente do `grupo`; testar se há diferença entre os grupos, independentemente do `tempo` e verificar se há interação entre `tempo` e `grupo`, ou seja, se a mudança ao longo do tempo difere entre os grupos (por ex., se o tratamento teve efeito). Usando o formato longo, pode-se fazer o ajuste do modelo com a função `aov_ez()` do pacote `afex`. Essa função também é apropriada para delineamentos com mais de um fatores: um fator intra-sujeitos (`tempo`); um fator entre sujeitos (`grupo`) e, principalmente, se houver interação, desbalanceamento e se deseja realizar uma ANOVA tipo III. Além disso, a `aov_ez` já calcula automaticamente o teste de esfericidade de Mauchly e as correções (Greenhouse-Geisser e Huynh-Feldt).\n\nVeja a sintaxe da função em @sec-anova1model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_ez2 <- afex::aov_ez(id = \"id\",\n                           data = dadosL_mista,\n                           dv = \"escores\",\n                           between = \"grupo\",\n                           within = \"tempo\")\n\nsummary(modelo_ez2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnivariate Type III Repeated-Measures ANOVA Assuming Sphericity\n\n             Sum Sq num Df Error SS den Df   F value    Pr(>F)    \n(Intercept) 9763350      1   430255     80 1815.3608 < 2.2e-16 ***\ngrupo          2923      1   430255     80    0.5435  0.463132    \ntempo         69803      2    81254    160   68.7251 < 2.2e-16 ***\ngrupo:tempo    8479      2    81254    160    8.3482  0.000356 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n\nMauchly Tests for Sphericity\n\n            Test statistic p-value\ntempo              0.95941 0.19459\ngrupo:tempo        0.95941 0.19459\n\n\nGreenhouse-Geisser and Huynh-Feldt Corrections\n for Departure from Sphericity\n\n             GG eps Pr(>F[GG])    \ntempo       0.96099  < 2.2e-16 ***\ngrupo:tempo 0.96099  0.0004365 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n              HF eps   Pr(>F[HF])\ntempo       0.984147 5.875378e-22\ngrupo:tempo 0.984147 3.867194e-04\n```\n\n\n:::\n:::\n\n\nO teste de Mauchly não foi significativo para tempo e para a interação `grupo:tempo` (*p* = 0,195), indicando que o pressuposto de esfericidade não foi violado. As correções de Greenhouse-Geisser ($\\epsilon = 0,961$) e Huynh-Feldt ($\\epsilon = 0,984$) confirmam resultados praticamente idênticos.\n\nEfeito principal de `grupo` não foi significativo (*p* = 0,463). Em média, os grupos `caso` e `controle` (n = 41 cada) não diferem nos escores quando se ignora o fator `tempo`.\n\nEfeito principal de `tempo` foi significativo (p \\< 0,001). Os escores variam ao longo dos três momentos (t~0~, t~1~, t~2~) independentemente do `grupo`.\n\nInteração `grupo × tempo` foi significativa (p \\< 0,001). **Este é o resultado mais importante** — a trajetória de mudança ao longo do tempo é diferente entre os grupos. Ou seja, o efeito do tempo depende do grupo (ou vice-versa).\n\nComo a interação é significativa (@fig-pfe2), os efeitos principais devem ser interpretados com cautela. O próximo passo natural é examinar os efeitos simples (*simple effects*) — comparar os grupos em cada momento separadamente, ou comparar os momentos dentro de cada grupo — para entender o padrão da interação.\n\n### Avaliação dos pressupostos do modelo\n\n#### Esfericidade\n\nO Teste de Mauchly, obtido junto com o modelo, mostrou que tanto o `tempo` como a interação `grupo:tempo` têm valores *p* \\> 0,05. Não houve violação da esfericidade. Como visto, as correções de GG e HF são semelhantes, mas elas são desnecessárias quando não há violação da esfericidade.\n\nDa mesma maneira que na ANOVA de Medidas Repetidas de uma via, pode também obter o teste de Mauchly com o seguinte código:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(modelo_ez2)$sphericity.tests\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Test statistic p-value\ntempo              0.95941 0.19459\ngrupo:tempo        0.95941 0.19459\n```\n\n\n:::\n:::\n\n\n#### Obtenção dos resíduos\n\nOs resíduos podem ser obtidos da seguinte maneira, utilizando o modelo_ez :\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista$residuos <- residuals(modelo_ez2)\n```\n:::\n\n\nIsto cria uma coluna denominada `residuos` (diferença entre os valores observados e os ajustados) e que deve ser usada na análise dos pressupostos.\n\n#### Avaliação da normalidade dos resíduos\n\nA verificação recomendada é por `grupo` e `tempo`, pois o pressuposto de normalidade na ANOVA diz respeito à distribuição dos erros dentro de cada célula do delineamento — ou seja, dentro de cada combinação de `grupo` × `tempo`. Verificar os resíduos totais agrega células diferentes numa distribuição única, o que pode mascarar violações localizadas (ex.: não-normalidade só no grupo caso no momento t~1~). Agregar todos os resíduos numa única distribuição confunde a variação sistemática entre células com a variação aleatória intra-célula, podendo tanto mascarar violações reais quanto criar falsos alarmes [@field2012mixed]; @tabachnick2013normalidade\\].\n\nUma consideração prática importante: com *n* = 41 por célula, o **Teorema Central do Limite** já oferece proteção considerável — mesmo que Shapiro indique algum desvio leve da normalidade, a ANOVA tende a ser robusta [@field2012mixed]; @howell2013repeated\\]. O que realmente importa é identificar violações graves (ex.: distribuição fortemente assimétrica ou com *outliers* extremos) em alguma célula específica.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista |>\n  dplyr::group_by(grupo, tempo) |>\n  rstatix::shapiro_test(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  grupo    tempo variable statistic      p\n  <fct>    <fct> <chr>        <dbl>  <dbl>\n1 caso     t0    residuos     0.945 0.0468\n2 caso     t1    residuos     0.960 0.154 \n3 caso     t2    residuos     0.961 0.167 \n4 controle t0    residuos     0.945 0.0484\n5 controle t1    residuos     0.961 0.172 \n6 controle t2    residuos     0.943 0.0414\n```\n\n\n:::\n:::\n\n\nOs três momentos apresentam *p* \\< 0,05, estatisticamente significativas, mas leves. Dois elementos sustentam essa afirmação:\n\n- *W* (estatística do teste) próximo de 1(0,943 a 0,045) - indica desvio pequeno da normalidade, não uma distribuição radicalmente assimétrica;\\\n- valores *p* limítrofes (0,041 - 0,048) - pequeno afastamento do limiar $\\alpha = 0,05$, sugerindo que a significância pode ser artefato da sensibilidade do teste com esse *n*.\n\nRecomenda-se complementar com QQ plots para inspecionar visualmente:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndadosL_mista |>\n  ggplot(aes(sample = residuos,\n             color = tempo)) +\n  stat_qq() +\n  stat_qq_line() +\n  facet_grid(grupo ~ tempo) +\n  labs(x = \"Quantis teóricos\",\n  y = \"Quantis observados\") +\n  theme_bw() +\n  theme(legend.position = \"none\") \n```\n\n::: {.cell-output-display}\n![Q-Q plots dos resíduos por momento](16-anovaRep_files/figure-html/fig-qqplots-1.png){#fig-qqplots fig-align='center' width=70% height=70%}\n:::\n:::\n\n\nComo os W ficaram entre 0,943 e 0,961, espera-se ver pontos majoritariamente na reta, com pequenos desvios nas caudas — o que é consistente com violação leve, não grave (@tbl-resultados2).\n\n\n::: {#tbl-resultados2 .cell tbl-cap='Interpretação dos padrões no Q-Q plot de normalidade'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-0272152c{}.cl-0269adb0{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(255, 255, 255, 1.00);background-color:transparent;}.cl-0269adc4{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-026d370a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-026d67ac{width:3.02in;background-color:rgba(127, 127, 127, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67c0{width:3.801in;background-color:rgba(127, 127, 127, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67c1{width:3.02in;background-color:rgba(229, 229, 229, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67c2{width:3.801in;background-color:rgba(229, 229, 229, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67ca{width:3.02in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67cb{width:3.801in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67d4{width:3.02in;background-color:rgba(229, 229, 229, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-026d67d5{width:3.801in;background-color:rgba(229, 229, 229, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0272152c'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-026d67ac\"><p class=\"cl-026d370a\"><span class=\"cl-0269adb0\">Padrão no gráfico</span></p></th><th class=\"cl-026d67c0\"><p class=\"cl-026d370a\"><span class=\"cl-0269adb0\">Interpretação</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026d67c1\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Pontos na reta</span></p></td><td class=\"cl-026d67c2\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Normalidade atendida</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026d67ca\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Curva em \"S\"</span></p></td><td class=\"cl-026d67cb\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Distribuição com caudas mais pesadas (heavy tails)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026d67c1\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Pontos acima da reta nas extremidades</span></p></td><td class=\"cl-026d67c2\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Assimetria positiva (cauda à direita)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026d67ca\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Pontos abaixo da reta nas extremidades</span></p></td><td class=\"cl-026d67cb\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Assimetria negativa (cauda à esquerda)</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-026d67d4\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Pontos isolados nas extremidades</span></p></td><td class=\"cl-026d67d5\"><p class=\"cl-026d370a\"><span class=\"cl-0269adc4\">Outliers</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\n#### Pesquisa de outliers nos residuos\n\nA presença de *outliers* serão analisados, usando função `identify_outliers()` do pacote `rstatix`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista |>\n  dplyr::group_by(grupo, tempo) |>\n  rstatix::identify_outliers(residuos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 7\n  grupo    tempo id    escores residuos is.outlier is.extreme\n  <fct>    <fct> <fct>   <dbl>    <dbl> <lgl>      <lgl>     \n1 controle t1    82        120     115. TRUE       FALSE     \n```\n\n\n:::\n:::\n\n\nO *outlier* está em uma célula sem violação de normalidade O participante id = 82 (controle ~t~1) aparece numa célula com W = 0,961 e *p* = 0,172 — que não havia sinalizado problema no Shapiro-Wilk.\\\nÉ um *outlier* leve, não extremo `is.extreme = FALSE` indica que o valor está entre $1,5 \\times IIQ$ e $3 \\times IIQ$ dos quartis — o critério do boxplot para outlier leve. Não ultrapassa o limiar de *outlier* extremo (\\> 3×IIQ), que seria mais preocupante.\n\nO resíduo de \\~115 é expressivo em termos absolutos, mas com n = 41 na célula e sem classificação como extremo, a ANOVA mista permanece válida. Poderia-se investigar o id = 82 nos dados originais para verificar se é um erro de entrada ou um valor genuíno. Como é plausível, deve-se mantê-lo na análise e reportar a sua existência.\n\n#### Homogeneidade de variâncias (fator entre-sujeitos)\n\nComo o fator `grupo` é entre-sujeitos, o modelo assume que a variância dos escores é igual entre os grupos em cada momento. Verifica-se com o teste de Levene:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista |>\n  dplyr::group_by(tempo) |>\n  rstatix::levene_test(escores ~ grupo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  tempo   df1   df2 statistic      p\n  <fct> <int> <int>     <dbl>  <dbl>\n1 t0        1    80   0.00639 0.936 \n2 t1        1    80   4.37    0.0397\n3 t2        1    80   4.71    0.0330\n```\n\n\n:::\n:::\n\n\nSerá realizada uma verificação da razão das variâncias entre grupos por tempo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosL_mista |>\n  dplyr::group_by(grupo, tempo) |>\n  dplyr::summarise(variancia = round(var(escores), 1), \n                   .groups = \"drop\") |>\n  tidyr::pivot_wider(names_from = grupo, values_from = variancia) |>\n  dplyr::mutate(razao = round(caso / controle, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  tempo  caso controle razao\n  <fct> <dbl>    <dbl> <dbl>\n1 t0    1835.    1899.  0.97\n2 t1    2830     1404.  2.01\n3 t2    3149     1670.  1.89\n```\n\n\n:::\n:::\n\n\nHá violação em t~1~ e t~2~, mas o contexto atenua a preocupação. A variância do grupo `caso` é aproximadamente o dobro da do grupo `controle` nesses momentos (razões de \\~2:1), enquanto t~0~ está praticamente idêntico (0,97).\n\nPor que os resultados da ANOVA permanecem confiáveis?\n\nO fator determinante aqui é o equilíbrio do delineamento — grupos com *n* igual (41 × 41). Com tamanhos amostrais iguais, o teste *F* da ANOVA é reconhecidamente robusto a violações moderadas da homogeneidade de variâncias: a taxa de erro Tipo I se mantém próxima ao $\\alpha$ nominal mesmo com razões de variância de 2:1 a 4:1 [@field2012mixed; @howell2013repeated; @maxwell2004assumptions].\n\nRazões acima de 9:1 com grupos desbalanceados seriam motivo de maior preocupação.\n\nOs pressupostos estão suficientemente atendidos para validar os resultados da ANOVA mista. A violação da homogeneidade deve ser reportada junto com a justificativa do *n* balanceado.\n\n### Testes *post hoc*\n\n[Efeitos simples de tempo dentro de cada grupo]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm_tempo <- emmeans(modelo_ez2, ~ tempo | grupo)\npairs(emm_tempo, adjust = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrupo = caso:\n contrast estimate   SE df t.ratio p.value\n t0 - t1     -30.2 4.45 80  -6.779 <0.0001\n t0 - t2     -54.6 5.15 80 -10.601 <0.0001\n t1 - t2     -24.4 5.28 80  -4.626 <0.0001\n\ngrupo = controle:\n contrast estimate   SE df t.ratio p.value\n t0 - t1      -7.8 4.45 80  -1.752  0.2508\n t0 - t2     -27.8 5.15 80  -5.395 <0.0001\n t1 - t2     -20.0 5.28 80  -3.785  0.0009\n\nP value adjustment: bonferroni method for 3 tests \n```\n\n\n:::\n:::\n\n\n[Efeitos simples de grupo em cada momento]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemm_grupo <- emmeans(modelo_ez2, ~ grupo | tempo)\npairs(emm_grupo, adjust = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntempo = t0:\n contrast        estimate    SE df t.ratio p.value\n caso - controle    -9.51  9.54 80  -0.997  0.3219\n\ntempo = t1:\n contrast        estimate    SE df t.ratio p.value\n caso - controle    12.88 10.20 80   1.267  0.2088\n\ntempo = t2:\n contrast        estimate    SE df t.ratio p.value\n caso - controle    17.32 10.80 80   1.597  0.1141\n```\n\n\n:::\n:::\n\n\n**Interpretação da interação:**\n\nOs dois grupos melhoram ao longo do tempo, mas com trajetórias distintas. O grupo *caso* apresenta melhora significativa em todos os intervalos — inclusive de t~0~ para t~1~ (*p* \\< 0,0001). O grupo *controle*, por sua vez, não apresenta mudança significativa entre t~0~ e t~1~ (*p* = 0,251), com a melhora ocorrendo apenas a partir de t~1~. Essa diferença na velocidade de mudança inicial é o que sustenta a interação significativa.\n\nEm nenhum momento isolado os grupos diferem significativamente entre si — o que é consistente com o efeito principal de `grupo` não significativo.\n\nA @fig-pfe2 confirma visualmente o padrão encontrado no *post hoc*. Algumas observações:\n\n- Em **t~0~**, o grupo *caso* parte de uma média ligeiramente inferior ao *controle* (\\~175 vs \\~184).\n\n- Entre **t~0~ e t~1~**, o grupo *caso* apresenta um salto expressivo (+30 pontos), enquanto o *controle* praticamente não muda (+8 pontos, n.s.) — essa é a origem da interação.\n\n- Entre **t~1~ e t~2~**, as duas linhas sobem com inclinações similares, convergindo para médias próximas em t~2~.\n\n- As barras de erro (IC 95%) das médias marginais estimadas se sobrepõem em todos os momentos, consistente com o efeito principal de `grupo` não significativo.\n\n### Tamanho do Efeito Padronizado\n\nO TEP extraído será o eta quadrado generalizado (GES) que é o mais recomendado para a ANOVA Mista. Para executar essa ação, será utilizada a função `eta_squared()` do pacote `effectsize` [@ben2020effectsize]. Essa função pode retornar o $eta^{2}$ , $eta^{2}$ parcial e o $eta^{2}$ generalizado. O padrão é o $eta^{2}$ parcial , portanto deve-se especificar com o argumento o tipo de $eta^{2}$ desejado.\n\n**Eta quadrado** **generalizado dos efeitos principais e da interação**\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_g <- effectsize::eta_squared(modelo_ez2, generalized = TRUE)\neffectsize::interpret_eta_squared(eta_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type III)\n\nParameter   | Eta2 (generalized) |       95% CI | Interpretation\n----------------------------------------------------------------\ngrupo       |           5.68e-03 | [0.00, 1.00] |     very small\ntempo       |               0.12 | [0.05, 1.00] |         medium\ngrupo:tempo |               0.02 | [0.00, 1.00] |          small\n\n- Observed variables: All\n- One-sided CIs: upper bound fixed at [1.00].\n- Interpretation rule: field2013\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-output .cell tbl-cap='Eta quadrado generalizado dos efeitos da ANOVA mista'}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"tabwid\"><style>.cl-02f3b0f0{}.cl-02e57c92{font-family:'Arial';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(255, 255, 255, 1.00);background-color:transparent;}.cl-02e57c9c{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-02ebcc3c{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02ebcc50{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-02ec0792{width:2.132in;background-color:rgba(44, 62, 80, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec079c{width:1.177in;background-color:rgba(44, 62, 80, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec079d{width:1.058in;background-color:rgba(44, 62, 80, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec079e{width:1.143in;background-color:rgba(44, 62, 80, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07a6{width:2.132in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07b0{width:1.177in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07b1{width:1.058in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07ba{width:1.143in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07bb{width:2.132in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07bc{width:1.177in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07c4{width:1.058in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07c5{width:1.143in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07ce{width:2.132in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07d8{width:1.177in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07d9{width:1.058in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-02ec07da{width:1.143in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-02f3b0f0'><thead><tr style=\"overflow-wrap:break-word;\"><th class=\"cl-02ec0792\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c92\">Efeito</span></p></th><th class=\"cl-02ec079c\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c92\">η²g</span></p></th><th class=\"cl-02ec079d\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c92\">IC 95% inf.</span></p></th><th class=\"cl-02ec079e\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c92\">IC 95% sup.</span></p></th></tr></thead><tbody><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02ec07a6\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">Grupo (entre-sujeitos)</span></p></td><td class=\"cl-02ec07b0\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.005682353</span></p></td><td class=\"cl-02ec07b1\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.000</span></p></td><td class=\"cl-02ec07ba\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">—</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02ec07bb\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">Tempo (intra-sujeitos)</span></p></td><td class=\"cl-02ec07bc\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.120077765</span></p></td><td class=\"cl-02ec07c4\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.048</span></p></td><td class=\"cl-02ec07c5\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">—</span></p></td></tr><tr style=\"overflow-wrap:break-word;\"><td class=\"cl-02ec07ce\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">Grupo × Tempo (interação)</span></p></td><td class=\"cl-02ec07d8\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.016306245</span></p></td><td class=\"cl-02ec07d9\"><p class=\"cl-02ebcc50\"><span class=\"cl-02e57c9c\">0.000</span></p></td><td class=\"cl-02ec07da\"><p class=\"cl-02ebcc3c\"><span class=\"cl-02e57c9c\">—</span></p></td></tr></tbody></table></div>\n```\n\n:::\n:::\n\n\nA saída do código do `effectsize` , usada para criar a @tbl-output, mostra que o efeito do `tempo` tem magnitude grande (η²g = 0,12), o que indica que aproximadamente 12% da variância dos escores (excluindo a variância do erro entre-sujeitos) é explicada pela mudança ao longo dos momentos. A interação `grupo × tempo` tem magnitude moderada (η²g = 0,02), e o efeito principal de `grupo` é negligenciável (η²g \\< 0,0057).\n\n### Conclusão\n\nA análise da ANOVA mista revelou que o fator **tempo** exerceu um efeito significativo sobre os valores de Peak Flow (*F*(2,160) = 68.725, *p* \\< 0.001, ges = 0.120), indicando uma evolução consistente da função pulmonar ao longo das avaliações. Além disso, observou‑se uma interação significativa entre **grupo × tempo** (*F*(2,160) = 8.348, *p* \\< 0.001, ges = 0.016), demonstrando que a trajetória de melhora diferiu entre os grupos. O efeito principal de **grupo**, entretanto, não foi significativo (*F*(1,80) = 0.544, *p* = 0.463, ges = 0.006), sugerindo que as diferenças globais entre os grupos não são suficientemente robustas quando se considera a variabilidade total.\n\nAs análises post hoc com correção de Bonferroni mostraram que, embora o grupo caso tenha apresentado médias superiores em t1 e t2, **as comparações diretas entre grupos em cada tempo não atingiram significância estatística** (t0: *p* = 0.305; t1: *p* = 0.212; t2: *p* = 0.101). Esses resultados indicam que, apesar da tendência favorável ao novo corticoide, as diferenças pontuais entre grupos não são estatisticamente confirmadas após ajuste conservador.\n\nPor outro lado, a análise dentro dos grupos mostrou um padrão claro: o **novo corticoide** promoveu uma melhora acentuada e progressiva, com diferenças significativas entre todos os momentos avaliados, enquanto o **corticoide padrão** apresentou melhora mais lenta, sem alteração significativa entre t0 e t1. O tamanho do efeito generalizado (GES) reforça essa interpretação: o efeito do tempo foi **moderado a forte** (ges = 0.120), enquanto a interação grupo × tempo apresentou **efeito pequeno, porém significativo** (ges = 0.016), compatível com diferenças na trajetória de evolução, mas não necessariamente nas comparações pontuais.\n\nEm síntese, os resultados indicam que o novo corticoide proporciona **melhora clínica mais rápida e mais pronunciada** na função pulmonar, ainda que as diferenças entre grupos em cada tempo isolado não tenham alcançado significância estatística (@fig-pfe3). A combinação dos achados — significância da interação, padrão dos post hocs e magnitude dos tamanhos de efeito — sugere que o novo tratamento apresenta **vantagem terapêutica relevante**, especialmente no ritmo e intensidade da recuperação do Peak Flow.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodelo <- dadosL_mista  |>  \n  rstatix::anova_test(dv = escores, \n             wid = id, \n             within = tempo,\n             between = grupo,\n             type = 3) \n\npwc <- dadosL_mista  |> \n  dplyr::group_by(tempo)  |> \n  pairwise_t_test(escores ~ grupo, \n                  paired = TRUE,\n                  p.adjust.method = \"bonferroni\")\n\npvalores <- dadosL_mista  |> \n  group_by(tempo)  |> \n  pairwise_t_test(escores ~ grupo, \n                  paired = TRUE,\n                  p.adjust.method = \"bonferroni\")  |> \n  mutate(y.position = 250)\n\nggpubr::ggline(dadosL_mista, \n               x = \"tempo\",\n               y = \"escores\",\n               color = \"grupo\",\n               palette = \"d3\",\n               linewidth = 0.7,\n               linetype = \"dashed\",\n               add = \"mean_ci\",\n               error.plot = \"errorbar\",\n               position = position_dodge(width = 0.3),\n               point.size = 1.5,\n               ylab = \"Pico de Fluxo Expiratório (l/min)\",\n               xlab = \"Momento\",\n               legend = \"top\",\n               ggtheme = theme_classic()) +\n  theme(legend.position = \"top\")+\n  geom_text(data = pvalores, \n            aes(x = tempo, \n                y = y.position, \n                label = paste0(\"p = \", signif(p, 3))),\n            inherit.aes = FALSE, size = 4) + \n  scale_x_discrete(limits = c(\"t0\", \"t1\", \"t2\"),\n                   labels = c(\"Basal\", \"45 dias\", \"90 dias\")) +\n  labs(subtitle = get_test_label(modelo, detailed = TRUE),\n       caption = get_pwc_label(pwc),\n       color = NULL)\n```\n\n::: {.cell-output-display}\n![Efeito do novo corticoide inalatório nos escores de Pico de Fluxo Expiratório ao longo do tempo por grupo](16-anovaRep_files/figure-html/fig-pfe3-1.png){#fig-pfe3 fig-align='center' width=70% height=70%}\n:::\n:::\n\n",
    "supporting": [
      "16-anovaRep_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/tabwid-1.1.3/tabwid.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/tabwid-1.1.3/tabwid.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}