{
  "hash": "1619f205d7081898148a3bc3fd6f55db",
  "result": {
    "engine": "knitr",
    "markdown": "# Manipulação dos dados no R\n\n## Dataframes no R {#sec-dataframes}\n\nDataFrames são objetos de dados genéricos em formato tabular, onde os dados são organizados de maneira lógica em linha-e-coluna semelhante ao de uma planilha do Excel. O dataframe é uma estrutura bidimensional e pode ser formado com objetos criados previamente, desde que tenham o mesmo comprimento [@zuur2009beginner].\n\nUma das formas de criar um DataFrame no R é a partir de um conjunto de vetores, como, por exemplo, estes, relacionados a 15 nascimentos em uma determinada maternidade:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nid <- c(1:15)\npeso_rn <- c (3340,3345,3750,3650,3220,4070,3380,3970,3060,3180,  \n              2865,2815,3245,2051,2630)  \ncomp_rn <- c (50,48,52,48,50,51,50,51,47,47,47,49,51,50,44)\nsexo <- c (\"F\", \"F\", \"F\", \"M\", \"M\", \"M\", \"F\", \"M\", \"M\", \"M\", \"F\", \"F\", \"M\", \"M\", \"F\")\ntipo_parto <- c (\"normal\", \"normal\", \"cesareo\", \"normal\", \"cesareo\", \"cesareo\", \"normal\", \"cesareo\", \"normal\", \"normal\", \"normal\", \"cesareo\", \"normal\", \"normal\", \"normal\")\nidade_mae <- c (40,19,26,19,32,24,27,20,21,19,23,36,21,23,23) \n```\n:::\n\n\nEste grupo de vetores (variáveis) isolados fica difícil de manusear. Portanto, seria útil reuni-los em um só objeto. Pode-se fazer isso, usando a função `data.frame()`, do R base. Este DataFrame será atribuído a um novo objeto de nome `dadosNeonatos`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosNeonatos <- data.frame (id,\n                             peso_rn,\n                             comp_rn, \n                             sexo,\n                             tipo_parto, \n                             idade_mae)\n```\n:::\n\n\nVerificando a classe deste novo objeto, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass (dadosNeonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data.frame\"\n```\n\n\n:::\n:::\n\n\nPara observar a modificação realizada, pode-se usar a função `str()` do R base, digitando no *R Script*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dadosNeonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t15 obs. of  6 variables:\n $ id        : int  1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num  3340 3345 3750 3650 3220 ...\n $ comp_rn   : num  50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : chr  \"F\" \"F\" \"F\" \"M\" ...\n $ tipo_parto: chr  \"normal\" \"normal\" \"cesareo\" \"normal\" ...\n $ idade_mae : num  40 19 26 19 32 24 27 20 21 19 ...\n```\n\n\n:::\n:::\n\n\nNa saída da função, verifica-se que o dataframe contém 15 linhas e 6 colunas.\n\n### Acrescentando variáveis a um dataframe\n\nSerá adicionada ao dataframe uma nova variável chamada `uti_neo`, que indica se cada recém-nascido foi encaminhado ou não para a UTI neonatal logo após o nascimento. Essa variável será construída a partir de um vetor contendo a situação de cada um dos 15 recém-nascidos, e será incorporada como uma nova coluna no dataframe. A sintaxe utilizada para essa operação segue o padrão `nome-do-dataframe$nome-da-variável`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosNeonatos$uti_neo <- c (\"não\",\"não\",\"não\",\"não\",\"sim\",\"não\",\"sim\",\"não\",\"não\",\"não\",\"não\",\"sim\",\"não\",\"não\",\"não\")\n```\n:::\n\n\nCom isso, a variável `uti_neo` passa a fazer parte do conjunto de dados, permitindo análises específicas sobre a necessidade de cuidados intensivos neonatais. A função`str()`, pode ser usada, novamente, para observar a modificação:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dadosNeonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t15 obs. of  7 variables:\n $ id        : int  1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num  3340 3345 3750 3650 3220 ...\n $ comp_rn   : num  50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : chr  \"F\" \"F\" \"F\" \"M\" ...\n $ tipo_parto: chr  \"normal\" \"normal\" \"cesareo\" \"normal\" ...\n $ idade_mae : num  40 19 26 19 32 24 27 20 21 19 ...\n $ uti_neo   : chr  \"não\" \"não\" \"não\" \"não\" ...\n```\n\n\n:::\n:::\n\n\n### Transformação de variáveis {#sec-transform}\n\nObserva-se que todas as variáveis `sexo`, `tipo_parto` e `uti_neo` estão, no dataframe, como caractere (`chr`). Entretanto, elas são variáveis categóricas, portanto, necessitam ser transformadas para fatores. Como pertencem à classe `character`, então, basta usar a `as.factor()` sem necessidade de alterar os rótulos (`labels`) nos níveis (`levels`), o que seria necessário com o uso da função `factor()`, como mostrado na @sec-fatores e @sec-newcol.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndadosNeonatos$tipo_parto <- as.factor(dadosNeonatos$tipo_parto)\ndadosNeonatos$sexo <- as.factor (dadosNeonatos$sexo) \ndadosNeonatos$uti_neo <- as.factor (dadosNeonatos$uti_neo)\n```\n:::\n\n\nApós a transformação, executa-se, novamente, a função `str()` para ver como ficou a estrutura do dataframe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(dadosNeonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t15 obs. of  7 variables:\n $ id        : int  1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num  3340 3345 3750 3650 3220 ...\n $ comp_rn   : num  50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : Factor w/ 2 levels \"F\",\"M\": 1 1 1 2 2 2 1 2 2 2 ...\n $ tipo_parto: Factor w/ 2 levels \"cesareo\",\"normal\": 2 2 1 2 1 1 2 1 2 2 ...\n $ idade_mae : num  40 19 26 19 32 24 27 20 21 19 ...\n $ uti_neo   : Factor w/ 2 levels \"não\",\"sim\": 1 1 1 1 2 1 2 1 1 1 ...\n```\n\n\n:::\n:::\n\n\nAgora, as três variáveis passaram a ser fatores e as outras mantiveram-se numéricas.\n\n### Salvando um dataframe {#sec-salvadf}\n\nO dataframe, criado e modificado anteriormente, pode ser salvo para uso posterior no diretório de trabalho. Os formatos mais comuns e eficientes incluem arquivos nativos do R como `.RData` e `.rds`, arquivos de texto como `.txt`, formatos otimizados para Big Data como `.parquet`, e extensões de outros softwares estatísticos como `.xlsx` (Excel), `.csv` (Valores Separados por Vírgula), `.sav` (SPSS) e `.dta` (Stata).\n\nAs formas bastante usadas para salvar um dataframe são `.xlsx` e `.csv`. Para salvar em uma extensão `.xlsx`, utiliza-se a função `write_xlsx ()` do pacote `writexl` [@ooms2022writexl]. O dataframe dadosNeonatos será salvo como:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwritexl::write_xlsx(dadosNeonatos, \"dados/dadosNeonatos.xlsx\")\n```\n:::\n\n\nPara salvar com a extensão `.csv`, usar a função `write_csv()` ou `write_csv2()` que fazem parte do pacote `readr` [@wickham2026readr]. A primeira função, usa `\".\"` para a separação dos decimais e `\",\"` para separar as variáveis; a segunda função usa `\",\"` para os decimais e `\";\"` para separar as variáveis, convenção do Excel para algumas localidades, como o Brasil [@write2022csv]. Portanto, uma maneira de salvar o arquivo é:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_csv2 (dadosNeonatos, \"dados/dadosNeonatos.csv\")\n```\n:::\n\n\n## Importando dados de outros *softwares*\n\nÉ possível inserir dados diretamente no *R Script*, como visto na @sec-dataframes. Entretanto, se o conjunto de dados for muito extenso, torna-se complicado. Desta forma, é melhor construir o dataframe em outro software, como o Excel, SPSS, etc. e, após, quando necessário, importar os dados para o R.\n\n### Importando dados de um arquivo CSV {#sec-csv}\n\nO formato CSV significa *Comma Separated Values*, ou seja, é um arquivo de valores separados por vírgula. Esse formato de armazenamento é simples e agrupa informações de arquivos de texto em planilhas. É possível gerar um arquivo `.csv`, a partir de uma planilha do *Excel*, usando o menu `salvar como` e escolher `CSV`.\n\nAs funções `read_csv()` e `read_csv2()`, pertencentes ao pacote `readr`, incluído no ecossistema `tidyverse` [@wickham2019tidyverse], podem ser utilizadas para importar arquivos CSV. A principal diferença entre elas está nos separadores de coluna (variáveis) e nos separadores decimais que cada uma utiliza por padrão.\n\n- `read_csv` (padrão americano)\n\n  - separador de colunas: vírgula (,)\n\n  - separador de decimais: ponto (.)\n\n  - uso ideal para arquivos gerados no padrão americano\n\n- `read_csv2` (padrão brasileiro/europeu)\n\n  - separador de colunas: ponto e vírgula (;)\n\n  - separador de decimais: vírgula (,)\n\n  - uso ideal para arquivos gerados por versões em português do Excel, onde a vírgula é usada nos números decimais\n\n::: callout-tip\n## Importante\n\nAo tentar abrir um arquivo com `read_csv()` e todas as colunas ficarem agrupadas em uma única linha má estruturada, ou se os números com vírgula virarem texto (`character`), mudar para `read_csv2()`.\n:::\n\nPortanto, quando se importa um arquivo `.csv`, é importante saber qual a sua estrutura. Verificar se os decimais estão separados por *ponto* ou por *vírgula* e se as colunas (variáveis), por *vírgula* ou *ponto e vírgula*. Para ver isso, basta abrir o arquivo em um bloco de notas (por exemplo, *Bloco de Notas do Windows*, *Notepad ++, etc.*).\n\nAlém disso, é necessário saber em que diretório do computador está o arquivo para informar ao comando. Recomenda-se colocar o arquivo na pasta do diretório de trabalho, pois assim basta apenas colocar o nome do arquivo na função de leitura dos dados. Caso contrário, tem-se que se usar todo o caminho (*path*).\n\nComo exemplo, será importado o arquivo `dadosNeonatos.csv` que se encontra no diretório de trabalho do autor, salvo anteriormente. Para obter o arquivo, siga os passos da @sec-dataframes ou clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosNeonatos.csv) e salve em seu diretório de trabalho.\n\nA estrutura deste arquivo mostra que as colunas estão separadas por ponto e vírgula e, portanto, a leitura dos dados será feita com a função `read_csv2()` e, como o arquivo está no diretório de trabalho, não há necessidade de informar o diretório completo. Os dados serão colocados em um objeto de nome `neonatos` [^05-manipulacao_dados-1]:\n\n[^05-manipulacao_dados-1]: A mudança do nome do dataframe de `dadosNeonatos` para `neonatos` é desnecessária. Foi realizada apenas por questões didáticas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\n\nneonatos <- read_csv2(\"dados/dadosNeonatos.csv\")\n```\n:::\n\n\nUse a função `str()` para visualizar o conjunto de dados:[^05-manipulacao_dados-2]\n\n[^05-manipulacao_dados-2]: Observe, na saída, que a variável `uti_neo` aparece palavras com acentuação (“não”). Às vezes, ao abrir o arquivo com a função `read_csv2()`, pode acontecer de esta palavra aparecer, por exemplo, como: “`n\\\\xe3o`”. Louco, não é? Se ocorrer isso, use, após o nome do arquivo e separado por vírgula, o argumento `locale = locale(encoding = \"latin1\")`. Dessa forma, o erro será corrigido.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(neonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [15 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ id        : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num [1:15] 3340 3345 3750 3650 3220 ...\n $ comp_rn   : num [1:15] 50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : chr [1:15] \"F\" \"F\" \"F\" \"M\" ...\n $ tipo_parto: chr [1:15] \"normal\" \"normal\" \"cesareo\" \"normal\" ...\n $ idade_mae : num [1:15] 40 19 26 19 32 24 27 20 21 19 ...\n $ uti_neo   : chr [1:15] \"não\" \"não\" \"não\" \"não\" ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   id = col_double(),\n  ..   peso_rn = col_double(),\n  ..   comp_rn = col_double(),\n  ..   sexo = col_character(),\n  ..   tipo_parto = col_character(),\n  ..   idade_mae = col_double(),\n  ..   uti_neo = col_character()\n  .. )\n - attr(*, \"problems\")=<pointer: 0x00000149510ffa10> \n```\n\n\n:::\n:::\n\n\nComo se observa na saída do comando, as variáveis foram importadas em classes que vão necessitar transformações para serem usadas. Isto deve ser feito como foi visto na @sec-transform.\n\n::: callout-caution\n## Atenção\n\nToda vez que se importa um dataset, deve-se verificar atentamente a sua estrutura antes de dar seguimento as análises\n:::\n\n### Importando um arquivo do Excel {#sec-xlsx}\n\nO pacote `readxl`, pertencente ao conjunto de pacotes do `tidyverse`, facilita a obtenção de dados do Excel para o R, através da função `read_excel()`. Esta função tem o argumento `sheet =`, que deve ser usado indicando o número ou o nome da planilha, colocado entre aspas. Este argumento é importante se houver mais de uma planilha, caso contrário, ele é opcional. Para saber os outros argumentos da função, coloque o cursor dentro da função e aperte a tecla `Tab` (@fig-sheet). Isto abrirá um menu com os argumentos:\n\n![Argumentos da função para importar arquivos .xlsx](images/sheet_arg.png){#fig-sheet fig-align=\"center\" width=\"16cm\"}\n\nSerá feita a leitura dos mesmos dados, usados na leitura de dados `csv`, apenas o arquivo agora está no formato `.xlsx`. Para obter o arquivo, siga os mesmos passos, usados anteriormente. Clique [**aqui**](https://github.com/petronioliveira/Arquivos/blob/main/dadosNeonatos.xlsx) e salve em seu diretório de trabalho.\n\nOs dados serão atribuídos a um objeto com outro nome (`recemNatos`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrecemNatos <- readxl::read_excel(\"dados/dadosNeonatos.xlsx\")\nstr(recemNatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [15 × 7] (S3: tbl_df/tbl/data.frame)\n $ id        : num [1:15] 1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num [1:15] 3340 3345 3750 3650 3220 ...\n $ comp_rn   : num [1:15] 50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : chr [1:15] \"F\" \"F\" \"F\" \"M\" ...\n $ tipo_parto: chr [1:15] \"normal\" \"normal\" \"cesareo\" \"normal\" ...\n $ idade_mae : num [1:15] 40 19 26 19 32 24 27 20 21 19 ...\n $ uti_neo   : chr [1:15] \"não\" \"não\" \"não\" \"não\" ...\n```\n\n\n:::\n:::\n\n\nComo se vê ao analisar a estrutura, deve-se proceder transformações nas variáveis, como visto na @sec-transform.\n\nNa @fig-sheet, o duplo dois pontos (`::`) precedido do nome do pacote, no caso `readxl`, especifica a procedência da função usada. Nessa situação, não há necessidade de usar a função `library()` para carregar o pacote já instalado em um diretório (biblioteca) previamente.\n\n### Importando arquivos com o *RStudio*\n\nO `RStudio` permite importar arquivos sem a necessidade de digitar comandos, que, para alguns podem ser tediosos.\n\nNa tela inicial do `RStudio`, à direita, na parte superior, clique na aba *Environment* e em `Import Dataset`. Esta ação abre um menu que permite importar arquivos .csv, Excel, SPSS, etc.\n\nPor exemplo, para importar o arquivo `dadosNeonatos.xlsx`, clicar em `From Excel...` Abre uma janela com uma caixa de diálogo. Clicar no botão `Browse...`, localizado em cima à direita, para buscar o arquivo `dadosNeonatos.xlsx`. Assim que o arquivo for aberto, ele mostra uma *preview* do arquivo e, em baixo, à direita mostra uma *pré-visualização* do código (@fig-import)), igual ao digitado anteriormente, que cria um objeto denominado `dadosNeonatos`, nome do objeto escolhido pelo R, mas pode ser modificado na janela, à esquerda, `Import Option` em `Name`, onde pode-se digitar qualquer nome. Após encerrar as escolhas, clicar em `Import`. É um caminho diferente para fazer o mesmo. Este é um dos fascínios do R!\n\n![Importando arquivos do excel com o RStudio](images/import_rstudio.png){#fig-import fig-align=\"center\" width=\"20cm\"}\n\n### Importando dados de forma simples\n\nA grande elegância do R está na simplicidade, o pacote `rio` (*R Input/Output*) [@chan2023rio] é o modelo de simplicidade quando se fala em importar e exportar dados. Está baseado no conceito de *Swiss Army Knife* (canivete suíço) e reduz o processo de entrada e saída de dados a duas funções principais: `import()` e `export()`.\n\nEle descobre o formato do arquivo automaticamente através da extensão (`.csv`, `.xlsx`, `.sav`, etc.) e chama o pacote correto nos bastidores (como `readr`, `readxl`, `haven`, `data.table`), sem que se necessite carregar todos eles manualmente.\n\nNão importa a fonte dos dados, a sintaxe é a mesma:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rio)\ndados <- rio::import(\"dados/dadosNeonatos.xlsx\")\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t15 obs. of  7 variables:\n $ id        : num  1 2 3 4 5 6 7 8 9 10 ...\n $ peso_rn   : num  3340 3345 3750 3650 3220 ...\n $ comp_rn   : num  50 48 52 48 50 51 50 51 47 47 ...\n $ sexo      : chr  \"F\" \"F\" \"F\" \"M\" ...\n $ tipo_parto: chr  \"normal\" \"normal\" \"cesareo\" \"normal\" ...\n $ idade_mae : num  40 19 26 19 32 24 27 20 21 19 ...\n $ uti_neo   : chr  \"não\" \"não\" \"não\" \"não\" ...\n```\n\n\n:::\n:::\n\n\nPara converter um arquivo de Excel para CSV, basta mudar a extensão no destino:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Salva um data.frame .xlsx como .csv\nrio::export(dados, \"dados/dados_rn.csv\")\n```\n:::\n\n\nEsta função `export()` faz o mesmo que as funções `write_xlsx()` e `write_csv2()`, vistas acima (@sec-salvadf).\n\n::: callout-tip\n## Dica\n\nPara garantir que o `rio` consiga ler absolutamente qualquer formato (incluindo SPSS, SAS, etc.), é recomendado instalar os pacotes auxiliares recomendados, rodando uma única vez:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrio::install_formats()\n```\n:::\n\n\nAssim, quando o `rio` for chamado a trabalhar, ele vai checar todos os formatos e instalar de uma só vez todos que faltarem no computador. Por isso, a metáfora \"canivete suíço\" se encaixa nas suas funções.\n:::\n\n## Tibble {#sec-tibble}\n\nA maneira mais comum de armazenar dados no R é usar `data.frames` ou `tibble`.\n\n*Tibble* é um novo tipo de dataframe. É como se fosse um dataframe mais moderno. Ele mantém muitos recursos importantes do data frame original, mas remove muitos dos recursos desatualizados.\n\nA maioria dos pacotes do R usa dataframes tradicionais; entretanto, é possível transformá-los em `tibble`, usando a função `as_tibble()`, do pacote `tibble` [@wickham2026tibble][^05-manipulacao_dados-2b]. Esse pacote fornece uma versão moderna do dataframe, com impressão mais informativa e comportamento mais previsível. A transformação de um dataframe tradicional em um `tibble` é um procedimento recomendável, em função da maior flexibilidade destes.\n\n[^05-manipulacao_dados-2b]: A função `as_tibble()` também fica disponível ao carregar outros pacotes do `tidyverse`, como o `tidyr` ou o `dplyr`, que a reexportam do pacote `tibble`.\n\nComo exemplo deste procedimento, será usado o dataframe criado na @sec-dataframes: `dadosNeonatos`.\n\nEste é um conjunto de dados da classe `data.frame`, contendo 15 observações de 7 variáveis (colunas), que pode ser convertido a um `tibble`, usando a função `as_tibble()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tibble)\nas_tibble(dadosNeonatos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 15 × 7\n      id peso_rn comp_rn sexo  tipo_parto idade_mae uti_neo\n   <int>   <dbl>   <dbl> <fct> <fct>          <dbl> <fct>  \n 1     1    3340      50 F     normal            40 não    \n 2     2    3345      48 F     normal            19 não    \n 3     3    3750      52 F     cesareo           26 não    \n 4     4    3650      48 M     normal            19 não    \n 5     5    3220      50 M     cesareo           32 sim    \n 6     6    4070      51 M     cesareo           24 não    \n 7     7    3380      50 F     normal            27 sim    \n 8     8    3970      51 M     cesareo           20 não    \n 9     9    3060      47 M     normal            21 não    \n10    10    3180      47 M     normal            19 não    \n11    11    2865      47 F     normal            23 não    \n12    12    2815      49 F     cesareo           36 sim    \n13    13    3245      51 M     normal            21 não    \n14    14    2051      50 M     normal            23 não    \n15    15    2630      44 F     normal            23 não    \n```\n\n\n:::\n:::\n\n\nPor padrão, quando o dataset é muito longo, apenas as primeiras dez linhas são mostradas. Aqui, aparece toda a estrutura dos dados. São apresentadas a dimensão da tabela e as classes de cada coluna. Verifica-se que não houve grandes mudanças, apenas o conjunto de dados está estruturalmente mais organizado, mais flexível.\n\n## Pacote tidyverse {#sec-tidyverse}\n\nA denominada ciência de dados é difícil de definir, pois a definição depende da formação específica de cada cientista de dados. Entretanto, é possível mostrar como a ciência de dados pode ser realizada na prática, constituindo aquilo que se costuma chamar de *Ciclo da Ciência de Dados* (@fig-ciclo).\\\nPrimeiramente, os dados brutos são coletados de diversas maneiras (veja @sec-producao). Após, são armazenados, por exemplo, em Excel, e, em seguida, são arrumados para reduzir problemas de padronização, conceituais e erros ou exclusão de variáveis e casos que não fazem parte do objetivo estabelecido no projeto de pesquisa. Isto constituirá a base de dados analítica.\\\nA base de dados analítica é então transformada, refinada, para produzir medidas resumidoras, tabela e gráficos. Quando necessário, são produzidos modelos estatísticos. O resultado final deve ser comunicado através dos meios de divulgação científica (relatórios, periódicos, livros, jornadas, congressos, GitHub, etc.).\n\n![Ciclo da Ciência de Dados](images/ciencias_dados.png){#fig-ciclo fig-align=\"center\" width=\"15cm\"}\n\nO pacote `tidyverse` é uma coleção de pacotes para a linguagem de programação R, pensada e desenvolvida para facilitar e otimizar o fluxo de trabalho em ciência de dados [@wickham2019tidyverse].\\\nEm vez de ser um pacote único, ele é um \"meta-pacote\", o que significa que, ao instalá-lo, você instala vários pacotes menores que trabalham em conjunto.\n\nA filosofia principal por trás do `tidyverse` é a de dados \"tidy\" (arrumados ou organizados) [@wickham2014tidy], onde:\n\n- Cada variável está em uma coluna.\n\n- Cada observação está em uma linha.\n\n- Cada valor está em uma célula.\n\nSeguindo essa lógica, as funções e pacotes do `tidyverse` são projetados para facilitar a manipulação dos dados dentro do *Ciclo da Ciência de Dados* (@fig-ciclo), tornando a manipulação, a análise e a visualização de dados mais consistentes e intuitivas.\n\n### Principais Pacotes do tidyverse\n\nO `tidyverse` simplifica tarefas complexas, oferecendo ferramentas específicas para cada etapa do Ciclo de Ciências de Dados. Alguns dos pacotes mais importantes são:\n\n- **dplyr**: Para manipulação de dados. Contém funções essenciais para filtrar linhas, selecionar colunas, criar novas variáveis, e resumir dados.\n\n- **ggplot2**: Para visualização de dados. É um dos pacotes mais populares do R para criar gráficos esteticamente agradáveis e informativos.\n\n- **tidyr**: Para organizar os dados. Ele transforma dados \"bagunçados\" (que não seguem o formato tidy) em um formato mais limpo e organizado.\n\n- **readr**: Para importar dados. Permite ler arquivos de texto (como CSVs) de forma rápida e robusta.\n\n- **tibble**: Uma versão aprimorada do data.frame do R base. O `tibble` é mais fácil de usar e interage melhor com os pacotes do `tidyverse`.\n\n- **stringr**: Para manipular strings (textos). Simplifica as tarefas de trabalhar com dados de texto.\n\n- **forcats**: Para lidar com fatores (variáveis categóricas).\n\n### Princípios do tidyverse {#sec-printidyverse}\n\nO `tidyverse` causou quase uma revolução na comunidade do R. Alguns chegam a dizer que existe uma linguagem R antes e depois do `tidyverse`. Pode parecer exagero, mas o certo é que o uso dos princípios do `tidyverse` foi abraçado pela maioria dos usuários de R e, em função disso, foram criados uma grande quantidade de pacotes que conversam entre si, facilitando o manuseio dos dados.\n\nOs princípios fundamentais são:\n\n1.  Reutilizar estruturas de dados existentes.\n\n2.  Organizar funções simples usando o `pipe`[^05-manipulacao_dados-3]. Esse operador, introduzido por Stefan Milton Bache no pacote `magrittr` [@bache2022magritt], permite encadear múltiplas operações em uma sequência clara e legível, de forma que a saída de uma função se torna a entrada da próxima. Isso torna o código mais fácil de ler e entender, eliminando a necessidade de criar muitas variáveis intermediárias. O `pipe` pode ser acionado digitando `%>%` ou usando o atalho `ctrl + shift + M`[^05-manipulacao_dados-4]. Neste livro, será dado preferência para o `pipe` nativo do R (`|>`).\n\n3.  Usar uma sintaxe consistente: As funções dos pacotes tidyverse seguem uma lógica de nomeação e de argumentos parecida, facilitando a memorização e o uso.\n\n4.  Projetado com foco nos seres humanos, priorizando a eficiência do programador.\n\n[^05-manipulacao_dados-3]: O nome é uma referência ao famoso quadro do pintor belga René Magritte [*La Trahison des images*](https://decorem.com.br/blogs/news/significado-da-obra-a-traicao-das-imagens-de-rene-magritte?srsltid=AfmBOoqG3gSMhNdnwgmQ3piepQPRSkJlXkNQjQv5mDq72QYRwub3vJKz) *(Ceci n’est pas une pipe)*.\n\n[^05-manipulacao_dados-4]: Além do `pipe`, indiretamente, embutido no `tidyverse`, existe o pipe nativo do R (`|>`) que também pode ser usado com as mesmas funções do `%>%`. No menu *Tools* \\> *Global Options...* \\> *Code* e marque a opção `Use native pipe operator |>` para que o atalho `ctrl + shift + M` retorne sempe o pipe nativo. Desmarcado, retorna o pipe `magrittr`.\n\nQuando o `tidyverse` é carregado, todos os pacotes embutidos nele, serão carregados.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n:::\n\n\n::: {.callout-warning title=\"Conflito de funções ao carregar tidyverse\"}\nAo carregar o pacote `tidyverse` ou qualquer outro, podem surgir mensagens de conflito indicando que funções previamente disponíveis foram sobrescritas por versões de mesmo nome.\n\nNo exemplo apresentado, as funções `filter()` e `lag()` do pacote `stats` foram substituídas pelas versões do pacote `dplyr`.\n\nPara utilizar as funções originais do pacote `stats` após esse carregamento, é necessário especificar o namespace diretamente, usando duplo dois pontos (`::`):\\\n`stats::filter()` e `stats::lag()`.\n:::\n\n## Pacote dplyr {#sec-dplyr}\n\nUm dos pacotes de maior utilidade abarcado pelo `tidyverse` é o `dplyr`. Ele permite realizar transformação dos dados de uma forma simples e eficiente. O uso dos verbos `dplyr`, aliado ao operador `pipe`, tendem a tornar os scripts mais \"enxutos\" e elegantes [@wickham2015dplyr].\\\nAs principais funções do `dplyr` são:\n\n- `select()` - seleciona colunas\\\n- `arrange()` - ordena uma variável em ordem crescente ou decrescente\\\n- `filter()` - filtra linhas\\\n- `mutate()` - cria/modifica colunas\\\n- `group_by()` - agrupa por fatores\\\n- `summarise()` - sumariza a base\n\nTodas as funções têm as mesmas características: o primeiro argumento é um `tibble` e os demais definem a ação da função.\n\nNeste capítulo e em muitos outros deste livro, será utilizado o dataframe `dadosMater.xlsx`.\n\n## Dataframe `dadosMater.xlsx` {#sec-dadosMater}\n\nO arquivo `dadosMater.xlsx` é um dataframe constituído por dados de 1368 partos consecutivos do Hospital Geral de Caxias do Sul (HGCS)[^05-manipulacao_dados-5], durante um estudo sobre infecções congênitas [@madi2010prevalence]. Para baixar esses dados, clique [aqui](https://github.com/petronioliveira/Arquivos/blob/main/dadosMater.xlsx) e faça o *download* para o diretório de trabalho, para uso posterior.\n\n[^05-manipulacao_dados-5]: Hospital Escola da Universidade de Caxias do Sul, RS.\n\n### Leitura dos dados\n\nPara ler arquivos do Excel (`.xlsx`), o pacote ideal é o `readxl`.[^05-manipulacao_dados-6] Ele é leve, rápido e não depende do Excel instalado. A função a ser usada é `read_excel()`. O objeto `mater` será utilizado para receber os dados [^05-manipulacao_dados-7]:\n\n[^05-manipulacao_dados-6]: Poderia usar o pacote `rio` com a função `import()`:\n\n    `dados <- rio::import(\"dados/dadosMater.xlsx\")`\n\n[^05-manipulacao_dados-7]: O nome `mater` é uma escolha do autor, nesta seção. Em outros momentos, será denominado, simplesmente, `dados`. O nome do objeto é uma escolha pessoal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- readxl::read_excel(\"dados/dadosMater.xlsx\")\n```\n:::\n\n\n::: callout-important\n## Importante\n\nO comando para carregar o conjunto de dados somente funciona, sem colocar o caminho completo, se tudo está sendo realizado no diretório de trabalho.\n:::\n\nComo rotina, em análise de dados, após a leitura é interessante explorar a estrutura dos dados. A função `as_tibble()` do pacote `tibble` é interessante para ver a estrutura dos dados:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- tibble::as_tibble(mater)\nprint(mater)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,368 × 30\n      id idade_mae altura  peso ganho_peso anos_est   cor estado_civil renda\n   <dbl>     <dbl>  <dbl> <dbl>      <dbl>    <dbl> <dbl>        <dbl> <dbl>\n 1     1        42   1.65  69.9        3.9        3     2            1  1.45\n 2     2        29   1.66  78         16.5       11     1            2  2.41\n 3     3        19   1.72  81          5          9     2            1  1.93\n 4     4        31   1.55  74         43          5     2            2  1.45\n 5     5        34   1.6   60         15          7     2            2  0.48\n 6     6        29   1.5   60         11.4        8     2            2  0.96\n 7     7        30   1.54  75.5       10.5        4     1            2  1.2 \n 8     8        34   1.63  61          9          6     1            2  2.41\n 9     9        17   1.68  57         15         10     1            2  2.17\n10    10        32   1.5   70         11.4        1     2            2  0.72\n# ℹ 1,358 more rows\n# ℹ 21 more variables: fumo <dbl>, quant_fumo <dbl>, prenatal <dbl>,\n#   para <dbl>, droga <dbl>, ig <dbl>, tipo_parto <dbl>, peso_pla <dbl>,\n#   sexo <dbl>, peso_rn <dbl>, comp_rn <dbl>, pc_rn <dbl>, apgar1 <dbl>,\n#   apgar5 <dbl>, uti_neo <dbl>, obito <dbl>, hiv <dbl>, sifilis <dbl>,\n#   rubeola <dbl>, toxo <dbl>, inf_cong <dbl>\n```\n\n\n:::\n:::\n\n\nPor padrão, a função retorna as dez primeiras linhas [^05-manipulacao_dados-8]. Além disso, colunas que não couberem na largura da tela serão omitidas. Também são apresentadas a dimensão da tabela e as classes de cada coluna. Observa-se que ele tem 1368 linhas (observações) e 30 colunas (variáveis). Além disso, verifica-se que todas as variáveis estão como numéricas (`dbl`) e, certamente, algumas, dependendo do objetivo na análise, precisarão ser transformadas.\n\n[^05-manipulacao_dados-8]: Para inserir maior número de linhas: `print(n = ...)`\n\nO significado de cada uma das variáveis do `tibble` `mater` é o seguinte:\n\n- **id** $\\to$ identificação do participante\\\n- **idade_mae** $\\to$ idade da parturiente em anos\\\n- **altura** $\\to$ altura da parturiente em metros\\\n- **peso** $\\to$ peso da parturiente em kg\\\n- **ganho_peso** $\\to$ aumento de peso durante a gestação\\\n- **anos_est** $\\to$ anos de estudo completos\\\n- **cor** $\\to$ cor declarada pela parturiente: 1 = branca; 2 = não branca\\\n- **estado_civil** $\\to$ estado civil: 1 = solteira; 2 = casada ou companheira\\\n- **renda** $\\to$ renda familiar em salários mínimos\\\n- **fumo** $\\to$ tabagismo: 1 = sim; 2 = não\\\n- **quant_fumo** $\\to$ quantidade de cigarros fumados diariamente\\\n- **prenatal** $\\to$ realizou pelo menos 6 consultas no pré-natal? 1 = sim; 2 = não\n- **para** $\\to$ número de filhos paridos\\\n- **droga** $\\to$ drogadição? 1 = sim; 2 = não\\\n- **ig** $\\to$ idade gestacional em semanas\\\n- **tipo_parto** $\\to$ tipo de parto: 1 = normal; 2 = cesareana\\\n- **peso_pla** $\\to$ peso da placenta em gramas\n- **sexo** $\\to$ sexo do recém-nascido (RN): 1 = masc; 2 = fem\\\n- **peso_rn** $\\to$ peso do RN em gramas\\\n- **comp_rn** $\\to$ comprimento do RN em cm\\\n- **pc_rn** $\\to$ perímetro cefálico do recém-nascido em cm\\\n- **apgar1** $\\to$ escore de Apgar no primeiro minuto\\\n- **apgar5** $\\to$ escore de Apgar no quinto minuto\\\n- **uti_neo** $\\to$ RN necessitou de terapia intensiva? 1 = sim; 2 = não\\\n- **obito** $\\to$ óbito no período neonatal? 1 = sim; 2 = não\\\n- **hiv** $\\to$ parturiente portadora de HIV? 1 = sim; 2 = não\\\n- **sifilis** $\\to$ parturiente portadora de sífilis? 1 = sim; 2 = não\\\n- **rubeola** $\\to$ parturiente portadora de rubéola? 1 = sim; 2 = não\\\n- **toxo** $\\longrightarrow$ parturiente portadora de toxoplasmose? 1 = sim; 2 = não\\\n- **inf_cong** $\\to$ parturiente portadora de alguma infecção congênita? 1 = sim; 2 = não\n\nO *tibble* `mater` pode ser facilmente modificado com os verbos do pacote `dplyr`.\n\n### Selecionando colunas\n\nA função `select ()` pode ser usada para escolher quais colunas (variáveis) entrarão na análise. Ela recebe como primeiro argumento o conjunto de dados e os demais argumentos são os nomes das colunas. O conjunto de dados `mater` contém 30 colunas e muitas podem ser removidas, dependendo do objetivo da análise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- dplyr::select(mater, - obito, -hiv, -sifilis, -rubeola, -toxo)\n```\n:::\n\n\nNote que foi usado o sinal de menos (-) antes das variáveis, porque elas foram removidas. Também poderiam ser listadas as variáveis que permanecem que, automaticamente, as não listadas serão removidas.\n\nOutra maneira, pode ser colocando o número da coluna como abaixo, o sinal de subtração antes da função concatenar `c()` com os números das colunas a serem removidas (25 a 29):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- dplyr::select(mater, - c(25:29))\n```\n:::\n\n\nA função `str()` permite visualizar a nova estrutura:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(mater)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [1,368 × 25] (S3: tbl_df/tbl/data.frame)\n $ id          : num [1:1368] 1 2 3 4 5 6 7 8 9 10 ...\n $ idade_mae   : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...\n $ altura      : num [1:1368] 1.65 1.66 1.72 1.55 1.6 1.5 1.54 1.63 1.68 1.5 ...\n $ peso        : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...\n $ ganho_peso  : num [1:1368] 3.9 16.5 5 43 15 11.4 10.5 9 15 11.4 ...\n $ anos_est    : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...\n $ cor         : num [1:1368] 2 1 2 2 2 2 1 1 1 2 ...\n $ estado_civil: num [1:1368] 1 2 1 2 2 2 2 2 2 2 ...\n $ renda       : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...\n $ fumo        : num [1:1368] 2 2 2 2 2 1 1 2 2 2 ...\n $ quant_fumo  : num [1:1368] 0 0 0 0 0 10 20 0 0 0 ...\n $ prenatal    : num [1:1368] 2 1 2 2 2 1 1 2 2 1 ...\n $ para        : num [1:1368] 5 0 0 1 2 1 2 1 0 4 ...\n $ droga       : num [1:1368] 2 2 2 2 2 2 2 2 2 2 ...\n $ ig          : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...\n $ tipo_parto  : num [1:1368] 2 2 1 1 2 1 2 1 1 2 ...\n $ peso_pla    : num [1:1368] 224 1118 452 432 574 ...\n $ sexo        : num [1:1368] 2 2 2 2 2 2 2 2 2 2 ...\n $ peso_rn     : num [1:1368] 1035 2300 1580 1840 2475 ...\n $ comp_rn     : num [1:1368] 35.5 45 39 41 47 41 44 44 47 48 ...\n $ pc_rn       : num [1:1368] 28 32 28 32 32 29 32 32 30 27 ...\n $ apgar1      : num [1:1368] NA NA NA NA NA NA NA NA NA NA ...\n $ apgar5      : num [1:1368] NA NA NA NA NA NA NA NA NA NA ...\n $ uti_neo     : num [1:1368] 1 2 1 1 1 1 2 2 1 1 ...\n $ inf_cong    : num [1:1368] 2 2 2 2 1 2 2 2 2 2 ...\n```\n\n\n:::\n:::\n\n\nA função `select ()` pode ser combinada com outras funções, como `filter ()`.\n\n### Modificando e criando novas colunas {#sec-newcol}\n\nPara esta ação, usa-se a função `mutate()`. Por exemplo, todas as variáveis no *tibble* `mater` foram lidas como numéricas. Entretanto, as variáveis `cor`, `estado_civil`, `fumo`, `prenatal`, `droga`, `tipo_parto`, `sexo`, `uti-neo` e `inf_cong` são categóricas e devem ser convertidas para fator, usando a função `factor()` [^05-manipulacao_dados-9] associada a `mutate()`:\n\n[^05-manipulacao_dados-9]: Veja também @sec-fatores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- dplyr::mutate(mater,\n                       cor = factor(cor, \n                                    levels = c(1,2), \n                                    labels = c(\"branca\", \"não branca\")), \n                       estado_civil = factor(estado_civil, \n                                             levels = c(1,2), \n                                             labels = c(\"solteira\", \"casada\")),\n                       fumo = factor(fumo, \n                                     levels = c(1,2), \n                                     labels = c(\"sim\", \"não\")), \n                       prenatal = factor(prenatal, \n                                         levels = c(1,2), \n                                         labels = c(\"sim\", \"não\")), \n                       droga = factor(droga, \n                                      levels = c(1,2), \n                                      labels = c(\"sim\", \"não\")), \n                       tipo_parto = factor(tipo_parto, \n                                           levels = c(1,2), \n                                           labels = c(\"normal\", \"cesareo\")), \n                       sexo = factor(sexo, \n                                     levels = c(1,2), \n                                     labels = c(\"masc\", \"fem\")), \n                       uti_neo = factor(uti_neo, \n                                        levels = c(1,2), \n                                        labels = c(\"sim\", \"não\")),\n                       inf_cong = factor(inf_cong, \n                                         levels = c(1,2), \n                                         labels = c(\"sim\", \"não\")))\n```\n:::\n\n\nO conjunto de dados está, agora, estruturado de forma correta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(mater)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [1,368 × 25] (S3: tbl_df/tbl/data.frame)\n $ id          : num [1:1368] 1 2 3 4 5 6 7 8 9 10 ...\n $ idade_mae   : num [1:1368] 42 29 19 31 34 29 30 34 17 32 ...\n $ altura      : num [1:1368] 1.65 1.66 1.72 1.55 1.6 1.5 1.54 1.63 1.68 1.5 ...\n $ peso        : num [1:1368] 69.9 78 81 74 60 60 75.5 61 57 70 ...\n $ ganho_peso  : num [1:1368] 3.9 16.5 5 43 15 11.4 10.5 9 15 11.4 ...\n $ anos_est    : num [1:1368] 3 11 9 5 7 8 4 6 10 1 ...\n $ cor         : Factor w/ 2 levels \"branca\",\"não branca\": 2 1 2 2 2 2 1 1 1 2 ...\n $ estado_civil: Factor w/ 2 levels \"solteira\",\"casada\": 1 2 1 2 2 2 2 2 2 2 ...\n $ renda       : num [1:1368] 1.45 2.41 1.93 1.45 0.48 0.96 1.2 2.41 2.17 0.72 ...\n $ fumo        : Factor w/ 2 levels \"sim\",\"não\": 2 2 2 2 2 1 1 2 2 2 ...\n $ quant_fumo  : num [1:1368] 0 0 0 0 0 10 20 0 0 0 ...\n $ prenatal    : Factor w/ 2 levels \"sim\",\"não\": 2 1 2 2 2 1 1 2 2 1 ...\n $ para        : num [1:1368] 5 0 0 1 2 1 2 1 0 4 ...\n $ droga       : Factor w/ 2 levels \"sim\",\"não\": 2 2 2 2 2 2 2 2 2 2 ...\n $ ig          : num [1:1368] 29 33 33 33 33 33 33 33 34 34 ...\n $ tipo_parto  : Factor w/ 2 levels \"normal\",\"cesareo\": 2 2 1 1 2 1 2 1 1 2 ...\n $ peso_pla    : num [1:1368] 224 1118 452 432 574 ...\n $ sexo        : Factor w/ 2 levels \"masc\",\"fem\": 2 2 2 2 2 2 2 2 2 2 ...\n $ peso_rn     : num [1:1368] 1035 2300 1580 1840 2475 ...\n $ comp_rn     : num [1:1368] 35.5 45 39 41 47 41 44 44 47 48 ...\n $ pc_rn       : num [1:1368] 28 32 28 32 32 29 32 32 30 27 ...\n $ apgar1      : num [1:1368] NA NA NA NA NA NA NA NA NA NA ...\n $ apgar5      : num [1:1368] NA NA NA NA NA NA NA NA NA NA ...\n $ uti_neo     : Factor w/ 2 levels \"sim\",\"não\": 1 2 1 1 1 1 2 2 1 1 ...\n $ inf_cong    : Factor w/ 2 levels \"sim\",\"não\": 2 2 2 2 1 2 2 2 2 2 ...\n```\n\n\n:::\n:::\n\n\nO Índice de Massa Corporal (IMC) é um cálculo que relaciona o peso e a altura de uma pessoa para avaliar se ela está com o peso ideal, abaixo do peso, acima do peso ou obesa. É uma ferramenta simples e amplamente utilizada na área da saúde para triagem e acompanhamento do estado nutricional. Para obter esse índice, serão utilizadas as variáveis peso e altura da gestante no início da gravidez. Como visto na @sec-funcoes, o cálculo do IMC é dado pela razão entre o peso em kg e a altura em metros elevada ao quadrado. Para criar uma nova coluna com a variável `imc`, pode-se também usar o `mutate()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- dplyr::mutate(mater,\n                       imc = peso/altura^2)\n\nmedia_imc <- mean(mater$imc, na.rm =TRUE)\nround(media_imc,1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24.6\n```\n\n\n:::\n:::\n\n\n### Filtrando linhas\n\nA função `filter()` é usada para criar um subconjunto de dados que obedeçam determinadas condições lógicas: & (e), \\| (ou) e ! (não). Por exemplo:\n\n- **y & !x** $\\to$ seleciona *y* e não *x*\n- **x & !y** $\\to$ seleciona *x* e não *y*\n- **x \\| y** $\\to$ seleciona *x* ou *y*\n- **x & y** $\\to$ seleciona *x* e *y*\n\nUm recém-nascido é dito a termo quando a duração da gestação está entre 37 e 42 semanas incompletas. Para extrair do banco de dados `mater` os recém-nascidos a termo (`dados_termo`), pode-se usar a função `filter()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_termo <- dplyr::filter (mater, ig>=37 & ig<42)\n```\n:::\n\n\nObserve que, agora, o conjunto de dados `dados_termo` tem 1084 linhas, número de recém-nascidos a termo do banco de dados original `mater` (1368). Logo, os recém nascidos a termo correspondem a 79.2% dos nascimentos, nesta maternidade.\n\n**Outro exemplo**\n\nPara selecionar apenas os meninos, nascidos a termo (`dados_termo`), codificados como `\"masc\"`, procede-se da seguinte maneira:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_masc <- dplyr::filter (dados_termo, sexo == 'masc')\n```\n:::\n\n\n::: callout-tip\n## Alerta\n\nNão esquecer que o sinal de igualdade, no R, é representado por um == (duplo igual)\n:::\n\n### Sumarizando uma coluna\n\nPara resumir uma coluna, por exemplo, `dados_termo$peso_rn`, utilizando uma métrica de interesse, como média, mediana, desvio padrão, etc. (@sec-resumo), pode-se usar a função `summarise()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dplyr::summarise(dados_termo,\n  n = length (id),\n  media = mean(peso_rn, na.rm = TRUE),\n  desvpad = sd(peso_rn, na.rm = TRUE))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n media desvpad\n  <int> <dbl>   <dbl>\n1  1084 3218.    459.\n```\n\n\n:::\n:::\n\n\nMuitas vezes, há necessidade de sumarizar uma coluna agrupada pelas categorias de uma segunda coluna. Por exemplo, peso dos recém-nascidos a termo por sexo. Para isso, além do `summarise()`, utilizamos também a função `group_by()`.\\\nPara facilitar o trabalho, será usado o operador pipe que pode ser acionado digitando `|>` ou usando o atalho `ctrl + shift + M`, como observado na @sec-printidyverse. Em vez de passar o argumento para a função separadamente, é possível escrever o valor ou objeto e, em seguida, usar o `pipe` para convertê-lo como o argumento da função na mesma linha. Funciona como se o `pipe` jogasse o objeto dentro da função seguinte.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresumo <- dados_termo |> \n  dplyr::group_by(sexo) |> \n  dplyr::summarise(\n    n = length (id),\n    media = mean(peso_rn, na.rm = TRUE),\n    desvpad = sd(peso_rn, na.rm = TRUE))\nresumo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  sexo      n media desvpad\n  <fct> <int> <dbl>   <dbl>\n1 masc    591 3277.    452.\n2 fem     493 3147.    458.\n```\n\n\n:::\n:::\n\n\n### Selecionando linhas específicas\n\nA função `slice()` do pacote `dplyr` é usada para selecionar linhas específicas de um dataframe (ou *tibble*) com base em suas posições. Ela é bastante útil quando se quer extrair subconjuntos de dados sem usar condições lógicas, mas sim índices de linha.\n\nDiferente de `filter()`, que seleciona linhas baseado em condições, `slice()` usa números de linhas. Por exemplo, para visualizar as cinco primeiras linhas do conjunto de dados `dados_termo`, usa-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice(dados_termo, 1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 26\n     id idade_mae altura  peso ganho_peso anos_est cor        estado_civil renda\n  <dbl>     <dbl>  <dbl> <dbl>      <dbl>    <dbl> <fct>      <fct>        <dbl>\n1    20        28   1.5   48.5       11          6 não branca casada        3.13\n2    21        31   1.55  65         24          5 branca     casada        0.72\n3    22        27   1.6   60         15          8 não branca casada        2.41\n4    23        28   1.58  47          9          8 branca     casada        1.69\n5    24        18   1.76  65.5        6.5        7 branca     solteira      1.93\n# ℹ 17 more variables: fumo <fct>, quant_fumo <dbl>, prenatal <fct>,\n#   para <dbl>, droga <fct>, ig <dbl>, tipo_parto <fct>, peso_pla <dbl>,\n#   sexo <fct>, peso_rn <dbl>, comp_rn <dbl>, pc_rn <dbl>, apgar1 <dbl>,\n#   apgar5 <dbl>, uti_neo <fct>, inf_cong <fct>, imc <dbl>\n```\n\n\n:::\n:::\n\n\nA função `slice()` é compatível com agrupamentos, por exemplo, para selecionar os cinco primeiros casos do tibble `dados_termo` por `sexo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_termo |>\n        group_by(sexo) |> \n        slice(1:5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 26\n# Groups:   sexo [2]\n      id idade_mae altura  peso ganho_peso anos_est cor       estado_civil renda\n   <dbl>     <dbl>  <dbl> <dbl>      <dbl>    <dbl> <fct>     <fct>        <dbl>\n 1    20        28   1.5   48.5       11          6 não bran… casada        3.13\n 2    21        31   1.55  65         24          5 branca    casada        0.72\n 3    22        27   1.6   60         15          8 não bran… casada        2.41\n 4    23        28   1.58  47          9          8 branca    casada        1.69\n 5    24        18   1.76  65.5        6.5        7 branca    solteira      1.93\n 6   751        17   1.65  60         11.4        7 não bran… solteira      1.92\n 7   752        30   1.6   54         12          5 branca    casada        1.92\n 8   753        27   1.53  43.5       20.5       11 branca    casada        1.93\n 9   755        28   1.4   60         11.4        8 não bran… casada        2.17\n10   756        17   1.55  78         20         10 branca    solteira      4.82\n# ℹ 17 more variables: fumo <fct>, quant_fumo <dbl>, prenatal <fct>,\n#   para <dbl>, droga <fct>, ig <dbl>, tipo_parto <fct>, peso_pla <dbl>,\n#   sexo <fct>, peso_rn <dbl>, comp_rn <dbl>, pc_rn <dbl>, apgar1 <dbl>,\n#   apgar5 <dbl>, uti_neo <fct>, inf_cong <fct>, imc <dbl>\n```\n\n\n:::\n:::\n\n\nO `tidyverse` introduziu funções auxiliares como:\n\n- `slice_head()`: que seleciona as primeiras `n` linhas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice_head(dados_termo, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 26\n     id idade_mae altura  peso ganho_peso anos_est cor        estado_civil renda\n  <dbl>     <dbl>  <dbl> <dbl>      <dbl>    <dbl> <fct>      <fct>        <dbl>\n1    20        28   1.5   48.5         11        6 não branca casada        3.13\n2    21        31   1.55  65           24        5 branca     casada        0.72\n3    22        27   1.6   60           15        8 não branca casada        2.41\n# ℹ 17 more variables: fumo <fct>, quant_fumo <dbl>, prenatal <fct>,\n#   para <dbl>, droga <fct>, ig <dbl>, tipo_parto <fct>, peso_pla <dbl>,\n#   sexo <fct>, peso_rn <dbl>, comp_rn <dbl>, pc_rn <dbl>, apgar1 <dbl>,\n#   apgar5 <dbl>, uti_neo <fct>, inf_cong <fct>, imc <dbl>\n```\n\n\n:::\n:::\n\n\n- `slice_tail()`: que seleciona as últimas `n` linhas.\\\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice_tail(dados_termo, n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 26\n     id idade_mae altura  peso ganho_peso anos_est cor    estado_civil renda\n  <dbl>     <dbl>  <dbl> <dbl>      <dbl>    <dbl> <fct>  <fct>        <dbl>\n1  1359        24   1.52  58.6       14.9        5 branca casada        1.45\n2  1360        24   1.6   60         15          6 branca casada        3.86\n3  1361        22   1.57  75          2         11 branca casada        7.23\n# ℹ 17 more variables: fumo <fct>, quant_fumo <dbl>, prenatal <fct>,\n#   para <dbl>, droga <fct>, ig <dbl>, tipo_parto <fct>, peso_pla <dbl>,\n#   sexo <fct>, peso_rn <dbl>, comp_rn <dbl>, pc_rn <dbl>, apgar1 <dbl>,\n#   apgar5 <dbl>, uti_neo <fct>, inf_cong <fct>, imc <dbl>\n```\n\n\n:::\n:::\n\n\n- `slice_sample()`: seleciona linhas aleatórias. Uma amostra de n = 200 será extraída do `tibble` `dados_termo`, como exemplo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_termo200 <- dados_termo |> slice_sample(n = 200)\n```\n:::\n\n\n- `slice_min()`: seleciona as linhas com os menores valores em uma coluna específica. Não ordena todo o dataframe, mas sim identifica e extrai as linhas que têm os menores valores na coluna indicada com `order_by`. Por exemplo, se o objetivo é extrarir do tibble dados_termo so cinco menores pesos ao nascer de cada sexo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados_termo |> \n  select(peso_rn, sexo) |> \n  slice_min(order_by = peso_rn, \n            n = 5, \n            with_ties = TRUE, \n            by = sexo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 2\n   peso_rn sexo \n     <dbl> <fct>\n 1    1425 masc \n 2    1795 masc \n 3    1810 masc \n 4    1980 masc \n 5    2051 masc \n 6    1715 fem  \n 7    1785 fem  \n 8    1895 fem  \n 9    2090 fem  \n10    2095 fem  \n```\n\n\n:::\n:::\n\n\n- `slice_max()`: funciona da mesma maneira que o `slice_min()`, apenas para os maiores valores.\n\n::: callout-tip\n## Exercício\n\nVerificar a média e o desvio padrão dos pesos dos recém-nascidos a termo de mães fumantes e não fumantes, por sexo.\n\n[Resposta]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Partindo do conjunto de dados `dados_termo` (recém-nascidos a termo), tem-se:\n\nresumo <- readxl::read_excel(\"dados/dadosMater.xlsx\") |>  \n  dplyr::filter(ig >= 37 & ig < 42) |> \n  dplyr::select(fumo, sexo, peso_rn) |> \n  dplyr::mutate(fumo = factor(fumo, \n                              levels = c(1,2), \n                              labels = c(\"sim\", \"não\")), \n                sexo = factor(sexo, \n                             levels = c(1,2),labels = c(\"masculino\", \"feminino\"))) |> \n  dplyr::group_by(sexo, fumo) |> \n  dplyr::summarise(\n                   media = mean(peso_rn, na.rm = TRUE),\n                   desv_pad = sd(peso_rn, na.rm = TRUE),\n                   .groups = \"drop_last\")\n                \nprint(resumo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n# Groups:   sexo [2]\n  sexo      fumo  media desv_pad\n  <fct>     <fct> <dbl>    <dbl>\n1 masculino sim   3177.     438.\n2 masculino não   3303.     453.\n3 feminino  sim   2998.     503.\n4 feminino  não   3190.     435.\n```\n\n\n:::\n:::\n\n:::\n\n### Ordenando uma coluna\n\nPara ordenar os dados de uma coluna, pode-se usar a função `arrange()` do `dplyr`. O primeiro argumento é o conjunto de base. Os demais argumentos são as colunas a serem ordenadas.\\\nPor padrão, a função coloca os dados em ordem crescente, mas é possível alterar e organizar em ordem decrescente usando a função `desc()`, que recebe o nome da coluna como argumento e ordena os valores em ordem decrescente.\n\nPor exemplo, a renda familiar das parturientes será ordenada de forma ascendente. Em primeiro lugar, apenas como exercício, a renda familiar em salários mínimos será convertida em reais, tomando como base o valor de 2026 de 1621 reais. Após, a variável `renda` será colocada em ordem crescente com a função `arrange()`. A seguir, usando as funções `slice_head()` e `slice_tail()`, se verificará as 5 menores e as 5 maiores rendas que serão atribuídos a dois objetos (`menores` e `maiores`). Estes vão ser exibidos juntos, usando a função `bind_rows()`, também do `dplyr`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cinco menores salários em ordem crescente\nmenores <- mater |> select(renda) |> \n    mutate(renda = renda *1621.00) |> \n    arrange(renda) |> \n    slice_head(n=5)\nmaiores <- mater |> select(renda) |> \n    mutate(renda = renda *1621.00) |> \n    arrange(renda) |> \n    slice_tail(n=5)\n\n# Exibição\nbind_rows(menores, maiores)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 1\n    renda\n    <dbl>\n 1   308.\n 2   389.\n 3   665.\n 4   697.\n 5   778.\n 6 15626.\n 7 15626.\n 8 15626.\n 9 17328.\n10 17572.\n```\n\n\n:::\n:::\n\n\n### Função `count()`\n\nPermite contar rapidamente os valores únicos de uma ou mais variáveis. Esta função tem os seguintes argumentos.\n\n- **x** $\\to$ dataframe\n- **wt** $\\to$ pode ser NULL (padrão) ou uma variável\n- **sort** $\\to$ padrão = FALSE; se TRUE, mostrará os maiores grupos no topo\n- **name** $\\to$ O nome da nova coluna na saída; padrão = NULL\n\nQuando o argumento `name` é omitido, a função retorna *n* como nome padrão.\n\nUsando o dataframe `mater`, a função `count()` irá contar o número de parturientes fumantes, variável dicotômica `fumo`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(mater, fumo)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  fumo      n\n  <fct> <int>\n1 sim     301\n2 não    1067\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n## Exercício\n\nCalcule o percentual de partos cesáreos no *tibble* `mater`.\n\n[Resposta]{.underline}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmater <- readxl::read_excel(\"dados/dadosMater.xlsx\") |> \n  dplyr::select(tipo_parto) |> \n  dplyr::mutate(tipo_parto = factor(tipo_parto, \n                              levels = c(1,2), \n                              labels = c(\"normal\", \"cesareo\")))\n\ntab <- with(data = mater, table(tipo_parto))\naddmargins(tab)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntipo_parto\n normal cesareo     Sum \n    813     555    1368 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(prop.table(tab), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntipo_parto\n normal cesareo \n  0.594   0.406 \n```\n\n\n:::\n:::\n\n:::\n\n## Pacote forcats\n\nO pacote `forcats` é uma das maravilhas do `tidyverse` voltada exclusivamente para o tratamento de variáveis categóricas no R — ou seja, os fatores. O nome vem de “*for categorical variables*”, e ele foi criado para resolver os desafios que surgem ao lidar com fatores, especialmente em visualizações e modelagens [@damiani2022forcats].\n\nO pacote oferece funções intuitivas e poderosas para:\n\n- Reordenar os níveis de um fator;\n- Modificar, combinar e recodificar níveis;\n- Lidar com níveis raros ou ausentes;\n- Preparar fatores para gráficos com `ggplot2` (@sec-ggplot2).\n\nAs principais funções do `forcats` são:\n\n- `fct_reorder()` — Reordena os níveis com base em outra variável (ex: média);\n- `fct_infreq()` — Reordena os níveis pela frequência (mais comum primeiro);\n- `fct_rev()` — Inverte a ordem dos níveis;\n- `fct_lump()` — Agrupa níveis menos frequentes em \"outros\";\n- `fct_recode()` — Renomeia níveis manualmente;\n- `fct_drop()` — Remove níveis não utilizados;\n- `fct_expand()` — Adiciona novos níveis.\n\nComo exemplo, será modificada a ordem de como a variável `tipo_parto` será apresentada. Para ver a ordem dos níveis, pode-se usar:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(mater$tipo_parto)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"normal\"  \"cesareo\"\n```\n\n\n:::\n:::\n\n\nOu seja, o parto normal está colocado antes do cesáreo Como é uma variável dicotômica, basta inverter a ordem, usando a função `fct_rev()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forcats)\n\nmater$tipo_parto <- fct_rev(mater$tipo_parto)\n\nlevels(mater$tipo_parto)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"cesareo\" \"normal\" \n```\n\n\n:::\n:::\n\n\n## Manipulação de datas\n\nOriginalmente, todos os que trabalham com o R queixavam-se de como era frustrante trabalhar com datas. Era um processo que causava grande perda de tempo nas análises. O pacote `lubridate` [@grolemund2011dates] foi criado para simplificar ao máximo a leitura de datas e extração de informações das mesmas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lubridate)\n```\n:::\n\n\nQuando o `lubridate` é carregado aparece uma mensagem, avisando que alguns nomes de funções também estão contidas no pacote base do R.\\\nPara evitar confusões e verificar que as funções corretas estão sendo usadas, usa-se o duplo dois pontos (`::`) antes do nome da função, precedido do nome do pacote, por exemplo: `lubridate::date()`.\n\nPara obter a data atual ou a data-hora, você pode usar as funções `today()` ou `now()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoday()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2026-08-11\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnow()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2026-08-11 18:47:24 -03\"\n```\n\n\n:::\n:::\n\n\n### Convertendo *strings* ou caractere para data\n\nPara converter *string* ou caracteres em datas, basta executar funções específicas adequadas aos dados. Elas determinam automaticamente o formato quando você especifica a ordem do componente. Para usá-los, identifique a ordem em que o ano, o mês e o dia aparecem em suas datas e, em seguida, organize \"y\", \"m\" e \"d\" na mesma ordem. Isso lhe dá o nome da função do `lubridate` que analisará a data. Por exemplo, suponhamos a data de 25/12/2022:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnatal <- \"25/12/2022\"\nnatal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"25/12/2022\"\n```\n\n\n:::\n:::\n\n\nAparentemente, o *R* aceitou a informação como uma data. Entretanto, se for verificada a classe do objeto, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(natal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\nEstando como caractere, esta data não poderá ser usada em operações com datas, pois necessitaria estar como uma classe `date`. Para converte-la, usa-se a função `dmy()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnatal <- dmy(natal)\nnatal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2022-12-25\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(natal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\nDessa forma, a data, agora está sendo reconhecida pelo *R* como `date`. É sempre importante verificar a classe da data.\n\nÀs vezes, as datas escritas estão com o mês abreviado, como 25/dez/2022. O procedimento é o mesmo\n\n\n::: {.cell}\n\n```{.r .cell-code}\nminha.data <- \"25/dez/2022\"\nminha.data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"25/dez/2022\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass (minha.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"character\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nminha.data <- dmy(minha.data)\nminha.data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2022-12-25\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass (minha.data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Date\"\n```\n\n\n:::\n:::\n\n\nSe além da data, houver necessidade de especificar o horário, basta usar `dmy_h()`, `dmy_hm()` e `dmy_hms()`. No padrão americano, pode ser usado `ymd()`.\n\nO `lubridate` traz diversas funções para extrair os componentes de um objeto da classe date.\n\n- `second()` $\\to$ extrai os segundos.\n- `minute()` $\\to$ extrai os minutos.\n- `hour()` $\\to$ extrai a hora.\n- `wday()` $\\to$ extrai o dia da semana.\n- `mday()` $\\to$ extrai o dia do mês.\n- `month()` $\\to$ extrai o mês.\n- `year()` $\\to$ extrai o ano.\n\nPor exemplo, usando a data de nascimento (`dn`) de um dos netos do autor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndn <- dmy(\"06/06/2018\")\nyear(dn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2018\n```\n\n\n:::\n:::\n\n\nPara acrescentar um horário ao objeto data de nascimento (`dn`)[^05-manipulacao_dados-10]:\n\n[^05-manipulacao_dados-10]: UTC = Coordinated Universal Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhour(dn) <- 18\ndn\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2018-06-06 18:00:00 UTC\"\n```\n\n\n:::\n:::\n\n\n### Juntando componentes de datas\n\nPara juntar componentes de datas e horas, pode-se utilizar as funções `make_date()` e `make_datetime()`. Em muitos arquivos, os componentes da data estão em colunas diferentes e há necessidade de juntá-los em uma única coluna para compor a data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfelix <- make_date(year = 2018, month = 06, day = 06)\nfelix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2018-06-06\"\n```\n\n\n:::\n:::\n\n\nPara juntar ano, mês, dia, hora e minuto:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nminha.data <- make_datetime(year = 2018, \n                            month = 06, \n                            day = 06, \n                            hour = 18,\n                            min = 00, \n                            sec = 15)\nminha.data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2018-06-06 18:00:15 UTC\"\n```\n\n\n:::\n:::\n\n\n### Extraindo componentes de datas\n\nQuando temos objetos do tipo POSIXt[^05-manipulacao_dados-11] podemos extrair componentes ou elementos deles. Para isso são usadas algumas funções específicas do pacote `lubridate` como mostrado a seguir.\n\n[^05-manipulacao_dados-11]: POSIXt é uma classe de objetos do R que representa datas e horas. POSIXt significa Portable Operating System Interface for Unix Time, que é um padrão para medir o tempo em segundos desde 1 de janeiro de 1970. Existem duas formas internas de implementar POSIXt: POSIXct e POSIXlt. POSIXct armazena os segundos desde a época UNIX e POSIXlt armazena uma lista de dia, mês, ano, hora, minuto, segundo, etc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- now()\n\nyear(data)            # Extrai o ano\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2026\n```\n\n\n:::\n\n```{.r .cell-code}\nmonth(data)           # Extrai o mês\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code}\nweek(data)            # Extrai a semana\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 32\n```\n\n\n:::\n\n```{.r .cell-code}\nday(data)             # Extrai o dia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11\n```\n\n\n:::\n\n```{.r .cell-code}\nminute(data)          # Extrai o minuto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 47\n```\n\n\n:::\n\n```{.r .cell-code}\nsecond(data)          # Extrai o segundo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.03393\n```\n\n\n:::\n:::\n\n\nPara verificar o número de dias tem em um determinado mês, usa-se a função `days_in_month()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n data1 <- dmy(\"25/02/2000\")\n days_in_month(data1)          \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFeb \n 29 \n```\n\n\n:::\n:::\n\n\n### Operações com datas\n\nO pacote `lubridate` possui funções de duração e de período para manipular as datas. As funções de duração calculam o número de segundos correspondentes a um determinado intervalo de tempo (por exemplo, dias, horas ou minutos). As funções de duração não levam em consideração anos bissextos e horário de verão, enquanto as funções de período consideram esses fatores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nddays (1)           # Número de segundos em 1 dia\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"86400s (~1 days)\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndhours (1)          # Número de segundos em 1 hora\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"3600s (~1 hours)\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndminutes (1)        # Número de segundos em 1 minuto\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"60s (~1 minutes)\"\n```\n\n\n:::\n\n```{.r .cell-code}\ndays (5)            # Cria um período de 5 dias\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"5d 0H 0M 0S\"\n```\n\n\n:::\n\n```{.r .cell-code}\nweeks (5)           # Cria um período de 5 semanas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"35d 0H 0M 0S\"\n```\n\n\n:::\n:::\n\n\nSuponha-se que haja necessidade de saber em qual dia cairá após acrescentarmos 5 semanas à `data1` (25/02/2000), criada acima:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata1 + weeks (5)           \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2000-03-31\"\n```\n\n\n:::\n:::\n\n\nAdicionando 1 ano à `data1` (25/02/2000) com uma função de duração, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata1 + dyears (1)           \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2001-02-24 06:00:00 UTC\"\n```\n\n\n:::\n:::\n\n\nSe for adicionado um ano à mesma data, mas agora com uma função de período, tem-se:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata1 + years (1)           \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2001-02-25\"\n```\n\n\n:::\n:::\n\n\n#### Intervalo de tempo entre datas\n\nUm intervalo de tempo pode ser obtido a partir de uma **data inicial** e uma **data final**. Suponha que uma gestante tenha como data da sua última menstruação 04/10/2022 e o bebê tenha nascido em 30/06/2023. Qual a idade gestacional em dias? A sintaxe para calcular um intervalo é dada pela subtração das duas datas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.inicial <- dmy(\"04/10/2022\")\ndata.final <- dmy(\"30/06/2023\")\nidade_gesta <- data.final - data.inicial\nidade_gesta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime difference of 269 days\n```\n\n\n:::\n:::\n\n\nOu seja a gestação durou 269 dias, constituindo-se em um parto a termo, entre 37 (259 dias) e 42 semanas (294 dias).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}