<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Medidas Resumidoras – Bioestatística Usando o R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-tabelas.html" rel="next">
<link href="./05-manipulacao_dados.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-364982630eef5352dd1537128a8ed5cb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">

<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar floating slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-medidasResumidoras.html">Parte III - Estatística Descritiva</a></li><li class="breadcrumb-item"><a href="./06-medidasResumidoras.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Medidas Resumidoras</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bioestatística Usando o R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte I: Fundamentos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Natureza dos Dados</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-producaoDados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Produção dos Dados</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte II - Ambiente Computacional com R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-introducaoR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introdução ao uso do R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-manipulacao_dados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulação dos dados no R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte III - Estatística Descritiva</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-medidasResumidoras.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Medidas Resumidoras</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-tabelas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tabelas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-graficos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gráficos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Módulo IV: Probabilidades e Distribuições</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-probabilidades.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introdução à Teoria das Probabilidades</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-assimetria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Assimetria e Curtose</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-distAmostrais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Módulo V: Inferência Estatística</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-estimacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Estimação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-valor_p.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Valor <em>p</em></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VI - Testes Paramétricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-teste-t.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Comparação entre duas médias</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Análise de Variância</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-anovaRep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Anova de Medidas Repetidas</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VII - Relações entre Variáveis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-correlacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Correlação</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-regressao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Regressão Linear Simples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte VIII - Métodos Não Paramétricos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-dadoscategoricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Análise de Dados Categóricos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-testes-naoParametricos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Métodos não paramétricos</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Parte IX - Bioestatística Aplicada à Epidemiologia</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-testesDiag.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Avaliação de testes diagnósticos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-medidasOcorrencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Medidas de ocorrência de doença</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-sobrevida.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Análise de Sobrevida</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#sec-dadosbrutos" id="toc-sec-dadosbrutos" class="nav-link active" data-scroll-target="#sec-dadosbrutos"><span class="header-section-number">6.1</span> Dados brutos</a></li>
  <li><a href="#introdução" id="toc-introdução" class="nav-link" data-scroll-target="#introdução"><span class="header-section-number">6.2</span> Introdução</a></li>
  <li><a href="#sec-dados-cap6" id="toc-sec-dados-cap6" class="nav-link" data-scroll-target="#sec-dados-cap6"><span class="header-section-number">6.3</span> Dados usados neste capítulo</a></li>
  <li><a href="#medidas-de-tendência-central" id="toc-medidas-de-tendência-central" class="nav-link" data-scroll-target="#medidas-de-tendência-central"><span class="header-section-number">6.4</span> Medidas de tendência central</a>
  <ul class="collapse">
  <li><a href="#média" id="toc-média" class="nav-link" data-scroll-target="#média"><span class="header-section-number">6.4.1</span> Média</a></li>
  <li><a href="#sec-mediana" id="toc-sec-mediana" class="nav-link" data-scroll-target="#sec-mediana"><span class="header-section-number">6.4.2</span> Mediana</a></li>
  <li><a href="#moda" id="toc-moda" class="nav-link" data-scroll-target="#moda"><span class="header-section-number">6.4.3</span> Moda</a></li>
  <li><a href="#sec-quantil" id="toc-sec-quantil" class="nav-link" data-scroll-target="#sec-quantil"><span class="header-section-number">6.4.4</span> Quantil</a></li>
  <li><a href="#média-aparada" id="toc-média-aparada" class="nav-link" data-scroll-target="#média-aparada"><span class="header-section-number">6.4.5</span> Média aparada</a></li>
  </ul></li>
  <li><a href="#medidas-de-dispersão" id="toc-medidas-de-dispersão" class="nav-link" data-scroll-target="#medidas-de-dispersão"><span class="header-section-number">6.5</span> Medidas de Dispersão</a>
  <ul class="collapse">
  <li><a href="#amplitude" id="toc-amplitude" class="nav-link" data-scroll-target="#amplitude"><span class="header-section-number">6.5.1</span> Amplitude</a></li>
  <li><a href="#intervalo-interquartil" id="toc-intervalo-interquartil" class="nav-link" data-scroll-target="#intervalo-interquartil"><span class="header-section-number">6.5.2</span> Intervalo Interquartil</a></li>
  <li><a href="#sec-variancia" id="toc-sec-variancia" class="nav-link" data-scroll-target="#sec-variancia"><span class="header-section-number">6.5.3</span> Variância e Desvio Padrão</a></li>
  <li><a href="#coeficiente-de-variação" id="toc-coeficiente-de-variação" class="nav-link" data-scroll-target="#coeficiente-de-variação"><span class="header-section-number">6.5.4</span> Coeficiente de Variação</a></li>
  <li><a href="#escolha-da-medida-resumidora" id="toc-escolha-da-medida-resumidora" class="nav-link" data-scroll-target="#escolha-da-medida-resumidora"><span class="header-section-number">6.5.5</span> Escolha da medida resumidora</a></li>
  </ul></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Referências</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-medidasResumidoras.html">Parte III - Estatística Descritiva</a></li><li class="breadcrumb-item"><a href="./06-medidasResumidoras.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Medidas Resumidoras</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-resumo" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Medidas Resumidoras</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-dadosbrutos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="sec-dadosbrutos"><span class="header-section-number">6.1</span> Dados brutos</h2>
<p>Habitualmente, costuma-se armazenar os dados em bancos de dados (<em>dataframes</em> ou <em>tibbles</em>). Entretanto, eles estão registrados de forma aleatória e não classificada. Ao se visualizar um dataframe, é difícil responder perguntas em relação a qualquer variável, principalmente, em grandes bancos de dados. Eles se constituem uma lista, um rol de valores colocados na ordem em que foram obtidos. Parecem um jogo de quebra cabeça antes de ser organizado! A <a href="#tbl-raw" class="quarto-xref">Tabela&nbsp;<span>6.1</span></a> é o tipo mais simples de tabela possível. Nela é apresentado um conjunto de dados, os valores dos pesos de 30 recém-nascidos. Não há nenhum significado especial para as linhas e colunas, estão dispostos da maneira como coletados. Eles pouco informam; são apenas os dados na sua forma inicial sem nenhum tratamento ou ordem. São denominados como <em>dados brutos</em> e se constituem no ponto de partida para uma análise. Quando colocados em ordem crescente, permitindo uma compreensão inicial, são chamados de dados não agrupados; quando classificados em categorias ou intervalos, são denominados dados agrupados.</p>
<div class="cell" data-tbl-align="center">
<div id="tbl-raw" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6.1: Peso de 30 recém-nascidos de partos consecutivos
</figcaption>
<div aria-describedby="tbl-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-f0532a44{}.cl-f0445794{font-family:'Arial';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-f048421e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-f0486d84{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-f0486d8e{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-f0532a44"><thead><tr style="overflow-wrap:break-word;"><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th><th class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794"> </span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,940</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,575</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,150</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,545</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,365</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,825</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,060</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,580</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,110</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,415</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">4,670</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,670</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">1,930</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,000</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,115</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,850</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,490</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">1,465</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">2,790</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">4,445</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,290</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,215</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,245</span></p></td><td class="cl-f0486d8e"><p class="cl-f048421e"><span class="cl-f0445794">3,420</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">1,750</span></p></td><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">2,925</span></p></td><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">3,345</span></p></td><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">1,105</span></p></td><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">3,445</span></p></td><td class="cl-f0486d84"><p class="cl-f048421e"><span class="cl-f0445794">3,150</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="introdução" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="introdução"><span class="header-section-number">6.2</span> Introdução</h2>
<p>Nos relatórios ou artigos científicos, a comunicação dos resultados é feita através da combinação de medidas resumidoras e visualização dos dados por meio de tabelas e gráficos, constituindo o que se costuma chamar de <strong>Estatística Descritiva</strong>. Neste capítulo, serão discutidas as principais medidas resumidoras dos dados de duas maneiras:</p>
<ul>
<li>Primeiro, um valor em torno do qual os dados têm uma tendência para se reunir ou se agrupar, denominado de <strong>medida de tendência central</strong>. Relacionadas a elas estão as <strong>medidas de posição</strong> (ou de localização), como os quantis, que situam um valor dentro do conjunto ordenado de dados; apenas uma delas, a mediana, é também uma medida de tendência central.</li>
<li>Em segundo lugar, um valor que mede o grau em que os dados se dispersam, denominado de <strong>medida de dispersão</strong> ou <strong>variabilidade</strong>.</li>
</ul>
<p>Nos próximos capítulos, desta Parte III, estarão em discussão a construção de Tabelas (<a href="07-tabelas.html" class="quarto-xref"><span>Capítulo 7</span></a>) e visualização dos dados através de gráficos (<a href="08-graficos.html" class="quarto-xref"><span>Capítulo 8</span></a>).</p>
</section>
<section id="sec-dados-cap6" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-dados-cap6"><span class="header-section-number">6.3</span> Dados usados neste capítulo</h2>
<p>Para as demonstrações práticas, será usado o banco de dados <code>dadosMater.xlsx</code> (ver <a href="05-manipulacao_dados.html#sec-dadosMater" class="quarto-xref"><span>Seção 5.6</span></a>). Após carregá-lo, serão filtrados os partos a termo e selecionadas as variáveis necessárias (<code>idade_mae</code>, <code>anos_est</code>, <code>peso_rn</code>, <code>apgar1</code>). Por último, será extraída com a função <code>slice_sample()</code> do pacote <code>dplyr</code> (<a href="05-manipulacao_dados.html#sec-dplyr" class="quarto-xref"><span>Seção 5.5</span></a>) uma amostra de n = 200. Cada vez que este comando for reproduzido, retornará uma nova série de 200 valores, diferente da anterior. Para tornar o código reproduzível, retornando o mesmo conjunto de valores, deve-se usar uma “semente” (<code>seed</code>), usando a função <code>set.seed()</code>, cujo argumento é um número que identificará a série gerada. Após extrair a amostra, esta será atribuída a um objeto denominado, <code>dados</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ig <span class="sc">&gt;=</span> <span class="dv">37</span> <span class="sc">&amp;</span> ig <span class="sc">&lt;</span> <span class="dv">42</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(idade_mae, anos_est, peso_rn, apgar1) <span class="sc">|&gt;</span> </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">200</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="medidas-de-tendência-central" class="level2 page-columns page-full" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="medidas-de-tendência-central"><span class="header-section-number">6.4</span> Medidas de tendência central</h2>
<section id="média" class="level3 page-columns page-full" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="média"><span class="header-section-number">6.4.1</span> Média</h3>
<p>A média (<span class="math inline">\(\overline{x}\)</span>) é a mais usada medida de tendência central para representar um valor típico dentro de um conjunto de números. O conceito mais comum é a <strong>média aritmética</strong>, que se calcula somando todos os valores do conjunto e dividindo pelo número total de elementos. A média é mais adequada para medidas numéricas simétricas, pois ela é sensível aos valores extremos (<em>outliers</em>).</p>
<p><span class="math display">\[\overline{x}= \frac{\sum_{i=1}^{n} x_i}{n}\]</span></p>
<p>O R base possui uma função para o cálculo da média, <code>mean()</code>, apresentada na <a href="04-introducaoR.html#sec-funcoes" class="quarto-xref"><span>Seção 4.4</span></a>, onde foi mostrado os seus argumentos. Se a variável analisada contiver algum valor ausente (<em>missing</em>), deve-se usar o argumento <code>na.rm = TRUE</code>, para removê-los, pois, caso contrário, a função retorna um resultado como NA (<em>Not Available</em>). Para evitar transtornos, recomenda-se usar sempre o argumento.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3228.095</code></pre>
</div>
</div>
<p>Para reduzir o número de dígitos decimais, na saída do resultado, pode-se colocar a função <code>mean()</code>, dentro da função <code>round()</code><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, atribuindo o resultado da função a um objeto, por exemplo <code>media</code>.</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;Usa-se esta sintaxe: <code>round(x, digits = 0)</code>, onde <code>x</code> é o numero que se quer arredondar e <code>digits</code> é número de casas decimais. O padrão é <code>0</code>, ou seja, arredonda para o inteiro mais próximo.</p></div></div><div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(media)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3228.1</code></pre>
</div>
</div>
<p>Ou, usar a função <code>round()</code>, separadamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(media, <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3228.1</code></pre>
</div>
</div>
</section>
<section id="sec-mediana" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="sec-mediana"><span class="header-section-number">6.4.2</span> Mediana</h3>
<p>A mediana (Md) representa o valor central em uma série ordenada de valores. Assim, metade dos valores será igual ou menor que o valor mediano e a outra metade igual ou maior do que ele. Para encontrar a mediana procede-se da seguinte maneira:</p>
<ol type="1">
<li>Ordenar o conjunto de dados, por exemplo, a variável <code>dados$peso_rn</code>, usando a função <code>sort()</code>:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>valores_ordenados <span class="ot">&lt;-</span> <span class="fu">sort</span>(dados<span class="sc">$</span>peso_rn)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(valores_ordenados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 2170 2300 2309 2310 2405 2480 2485 2570 2590 2590 2640 2650 2650 2650 2680
 [16] 2680 2705 2710 2720 2725 2730 2750 2770 2770 2775 2775 2775 2780 2780 2795
 [31] 2795 2800 2830 2850 2850 2855 2865 2870 2870 2870 2870 2870 2875 2885 2890
 [46] 2910 2910 2910 2920 2935 2940 2965 2965 2970 2980 2980 2980 2990 2990 2995
 [61] 3005 3010 3015 3030 3030 3030 3040 3040 3055 3060 3075 3080 3085 3090 3100
 [76] 3100 3105 3115 3115 3120 3140 3145 3145 3150 3150 3150 3150 3150 3155 3160
 [91] 3160 3165 3170 3170 3180 3180 3185 3190 3190 3200 3200 3205 3215 3220 3240
[106] 3260 3270 3270 3270 3270 3270 3275 3280 3280 3295 3300 3305 3305 3315 3320
[121] 3320 3330 3335 3335 3355 3360 3375 3380 3380 3385 3385 3385 3390 3390 3390
[136] 3395 3395 3400 3415 3420 3425 3430 3430 3430 3460 3460 3470 3480 3480 3495
[151] 3500 3500 3505 3515 3520 3535 3540 3540 3540 3550 3550 3550 3570 3580 3580
[166] 3580 3590 3625 3630 3635 3640 3645 3650 3660 3665 3675 3695 3715 3715 3715
[181] 3715 3740 3780 3780 3825 3830 3830 3840 3840 3850 3855 3880 3970 4045 4050
[196] 4240 4305 4380 4485 4535</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Quando o número de valores é par, caso do exemplo, a mediana é a média dos dois valores do meio, ou seja, o valor central corresponde a média do valor 100 e do valor 101 dos valores ordenados:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mediana <span class="ot">=</span> (valores_ordenados[<span class="dv">100</span>] <span class="sc">+</span> valores_ordenados[<span class="dv">101</span>])<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mediana)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3200</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Quando o número de valores no conjunto de dados for ímpar, a mediana é o valor do meio.</li>
</ol>
<ul>
<li>No exemplo, tem-se 200 valores. Para transformar a amostra em uma amostra com <em>n</em> ímpar, remover aleatoriamente uma observação dos valores dos <code>dados$peso_rn</code>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>index_aleatorio <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">length</span>(dados<span class="sc">$</span>peso_rn), <span class="dv">1</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>index_aleatorio</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31</code></pre>
</div>
</div>
<ul>
<li>Ou seja, o valor selecionado é o 31º valor. A seguir, obtem-se o peso aleatório que foi selecionado:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>peso_aleatorio <span class="ot">&lt;-</span> dados<span class="sc">$</span>peso_rn[index_aleatorio]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>peso_aleatorio</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2720</code></pre>
</div>
</div>
<ul>
<li>Remover o 31º valor (index_aleatório) da lista de <code>dados$peso_rn</code> que corresponde ao peso selecionado:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pesos_restantes <span class="ot">&lt;-</span> dados<span class="sc">$</span>peso_rn[<span class="sc">-</span>index_aleatorio]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Colocar os pesos_restantes em ordem crescente:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>restantes_ordenados <span class="ot">&lt;-</span> <span class="fu">sort</span>(pesos_restantes)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(restantes_ordenados)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 2170 2300 2309 2310 2405 2480 2485 2570 2590 2590 2640 2650 2650 2650 2680
 [16] 2680 2705 2710 2725 2730 2750 2770 2770 2775 2775 2775 2780 2780 2795 2795
 [31] 2800 2830 2850 2850 2855 2865 2870 2870 2870 2870 2870 2875 2885 2890 2910
 [46] 2910 2910 2920 2935 2940 2965 2965 2970 2980 2980 2980 2990 2990 2995 3005
 [61] 3010 3015 3030 3030 3030 3040 3040 3055 3060 3075 3080 3085 3090 3100 3100
 [76] 3105 3115 3115 3120 3140 3145 3145 3150 3150 3150 3150 3150 3155 3160 3160
 [91] 3165 3170 3170 3180 3180 3185 3190 3190 3200 3200 3205 3215 3220 3240 3260
[106] 3270 3270 3270 3270 3270 3275 3280 3280 3295 3300 3305 3305 3315 3320 3320
[121] 3330 3335 3335 3355 3360 3375 3380 3380 3385 3385 3385 3390 3390 3390 3395
[136] 3395 3400 3415 3420 3425 3430 3430 3430 3460 3460 3470 3480 3480 3495 3500
[151] 3500 3505 3515 3520 3535 3540 3540 3540 3550 3550 3550 3570 3580 3580 3580
[166] 3590 3625 3630 3635 3640 3645 3650 3660 3665 3675 3695 3715 3715 3715 3715
[181] 3740 3780 3780 3825 3830 3830 3840 3840 3850 3855 3880 3970 4045 4050 4240
[196] 4305 4380 4485 4535</code></pre>
</div>
</div>
<ul>
<li>Cálculo da mediana com os valores restantes ordenados. O valor central entre 1 e 199 é o 100º valor:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mediana <span class="ot">&lt;-</span> restantes_ordenados[<span class="dv">100</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mediana</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3200</code></pre>
</div>
</div>
<p>Imaginem que sempre que se for calcular a mediana houvesse necessidade de se proceder como realizado acima. Seria tedioso, quase um caos! Entretanto, usando o R, a situação fica bem mais agradável e intuitiva. O R facilita esse trabalho, fornecendo a função <code>median()</code>.</p>
<p>Como exemplo, será usada a variável <code>apgar1</code> já incluída no dataframe <code>dados</code>. Como o Apgar é um escore <span class="citation" data-cites="american2006apgar">(<a href="#ref-american2006apgar" role="doc-biblioref">1</a>)</span>, a medida resumidora mais adequada, realmente, é a mediana.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span> (dados<span class="sc">$</span>apgar1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercício
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calcular a mediana dos valores <code>dados$peso_rn.</code></p>
<p><u>Resposta</u></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(dados<span class="sc">$</span>peso_rn, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3200</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="moda" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="moda"><span class="header-section-number">6.4.3</span> Moda</h3>
<p>Moda (Mo) é o valor que ocorre com maior frequência em um conjunto de dados. O <em>R</em> não possui uma função nativa e direta para calcular a moda como tem para a média (<code>mean()</code>) e a mediana (<code>median()</code>). Isso acontece porque a moda pode não ser única em um conjunto de dados (podem existir múltiplos valores com a mesma frequência máxima) ou pode nem existir (se todos os valores ocorrerem apenas uma vez). É a medida de tendência central com o menor nível de sofisticação estatística. No entanto, pode-se facilmente criar uma função própria para calcular a moda ou usar pacotes que oferecem essa funcionalidade, como o <code>DescTools</code> que oferece uma função chamada <code>Mode()</code>. Aqui estão algumas maneiras de calcular a moda em R:</p>
<p><strong>Função personalizada</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  freq_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(v)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  max_freq <span class="ot">&lt;-</span> <span class="fu">max</span>(freq_tab)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  moda <span class="ot">&lt;-</span> <span class="fu">names</span>(freq_tab[freq_tab <span class="sc">==</span> max_freq])</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(moda)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esta função <code>moda()</code>é constituída por:</p>
<ul>
<li><strong>table(v)</strong>: Cria uma tabela de frequência dos valores v.</li>
<li><strong>max(freq_tab)</strong>: Encontra a frequência máxima.</li>
<li><strong>freq_tab[freq_tab == max_freq]</strong>: Seleciona as entradas da tabela de frequência que são iguais à frequência máxima.</li>
<li><strong>names(…)</strong>: Obtém os nomes (os valores originais) dessas entradas, que são as modas.</li>
</ul>
<p>Usando a função criada, a moda da variável <code>dados$apgar1</code> é igual a:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moda</span> (dados<span class="sc">$</span>apgar1) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "9"</code></pre>
</div>
</div>
<p>A função <code>moda()</code> pode ser salva em seu diretório de trabalho, na pasta das suas funções próprias. Quando necessário ela pode ser acessada, como foi visto na <a href="04-introducaoR.html#sec-funcpropria" class="quarto-xref"><span>Seção 4.4.1</span></a>.</p>
<p><strong>Função Mode() do pacote DescTools</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="fu">Mode</span>(dados<span class="sc">$</span>apgar1)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(moda)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9
attr(,"freq")
[1] 83</code></pre>
</div>
</div>
</section>
<section id="sec-quantil" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="sec-quantil"><span class="header-section-number">6.4.4</span> Quantil</h3>
<p>Os <strong>quantis</strong> são uma <strong>medida de posição</strong> (ou de localização) bastante utilizada: pontos estabelecidos em intervalos regulares que dividem a amostra em subconjuntos iguais. Diferentemente das medidas de tendência central, os quantis, isoladamente, não indicam um valor típico do conjunto de dados, mas sim a posição relativa de um valor dentro da distribuição ordenada. A mediana (o quantil 50%) é a única exceção: além de ser uma medida de posição, ela também é uma medida de tendência central (ver <a href="#sec-mediana" class="quarto-xref"><span>Seção 6.4.2</span></a>), pois representa o valor central da distribuição.</p>
<p>Se estes subconjuntos são em número de 100, são denominados de <strong>percentis</strong>; se são em número de 10, são os <strong>decis</strong> e em número de 4, são os <strong>quartis</strong>. A função nativa no R para obter o quantil é <code>quantile()</code>.</p>
<p>Para determinar os três quartis do peso dos recém-nascidos (<code>dados$peso_rn</code>), usa-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (dados<span class="sc">$</span>peso_rn, <span class="fu">c</span> (<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    25%     50%     75% 
2938.75 3200.00 3496.25 </code></pre>
</div>
</div>
<p>Observe que o percentil 50º é igual a mediana. O percentil 75º é o ponto do conjunto de dados onde 75% dos recém-nascidos têm um peso inferior a 3496.25g e 25% está acima deste valor.</p>
</section>
<section id="média-aparada" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="média-aparada"><span class="header-section-number">6.4.5</span> Média aparada</h3>
<p>As médias aparadas são estimadores robustos da tendência central. Para calcular uma média aparada, é removida uma quantidade predeterminada de observações em cada lado de uma distribuição e realizada a média das observações restantes. Um exemplo de média aparada é a própria mediana.</p>
<p>A base R tem como calcular a média aparada acrescentando o argumento <code>trim =</code>, proporção a ser aparada. Se for aparado 20%, usa-se <code>trim = 0.2</code>. Isto significa que serão removidos 20% dos dados dos dois extremos. No caso da amostra de 200 recém-nascidos, serão removidos 40 valores mais baixos e 40 valores mais altos, passando a amostra a ter 120 valores, e a média aparada será a média destes 120 valores.</p>
<p>O comando para obter a média aparada é:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">trim =</span> <span class="fl">0.20</span>), <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3216.7</code></pre>
</div>
</div>
</section>
</section>
<section id="medidas-de-dispersão" class="level2 page-columns page-full" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="medidas-de-dispersão"><span class="header-section-number">6.5</span> Medidas de Dispersão</h2>
<section id="amplitude" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="amplitude"><span class="header-section-number">6.5.1</span> Amplitude</h3>
<p>A amplitude de um grupo de medições é definida como a diferença entre a maior observação e a menor.<br>
No conjunto de dados dos pesos dos recém-nascidos, a amplitude pode ser obtida, no <em>R</em>, com a função <code>range()</code>, que retorna o valor mínimo e o máximo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2170 4535</code></pre>
</div>
</div>
</section>
<section id="intervalo-interquartil" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="intervalo-interquartil"><span class="header-section-number">6.5.2</span> Intervalo Interquartil</h3>
<p>O intervalo interquartil (IIQ), também conhecido como amplitude interquartil (AIQ), é uma medida de dispersão robusta análoga a uma <em>amplitude aparada</em>: assim como a média aparada exclui os valores mais extremos antes de calcular a média, o IIQ exclui os 25% de valores mais baixos e os 25% mais altos antes de medir a dispersão dos valores restantes. É simplesmente a diferença entre o terceiro e o primeiro quartil, ou seja, a diferença entre o percentil 75 e o percentil 25. Considere a variável escolaridade (<code>dados$anos_est</code>), anos de estudos completos.</p>
<p>Os percentis 25 e 75 são obtidos, usando a função <code>quantile()</code>, vista acima, ou com a função <code>summary()</code>, que retorna os valores mínimo, primeiro quartil, mediana, média, terceiro quartil e máximo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (dados<span class="sc">$</span>anos_est, <span class="fu">c</span>(<span class="fl">0.25</span>,<span class="fl">0.75</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>25% 75% 
  6  10 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados<span class="sc">$</span>anos_est)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    6.00    8.00    7.61   10.00   17.00 </code></pre>
</div>
</div>
<p>Portanto, o IIQ está entre 6 a 10 anos de estudo ou, 4 anos de estudos completos. Em outras palavras, 50% das mulheres desta amostra têm entre 6 a 10 anos de estudo.</p>
<p>O R possui uma função específica para calcular o intervalo interquartil, denominada <code>IQR()</code> e incluída no <code>R</code> base. Ela possui os seguintes argumentos:</p>
<p><strong>x</strong> <span class="math inline">\(\to\)</span> Representa o vetor numérico;<br>
<strong>na.rm</strong> <span class="math inline">\(\to\)</span> Este assume um valor lógico, TRUE ou FALSE, indicando se os valores ausentes devem ser removidos ou não;<br>
<strong>type</strong> <span class="math inline">\(\to\)</span> Representa um número inteiro selecionando um dos muitos algoritmos de quantil. Este é um parâmetro opcional.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(dados<span class="sc">$</span>anos_est, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
</section>
<section id="sec-variancia" class="level3 page-columns page-full" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="sec-variancia"><span class="header-section-number">6.5.3</span> Variância e Desvio Padrão</h3>
<p>A variância e o desvio padrão fornecem uma indicação de quão aglomerados em torno da média os dados de uma amostra estão. Estes tipos de medidas representam desvios (erros) da média. Quando se verifica o desvio de cada valor (x) em relação à média <span class="math inline">\(\overline{x}\)</span>, os desvios positivos se anulam com os negativos, resultando em uma soma igual a zero.</p>
<p>A consequência deste fato é que não é possível resumir os desvios numa única medida de variabilidade. Para se chegar a uma medida de variabilidade há necessidade de se eliminar os sinais, antes de somar todos os desvios em relação à média.</p>
<p>Uma maneira de se fazer isso é elevar todas as diferenças ao quadrado. Assim, se obtém o desvio em relação à média elevado ao quadrado. A soma destes valores é denominada de <em>Soma dos Quadrados (SQ) dos Desvios</em> ou <em>Soma dos Erros ao Quadrado</em>. Se o interesse é apenas saber o erro ou desvio médio, divide-se por <em>n</em> (tamanho da amostra). No entanto, em geral o interesse se concentra em usar o desvio ou erro na amostra para estimar o erro na população. Dessa maneira, divide-se a Soma dos Quadrados por <span class="math inline">\(n-1\)</span>. Essa medida é conhecida como <strong>variância</strong> (<span class="math inline">\(s^2\)</span>). O divisor, <span class="math inline">\(n – 1\)</span>, é denominado de <em>graus de liberdade</em> (gl) associados à variância.</p>
<p>Os graus de liberdade representam o número de desvios que estão livres para variar. É um conceito de difícil explicação, mas é possível compreendê-lo, usando a seguinte explicação:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Graus de liberdade
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suponha uma maternidade há 50 anos atrás, quando não havia alojamento conjunto. Nessa época era comum os recém-nascidos normais ficarem em um berçário. A cada horário de amamentação eles eram levados para os quartos de suas mães para mamar. Posteriormente, eram trazidos para o berçário e colocados nos berços até a próxima mamada. Suponha que, em um determinado momento, havia 15 bebês e que, no berçário, existiam 15 berços (postos) para colocá-los durante o intervalo das mamadas. Quando o primeiro recém-nascido chega, a enfermeira poderá escolher qualquer um dos berços para o colocar. Depois, quando o próximo recém-nascido chegar, ela terá 14 opções de escolha, pois um dos berços está ocupado. Ainda existe uma boa liberdade de escolha. No entanto, à medida que os recém-nascidos forem sendo trazidos para o berçário, chegará a um ponto em que 14 berços estarão ocupados. Agora, a enfermeira não terá liberdade de escolha, pois só resta um berço. Nesse exemplo existem 14 graus de liberdade (gl)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Para o último recém-nascido não houve liberdade de escolha <span class="citation" data-cites="field2012df">(<a href="#ref-field2012df" role="doc-biblioref">2</a>)</span>. Portanto, os graus de liberdade são iguais ao tamanho da amostra menos um (<span class="math inline">\(n-1\)</span>).</p>
</div>
</div>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;No texto deste livro, <code>graus de liberdade</code> são abreviados por <code>gl</code>. Muitas vezes, é usado a abreviação <code>df</code> de <code>degree of freedom</code> porque em algumas funções aparecem como df e optou-se por manter sem a tradução.</p></div></div><p>A variância é a razão entre a soma dos quadrados e os graus de liberdade (observações realizadas menos um).</p>
<p><span class="math display">\[s^2= \frac{\sum(x_i - \overline{x})^2}{n-1}\]</span></p>
<p>No <em>R</em> existem embutidas as funções <code>sd()</code> e <code>var()</code>que facilmente calculam essas medidas de dispersão.</p>
<p>Usando a variável <code>dados$peso_rn</code>, tem-se:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 169623.2</code></pre>
</div>
</div>
<p>O desvio padrão é a raiz quadrada da variância: <span class="math display">\[s = \sqrt{s^2}\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span> (<span class="fu">var</span>(dados<span class="sc">$</span>peso_rn))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 411.8534</code></pre>
</div>
</div>
<p>Ou, usando a função <code>sd()</code> e arredondando para 1 dígito decimal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sd</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 411.9</code></pre>
</div>
</div>
<p>A variância e desvio padrão são medidas de variabilidade e revelam quão bem a média representa os dados. Informa se ela está <em>funcionando bem como modelo</em>. Pequenos desvios padrão mostram que existe pouca variabilidade nos dados, que eles se aproximam da média. Quando existe um grande desvio padrão, a média não é muito precisa para representar os dados.</p>
<p>O desvio padrão, além de medir a precisão com que a média representa os dados, também informa sobre o formato dos dados e por isso é uma medida de dispersão. Em uma amostra onde desvio padrão é pequeno, os dados se agrupam próximo a média e o formato da distribuição fica mais pontiagudo (curva em azul, <a href="#fig-dispersao" class="quarto-xref">Figura&nbsp;<span>6.1</span></a>). Nesse caso a média representa bem os dados. Em outra amostra, com a mesma média anterior, mas com os dados mais dispersos entorno da média, o desvio padrão é maior e o formato da distribuição fica achatado (curva verde, na Figura <a href="#fig-dispersao" class="quarto-xref">Figura&nbsp;<span>6.1</span></a>). Nesse caso a média não é uma boa representação dos dados.</p>
<div class="cell" data-layout-align="center" data-crop="false">
<div class="cell-output-display">
<div id="fig-dispersao" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dispersao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-medidasResumidoras_files/figure-html/fig-dispersao-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dispersao-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6.1: Dispersão dos dados em torno da média.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="coeficiente-de-variação" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="coeficiente-de-variação"><span class="header-section-number">6.5.4</span> Coeficiente de Variação</h3>
<p>O desvio padrão por si só tem limitações. Um desvio padrão igual a 2 pode ser considerado pequeno para um conjunto de valores cuja média é 100. Entretanto, se a média for 5, ele se torna muito grande. Além disso, o desvio padrão por ser expresso na mesma unidade dos dados, não permite aplicá-lo na comparação de dois ou mais conjunto de dados que têm unidades diferentes. Para eliminar essas limitações, é possível caracterizar a dispersão ou variabilidade dos dados em termos relativos, usando uma medida denominada Coeficiente de Variação (CV), também conhecido como <em>Desvio Padrão Relativo</em> ou <em>Coeficiente de Variação de Pearson</em>. É expresso, em geral como uma porcentagem, sendo definido como a razão do desvio padrão pela média:</p>
<p><span class="math display">\[CV = \frac{s}{\overline{x}}\]</span></p>
<p>Multiplicando o valor da equação por 100 tem-se o CV percentual. O <em>R</em> não possui uma função específica para calcular o CV.</p>
<p>Foi criada uma função específica para isso, já multiplicada por 100 (ver <a href="04-introducaoR.html#sec-funcpropria" class="quarto-xref"><span>Seção 4.4.1</span></a>). Será repetida aqui a função para facilitar a visualização:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>coefVar <span class="ot">&lt;-</span> <span class="cf">function</span> (x) {</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (<span class="fu">sd</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">mean</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Portanto, o CV da variável <code>dados$peso_rn</code> é igual a:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coefVar</span>(dados<span class="sc">$</span>peso_rn), <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.8</code></pre>
</div>
</div>
<p>Usando outra variável do banco de dados, por exemplo, <code>dados$idade_mae</code>, o CV será igual a:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coefVar</span>(dados<span class="sc">$</span>idade_mae), <span class="dv">1</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25.4</code></pre>
</div>
</div>
<p>O peso do recém-nascido tem um CV = 12.8 % e a idade materna um CV = 25.4 %, mostrando que esta tem uma maior variabilidade. Quanto menor o desvio padrão, menor o CV e, consequentemente, menor a variabilidade. Um CV <span class="math inline">\(\ge\)</span> 50%, sugere que a variável tem uma distribuição assimétrica.</p>
</section>
<section id="escolha-da-medida-resumidora" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="escolha-da-medida-resumidora"><span class="header-section-number">6.5.5</span> Escolha da medida resumidora</h3>
<p>A seleção da medida de tendência central mais adequada depende de vários fatores, incluindo a natureza dos dados e do propósito da sumarização.</p>
<p>O tipo da variável tem substancial influência na escolha da medida de tendência central a ser usada. A moda é mais apropriada para dados nominais e seu uso com variáveis ordinais resulta em uma perda no poder em termos de informação que se poderia obter dos dados.</p>
<p>A mediana é mais adequada para variáveis ordinais, embora possa ser usada para variáveis contínuas, especialmente quando a distribuição dos dados é assimétrica. A mediana não deveria ser usada com dados nominais porque os postos assumidos não podem ser obtidos com dados de nível nominal.</p>
<p>Finalmente, a média somente deve ser usada com dados contínuos simétricos, se houver assimetria a mediana deve ser preferida.</p>
<p>As medidas de dispersão devem estar associadas a uma medida de tendência central. Elas caracterizam a variabilidade dos dados na amostra. Com dados ordinais usar a amplitude ou o intervalo interquartil. O desvio padrão não é apropriado em dados ordinais devido à natureza não numérica destes.</p>
<p>Com os dados numéricos deve-se usar o desvio padrão, que utiliza toda a informação nos dados, ou o intervalo interquartil (IIQ). Quando os dados forem simétricos, usar a média acompanhada do desvio padrão, caso contrário, usar a mediana e o IIQ. Não misturar e combinar medidas <span class="citation" data-cites="bowers2008scratch">(<a href="#ref-bowers2008scratch" role="doc-biblioref">3</a>)</span>.</p>


<!-- -->

</section>
</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">Referências</h1>
<div id="refs" class="references csl-bib-body" role="list">
<div id="ref-american2006apgar" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Pediatrics AA of, Obstetricians AC of. The apgar score. Pediatrics. 2006;117(4):1444–7. </div>
</div>
<div id="ref-field2012df" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Field A, Miles J, Field Z. Everithing you ever wanted to know about statistics (well, sort of). Em: Discovering statistics using R. Sage Publications, Ltd; 2012. p. 38. </div>
</div>
<div id="ref-bowers2008scratch" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Bowers D. First things first-the nature of data. Em: Medical Statistics from Scratch. Second Edition. John Wiley; Sons; 2008. p. 3–13. </div>
</div>
</div>
</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-manipulacao_dados.html" class="pagination-link" aria-label="Manipulação dos dados no R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Manipulação dos dados no R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-tabelas.html" class="pagination-link" aria-label="Tabelas">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tabelas</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb53" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Medidas Resumidoras {#sec-resumo}</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dados brutos {#sec-dadosbrutos}</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>Habitualmente, costuma-se armazenar os dados em bancos de dados (*dataframes* ou *tibbles*). Entretanto, eles estão registrados de forma aleatória e não classificada. Ao se visualizar um dataframe, é difícil responder perguntas em relação a qualquer variável, principalmente, em grandes bancos de dados. Eles se constituem uma lista, um rol de valores colocados na ordem em que foram obtidos. Parecem um jogo de quebra cabeça antes de ser organizado! A @tbl-raw é o tipo mais simples de tabela possível. Nela é apresentado um conjunto de dados, os valores dos pesos de 30 recém-nascidos. Não há nenhum significado especial para as linhas e colunas, estão dispostos da maneira como coletados. Eles pouco informam; são apenas os dados na sua forma inicial sem nenhum tratamento ou ordem. São denominados como *dados brutos* e se constituem no ponto de partida para uma análise. Quando colocados em ordem crescente, permitindo uma compreensão inicial, são chamados de dados não agrupados; quando classificados em categorias ou intervalos, são denominados dados agrupados.</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-raw</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-align: "center"</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Peso de 30 recém-nascidos de partos consecutivos"</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(officer)</span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(peso_rn) <span class="sc">|&gt;</span> </span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">30</span>)</span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a>matriz <span class="ot">&lt;-</span> <span class="fu">matrix</span>(dados<span class="sc">$</span>peso_rn, <span class="at">nrow =</span> <span class="dv">5</span>,<span class="at">ncol =</span> <span class="dv">6</span>)</span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(matriz)</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a>std_border <span class="ot">=</span> <span class="fu">fp_border</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">style =</span> <span class="st">"solid"</span>, <span class="at">width =</span> <span class="fl">1.5</span>)</span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>ft <span class="ot">&lt;-</span> <span class="fu">flextable</span>(df) <span class="sc">|&gt;</span> </span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_header_labels</span>(<span class="at">V1 =</span> <span class="st">" "</span>, <span class="at">V2 =</span> <span class="st">" "</span>, <span class="at">V3 =</span> <span class="st">" "</span>, <span class="at">V4 =</span> <span class="st">" "</span>, <span class="at">V5 =</span> <span class="st">" "</span>, <span class="at">V6 =</span> <span class="st">" "</span>) <span class="sc">|&gt;</span> </span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">border_remove</span>() <span class="sc">|&gt;</span> </span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hline</span>(<span class="at">part =</span> <span class="st">"header"</span>, <span class="at">border =</span> std_border) <span class="sc">|&gt;</span> </span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hline_bottom</span>(<span class="at">part =</span> <span class="st">"body"</span>, <span class="at">border =</span> std_border)</span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>ft</span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introdução</span></span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-40"><a href="#cb53-40" aria-hidden="true" tabindex="-1"></a>Nos relatórios ou artigos científicos, a comunicação dos resultados é feita através da combinação de medidas resumidoras e visualização dos dados por meio de tabelas e gráficos, constituindo o que se costuma chamar de **Estatística Descritiva**. Neste capítulo, serão discutidas as principais medidas resumidoras dos dados de duas maneiras:</span>
<span id="cb53-41"><a href="#cb53-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-42"><a href="#cb53-42" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Primeiro, um valor em torno do qual os dados têm uma tendência para se reunir ou se agrupar, denominado de **medida de tendência central**. Relacionadas a elas estão as **medidas de posição** (ou de localização), como os quantis, que situam um valor dentro do conjunto ordenado de dados; apenas uma delas, a mediana, é também uma medida de tendência central.</span>
<span id="cb53-43"><a href="#cb53-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Em segundo lugar, um valor que mede o grau em que os dados se dispersam, denominado de **medida de dispersão** ou **variabilidade**.</span>
<span id="cb53-44"><a href="#cb53-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-45"><a href="#cb53-45" aria-hidden="true" tabindex="-1"></a>Nos próximos capítulos, desta Parte III, estarão em discussão a construção de Tabelas (@sec-tabelas) e visualização dos dados através de gráficos (@sec-graficos).</span>
<span id="cb53-46"><a href="#cb53-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-47"><a href="#cb53-47" aria-hidden="true" tabindex="-1"></a><span class="fu">## Dados usados neste capítulo {#sec-dados-cap6}</span></span>
<span id="cb53-48"><a href="#cb53-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-49"><a href="#cb53-49" aria-hidden="true" tabindex="-1"></a>Para as demonstrações práticas, será usado o banco de dados <span class="in">`dadosMater.xlsx`</span> (ver @sec-dadosMater). Após carregá-lo, serão filtrados os partos a termo e selecionadas as variáveis necessárias (<span class="in">`idade_mae`</span>, <span class="in">`anos_est`</span>, <span class="in">`peso_rn`</span>, <span class="in">`apgar1`</span>). Por último, será extraída com a função <span class="in">`slice_sample()`</span> do pacote <span class="in">`dplyr`</span> (@sec-dplyr) uma amostra de n = 200. Cada vez que este comando for reproduzido, retornará uma nova série de 200 valores, diferente da anterior. Para tornar o código reproduzível, retornando o mesmo conjunto de valores, deve-se usar uma “semente” (<span class="in">`seed`</span>), usando a função <span class="in">`set.seed()`</span>, cujo argumento é um número que identificará a série gerada. Após extrair a amostra, esta será atribuída a um objeto denominado, <span class="in">`dados`</span>:</span>
<span id="cb53-50"><a href="#cb53-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-53"><a href="#cb53-53" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-54"><a href="#cb53-54" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb53-55"><a href="#cb53-55" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb53-56"><a href="#cb53-56" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb53-57"><a href="#cb53-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-58"><a href="#cb53-58" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb53-59"><a href="#cb53-59" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> readxl<span class="sc">::</span><span class="fu">read_excel</span>(<span class="st">"dados/dadosMater.xlsx"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb53-60"><a href="#cb53-60" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ig <span class="sc">&gt;=</span> <span class="dv">37</span> <span class="sc">&amp;</span> ig <span class="sc">&lt;</span> <span class="dv">42</span>) <span class="sc">|&gt;</span> </span>
<span id="cb53-61"><a href="#cb53-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(idade_mae, anos_est, peso_rn, apgar1) <span class="sc">|&gt;</span> </span>
<span id="cb53-62"><a href="#cb53-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n=</span><span class="dv">200</span>)</span>
<span id="cb53-63"><a href="#cb53-63" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-64"><a href="#cb53-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-65"><a href="#cb53-65" aria-hidden="true" tabindex="-1"></a><span class="fu">## Medidas de tendência central</span></span>
<span id="cb53-66"><a href="#cb53-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-67"><a href="#cb53-67" aria-hidden="true" tabindex="-1"></a><span class="fu">### Média</span></span>
<span id="cb53-68"><a href="#cb53-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-69"><a href="#cb53-69" aria-hidden="true" tabindex="-1"></a>A média ($\overline{x}$) é a mais usada medida de tendência central para representar um valor típico dentro de um conjunto de números. O conceito mais comum é a **média aritmética**, que se calcula somando todos os valores do conjunto e dividindo pelo número total de elementos. A média é mais adequada para medidas numéricas simétricas, pois ela é sensível aos valores extremos (*outliers*).</span>
<span id="cb53-70"><a href="#cb53-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-71"><a href="#cb53-71" aria-hidden="true" tabindex="-1"></a>$$\overline{x}= \frac{\sum_{i=1}^{n} x_i}{n}$$</span>
<span id="cb53-72"><a href="#cb53-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-73"><a href="#cb53-73" aria-hidden="true" tabindex="-1"></a>O R base possui uma função para o cálculo da média, <span class="in">`mean()`</span>, apresentada na @sec-funcoes, onde foi mostrado os seus argumentos. Se a variável analisada contiver algum valor ausente (*missing*), deve-se usar o argumento `na.rm = TRUE`, para removê-los, pois, caso contrário, a função retorna um resultado como NA (*Not Available*). Para evitar transtornos, recomenda-se usar sempre o argumento.</span>
<span id="cb53-74"><a href="#cb53-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-77"><a href="#cb53-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-78"><a href="#cb53-78" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-79"><a href="#cb53-79" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-80"><a href="#cb53-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-81"><a href="#cb53-81" aria-hidden="true" tabindex="-1"></a>Para reduzir o número de dígitos decimais, na saída do resultado, pode-se colocar a função <span class="in">`mean()`</span>, dentro da função <span class="in">`round()`</span><span class="ot">[^06-medidasresumidoras-1]</span>, atribuindo o resultado da função a um objeto, por exemplo <span class="in">`media`</span>.</span>
<span id="cb53-82"><a href="#cb53-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-83"><a href="#cb53-83" aria-hidden="true" tabindex="-1"></a><span class="ot">[^06-medidasresumidoras-1]: </span>Usa-se esta sintaxe: <span class="in">`round(x, digits = 0)`</span>, onde <span class="in">`x`</span> é o numero que se quer arredondar e <span class="in">`digits`</span> é número de casas decimais. O padrão é <span class="in">`0`</span>, ou seja, arredonda para o inteiro mais próximo.</span>
<span id="cb53-84"><a href="#cb53-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-87"><a href="#cb53-87" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-88"><a href="#cb53-88" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span>
<span id="cb53-89"><a href="#cb53-89" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(media)</span>
<span id="cb53-90"><a href="#cb53-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-91"><a href="#cb53-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-92"><a href="#cb53-92" aria-hidden="true" tabindex="-1"></a>Ou, usar a função <span class="in">`round()`</span>, separadamente:</span>
<span id="cb53-93"><a href="#cb53-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-96"><a href="#cb53-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-97"><a href="#cb53-97" aria-hidden="true" tabindex="-1"></a>media <span class="ot">&lt;-</span> <span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-98"><a href="#cb53-98" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(media, <span class="dv">1</span>)</span>
<span id="cb53-99"><a href="#cb53-99" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-100"><a href="#cb53-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-101"><a href="#cb53-101" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mediana {#sec-mediana}</span></span>
<span id="cb53-102"><a href="#cb53-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-103"><a href="#cb53-103" aria-hidden="true" tabindex="-1"></a>A mediana (Md) representa o valor central em uma série ordenada de valores. Assim, metade dos valores será igual ou menor que o valor mediano e a outra metade igual ou maior do que ele. Para encontrar a mediana procede-se da seguinte maneira:</span>
<span id="cb53-104"><a href="#cb53-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-105"><a href="#cb53-105" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>Ordenar o conjunto de dados, por exemplo, a variável <span class="in">`dados$peso_rn`</span>, usando a função <span class="in">`sort()`</span>:</span>
<span id="cb53-106"><a href="#cb53-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-109"><a href="#cb53-109" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-110"><a href="#cb53-110" aria-hidden="true" tabindex="-1"></a>valores_ordenados <span class="ot">&lt;-</span> <span class="fu">sort</span>(dados<span class="sc">$</span>peso_rn)</span>
<span id="cb53-111"><a href="#cb53-111" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(valores_ordenados)</span>
<span id="cb53-112"><a href="#cb53-112" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-113"><a href="#cb53-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-114"><a href="#cb53-114" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>Quando o número de valores é par, caso do exemplo, a mediana é a média dos dois valores do meio, ou seja, o valor central corresponde a média do valor 100 e do valor 101 dos valores ordenados:</span>
<span id="cb53-115"><a href="#cb53-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-118"><a href="#cb53-118" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-119"><a href="#cb53-119" aria-hidden="true" tabindex="-1"></a>mediana <span class="ot">=</span> (valores_ordenados[<span class="dv">100</span>] <span class="sc">+</span> valores_ordenados[<span class="dv">101</span>])<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb53-120"><a href="#cb53-120" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mediana)</span>
<span id="cb53-121"><a href="#cb53-121" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-122"><a href="#cb53-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-123"><a href="#cb53-123" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>Quando o número de valores no conjunto de dados for ímpar, a mediana é o valor do meio.</span>
<span id="cb53-124"><a href="#cb53-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-125"><a href="#cb53-125" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>No exemplo, tem-se 200 valores. Para transformar a amostra em uma amostra com *n* ímpar, remover aleatoriamente uma observação dos valores dos <span class="in">`dados$peso_rn`</span>:</span>
<span id="cb53-126"><a href="#cb53-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-129"><a href="#cb53-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-130"><a href="#cb53-130" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb53-131"><a href="#cb53-131" aria-hidden="true" tabindex="-1"></a>index_aleatorio <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">length</span>(dados<span class="sc">$</span>peso_rn), <span class="dv">1</span>)</span>
<span id="cb53-132"><a href="#cb53-132" aria-hidden="true" tabindex="-1"></a>index_aleatorio</span>
<span id="cb53-133"><a href="#cb53-133" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-134"><a href="#cb53-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-135"><a href="#cb53-135" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Ou seja, o valor selecionado é o <span class="in">`r index_aleatorio`</span>º valor. A seguir, obtem-se o peso aleatório que foi selecionado:</span>
<span id="cb53-136"><a href="#cb53-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-139"><a href="#cb53-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-140"><a href="#cb53-140" aria-hidden="true" tabindex="-1"></a>peso_aleatorio <span class="ot">&lt;-</span> dados<span class="sc">$</span>peso_rn[index_aleatorio]</span>
<span id="cb53-141"><a href="#cb53-141" aria-hidden="true" tabindex="-1"></a>peso_aleatorio</span>
<span id="cb53-142"><a href="#cb53-142" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-143"><a href="#cb53-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-144"><a href="#cb53-144" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Remover o <span class="in">`r index_aleatorio`</span>º valor (index_aleatório) da lista de <span class="in">`dados$peso_rn`</span> que corresponde ao peso selecionado:</span>
<span id="cb53-145"><a href="#cb53-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-148"><a href="#cb53-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-149"><a href="#cb53-149" aria-hidden="true" tabindex="-1"></a>pesos_restantes <span class="ot">&lt;-</span> dados<span class="sc">$</span>peso_rn[<span class="sc">-</span>index_aleatorio]</span>
<span id="cb53-150"><a href="#cb53-150" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-151"><a href="#cb53-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-152"><a href="#cb53-152" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Colocar os pesos_restantes em ordem crescente:</span>
<span id="cb53-153"><a href="#cb53-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-156"><a href="#cb53-156" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-157"><a href="#cb53-157" aria-hidden="true" tabindex="-1"></a>restantes_ordenados <span class="ot">&lt;-</span> <span class="fu">sort</span>(pesos_restantes)</span>
<span id="cb53-158"><a href="#cb53-158" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(restantes_ordenados)</span>
<span id="cb53-159"><a href="#cb53-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-160"><a href="#cb53-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-161"><a href="#cb53-161" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Cálculo da mediana com os valores restantes ordenados. O valor central entre 1 e 199 é o 100º valor:</span>
<span id="cb53-162"><a href="#cb53-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-165"><a href="#cb53-165" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-166"><a href="#cb53-166" aria-hidden="true" tabindex="-1"></a>mediana <span class="ot">&lt;-</span> restantes_ordenados[<span class="dv">100</span>]</span>
<span id="cb53-167"><a href="#cb53-167" aria-hidden="true" tabindex="-1"></a>mediana</span>
<span id="cb53-168"><a href="#cb53-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-169"><a href="#cb53-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-170"><a href="#cb53-170" aria-hidden="true" tabindex="-1"></a>Imaginem que sempre que se for calcular a mediana houvesse necessidade de se proceder como realizado acima. Seria tedioso, quase um caos! Entretanto, usando o R, a situação fica bem mais agradável e intuitiva. O R facilita esse trabalho, fornecendo a função <span class="in">`median()`</span>.</span>
<span id="cb53-171"><a href="#cb53-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-172"><a href="#cb53-172" aria-hidden="true" tabindex="-1"></a>Como exemplo, será usada a variável <span class="in">`apgar1`</span> já incluída no dataframe <span class="in">`dados`</span>. Como o Apgar é um escore <span class="co">[</span><span class="ot">@american2006apgar</span><span class="co">]</span>, a medida resumidora mais adequada, realmente, é a mediana.</span>
<span id="cb53-173"><a href="#cb53-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-176"><a href="#cb53-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-177"><a href="#cb53-177" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span> (dados<span class="sc">$</span>apgar1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-178"><a href="#cb53-178" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-179"><a href="#cb53-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-180"><a href="#cb53-180" aria-hidden="true" tabindex="-1"></a>::: callout-tip</span>
<span id="cb53-181"><a href="#cb53-181" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercício</span></span>
<span id="cb53-182"><a href="#cb53-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-183"><a href="#cb53-183" aria-hidden="true" tabindex="-1"></a>Calcular a mediana dos valores <span class="in">`dados$peso_rn.`</span></span>
<span id="cb53-184"><a href="#cb53-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-185"><a href="#cb53-185" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Resposta</span><span class="co">]</span>{.underline}</span>
<span id="cb53-186"><a href="#cb53-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-189"><a href="#cb53-189" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-190"><a href="#cb53-190" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(dados<span class="sc">$</span>peso_rn, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb53-191"><a href="#cb53-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-192"><a href="#cb53-192" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-193"><a href="#cb53-193" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb53-194"><a href="#cb53-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-195"><a href="#cb53-195" aria-hidden="true" tabindex="-1"></a><span class="fu">### Moda</span></span>
<span id="cb53-196"><a href="#cb53-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-197"><a href="#cb53-197" aria-hidden="true" tabindex="-1"></a>Moda (Mo) é o valor que ocorre com maior frequência em um conjunto de dados. O *R* não possui uma função nativa e direta para calcular a moda como tem para a média (<span class="in">`mean()`</span>) e a mediana (<span class="in">`median()`</span>). Isso acontece porque a moda pode não ser única em um conjunto de dados (podem existir múltiplos valores com a mesma frequência máxima) ou pode nem existir (se todos os valores ocorrerem apenas uma vez). É a medida de tendência central com o menor nível de sofisticação estatística. No entanto, pode-se facilmente criar uma função própria para calcular a moda ou usar pacotes que oferecem essa funcionalidade, como o <span class="in">`DescTools`</span> que oferece uma função chamada <span class="in">`Mode()`</span>. Aqui estão algumas maneiras de calcular a moda em R:</span>
<span id="cb53-198"><a href="#cb53-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-199"><a href="#cb53-199" aria-hidden="true" tabindex="-1"></a>**Função personalizada**</span>
<span id="cb53-200"><a href="#cb53-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-203"><a href="#cb53-203" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-204"><a href="#cb53-204" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb53-205"><a href="#cb53-205" aria-hidden="true" tabindex="-1"></a>  freq_tab <span class="ot">&lt;-</span> <span class="fu">table</span>(v)</span>
<span id="cb53-206"><a href="#cb53-206" aria-hidden="true" tabindex="-1"></a>  max_freq <span class="ot">&lt;-</span> <span class="fu">max</span>(freq_tab)</span>
<span id="cb53-207"><a href="#cb53-207" aria-hidden="true" tabindex="-1"></a>  moda <span class="ot">&lt;-</span> <span class="fu">names</span>(freq_tab[freq_tab <span class="sc">==</span> max_freq])</span>
<span id="cb53-208"><a href="#cb53-208" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(moda)</span>
<span id="cb53-209"><a href="#cb53-209" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-210"><a href="#cb53-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-211"><a href="#cb53-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-212"><a href="#cb53-212" aria-hidden="true" tabindex="-1"></a>Esta função <span class="in">`moda()`</span>é constituída por:</span>
<span id="cb53-213"><a href="#cb53-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-214"><a href="#cb53-214" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**table(v)**: Cria uma tabela de frequência dos valores v.</span>
<span id="cb53-215"><a href="#cb53-215" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**max(freq_tab)**: Encontra a frequência máxima.</span>
<span id="cb53-216"><a href="#cb53-216" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**freq_tab\[freq_tab == max_freq\]**: Seleciona as entradas da tabela de frequência que são iguais à frequência máxima.</span>
<span id="cb53-217"><a href="#cb53-217" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**names(...)**: Obtém os nomes (os valores originais) dessas entradas, que são as modas.</span>
<span id="cb53-218"><a href="#cb53-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-219"><a href="#cb53-219" aria-hidden="true" tabindex="-1"></a>Usando a função criada, a moda da variável <span class="in">`dados$apgar1`</span> é igual a:</span>
<span id="cb53-220"><a href="#cb53-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-223"><a href="#cb53-223" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-224"><a href="#cb53-224" aria-hidden="true" tabindex="-1"></a><span class="fu">moda</span> (dados<span class="sc">$</span>apgar1) </span>
<span id="cb53-225"><a href="#cb53-225" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-226"><a href="#cb53-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-227"><a href="#cb53-227" aria-hidden="true" tabindex="-1"></a>A função <span class="in">`moda()`</span> pode ser salva em seu diretório de trabalho, na pasta das suas funções próprias. Quando necessário ela pode ser acessada, como foi visto na @sec-funcpropria.</span>
<span id="cb53-228"><a href="#cb53-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-229"><a href="#cb53-229" aria-hidden="true" tabindex="-1"></a>**Função Mode() do pacote DescTools**</span>
<span id="cb53-230"><a href="#cb53-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-233"><a href="#cb53-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-234"><a href="#cb53-234" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb53-235"><a href="#cb53-235" aria-hidden="true" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="fu">Mode</span>(dados<span class="sc">$</span>apgar1)</span>
<span id="cb53-236"><a href="#cb53-236" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(moda)</span>
<span id="cb53-237"><a href="#cb53-237" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-238"><a href="#cb53-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-239"><a href="#cb53-239" aria-hidden="true" tabindex="-1"></a><span class="fu">### Quantil {#sec-quantil}</span></span>
<span id="cb53-240"><a href="#cb53-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-241"><a href="#cb53-241" aria-hidden="true" tabindex="-1"></a>Os **quantis** são uma **medida de posição** (ou de localização) bastante utilizada: pontos estabelecidos em intervalos regulares que dividem a amostra em subconjuntos iguais. Diferentemente das medidas de tendência central, os quantis, isoladamente, não indicam um valor típico do conjunto de dados, mas sim a posição relativa de um valor dentro da distribuição ordenada. A mediana (o quantil 50%) é a única exceção: além de ser uma medida de posição, ela também é uma medida de tendência central (ver @sec-mediana), pois representa o valor central da distribuição.</span>
<span id="cb53-242"><a href="#cb53-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-243"><a href="#cb53-243" aria-hidden="true" tabindex="-1"></a>Se estes subconjuntos são em número de 100, são denominados de **percentis**; se são em número de 10, são os **decis** e em número de 4, são os **quartis**. A função nativa no R para obter o quantil é <span class="in">`quantile()`</span>.</span>
<span id="cb53-244"><a href="#cb53-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-245"><a href="#cb53-245" aria-hidden="true" tabindex="-1"></a>Para determinar os três quartis do peso dos recém-nascidos (<span class="in">`dados$peso_rn`</span>), usa-se:</span>
<span id="cb53-246"><a href="#cb53-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-249"><a href="#cb53-249" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-250"><a href="#cb53-250" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (dados<span class="sc">$</span>peso_rn, <span class="fu">c</span> (<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>))</span>
<span id="cb53-251"><a href="#cb53-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-252"><a href="#cb53-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-253"><a href="#cb53-253" aria-hidden="true" tabindex="-1"></a>Observe que o percentil 50º é igual a mediana. O percentil 75º é o ponto do conjunto de dados onde 75% dos recém-nascidos têm um peso inferior a <span class="in">`r quantile (dados$peso_rn, 0.75)`</span>g e 25% está acima deste valor.</span>
<span id="cb53-254"><a href="#cb53-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-255"><a href="#cb53-255" aria-hidden="true" tabindex="-1"></a><span class="fu">### Média aparada</span></span>
<span id="cb53-256"><a href="#cb53-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-257"><a href="#cb53-257" aria-hidden="true" tabindex="-1"></a>As médias aparadas são estimadores robustos da tendência central. Para calcular uma média aparada, é removida uma quantidade predeterminada de observações em cada lado de uma distribuição e realizada a média das observações restantes. Um exemplo de média aparada é a própria mediana.</span>
<span id="cb53-258"><a href="#cb53-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-259"><a href="#cb53-259" aria-hidden="true" tabindex="-1"></a>A base R tem como calcular a média aparada acrescentando o argumento <span class="in">`trim =`</span>, proporção a ser aparada. Se for aparado 20%, usa-se <span class="in">`trim = 0.2`</span>. Isto significa que serão removidos 20% dos dados dos dois extremos. No caso da amostra de 200 recém-nascidos, serão removidos 40 valores mais baixos e 40 valores mais altos, passando a amostra a ter 120 valores, e a média aparada será a média destes 120 valores.</span>
<span id="cb53-260"><a href="#cb53-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-261"><a href="#cb53-261" aria-hidden="true" tabindex="-1"></a>O comando para obter a média aparada é:</span>
<span id="cb53-262"><a href="#cb53-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-265"><a href="#cb53-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-266"><a href="#cb53-266" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">mean</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">trim =</span> <span class="fl">0.20</span>), <span class="dv">1</span>)</span>
<span id="cb53-267"><a href="#cb53-267" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-268"><a href="#cb53-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-269"><a href="#cb53-269" aria-hidden="true" tabindex="-1"></a><span class="fu">## Medidas de Dispersão</span></span>
<span id="cb53-270"><a href="#cb53-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-271"><a href="#cb53-271" aria-hidden="true" tabindex="-1"></a><span class="fu">### Amplitude</span></span>
<span id="cb53-272"><a href="#cb53-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-273"><a href="#cb53-273" aria-hidden="true" tabindex="-1"></a>A amplitude de um grupo de medições é definida como a diferença entre a maior observação e a menor.\</span>
<span id="cb53-274"><a href="#cb53-274" aria-hidden="true" tabindex="-1"></a>No conjunto de dados dos pesos dos recém-nascidos, a amplitude pode ser obtida, no *R*, com a função <span class="in">`range()`</span>, que retorna o valor mínimo e o máximo.</span>
<span id="cb53-275"><a href="#cb53-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-278"><a href="#cb53-278" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-279"><a href="#cb53-279" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-280"><a href="#cb53-280" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-281"><a href="#cb53-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-282"><a href="#cb53-282" aria-hidden="true" tabindex="-1"></a><span class="fu">### Intervalo Interquartil</span></span>
<span id="cb53-283"><a href="#cb53-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-284"><a href="#cb53-284" aria-hidden="true" tabindex="-1"></a>O intervalo interquartil (IIQ), também conhecido como amplitude interquartil (AIQ), é uma medida de dispersão robusta análoga a uma *amplitude aparada*: assim como a média aparada exclui os valores mais extremos antes de calcular a média, o IIQ exclui os 25% de valores mais baixos e os 25% mais altos antes de medir a dispersão dos valores restantes. É simplesmente a diferença entre o terceiro e o primeiro quartil, ou seja, a diferença entre o percentil 75 e o percentil 25. Considere a variável escolaridade (<span class="in">`dados$anos_est`</span>), anos de estudos completos.</span>
<span id="cb53-285"><a href="#cb53-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-286"><a href="#cb53-286" aria-hidden="true" tabindex="-1"></a>Os percentis 25 e 75 são obtidos, usando a função <span class="in">`quantile()`</span>, vista acima, ou com a função <span class="in">`summary()`</span>, que retorna os valores mínimo, primeiro quartil, mediana, média, terceiro quartil e máximo.</span>
<span id="cb53-287"><a href="#cb53-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-290"><a href="#cb53-290" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-291"><a href="#cb53-291" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span> (dados<span class="sc">$</span>anos_est, <span class="fu">c</span>(<span class="fl">0.25</span>,<span class="fl">0.75</span>))</span>
<span id="cb53-292"><a href="#cb53-292" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-293"><a href="#cb53-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-296"><a href="#cb53-296" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-297"><a href="#cb53-297" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados<span class="sc">$</span>anos_est)</span>
<span id="cb53-298"><a href="#cb53-298" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-299"><a href="#cb53-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-300"><a href="#cb53-300" aria-hidden="true" tabindex="-1"></a>Portanto, o IIQ está entre <span class="in">`r quantile (dados$anos_est, 0.25)`</span> a <span class="in">`r quantile (dados$anos_est, 0.75)`</span> anos de estudo ou, <span class="in">`r quantile (dados$anos_est, 0.75) - quantile (dados$anos_est, 0.25)`</span> anos de estudos completos. Em outras palavras, 50% das mulheres desta amostra têm entre <span class="in">`r quantile (dados$anos_est, 0.25)`</span> a <span class="in">`r quantile (dados$anos_est, 0.75)`</span> anos de estudo.</span>
<span id="cb53-301"><a href="#cb53-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-302"><a href="#cb53-302" aria-hidden="true" tabindex="-1"></a>O R possui uma função específica para calcular o intervalo interquartil, denominada <span class="in">`IQR()`</span> e incluída no <span class="in">`R`</span> base. Ela possui os seguintes argumentos:</span>
<span id="cb53-303"><a href="#cb53-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-304"><a href="#cb53-304" aria-hidden="true" tabindex="-1"></a>**x** $\to$ Representa o vetor numérico;\</span>
<span id="cb53-305"><a href="#cb53-305" aria-hidden="true" tabindex="-1"></a>**na.rm** $\to$ Este assume um valor lógico, TRUE ou FALSE, indicando se os valores ausentes devem ser removidos ou não;\</span>
<span id="cb53-306"><a href="#cb53-306" aria-hidden="true" tabindex="-1"></a>**type** $\to$ Representa um número inteiro selecionando um dos muitos algoritmos de quantil. Este é um parâmetro opcional.</span>
<span id="cb53-307"><a href="#cb53-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-310"><a href="#cb53-310" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-311"><a href="#cb53-311" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(dados<span class="sc">$</span>anos_est, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-312"><a href="#cb53-312" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-313"><a href="#cb53-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-314"><a href="#cb53-314" aria-hidden="true" tabindex="-1"></a><span class="fu">### Variância e Desvio Padrão {#sec-variancia}</span></span>
<span id="cb53-315"><a href="#cb53-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-316"><a href="#cb53-316" aria-hidden="true" tabindex="-1"></a>A variância e o desvio padrão fornecem uma indicação de quão aglomerados em torno da média os dados de uma amostra estão. Estes tipos de medidas representam desvios (erros) da média. Quando se verifica o desvio de cada valor (x) em relação à média $\overline{x}$, os desvios positivos se anulam com os negativos, resultando em uma soma igual a zero.</span>
<span id="cb53-317"><a href="#cb53-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-318"><a href="#cb53-318" aria-hidden="true" tabindex="-1"></a>A consequência deste fato é que não é possível resumir os desvios numa única medida de variabilidade. Para se chegar a uma medida de variabilidade há necessidade de se eliminar os sinais, antes de somar todos os desvios em relação à média.</span>
<span id="cb53-319"><a href="#cb53-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-320"><a href="#cb53-320" aria-hidden="true" tabindex="-1"></a>Uma maneira de se fazer isso é elevar todas as diferenças ao quadrado. Assim, se obtém o desvio em relação à média elevado ao quadrado. A soma destes valores é denominada de *Soma dos Quadrados (SQ) dos Desvios* ou *Soma dos Erros ao Quadrado*. Se o interesse é apenas saber o erro ou desvio médio, divide-se por *n* (tamanho da amostra). No entanto, em geral o interesse se concentra em usar o desvio ou erro na amostra para estimar o erro na população. Dessa maneira, divide-se a Soma dos Quadrados por $n-1$. Essa medida é conhecida como **variância** ($s^2$). O divisor, $n – 1$, é denominado de *graus de liberdade* (gl) associados à variância.</span>
<span id="cb53-321"><a href="#cb53-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-322"><a href="#cb53-322" aria-hidden="true" tabindex="-1"></a>Os graus de liberdade representam o número de desvios que estão livres para variar. É um conceito de difícil explicação, mas é possível compreendê-lo, usando a seguinte explicação:</span>
<span id="cb53-323"><a href="#cb53-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-324"><a href="#cb53-324" aria-hidden="true" tabindex="-1"></a>::: callout-note</span>
<span id="cb53-325"><a href="#cb53-325" aria-hidden="true" tabindex="-1"></a><span class="fu">## Graus de liberdade {#sec-gl}</span></span>
<span id="cb53-326"><a href="#cb53-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-327"><a href="#cb53-327" aria-hidden="true" tabindex="-1"></a>Suponha uma maternidade há 50 anos atrás, quando não havia alojamento conjunto. Nessa época era comum os recém-nascidos normais ficarem em um berçário. A cada horário de amamentação eles eram levados para os quartos de suas mães para mamar. Posteriormente, eram trazidos para o berçário e colocados nos berços até a próxima mamada. Suponha que, em um determinado momento, havia 15 bebês e que, no berçário, existiam 15 berços (postos) para colocá-los durante o intervalo das mamadas. Quando o primeiro recém-nascido chega, a enfermeira poderá escolher qualquer um dos berços para o colocar. Depois, quando o próximo recém-nascido chegar, ela terá 14 opções de escolha, pois um dos berços está ocupado. Ainda existe uma boa liberdade de escolha. No entanto, à medida que os recém-nascidos forem sendo trazidos para o berçário, chegará a um ponto em que 14 berços estarão ocupados. Agora, a enfermeira não terá liberdade de escolha, pois só resta um berço. Nesse exemplo existem 14 graus de liberdade (gl)<span class="ot">[^06-medidasresumidoras-2]</span>. Para o último recém-nascido não houve liberdade de escolha <span class="co">[</span><span class="ot">@field2012df</span><span class="co">]</span>. Portanto, os graus de liberdade são iguais ao tamanho da amostra menos um ($n-1$).</span>
<span id="cb53-328"><a href="#cb53-328" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb53-329"><a href="#cb53-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-330"><a href="#cb53-330" aria-hidden="true" tabindex="-1"></a><span class="ot">[^06-medidasresumidoras-2]: </span>No texto deste livro, <span class="in">`graus de liberdade`</span> são abreviados por <span class="in">`gl`</span>. Muitas vezes, é usado a abreviação <span class="in">`df`</span> de <span class="in">`degree of freedom`</span> porque em algumas funções aparecem como df e optou-se por manter sem a tradução.</span>
<span id="cb53-331"><a href="#cb53-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-332"><a href="#cb53-332" aria-hidden="true" tabindex="-1"></a>A variância é a razão entre a soma dos quadrados e os graus de liberdade (observações realizadas menos um).</span>
<span id="cb53-333"><a href="#cb53-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-334"><a href="#cb53-334" aria-hidden="true" tabindex="-1"></a>$$s^2= \frac{\sum(x_i - \overline{x})^2}{n-1}$$</span>
<span id="cb53-335"><a href="#cb53-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-336"><a href="#cb53-336" aria-hidden="true" tabindex="-1"></a>No *R* existem embutidas as funções <span class="in">`sd()`</span> e <span class="in">`var()`</span>que facilmente calculam essas medidas de dispersão.</span>
<span id="cb53-337"><a href="#cb53-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-338"><a href="#cb53-338" aria-hidden="true" tabindex="-1"></a>Usando a variável <span class="in">`dados$peso_rn`</span>, tem-se:</span>
<span id="cb53-339"><a href="#cb53-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-342"><a href="#cb53-342" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-343"><a href="#cb53-343" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb53-344"><a href="#cb53-344" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-345"><a href="#cb53-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-346"><a href="#cb53-346" aria-hidden="true" tabindex="-1"></a>O desvio padrão é a raiz quadrada da variância: $$s = \sqrt{s^2}$$</span>
<span id="cb53-347"><a href="#cb53-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-350"><a href="#cb53-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-351"><a href="#cb53-351" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span> (<span class="fu">var</span>(dados<span class="sc">$</span>peso_rn))</span>
<span id="cb53-352"><a href="#cb53-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-353"><a href="#cb53-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-354"><a href="#cb53-354" aria-hidden="true" tabindex="-1"></a>Ou, usando a função <span class="in">`sd()`</span> e arredondando para 1 dígito decimal:</span>
<span id="cb53-355"><a href="#cb53-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-358"><a href="#cb53-358" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-359"><a href="#cb53-359" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sd</span> (dados<span class="sc">$</span>peso_rn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>)</span>
<span id="cb53-360"><a href="#cb53-360" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-361"><a href="#cb53-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-362"><a href="#cb53-362" aria-hidden="true" tabindex="-1"></a>A variância e desvio padrão são medidas de variabilidade e revelam quão bem a média representa os dados. Informa se ela está *funcionando bem como modelo*. Pequenos desvios padrão mostram que existe pouca variabilidade nos dados, que eles se aproximam da média. Quando existe um grande desvio padrão, a média não é muito precisa para representar os dados.</span>
<span id="cb53-363"><a href="#cb53-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-364"><a href="#cb53-364" aria-hidden="true" tabindex="-1"></a>O desvio padrão, além de medir a precisão com que a média representa os dados, também informa sobre o formato dos dados e por isso é uma medida de dispersão. Em uma amostra onde desvio padrão é pequeno, os dados se agrupam próximo a média e o formato da distribuição fica mais pontiagudo (curva em azul, @fig-dispersao). Nesse caso a média representa bem os dados. Em outra amostra, com a mesma média anterior, mas com os dados mais dispersos entorno da média, o desvio padrão é maior e o formato da distribuição fica achatado (curva verde, na Figura @fig-dispersao). Nesse caso a média não é uma boa representação dos dados.</span>
<span id="cb53-365"><a href="#cb53-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-368"><a href="#cb53-368" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-369"><a href="#cb53-369" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-dispersao</span></span>
<span id="cb53-370"><a href="#cb53-370" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb53-371"><a href="#cb53-371" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb53-372"><a href="#cb53-372" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-align: 'center'</span></span>
<span id="cb53-373"><a href="#cb53-373" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Dispersão dos dados em torno da média."</span></span>
<span id="cb53-374"><a href="#cb53-374" aria-hidden="true" tabindex="-1"></a><span class="co">#| crop: false</span></span>
<span id="cb53-375"><a href="#cb53-375" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span> (<span class="fu">dnorm</span> (x, </span>
<span id="cb53-376"><a href="#cb53-376" aria-hidden="true" tabindex="-1"></a>              <span class="at">mean=</span><span class="dv">0</span>, </span>
<span id="cb53-377"><a href="#cb53-377" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd=</span><span class="fl">0.7</span>), </span>
<span id="cb53-378"><a href="#cb53-378" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"steelblue"</span>, </span>
<span id="cb53-379"><a href="#cb53-379" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span>,</span>
<span id="cb53-380"><a href="#cb53-380" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb53-381"><a href="#cb53-381" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.6</span>),</span>
<span id="cb53-382"><a href="#cb53-382" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>),</span>
<span id="cb53-383"><a href="#cb53-383" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Densidade"</span>,</span>
<span id="cb53-384"><a href="#cb53-384" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"X"</span>,</span>
<span id="cb53-385"><a href="#cb53-385" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span>
<span id="cb53-386"><a href="#cb53-386" aria-hidden="true" tabindex="-1"></a><span class="fu">box</span>(<span class="at">bty =</span> <span class="st">"L"</span>)</span>
<span id="cb53-387"><a href="#cb53-387" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (<span class="at">v=</span> <span class="dv">0</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb53-388"><a href="#cb53-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-389"><a href="#cb53-389" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span> (<span class="fu">dnorm</span> (x, </span>
<span id="cb53-390"><a href="#cb53-390" aria-hidden="true" tabindex="-1"></a>              <span class="at">mean=</span><span class="dv">0</span>, </span>
<span id="cb53-391"><a href="#cb53-391" aria-hidden="true" tabindex="-1"></a>              <span class="at">sd=</span><span class="fl">1.3</span>), </span>
<span id="cb53-392"><a href="#cb53-392" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"green3"</span>, </span>
<span id="cb53-393"><a href="#cb53-393" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty=</span><span class="dv">1</span>,</span>
<span id="cb53-394"><a href="#cb53-394" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd=</span><span class="dv">2</span>,</span>
<span id="cb53-395"><a href="#cb53-395" aria-hidden="true" tabindex="-1"></a>       <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-396"><a href="#cb53-396" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-397"><a href="#cb53-397" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-398"><a href="#cb53-398" aria-hidden="true" tabindex="-1"></a><span class="fu">### Coeficiente de Variação</span></span>
<span id="cb53-399"><a href="#cb53-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-400"><a href="#cb53-400" aria-hidden="true" tabindex="-1"></a>O desvio padrão por si só tem limitações. Um desvio padrão igual a 2 pode ser considerado pequeno para um conjunto de valores cuja média é 100. Entretanto, se a média for 5, ele se torna muito grande. Além disso, o desvio padrão por ser expresso na mesma unidade dos dados, não permite aplicá-lo na comparação de dois ou mais conjunto de dados que têm unidades diferentes. Para eliminar essas limitações, é possível caracterizar a dispersão ou variabilidade dos dados em termos relativos, usando uma medida denominada Coeficiente de Variação (CV), também conhecido como *Desvio Padrão Relativo* ou *Coeficiente de Variação de Pearson*. É expresso, em geral como uma porcentagem, sendo definido como a razão do desvio padrão pela média:</span>
<span id="cb53-401"><a href="#cb53-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-402"><a href="#cb53-402" aria-hidden="true" tabindex="-1"></a>$$CV = \frac{s}{\overline{x}}$$</span>
<span id="cb53-403"><a href="#cb53-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-404"><a href="#cb53-404" aria-hidden="true" tabindex="-1"></a>Multiplicando o valor da equação por 100 tem-se o CV percentual. O *R* não possui uma função específica para calcular o CV.</span>
<span id="cb53-405"><a href="#cb53-405" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-406"><a href="#cb53-406" aria-hidden="true" tabindex="-1"></a>Foi criada uma função específica para isso, já multiplicada por 100 (ver @sec-funcpropria). Será repetida aqui a função para facilitar a visualização:</span>
<span id="cb53-407"><a href="#cb53-407" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-410"><a href="#cb53-410" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-411"><a href="#cb53-411" aria-hidden="true" tabindex="-1"></a>coefVar <span class="ot">&lt;-</span> <span class="cf">function</span> (x) {</span>
<span id="cb53-412"><a href="#cb53-412" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (<span class="fu">sd</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">mean</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb53-413"><a href="#cb53-413" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-414"><a href="#cb53-414" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-415"><a href="#cb53-415" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-416"><a href="#cb53-416" aria-hidden="true" tabindex="-1"></a>Portanto, o CV da variável <span class="in">`dados$peso_rn`</span> é igual a:</span>
<span id="cb53-417"><a href="#cb53-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-420"><a href="#cb53-420" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-421"><a href="#cb53-421" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coefVar</span>(dados<span class="sc">$</span>peso_rn), <span class="dv">1</span>)</span>
<span id="cb53-422"><a href="#cb53-422" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-423"><a href="#cb53-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-424"><a href="#cb53-424" aria-hidden="true" tabindex="-1"></a>Usando outra variável do banco de dados, por exemplo, <span class="in">`dados$idade_mae`</span>, o CV será igual a:</span>
<span id="cb53-425"><a href="#cb53-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-428"><a href="#cb53-428" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb53-429"><a href="#cb53-429" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coefVar</span>(dados<span class="sc">$</span>idade_mae), <span class="dv">1</span>)</span>
<span id="cb53-430"><a href="#cb53-430" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb53-431"><a href="#cb53-431" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-432"><a href="#cb53-432" aria-hidden="true" tabindex="-1"></a>O peso do recém-nascido tem um CV = <span class="in">`r round(coefVar(dados$peso_rn), 1)`</span> % e a idade materna um CV = <span class="in">`r round(coefVar(dados$idade_mae), 1)`</span> %, mostrando que esta tem uma maior variabilidade. Quanto menor o desvio padrão, menor o CV e, consequentemente, menor a variabilidade. Um CV $\ge$ 50%, sugere que a variável tem uma distribuição assimétrica.</span>
<span id="cb53-433"><a href="#cb53-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-434"><a href="#cb53-434" aria-hidden="true" tabindex="-1"></a><span class="fu">### Escolha da medida resumidora</span></span>
<span id="cb53-435"><a href="#cb53-435" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-436"><a href="#cb53-436" aria-hidden="true" tabindex="-1"></a>A seleção da medida de tendência central mais adequada depende de vários fatores, incluindo a natureza dos dados e do propósito da sumarização.</span>
<span id="cb53-437"><a href="#cb53-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-438"><a href="#cb53-438" aria-hidden="true" tabindex="-1"></a>O tipo da variável tem substancial influência na escolha da medida de tendência central a ser usada. A moda é mais apropriada para dados nominais e seu uso com variáveis ordinais resulta em uma perda no poder em termos de informação que se poderia obter dos dados.</span>
<span id="cb53-439"><a href="#cb53-439" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-440"><a href="#cb53-440" aria-hidden="true" tabindex="-1"></a>A mediana é mais adequada para variáveis ordinais, embora possa ser usada para variáveis contínuas, especialmente quando a distribuição dos dados é assimétrica. A mediana não deveria ser usada com dados nominais porque os postos assumidos não podem ser obtidos com dados de nível nominal.</span>
<span id="cb53-441"><a href="#cb53-441" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-442"><a href="#cb53-442" aria-hidden="true" tabindex="-1"></a>Finalmente, a média somente deve ser usada com dados contínuos simétricos, se houver assimetria a mediana deve ser preferida.</span>
<span id="cb53-443"><a href="#cb53-443" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-444"><a href="#cb53-444" aria-hidden="true" tabindex="-1"></a>As medidas de dispersão devem estar associadas a uma medida de tendência central. Elas caracterizam a variabilidade dos dados na amostra. Com dados ordinais usar a amplitude ou o intervalo interquartil. O desvio padrão não é apropriado em dados ordinais devido à natureza não numérica destes.</span>
<span id="cb53-445"><a href="#cb53-445" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-446"><a href="#cb53-446" aria-hidden="true" tabindex="-1"></a>Com os dados numéricos deve-se usar o desvio padrão, que utiliza toda a informação nos dados, ou o intervalo interquartil (IIQ). Quando os dados forem simétricos, usar a média acompanhada do desvio padrão, caso contrário, usar a mediana e o IIQ. Não misturar e combinar medidas <span class="co">[</span><span class="ot">@bowers2008scratch</span><span class="co">]</span>.</span>
</code><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>